### PR TITLE
Exit parsing header if line of data is encountered.

### PR DESCRIPTION
**Pull request by aymanhab**
Fixes issue #2432 

### Brief summary of changes
Check if a line of data (not key=value or other acceptable non-data) is encountered during parsing header.
### Testing I've completed
Tried loading csv file from APDM using CSVFileAdapter failed quickly rather than hung.

### CHANGELOG.md (choose one)

- will update once reviewed.

- - -
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3338)

### CODE REVIEW

**Comment by aymanhab** [comment]
change made per discussion with @AlbertoCasasOrtiz, ready for review

**Comment by AlbertoCasasOrtiz** [comment]
Hi @aymanhab. I have just tested this and it is working as expected. Without your changes, it is hanging, but with the changes, it is throwing the following error:

```
terminate called after throwing an instance of 'OpenSim::Exception'
  what():  Missing end of header block
	Thrown at DelimFileAdapter.h:345 in extendRead().
Aborted (core dumped)
```
I did this in C++ using the following code.

```
CSVFileAdapter adaptor = CSVFileAdapter();
adaptor.read("imuData01csv.csv");
```

I initially tried to to this in Python. However, it is complaining about the read function not existing:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'CSVFileAdapter' object has no attribute 'read'
```

When I print the attributes of the adapter, read is not shown:

```
> dir(adapter)

['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__swig_destroy__', '__weakref__', 'clone', 'thisown', 'write']
```
I think this is related to this issue #3128, in which another user was having the same problem in MatLab. Looks like none of the inherited functions are exposed in both Matlab and Python ([Documentation with inherited functions](https://simtk.org/api_docs/opensim/api_docs/classOpenSim_1_1CSVFileAdapter.html)).

**Review by AlbertoCasasOrtiz — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3338#-:-NL2TRqXEAY2jHBM91Ew:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aymanhab)

**Comment by aymanhab** [comment]
Perfect, thanks for testing @AlbertoCasasOrtiz 👍

**Pull request merged**
