### PR TITLE
Support Swig 4.0

### PR DESCRIPTION
**Pull request by aymanhab**
Fixes issue #2524

### Brief summary of changes
-Upgrade makefiles to require SWIG 4.0
- Include doxygen option to pass docs to python, java 
- Update interface files to 4.0 
- Some ifdef/endif in headers due to issues parsing doxygen comments by SWIG
- Moved methods that traverse componentLists to Model class due to new stricter scoping rules

### Testing I've completed
Standard test suite passes, Java bindings work in GUI and comments available in GUI IDE

### Looking for feedback on...
How this looks in Matlab and in Python, whether comments are available/helpful

### CHANGELOG.md (choose one)

- no need to update because...
- updated.

---
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2976)

### CODE REVIEW

**Comment by aymanhab** [comment]
@carmichaelong you may want to take a look/review if @nickbianco is not available

**Comment by nickbianco** [comment]
From dev meeting today: create Python (and maybe Java) versions of osimC3D and add tests for them.

**Review by nickbianco — CHANGES_REQUESTED** [review]
> Reviewed 14 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2976)* status: all files reviewed, 2 unresolved discussions (waiting on @aymanhab)

___
*[Bindings/common.i, line 389 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2976#-MXnVztoBBl1oaqmFbB1:-MXnVztoBBl1oaqmFbB2:b-89ew3v) ([raw file](https://github.com/opensim-org/opensim-core/blob/7e8ffc9395f4aca584ef8b567df3acf8fdd46c70/Bindings/common.i#L389)):*
> ```SWIG
>         std::map<std::string, std::shared_ptr<OpenSim::AbstractDataTable> >;
> //%template(StdMapStringTimeSeriesTableVec3)
> //        std::map<std::string, std::shared_ptr<OpenSim::TimeSeriesTable_<SimTK::Vec3> > >;
> ```

Is this supposed to be commented out?
___
*[OpenSim/Tools/InverseKinematicsTool.h, line 111 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2976#-MXnXLLw-cOwj9quFrJI:-MXnXLLw-cOwj9quFrJJ:b-tjkfhr) ([raw file](https://github.com/opensim-org/opensim-core/blob/7e8ffc9395f4aca584ef8b567df3acf8fdd46c70/OpenSim/Tools/InverseKinematicsTool.h#L111)):*
> ```objc
> #ifndef SWIG
>     /** @cond **/ // hide from Doxygen
> #endif
> ```

Will this get exposed if Doxygen is installed but not SWIG?

**Comment by nickbianco** [comment]
The changes look good, just a few minor comments.

Creating a local build now to test osimC3D.

**Review by aymanhab — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2976#-:-MXrVv0C65bGYUOeIc07:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @nickbianco)

___
*[Bindings/common.i, line 389 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2976#-MXnVztoBBl1oaqmFbB1:-MXrW-F6AaqsDT8YC8TT:b3q04km) ([raw file](https://github.com/opensim-org/opensim-core/blob/7e8ffc9395f4aca584ef8b567df3acf8fdd46c70/Bindings/common.i#L389)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

Is this supposed to be commented out?
</blockquote></details>

Yes, this map is used internally and is exposed only by the C3DAdapter class's write method which is never used. If left behind, the code generated by SWIG fails to compile because an Iterator over the Map has to be generated and that was quite difficult to communicate to SWIG and is rather unnecessary.
___
*[OpenSim/Tools/InverseKinematicsTool.h, line 111 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2976#-MXnXLLw-cOwj9quFrJI:-MXrX9fH3cAgAn9nm6tS:b2v9hmm) ([raw file](https://github.com/opensim-org/opensim-core/blob/7e8ffc9395f4aca584ef8b567df3acf8fdd46c70/OpenSim/Tools/InverseKinematicsTool.h#L111)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

Will this get exposed if Doxygen is installed but not SWIG?
</blockquote></details>

Yes, while running SWIG the block disappears to it can digest comments, if not running SWIG the ifndef/endif is a no-op so Doxygen and any other old code/processor work as expected.

**Review by nickbianco — COMMENTED** [review]
Changes LGTM. I tested osimC3D locally and it seems to work fine. However, I'm having trouble getting a Python environment to work. I was able to get an older version of pre-release 4.2 working (with changes to the install process I commented here: https://github.com/opensim-org/opensim-core/issues/2968), but the same process hasn't worked for this build (I'm working on Mac). 

I don't want to hold this up unnecessarily, but I also want to make sure that installing Python still works with the new swig changes.

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2976#-:-MXs4tfb5I8oHg2AFVs9:b-mu8y4z)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aymanhab)

**Review by aymanhab — COMMENTED** [review]
Sure, I understand, just keep me posted.

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2976#-:-MXs6_RU-9iy0kmhFmLL:b-ahovob)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aymanhab)

**Comment by nickbianco** [comment]
I'm getting the familiar ImportError issue:

image

A quick Google search suggests that this could be due to circular imports, but nothing in `__init__.py` has been changed. Not sure what the issue is. I am using an Anaconda environment, but I was able to get the OpenSim 4.2 release working with an Anaconda environment. When installing with 4.2, the 'opensim' package shows up in the list of packages (when you call `conda list`) in your conda environment. However, with the Mac build I downloaded for this release, it did not appear.

**Comment by aymanhab** [comment]
@nickbianco Can you do plain python 3.7-9 to isolate Anaconda specific issues? The ci build runs python tests so it must be able to import simbody without an issue I'm guessing

**Comment by aymanhab** [comment]
Note that ci was built against python 3.9.2 (just to test) but we could bring it down to 3.7, this could be the difference between this and 4.2 public release which couldn't go above 3.7

**Comment by nickbianco** [comment]
@aymanhab that could be the issue. I thought we we're still building against python 3.7.

**Comment by nickbianco** [comment]
Okay, I got it to work with an Anaconda environment with Python 3.9.2. However, it only works if I'm in the `setup.py` directory. I get the following warning when running `python setup.py install`:

```
UserWarning: The version specified ('4.3-2021-04-08-0253fd959') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
```
In addition, the opensim package still doesn't appear in the conda package list. I'm not sure if there's a conflict with `setuptools` and the version of Python used in the CI build. We might consider rolling back to an earlier Python version.

**Comment by aymanhab** [comment]
@nickbianco I reverted osx and windows builds to use python 3.7. The warning about version number is rather benign (https://stackoverflow.com/questions/27493792/python-and-pep-440-how-serious-is-this-warning-about-pep440) and will not happen in official releases because we don't embed build date and hash in release versions.

**Comment by nickbianco** [comment]
Thanks @aymanhab, I'll try out the new build.

I know the warning is benign, but it mentions potentially loss of compatibility with setuptools, which we need for `python setup.py install`. Just something to keep an eye on.

**Comment by nickbianco** [comment]
Update: I've tried installing the Python bindings with same Homebrew version of Python 3.7 as the CI uses, but I'm still running into issues. I'm now encountering this error:

```
ImportError: dlopen(/Applications/opensim-core-4.3-2021-04-10-63168d063/sdk/Python/opensim/_simbody.so, 2): Symbol not found: _PyCMethod_New
  Referenced from: /Applications/opensim-core-4.3-2021-04-10-63168d063/sdk/Python/opensim/_simbody.so
  Expected in: flat namespace
 in /Applications/opensim-core-4.3-2021-04-10-63168d063/sdk/Python/opensim/_simbody.so
```

I'm there is some issue with Python version compatibility that I'm missing now. This is probably an issue with my environment and not the updates to SWIG. I'm fine with merging this and can sort out the install issues afterwards.

**Review by nickbianco — COMMENTED** [review]
@aymanhab Okay I finally got a local build working. I needed to set the `PYTHONPATH` in addition to `DYLD_LIBRARY_PATH` on Mac to get it work. I did this using my own local build of the bindings. 

I'm going to try again using the build from CI. If you want, we could test again using the latest version of Python through CI since that was a motivating factor for updating SWIG.

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2976#-:-MY1i3saAL-fSEYKhvgl:bb8vpuv)* status: 13 of 14 files reviewed, all discussions resolved (waiting on @nickbianco)

**Review by nickbianco — COMMENTED** [review]
Actually, I forgot I already had a Python 3.9 build downloaded and set up. Just tested again and it works! So we don't have to force Python 3.7. Once you revert that change and the tests pass, feel free to merge.

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2976#-:-MY1lXY_9e2MJQYrya8y:bccm4la)* status: 13 of 14 files reviewed, all discussions resolved (waiting on @nickbianco)

**Review by aymanhab — COMMENTED** [review]
Thanks @nickbianco much appreciated. So do you prefer we make builds with 3.7 or 3.9?  I prefer we fix a python version either way rather than get the randomly chosen version selected by ci.

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2976#-:-MY1uzyU9GLJylxTAdcv:b-z5u89e)* status: 13 of 14 files reviewed, all discussions resolved (waiting on @nickbianco)

**Comment by nickbianco** [comment]
I was going back and forth about this, but I think I agree that we should fix to a specific version (until something in Python changes that necessitates a version upgrade). It could make sense to stay at 3.7 since other Python package might not stay as current ([like Antoine's issue with NumPy and Tensorflow](https://github.com/opensim-org/opensim-core/issues/2968)).

**Review by nickbianco — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2976#-:-MY3oxeWALFYZ8gSZU-9:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aymanhab)

**Comment by aymanhab** [comment]
Thanks @nickbianco much appreciated 👍

**Pull request merged**
