### PR TITLE
[readme] Wrapping -> Bindings.

### PR DESCRIPTION
**Pull request by chrisdembia**

### CODE REVIEW

**Comment by chrisdembia** [comment]
I cancelled the appveyor tests; that's why some of them are failing.

**Comment by aymanhab** [comment]
Sure. Thanks @chrisdembia

**Comment by aymanhab** [comment]
@chrisdembia Please delete the branch if you're not planning to reuse it. Thanks.

**Comment by chrisdembia** [comment]
Thanks @aymanhab

**Pull request merged**
