### PR TITLE
Rewrite PropertyTable to use std::unordered_map

### PR DESCRIPTION
**Pull request by adamkewley**
Reimplements `PropertyTable` to store the string-to-index lookup in an `std::unordered_map`, rather than a `std::map`.

The motivation for doing this is model editing performance. `PropertyTable`, `Component`, `Socket`, etc. are all using `std::map`, which is almost always implemented as a red-black tree. This means that copying a `Model` (e.g. because an editor wants to back up an old version) spends a large amount of time copying tree nodes, strings, etc.

Changing the lookup to an `O(1)` lookup also has the advantage of making runtime property lookups faster

I will try to build a downstream fork of OSC with this branch to get an idea of where the performance impact is, but I figure that it's a nice refactor to do in general.

### Brief summary of changes

- Change PropertyTable to store `PropertyHolder`s (pointers to `AbstractProperty`)
- Use modern C++ abstractions to remove the manual copy ctor/assignment etc.

### Testing I've completed

- Ran the original test suite, which extensively tests the property API

### CHANGELOG.md (choose one)

- no need to update because internal

- - -
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3722)

### CODE REVIEW

**Comment by adamkewley** [comment]
Downstream benchmarking indicates that this doesn't have a big impact on model copying, so this is more of a feel-good change ;)

**Review by nickbianco — APPROVED** [review]
Two minor comments about copyright dates, but otherwise :lgtm:.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3722#-:-Nrr6--Z7JYGkeyX8pZp:bm3l45u)* status: all files reviewed, 2 unresolved discussions (waiting on @adamkewley)

___
*[`OpenSim/Common/PropertyTable.h` line 13 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3722#-Nrr4F6H2uj73sWPuZRl:-Nrr4F6H2uj73sWPuZRm:bb6ht39) ([raw file](https://github.com/opensim-org/opensim-core/blob/baf28990e0f8d3cb0cf16d195a26f60ea79b70d4/OpenSim/Common/PropertyTable.h#L13)):*
> ```objc
>  * through the Warrior Web program.                                           *
>  *                                                                            *
>  * Copyright (c) 2005-2023 Stanford University and the Authors                *
> ```

2024
___
*[`OpenSim/Common/PropertyTable.cpp` line 10 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3722#-Nrr4mLzEDOT5-jNbkm8:-Nrr4mLzEDOT5-jNbkm9:bb6ht39) ([raw file](https://github.com/opensim-org/opensim-core/blob/baf28990e0f8d3cb0cf16d195a26f60ea79b70d4/OpenSim/Common/PropertyTable.cpp#L10)):*
> ```cpp
>  * through the Warrior Web program.                                           *
>  *                                                                            *
>  * Copyright (c) 2005-2023 Stanford University and the Authors                *
> ```

2024

**Comment by adamkewley** [comment]
Thanks for checking it out @nickbianco - too bad it doesn't have any particularly big gains, but hopefully it's an otherwise nice little clean-up!

**Comment by nickbianco** [comment]
@adamkewley definitely worth a shot, and yes, a nice refactor regardless :)

**Pull request merged**
