### PR TITLE
Kinematics reporter used internally by InverseKinematicsTool should n…

### PR DESCRIPTION
**Pull request by aymanhab**
…ot be deleted (will go out of scope)

Fixes issue https://github.com/opensim-org/opensim-gui/issues/421

### Brief summary of changes
Analysis created on the stack shouldn't be deleted as it will be deleted again when goes out of scope.
### Testing I've completed
Ran Scale followed by IK or IK standalone in the GUI

### CHANGELOG.md (choose one)

- no need to update because...
- updated...

The Doxygen for this PR can be viewed at http://myosin.sourceforge.net/?C=N;O=D; click the folder whose name is this PR's number.

### CODE REVIEW

**Comment by aymanhab** [comment]
@chrisdembia Can you please review this fix? I'll submit to master as well but need to get it into branch for automated build/test on OSX. Thanks

**Comment by chrisdembia** [comment]
@aymanhab you'll need to update `.travis-ci.yml` from the master branch for the Mac build to pass.

I might need some help on how to reproduce the error and verify the fix.

**Comment by chrisdembia** [comment]
@aymanhab I updated your link above for https://github.com/opensim-org/opensim-gui/issues/421

**Comment by chrisdembia** [comment]
I was able to update `libosimTools.dylib` within an OpenSim GUI distribution with a `libosimTools.dylib` built from this branch, and the IK crash went away. Seems like the fix works.

However, we established that we cannot merge PRs directly into `4.0beta_nov2017`; they must go into master first.

**Comment by aymanhab** [comment]
Thanks @chrisdembia I changed the PR to go into master. Will need another reviewer @tkuchida or @aseth1 if available.

**Comment by aymanhab** [comment]
Thanks @aseth1 for the quick turnaround. Likely we got away with it since the reporter was last object allocated.

**Comment by aymanhab** [comment]
Failures unrelated to change. Merging

**Pull request merged**
