### PR TITLE
Fix ForceSet::append() bug

### PR DESCRIPTION
**Pull request by chrisdembia**
This PR is similar to #490, except I've tried to clean up the git history. Unfortunately, now the history makes it seem like I made these changes, but @aymanhab made most of the changes.

This partially addresses #432; @aymanhab did you already make a similar fix for java? #432 might also entail documentation improvements.

### CODE REVIEW

**Comment by chrisdembia** [comment]
Ready for review; @aymanhab

**Comment by aymanhab** [comment]
@chrisdembia should the test call ForceSet::append instead of ForceSet::adoptAndAppend()? the rest of the cleanup looks good. Thanks a million.

**Comment by chrisdembia** [comment]
Haha not a bad idea, since that was the whole point of this PR. Just pushed another commit.

**Comment by chrisdembia** [comment]
Ready for review again.

**Comment by chrisdembia** [comment]
BTW I'm not sure if this fix ever got into 3.3.

**Comment by chrisdembia** [comment]
Merge the parts of this PR that are not accounted for by #543.

**Comment by aymanhab** [comment]
@chrisdembia I think this was backported to another PR already and can be closed.

**Comment by chrisdembia** [comment]
Thanks for the reminder.

**Pull request closed without merging**
