### PR TITLE
[WIP] Doxygen users guide

### PR DESCRIPTION
**Pull request by chrisdembia**
I've created this PR based on discussion with @aseth1 about investigating how to use Markdown for the API guide and simultaneously incorporate the API guide into doxygen. The result looks like this:

image

It may be helpful to use the Atom text editor locally to preview how the Markdown files would look on GitHub.

Here's another project on GitHub that does something similar: https://github.com/smtrat/smtrat

### CODE REVIEW

**Comment by aseth1** [comment]
@chrisdembia this looks exactly like what I was hoping for. If you are OK with it, I can add to this PR directly, or we can merge now and I can update incrementally. Both are fine with me.

**Comment by chrisdembia** [comment]
There are a few rough edges (in trying to avoid havinge `OpenSim::` show up, and in doxygen commands like `@subpage` and `{#labels}` showing up on GitHub), but I think these are mostly tolerable.

Yeah, please feel free to add to this PR directly. I think this should be fleshed out a little more before being merged.

**Comment by jimmyDunne** [comment]
Does the markdown render images well?

**Comment by aseth1** [comment]
I've incorporate the contents of the [Devloper's API Guide GoogleDoc](https://docs.google.com/document/d/1aDAwIf_RQG32QcuKAISdG6mGeDqSdIyfg0cMyZwgJOE/edit) so this can become the central place to make updates to the guide for 4.0. It renders in both MarkDown and Doxygen so I think this is the way to move forward to encourage updates and to minimize duplication.

**Comment by chrisdembia** [comment]
This link should eventually show the doxygen output for the API guide: http://myosin.sourceforge.net/1706

**Comment by chrisdembia** [comment]
Looks pretty good. The formatting in [this section](https://github.com/opensim-org/opensim-core/blob/435637672ebaab4ba55383f2edd1feb67f5dbc3f/doc/APIGuide.md#ii-finalize-properties-and-connections-of-the-component-finalizefromproperties) is messed up (see bullet 2).

**Comment by tkuchida** [comment]
Cool; this will be a great resource. It looks like some of this information might be useful for users who aren't API developers. To avoid duplication on Confluence, etc., I'm wondering whether the page could be separated into a few .md files so that the more general information/descriptions could be assembled into a page for other users (without the coding details)?

**Comment by chrisdembia** [comment]
> It looks like some of this information might be useful for users who aren't API developers.

I agree.

>  To avoid duplication on Confluence, etc., I'm wondering whether the page could be separated into a few .md files so that the more general information/descriptions could be assembled into a page for other users (without the coding details)?

Based on discussion in the dev meeting, it sounds like splitting the guide into multiple .md files causes doxygen to generate separate html pages, potentially making the guide harder to navigate.

It is possible to embed markdown from github into confluence: https://community.atlassian.com/t5/Confluence-questions/Embed-md-file-from-Github-in-Confluence-page/qaq-p/407068

**Comment by chrisdembia** [comment]
Should we delete OpenSimProgrammingGuide.md?

**Comment by chrisdembia** [comment]
The aspect ratio of the frames image is not correct (viewed in the markdown on github); what is causing that?

There are still some issues with formatting: 
screen shot 2017-09-22 at 5 47 28 pm

I'm pretty sure most of the code blocks are supposed to be indented (the ones that appear within a list), but are not.

This PR looks good to me. I was unable to view the generated doxygen (I think these files were cleaned up on myosin b/c the PR was started so long ago).

**Comment by chrisdembia** [comment]
@jenhicks here's a zip of the doxygen for this PR: https://www.dropbox.com/s/7ay056u8htjo4ql/opensim-core-1706-doxygen.zip?dl=0

@aseth1 I pushed two small commits. 

I killed the appveyor builds because they're not necessary.

**Pull request merged**
