### PR TITLE
Remove undistributable c3d files.

### PR DESCRIPTION
**Pull request by klshrinidhi**
As per #991.

Removing c3d files from repo that we don't have permission to distribute.

### CODE REVIEW

**Comment by tkuchida** [comment]
LGTM. We could also try [purging these files from the repo history](https://help.github.com/articles/remove-sensitive-data/)—though we can't do anything about existing clones and forks.

**Comment by tkuchida** [comment]
The tests are failing because [test_DataAdapter.py](https://github.com/opensim-org/opensim-core/blob/remove_undistributable_c3d_files/Bindings/Python/tests/test_DataAdapter.py) is trying to read singleLeglanding_2.c3d and jogging.c3d.

**Comment by chrisdembia** [comment]
> LGTM. We could also try purging these files from the repo history—though we can't do anything about existing clones and forks.

I used methods like this when I created the original git repo. But from what I remember, it's not really a good idea to delete files from a repo once it's already in use. I think doing something like that changes all the commit hashes (since a commit hash is generated by the contents of the files in the commit), etc. and basically creates a new repo that doesn't work with the previous one.

**Comment by jenhicks** [comment]
What is the source of the CI failures? Besides that, let's go ahead and merge.

**Comment by tkuchida** [comment]
> What is the source of the CI failures?

As mentioned above, test_DataAdapter.py is trying to read singleLeglanding_2.c3d and jogging.c3d, which are among the files that were removed. test_DataAdapter.py should be updated to read walking2.c3d and/or walking5.c3d instead.

**Comment by tkuchida** [comment]
:+1: Looks good to merge if tests pass.

**Comment by chrisdembia** [comment]
LGTM too.

**Comment by jenhicks** [comment]
@klshrinidhi can you id the source of the ci failure?

**Comment by klshrinidhi** [comment]
CI builds are passing except for segfault in clang. This is merge-able now.

**Pull request merged**
