### PR TITLE
[readme] Mention python version of README example

### PR DESCRIPTION
**Pull request by chrisdembia**
In #1241, a user started converting the README example into python, presumably because the user did not know that a python version already exists. This PR attempts to avoid such duplicated effort in the future by putting a note in the README about the python example.

### CODE REVIEW

**Comment by chrisdembia** [comment]
I cancelled the CI builds because this PR only affects the README.

**Comment by jenhicks** [comment]
Looks good! Ok by me to merge.

**Comment by carmichaelong** [comment]
It could merge as is, or I would consider moving it to the top of the section where it says "Let's simulate a simple arm whose elbow is actuated by a muscle:" so that a Python user won't go through the whole C++ code first and maybe miss the comment at the end. Maybe it could be something like:

Let's simulate a simple arm whose elbow is actuated by a muscle using the C++ libraries. (You can find a python version of this example at Bindings/Python/examples/build_simple_arm_model.py).

**Comment by chrisdembia** [comment]
Thanks @jenhicks and @carmichaelong.

> I would consider moving it to the top of the section

Addressed.

Ready for review again.

**Comment by chrisdembia** [comment]
Thank you!

**Pull request merged**
