### PR TITLE
Avoid excluding single-character Component name in path

### PR DESCRIPTION
**Pull request by tkuchida**
Fixes issue #1599.

### Brief summary of changes
Fixed off-by-one string parsing bug.

### Testing I've completed
Tests pass locally. Also tested on example code provided in #1599.

### Looking for feedback on...
No specific feedback sought.

### CHANGELOG.md (choose one)
No need to update because this code is part of the new 4.0 API.

### CODE REVIEW

**Comment by tkuchida** [comment]
Timeout of testCMCEMGDrivenArm_Millard on Travis (clang/Debug).

**Comment by aseth1** [comment]
Changes LGTM. Do you want to include the example code in #1599 (or similar) as a test case in `testComponentInterface`'s `testComponentPathNames` subtest?

**Comment by aseth1** [comment]
@tkuchida I don't think it is necessary to add the test formally since you verified it. You're welcome to add it later for completeness if you wish, but I will merge it so we'll have your fix as part of the beta.

**Comment by tkuchida** [comment]
@aseth1 Not sure what you'd like done here. Currently, testComponentInterface.cpp lives in OpenSim/Common and doesn't use Model or the osimSimulation library. The string parsing bug was in `Component::getStateVariableNames()` and AFAIK the only way it can be called without throwing a [`!hasSystem()` exception](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Common/Component.cpp#L720) is if Model.h is #included in testComponentInterface.cpp so that `Model::initSystem()` can be called. Is there a better home for this test or am I missing something?

**Pull request merged**
