### PR TITLE
[cmake] Create CMake macro to manage test creation

### PR DESCRIPTION
**Pull request by chrisdembia**
Currently, the CMakeLists.txt files for test directories are somewhat messy, and often copied and pasted from similar directories. In this PR, I've cleaned up almost all CMakeLists.txt files for test directories by creating a CMake macro OPENSIM_ADD_TESTS.

This PR also fixes a bug that Matt noticed when building in Debug mode: the library dependencies for certain tests were not being recognized: (1) testCMC* did not know it depended on osimCommon, and (2) testCMC* was not linking to SimTK libraries. I think I introduced this bug with cmake changes I made previously. This bug is fixed by specifying the names of targets rather than of both the debug and release variants of library names. 

The benefit of using names of targets rather than listing both debug and release variants is that if you do the former, CMake will automatically link that target's link libraries as well. That is, when specifying link libraries for testCMC, I don't need to specify SimTK libraries, since the OpenSim libraries already have those libraries as link libraries. It is preferable to use CMake's automatic detection of link library dependencies to minimize our own manual error when specifying link libraries.

One important question that you as a reviewer might have is "If I'm building in debug, are you sure I'll link to libosimCommon_d and not libosimCommon, etc.?" The answer is yes; see https://github.com/simbody/simbody/pull/197.

I also slightly cleaned up the CMake for example tests, but did not migrate the example tests to the new CMAKE_ADD_TESTS macro. This is because we might be moving the examples to a separate repo and have also discussed reorganizing them so that the tests for an example live with the example.

I also discovered that we were missing a test: https://github.com/opensim-org/opensim-core/pull/395/files#diff-7a8df070e011197f729d4222c6874f3cR44

I think the best way to examine if this PR breaks anything is to see if the number of tests is preserved. Right now, there are 63 tests if JAVA_WRAPPING is not built; you should now see 64 test without JAVA_WRAPPING since I added an additional test.

### CODE REVIEW

**Comment by jenhicks** [comment]
@elen4 Would you mind reviewing this PR? Thanks!!

**Comment by chrisdembia** [comment]
I think this PR currently fails under debug (I don't think it did originally; it might be a result of the merge). I'll have to look into this.

**Comment by elen4** [comment]
Hi @jenhicks and @chrisdembia, I tested the PR on Windows so far (VS12, 64 bit) and it compiles (Debug and Release) and runs the tests (Release) successfully. However, I only see 63 tests (64 with BUILD_JAVA_WRAPPING enabled). Will try on Ubuntu shortly.
I definitely approve of using target names for linking :+1:  and I think this PR cleans up CMake code a bit, which is good :smile:
However, I have some comments about the new macro:
- I am not sure I understand the signature: a list of cpp files are passed as TESTPROGRAMS, a test of the same name is created for each, then additional source files are specified as SOURCES and used for compilation of *all* these tests. Is this how tests always work and always will work? It seems like an unnecessary loss of generality to me. I find it more intuitive to call the macro for each test, specifying explicitly the name of the test and the source files needed to compile it.
- I don't think you need to know the location of the executable to use it in a test, according to CMake docs you can just use the target name, CMake will know where it has been built (you need to use the complete `add_test(NAME....COMMAND)` signature). I see that in the macro you are using the same name for both executable and test, not sure if this causes ambiguities when resolving target names.
- I spotted a typo on line 185 of cmake/OpenSimMacros.cmake: `${OSIIMADDTESTS_SOURCES}`
- why use `configure_file(... COPYONLY)` instead of `file(COPY ...)` ?

Other "issues", which do not impact this PR's acceptability, but caught my eye :
- CMake developers recommend not to use `file(GLOB ...)` to list source files (see CMake docs for the file command), which you suggest in the macro description. I know that most of OpenSim CMake files do that, but for CMake, *globbing is evil*
- this is just aesthetics really, but I would try to gradually move to lower-case CMake commands instead of keep using the *SCREAM CMake* style :smile:

**Comment by chrisdembia** [comment]
Thanks for the feedback. I'll address your feedback more fully soon, but for now I just want to say I agree with you about the SCREAMING. Perhaps if there's an automated way to fix this, it's worthwhile.

**Comment by chrisdembia** [comment]
Oh! [There *is* a tool for this](http://www.cmake.org/pipermail/cmake/2008-May/021900.html)!

> If you are an emacs user, the most recent emacs mode for cmake has a 
function: M-x unscreamify-cmake-buffer  which works quite well.  It also 
does auto-indenting.

**Comment by chrisdembia** [comment]
I also found this script from that link:

```
#!/bin/sh
command_list=`cmake --help-command-list | grep -v 'cmake version '`

fix_case ()
{
    LC_COMMAND=$1
    UC_COMMAND=`echo $LC_COMMAND | tr '[a-z]' '[A-Z]'`
    echo "Replacing \"$UC_COMMAND\" with \"$LC_COMMAND\"..."
    find . -name CMakeLists.txt -exec sed -i s/$UC_COMMAND\
*\(/$LC_COMMAND\(/ {} \;
    find . -name \*.cmake       -exec sed -i s/$UC_COMMAND\
*\(/$LC_COMMAND\(/ {} \;
}

for command in $command_list
do
    fix_case $command
done

```

**Comment by sherm1** [comment]
One caution is that although CMake commands can be lower case, many CMake argument keywords are only recognized in upper case. Hopefully there aren't any commands and arguments with the same names.

**Comment by elen4** [comment]
Wow I didn't know about the Emacs function, I really like the name! :blush: Anyway, the main pit-hole I see with the automatic conversion is that it might create (time-consuming) conflicts when merging existing branches and PRs- not sure about how many of them involve CMake files :pensive:

**Comment by chrisdembia** [comment]
Good point. Most cmake-related branches are mine; so I should only be punishing myself. We could also run the same script on those branches to remove the conflicts.

> Hopefully there aren't any commands and arguments with the same names.

I ight be able to write a script to check this by checking for instances of command names *without* a trailing `(`. Can you think of any pitfalls with this?

**Comment by chrisdembia** [comment]
Does anyone object to the unscreamifying of cmake commands?

**Comment by aymanhab** [comment]
No objections but please no massive pushes to master until the geometry branch merge if possible.

**Comment by chrisdembia** [comment]
Hehe sounds good; we can avoid that :boom: .

**Comment by sherm1** [comment]
> checking for instances of command names without a trailing (. Can you think of any pitfalls with this?

Could miss some commands if they are formatted with the ( on the next line; not tragic. Could also check to see if there is any overlap between commands and keyword arguments -- might not be.

**Comment by chrisdembia** [comment]
Since @klshrinidhi is interested in the cmake for tests, we should hold off on this. @klshrinidhi , when you're ready to look at this, let me know.

**Comment by chrisdembia** [comment]
I've changed my mind about waiting for @klshrinidhi to take on the testing framework. I think this should be merged, and then @klshrinidhi can build upon it when he introduces a testing framework. This PR fixes something that's broken in master right now (in debug, the target dependencies aren't set up).

I'll respond to @elen4's review.

> I am not sure I understand the signature: a list of cpp files are passed as TESTPROGRAMS, a test of the same name is created for each, then additional source files are specified as SOURCES and used for compilation of all these tests. Is this how tests always work and always will work? It seems like an unnecessary loss of generality to me. I find it more intuitive to call the macro for each test, specifying explicitly the name of the test and the source files needed to compile it.

I agree and I think @klshrinidhi will address this in the future.

> I don't think you need to know the location of the executable to use it in a test, according to CMake docs you can just use the target name, CMake will know where it has been built (you need to use the complete add_test(NAME....COMMAND) signature). I see that in the macro you are using the same name for both executable and test, not sure if this causes ambiguities when resolving target names.

Fixed.

> I spotted a typo on line 185 of cmake/OpenSimMacros.cmake: ${OSIIMADDTESTS_SOURCES}

Thank you!!! Fixed.

> why use configure_file(... COPYONLY) instead of file(COPY ...) ?

Fixed.

> CMake developers recommend not to use file(GLOB ...) to list source files (see CMake docs for the file command), which you suggest in the macro description. I know that most of OpenSim CMake files do that, but for CMake, globbing is evil

@klshrinidhi might fix this in the future.

> this is just aesthetics really, but I would try to gradually move to lower-case CMake commands instead of keep using the SCREAM CMake style

Fixed.


If the tests pass, I think this can be merged.

Thank you for reviewing this, @elen4. Your comments were helpful.

**Comment by sherm1** [comment]
clang test failed -- I restarted it

**Comment by sherm1** [comment]
Build worked. Chris, I really like this -- it gave me a warm happy feeling to see all that code being removed!

BTW, @elen4 I strongly disagree with CMake's no-globbing rule. Humans should not be making giant lists of hundreds of constantly changing files. That is a sure recipe for missing dependencies. Having automated methods is much better, provided that we also use some discipline about what files go where (which we do quite well, IMO). Manual lists work fine for toy programs; I think they are impractical for large projects.

**Comment by chrisdembia** [comment]
Thanks for merging.

**Comment by chrisdembia** [comment]
There is some discussion on globbing here: http://stackoverflow.com/questions/1027247/best-way-to-specify-sourcefiles-in-cmake

The biggest issue with globbing is mentioned in the second best answer: someone else pulls your code from git, in which new source files have been added, and tries to build without rerunning cmake.

I usually re-run CMake after updating the repo, so this hasn't been an issue for me.

**Pull request merged**
