### PR TITLE
Add ability to skip Travis build using [skip travis]

### PR DESCRIPTION
**Pull request by klshrinidhi**
Right now, Travis does not have an equivalent of [skip appveyor].

---
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/989)

### CODE REVIEW

**Comment by klshrinidhi** [comment]
Travis Linux builds are failing becuase http://llvm.org/apt/llvm-snapshot.gpg.key is not reachable.
Will restart the build later.

**Comment by chrisdembia** [comment]
Should travis give green or red when skipped?

**Comment by klshrinidhi** [comment]
Travis will give green when [skip travis] is specified. It will finish the build in something like 35sec.

**Comment by tkuchida** [comment]
Does `[ci skip]` still work? If so, perhaps `[travis skip]` and `[appveyor skip]` for consistency?

**Comment by chrisdembia** [comment]
Appveyor only has `[skip appveyor]`, so this PR is consistent:

image

Travis and Appveyor both detect `[skip ci]` and `[skip ci]`, but Appveyor does not detect `[appveyor skip]`.

**Comment by chrisdembia** [comment]
Though, @klshrinidhi could you update this PR so the tests pass?

**Comment by tkuchida** [comment]
@chrisdembia Thanks for the explanation. :snowboarder:

**Comment by klshrinidhi** [comment]
:white_check_mark:

**Comment by chrisdembia** [comment]
@klshrinidhi it's not clear to me that the travis builds will be green ✅ if one uses `[skip travis]`. Could you push a commit that skips travis so we can verify?

**Comment by chrisdembia** [comment]
This will be very helpful to have! The builds still queue up but then take only a minute or so before aborting.

**Pull request merged**
