### PR TITLE
[TGCS] Interactive hopper: updates to GUI

### PR DESCRIPTION
**Pull request by nickbianco**
### Brief summary of changes
- Added margin to user control entry so maximum or minimum control values can be entered without accidentally clicking outside the window
- Previous excitation/control entries now fade out
- If active device control is not needed (i.e. active device is disabled), visibility of device control is turned off
- Loading a setup file now loads most recent excitation/control in window
- Default excitation/control now loads in window

### Testing I've completed
- Changes work fine on my machine

### Looking for feedback on...
- I remember that setup files were not being loaded correctly for some people during the test run. I've not had any problems with this myself, but please let me know or raise an issue if you do.

### CODE REVIEW

**Comment by chrisdembia** [comment]
Everything you added worked very well. The fading out of the curves looks awesome!

The "ERROR" message window when clicking "backwards" on the control plot is excellent.

The message "click outside the gridded area when done" is not quite correct. Now that clicking "backwards" is not allowed, you must actually click to the *right* of the plot (specifically, to the right of x=5) to stop the curve-drawing procedure. 

Also, clicking the *lower* plot "backwards" causes the "ERROR" message to appear on the lower plot rather than on the upper control plot:

image



> I remember that setup files were not being loaded correctly for some people during the test run. I've not had any problems with this myself, but please let me know or raise an issue if you do.

I had no such issues.

**Comment by nickbianco** [comment]
Good catch. The changes in the latest commit should fix this issue. I also widened the box to the left and right edges of the gridded window, looks a little cleaner.

**Comment by chrisdembia** [comment]
@carmichaelong let me know if you'd like to review this. Otherwise, I think we should merge it.

**Comment by carmichaelong** [comment]
Don't think I'll have time to really test for at least a day or so, so it sounds like you guys should merge at will.

**Comment by chrisdembia** [comment]
I changed the target branch of this PR to `master`, because PR #1737 has been merged. 

The AppVeyor build crashed:

```
Execution protection violation
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x15964220, pid=2676, tid=0x0000077c
#
# JRE version: Java(TM) SE Runtime Environment (8.0_121-b13) (build 1.8.0_121-b13)
# Java VM: Java HotSpot(TM) Client VM (25.121-b13 mixed mode, sharing windows-x86 )
# Problematic frame:
# C  0x15964220
#
# Core dump written. Default location: C:\projects\opensim_build\Bindings\Java\tests\TestReporter\hs_err_pid2676.mdmp
#
# An error report file with more information is saved as:
# C:\projects\opensim_build\Bindings\Java\tests\TestReporter\hs_err_pid2676.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
ModelVisualizer ignoring 'Unassigned'; only .vtp .stl and .obj files currently supported.
ModelVisualizer ignoring 'Unassigned'; only .vtp .stl and .obj files currently supported.
```

I'm confident that this PR did not introduce this crash, but I am going to restart the AppVeyor build just to see if the crash is consistent.

**Comment by chrisdembia** [comment]
The crash went away! I'm merging this.

**Comment by nickbianco** [comment]
Awesome! Thanks @chrisdembia

**Pull request merged**
