### PR TITLE
Add readme to sandbox folder.

### PR DESCRIPTION
**Pull request by chrisdembia**

### CODE REVIEW

**Comment by klshrinidhi** [comment]
Allow people to write `.md` (markdown) files as well ? If wanting to write just plain English, it may help both writers and readers.
For example, 

----------------------------------------------------------------------
I want to be able to do xxxxxxxxx. Here are the steps I would like see in OpenSim:
* Step 1 -- Read in data from xxxxxx file into an OpenSim data-structure. 
* Step 2 -- xxxxxxx transformation applied to the data.
* More steps as appropriate
* Step N -- Write out data to xxxxx file or save the image.

---------------------------------------------------------------------
There may not be any code at all but the message will still be clear. It will be up to OpenSim to make it happen.

**Comment by chrisdembia** [comment]
@klshrinidhi I added to the README to account for your comments. If you'd like to add anything else, please edit the README, etc (you can do so through GitHub).

**Comment by chrisdembia** [comment]
@klshrinidhi I'm getting the same failure on appveyor as you are:

```
*******************************************************
FAILURE: SliderJoint
SliderJoint.initSystem() increased memory use by 1.32e+12%.
Exceeds acceptable tolerance of 1.000000%.
 Instance size: 13668KB increased by 18014398509477400KB over 100 iterations = 1317998135021.758789%.
 
 
**********************************************************
```

I got the error for **both** SliderJoint and PlanarJoint!

**Comment by chrisdembia** [comment]
@klshrinidhi could you merge this if you're happy with it?

**Comment by klshrinidhi** [comment]
:white_check_mark:

**Comment by chrisdembia** [comment]
:) thank you

**Pull request merged**
