### PR TITLE
Create Resources/CodeExamples folder in installation; change installation layout for GUI on Mac.

### PR DESCRIPTION
**Pull request by chrisdembia**
This PR is part of addressing https://github.com/opensim-org/opensim-gui/issues/358, https://github.com/opensim-org/opensim-gui/issues/502.

### Brief summary of changes

- Instead of using a typical UNIX layout for the installation on Mac for the GUI, we now use the same layout as on Windows (this required updating the Travis CI script).
- I also modified the layout to move code examples from the `sdk` folder to a new `Resources/CodeExamples` folder, which the GUI will copy into the user's documents folder.
- I had to alter RPATH (for UNIX platforms) to work with this non-UNIX installation layout.

Here's the layout (on Mac):

```
├── Resources
│   └── CodeExamples
│       ├── C++
│       ├── Matlab
│       └── Python
├── bin
├── cmake
└── sdk
    ├── Java
    │   └── org
    ├── Python
    │   └── opensim
    ├── Simbody
    │   ├── include
    │   ├── lib
    │   └── libexec
    ├── doc
    │   ├── html_developer
    │   └── html_user
    ├── include
    │   └── OpenSim
    └── lib
```

### Testing I've completed

- Ensured that the new RPATH-related CMake lines work with various settings (OPENSIM_INSTALL_UNIX_FHS, OPENSIM_COPY_DEPENDENCIES, OPENSIM_PYTHON_STANDALONE).
- Ensured I could build a C++ example on Mac with the new layout (and the simbody-visualizer gets launched properly).
- Ensured this new layout works with the GUI (with some changes to the GUI codebase; see the upcoming PR).

### Looking for feedback on...

- Do you like the new installation layout?
- Thanks to those who already helped develop this new layout (@aymanhab @tkuchida @aseth1).

### CODE REVIEW

**Comment by chrisdembia** [comment]
The tests now pass. Ready for review.

**Comment by chrisdembia** [comment]
Needs review.

**Comment by chrisdembia** [comment]
Fixes #2079.

**Comment by chrisdembia** [comment]
Thanks @aymanhab

**Comment by chrisdembia** [comment]
@aseth1 could you review this?

**Comment by chrisdembia** [comment]
Actually, I think we should NOT merge this until after Monday. There are multiple things that have to change on the GUI side once this is merged, and it could take more time than we have to sort out those issues.

**Comment by aseth1** [comment]
@chrisdembia just to be certain, the user Documents folder will contain:
- OpenSim4.0
  - Models
  - CodeExamples

and **sdk** dir will now remain in Application folder?

**Comment by chrisdembia** [comment]
@aseth1 Yes (except that the folder is `OpenSim/4.0`, not `OpenSim4.0`). That way, read-only files stay in the Application folder and files that users may edit are in Documents.

**Comment by chrisdembia** [comment]
Thanks @aseth1

**Pull request merged**
