### PR TITLE
Add space in Storage exception.

### PR DESCRIPTION
**Pull request by chrisdembia**

### CODE REVIEW

**Comment by tkuchida** [comment]
`_columnLabels.getSize()==1 ? " was found" : " were found"` ?

**Comment by chrisdembia** [comment]
Oh I like that!

**Comment by sherm1** [comment]
It makes me a little nervous to handle singular/plural issues with code in error messages. There are *lots* of places where this should be done for consistency. Those are very rarely executed so are prone to hidden bugs. A less elegant but serviceable bug-free alternative would be something like: `nColumns=3 but 1 column(s) were found.` I'm also OK with leaving it "were" and begging forgiveness from users who should be damn glad they are getting good error diagnostics even if somewhat ungrammatical.

**Comment by chrisdembia** [comment]
On my bikeride to work, I was daydreaming about creating an `OpenSim::plural(int, string singular, string plural)` method that would, in this case, be called as `plural(_columnLabels.getSize(), "was", "were")` and an alternative method `OpenSim::plural(int, string singular)` that could be used whose plural form is just appending an `s` to the singular form.

Thanks for merging.

**Comment by sherm1** [comment]
> `OpenSim::plural(int, string singular, string plural)`

That's a cool idea! That would make bugs much less likely. Could be overkill for scientific software error messages, but I like it.

**Pull request merged**
