### PR TITLE
Scapulothoracic joint tests

### PR DESCRIPTION
**Pull request by aseth1**
Fixes issue #2877
Addresses the need for a regression test to ensure that the ScapulothoracicJoint produces the same answers as in OpenSim 3.3
Along the way two bugs were addressed: 1) The ellipsoid was not being scaled since 4.0 because the scale code method was not correctly finding the scale factors of the respective parent body. 2) The origin of the winging axis was not being scaled.

### Brief summary of changes
1. Added regression test to testIK to verify that ScapulothoracicJoint produces the same answers as in the PLOS One article.
2. Fixed Ellipsoid scaling by identifying the scale factors of the body of the joint's 'parent_frame`.
3. Added scaling of the winging axis origin according to the `child_frame` 's body scale factors. 

### Testing I've completed
- regression test passes
- scaling test case added and passes
-  all tests pass locally

### CHANGELOG.md (choose one)
- update to reflect ScapulothoracicJoint being included as of OpenSim 4.2

---
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2932)

### CODE REVIEW

**Review by aymanhab — CHANGES_REQUESTED** [review]
> Reviewed 8 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2932)* status: 8 of 9 files reviewed, 4 unresolved discussions (waiting on @aseth1)

___
*[Applications/IK/test/testIK.cpp, line 126 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2932#-MRubaYT878Hgl3WXS8q:-MRubaYU7NNfNbd-Sx-R:bqvlcc7) ([raw file](https://github.com/opensim-org/opensim-core/blob/6b8392e17377745c0ed25fdfc62a6915efd98282/Applications/IK/test/testIK.cpp#L126)):*
> ```cpp
>         CHECK_STORAGE_AGAINST_STANDARD(result, standard,
>                 std::vector<double>(17, 0.2), __FILE__, __LINE__,
>                 "testInverseKinematicsScapulothoracicAbduction failed");
> ```

What are the units here? 0.2 m for translations would be too loose, are the rotations in radians? Not clear where 0.2 came from, some comment would help maintainers.
___
*[OpenSim/Simulation/Model/ModelComponent.cpp, line 151 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2932#-MRufFgr8qlhWXQMjrGU:-MRufFgs-BbNEWgyM9j7:b-84541e) ([raw file](https://github.com/opensim-org/opensim-core/blob/6b8392e17377745c0ed25fdfc62a6915efd98282/OpenSim/Simulation/Model/ModelComponent.cpp#L151)):*
> ```cpp
> 
>     for (int i = 0; i < size; ++i)
>         if (scaleSet[i].getSegmentName() == baseFrameName)
> ```

I'd put braces around the for loop to avoid future mistakes now that there are nested if statements or just && the two conditions
___
*[OpenSim/Simulation/SimbodyEngine/ScapulothoracicJoint.cpp, line 137 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2932#-MRug4fKBR38QMzBQzt5:-MRug4fKBR38QMzBQzt6:bcxwtlx) ([raw file](https://github.com/opensim-org/opensim-core/blob/6b8392e17377745c0ed25fdfc62a6915efd98282/OpenSim/Simulation/SimbodyEngine/ScapulothoracicJoint.cpp#L137)):*
> ```cpp
>     // Scaling related to the parent body:
>     // Get scale factors (if an entry for the parent Frame's base Body exists).
>     const Vec3& scaleFactorsP = getScaleFactors(scaleSet, getParentFrame());
> ```

If we have a chain of Frames(e.g. Offsets etc.), would that work, or we should track this up to an actual Body as ScaleSet contains Bodies only) If that's not supported would be good to note in a comment.
___
*[OpenSim/Simulation/SimbodyEngine/Test/testJoints.cpp, line 47 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2932#-MRuuOu_2pXySIpdfw5c:-MRuuOua-llOWpTCTtNH:byzb1rg) ([raw file](https://github.com/opensim-org/opensim-core/blob/6b8392e17377745c0ed25fdfc62a6915efd98282/OpenSim/Simulation/SimbodyEngine/Test/testJoints.cpp#L47)):*
> ```cpp
> 
> #include <OpenSim/Auxiliary/auxiliaryTestFunctions.h>
> #include <OpenSim/Common/Constant.h>
> ```

The formatting of the whole file has changed making it impossible to see the changes specific to this PR, can you revert the formatting change or point out what was intentionally changed in this file? Thank you

**Comment by aseth1** [comment]
@aymanhab Thanks for the quick review. Addressing your comments:
1. 0.2 tolerance is for joint angles in degrees and comes from the previous IK tests. Translations in the Scapulothoracic model (its base) are of no real concern. I added comments that angles are in degrees.
2. Braces added.
3. Yes, `ModelComponent::getScaleFactors()` finds the scale factors of its base frame and a chain of OffsetFramess have the same base frame, which is a PhysicalFrame (Ground or a Body).
4. Sorry, I didn't realize that Clang formatter was turned on in my VS after an update. The formatting is actually better (now conforms to 80 chars), so if you don't mind keeping I would rather not revert. The actual changes to `testJoints.cpp` are contained in `testScapulothoracicJoint()` [here](https://github.com/opensim-org/opensim-core/pull/2932/files#diff-6c90911af24dd43d2f33de37d253acc58e088d34aa47211a106ddff3aff5b29eR1276-R1357)

**Review by aymanhab — APPROVED** [review]
> Reviewed 1 of 9 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2932)* status: all files reviewed, 3 unresolved discussions (waiting on @aseth1)

**Review by aymanhab — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2932#-:-MS67gZs9hILsl7MuM3l:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @aseth1)

**Review by aymanhab — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2932#-:-MS67j4b6QwOmdAWyS8y:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @aseth1)

**Pull request merged**
