### PR TITLE
Add utility class `LatinHypercubeDesign`

### PR DESCRIPTION
**Pull request by nickbianco**
Fixes issue #3570

### Brief summary of changes
Added `LatinHypercubeDesign`, a class for generating Latin hypercube designs using random and algorithm methods. See #3570 for more details about the algorithms implemented.

Add

### Testing I've completed
Lots of local testing and comparisons to Matlab's `lhsdesign`. Everything seems to work as expected. Happy to add unit tests if desired (for the aspects of the class that are not randomized).

### CHANGELOG.md (choose one)
- updated.

- - -
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3573)

### CODE REVIEW

**Comment by nickbianco** [comment]
@carmichaelong, let me know if you have some cycles to review this one.

**Comment by nickbianco** [comment]
Reminder for myself: replace all `Logger::info` instances with `log_info`.

**Comment by nickbianco** [comment]
More reminders:
- Randomly sample around design points (i.e., `design -= SimTK::Test::randMatrix(numSamples, numVariables);`, make sure [-1, 1])
- Add unit tests for TPLHD

**Review by carmichaelong — CHANGES_REQUESTED** [review]
@nickbianco finished a pass through. i felt good with reviewing most sections, except the very short section within the reshapeTPLHD section on eliminating empty coordinates. happy to chat about any piece that's unclear, or if it seems like i misunderstood some of the code here or in the original papers

> Reviewed 3 of 5 files at r1, 1 of 1 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3573#-:-Nga3Ki38tXSeF7wCXsi:b-56ea9y)* status: all files reviewed (commit messages unreviewed), 15 unresolved discussions (waiting on @nickbianco)

___
*[`OpenSim/Common/CommonUtilities.h` line 177 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3573#-NgR73ng6OwYmH_2clzy:-NgR73nhCeO9luf2w7HV:bfa0x7w) ([raw file](https://github.com/opensim-org/opensim-core/blob/96a5f3f1adb351fd693e879e91cbad867e553fb6/OpenSim/Common/CommonUtilities.h#L177)):*
> ```objc
> /// @ingroup commonutil
> OSIMCOMMON_API SimTK::Matrix computeKNearestNeighbors(const SimTK::Matrix& x,
>         const SimTK::Matrix& y, int k = 1);
> ```

for consistency, should this be capital 'K'?
___
*[`OpenSim/Common/LatinHypercubeDesign.h` line 56 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3573#-NgPw2TyErR06PWo9vSV:-NgPw2TyErR06PWo9vSW:b-gi8aaw) ([raw file](https://github.com/opensim-org/opensim-core/blob/96a5f3f1adb351fd693e879e91cbad867e553fb6/OpenSim/Common/LatinHypercubeDesign.h#L56)):*
> ```objc
>  * used to evaluate each design. The distance criterion can be either "maximin"
>  * or "phi_p", where "maximin" is the default. The "phi_p" distance criterion
>  * is a approximation of the "maximin" criterion that can be used to generate
> ```

a -> an
___
*[`OpenSim/Common/LatinHypercubeDesign.h` line 57 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3573#-NgPw3jiAZarWub4PTsG:-NgPw3jiAZarWub4PTsH:bj7eoun) ([raw file](https://github.com/opensim-org/opensim-core/blob/96a5f3f1adb351fd693e879e91cbad867e553fb6/OpenSim/Common/LatinHypercubeDesign.h#L57)):*
> ```objc
>  * or "phi_p", where "maximin" is the default. The "phi_p" distance criterion
>  * is a approximation of the "maximin" criterion that can be used to generate
>  * designs with a using inverse distances raised to a large exponent (see [2]
> ```

i don't quite follow this sentence. perhaps it should be "... that can be used to generate designs that minimize the sum of inverse distances raised to a large exponent"?
___
*[`OpenSim/Common/LatinHypercubeDesign.h` line 87 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3573#-NgZyqMe2JIhWbA4-wuF:-NgPwpW04wn6CGYthbrY:b87fftw) ([raw file](https://github.com/opensim-org/opensim-core/blob/96a5f3f1adb351fd693e879e91cbad867e553fb6/OpenSim/Common/LatinHypercubeDesign.h#L87)):*
> ```objc
>  * @endcode
>  *
>  * Lower design scores are better. The "maximin" criterion returns a negative
> ```

I was confused at first and expected that it would be better for a "maximin" function to be larger. Looking at the code, it looks like you've (actively) added a negative sign so that a lower number is better. Perhaps the note as written here sounds like the "maximin" criterion inherently returns a negative number?
___
*[`OpenSim/Common/LatinHypercubeDesign.h` line 89 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3573#-NgPwv-N9ZFobW_EGKdM:-NgPwv-N9ZFobW_EGKdN:bmk4zpi) ([raw file](https://github.com/opensim-org/opensim-core/blob/96a5f3f1adb351fd693e879e91cbad867e553fb6/OpenSim/Common/LatinHypercubeDesign.h#L89)):*
> ```objc
>  * Lower design scores are better. The "maximin" criterion returns a negative
>  * value since it is a maximization criterion, while the "phi_p" criterion
>  * returns a positive value since it is a minimization criterion.
> ```

Perhaps worth to emphasize that a user can't compare scores between the two criteria?
___
*[`OpenSim/Common/LatinHypercubeDesign.h` line 98 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3573#-NgPx2xm5IarhQ3Cs-TX:-NgPx2xm5IarhQ3Cs-TY:befrm0a) ([raw file](https://github.com/opensim-org/opensim-core/blob/96a5f3f1adb351fd693e879e91cbad867e553fb6/OpenSim/Common/LatinHypercubeDesign.h#L98)):*
> ```objc
>  *
>  * To rapidly create Latin hypercube designs with a small number of samples
>  * (less than 25) and variables (less than 5),
> ```

less -> fewer (in both cases)
___
*[`OpenSim/Common/LatinHypercubeDesign.cpp` line 130 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3573#-Ng_yA3034NVWKkYt0D1:-Ng_yA3034NVWKkYt0D2:brdch72) ([raw file](https://github.com/opensim-org/opensim-core/blob/dc892f0680bbeed45b12f07b8b3593711b37ecf5/OpenSim/Common/LatinHypercubeDesign.cpp#L130)):*
> ```cpp
>             currentDesign = computeTranslationalPropagationDesign(
>                     m_numSamples, seed);
>             currentDesign /= m_numSamples;
> ```

what's the rationale for normalizing the designs outside of the `compute` functions?
___
*[`OpenSim/Common/LatinHypercubeDesign.cpp` line 241 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3573#-Ng_0KhOCn0jqqUSSuj5:-Ng_0KhP1iV_Z0qOym-4:b-pfr0o0) ([raw file](https://github.com/opensim-org/opensim-core/blob/dc892f0680bbeed45b12f07b8b3593711b37ecf5/OpenSim/Common/LatinHypercubeDesign.cpp#L241)):*
> ```cpp
>             const SimTK::RowVectorView row_j = design.row(j);
>             double distance = (row_j - row_i).abs().sum();
>             sumInverseDistancesP += pow(distance, 1.0 / m_phiDistanceExponent);
> ```

should this be `pow(1.0 / distance, m_phiDistanceExponent);`?
___
*[`OpenSim/Common/LatinHypercubeDesign.cpp` line 268 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3573#-Ng_5e5aBv5vgFFWTidk:-Ng_5e5aBv5vgFFWTidl:b-dszrtx) ([raw file](https://github.com/opensim-org/opensim-core/blob/dc892f0680bbeed45b12f07b8b3593711b37ecf5/OpenSim/Common/LatinHypercubeDesign.cpp#L268)):*
> ```cpp
>            std::pow(numSamples / numSeedPoints, 1.0 / numVariables);
>     int numDivisionsRounded = (int)std::ceil(numDivisions);
>     int numSeeds;
> ```

perhaps `numSeeds` -> `numBlocks`? this would be more in line with the paper and could make the code easier to read
___
*[`OpenSim/Common/LatinHypercubeDesign.cpp` line 277 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3573#-Ng_fGDd4yALBFWHE3Le:-Ng_fGDd4yALBFWHE3Lf:bu4ziv5) ([raw file](https://github.com/opensim-org/opensim-core/blob/dc892f0680bbeed45b12f07b8b3593711b37ecf5/OpenSim/Common/LatinHypercubeDesign.cpp#L277)):*
> ```cpp
>     int numSamplesRounded = numSeeds * numSeedPoints;
> 
>     // Reshape the seed to create the first design.
> ```

for this section and the rest, i focused on translation from the paper's MATLAB code, and less on if it made sense on a higher level
___
*[`OpenSim/Common/LatinHypercubeDesign.cpp` line 299 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3573#-Ng_ojAGEESxEZHy8-Pu:-Ng_ojAGEESxEZHy8-Pv:b-zcz9qf) ([raw file](https://github.com/opensim-org/opensim-core/blob/dc892f0680bbeed45b12f07b8b3593711b37ecf5/OpenSim/Common/LatinHypercubeDesign.cpp#L299)):*
> ```cpp
>     }
> 
>     // Create the TPLHD.
> ```

if there the seed already has sufficient numbers of samples, can this part be skipped?
___
*[`OpenSim/Common/LatinHypercubeDesign.cpp` line 377 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3573#-Ng_vTXl17JH_020Ibgj:-Ng_vTXl17JH_020Ibgk:b-22ktcl) ([raw file](https://github.com/opensim-org/opensim-core/blob/dc892f0680bbeed45b12f07b8b3593711b37ecf5/OpenSim/Common/LatinHypercubeDesign.cpp#L377)):*
> ```cpp
>            tplhdResized.updCol(ivar) += 1;
> 
>            // Eliminate empty coordinates.
> ```

this section (Eliminate empty coordinates) differs quite a bit from the published MATLAB code. the MATLAB code is also a little opaque to me (i did a little bit of testing to get a sense of it though)

regardless of the MATLAB code, i'm reading this section that it will turn every column into: `[1, 2, 3, ... numSamples]'`, which doesn't seem to match the MATLAB code's intention
___
*[`OpenSim/Common/LatinHypercubeDesign.cpp` line 515 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3573#-Nga2T8X1i43inIk3Sdc:-Nga2T8Y99CB_W53jN0L:b-euq0e7) ([raw file](https://github.com/opensim-org/opensim-core/blob/dc892f0680bbeed45b12f07b8b3593711b37ecf5/OpenSim/Common/LatinHypercubeDesign.cpp#L515)):*
> ```cpp
>             }
>         } else {
>             if (acceptanceRatio > 0.1) {
> ```

flip to a less than (`<`) sign?
___
*[`OpenSim/Common/LatinHypercubeDesign.cpp` line 567 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3573#-NgZstTN3adK39vlfwKj:-NgZstTN3adK39vlfwKk:b-x4puyw) ([raw file](https://github.com/opensim-org/opensim-core/blob/dc892f0680bbeed45b12f07b8b3593711b37ecf5/OpenSim/Common/LatinHypercubeDesign.cpp#L567)):*
> ```cpp
>         // Generate a random hypercube and normalize it.
>         design = computeRandomHypercube(numSamples, numVariables);
>         design -= SimTK::Test::randMatrix(numSamples, numVariables);
> ```

is adding a little bit of noise here intentional? if so, perhaps add that note in the comment a couple lines above.

also, looks like `randMatrix()` eventually calls `randReal()` which generates numbers between -1 and 1. since `computeRandomHypercube()` creates a matrix with numbers that are not normalized, will this noise be relatively larger for smaller hypercubes?
___
*[`OpenSim/Common/LatinHypercubeDesign.cpp` line 568 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3573#-NgZubCK-Tm-QbstIRzu:-NgZubCK-Tm-QbstIRzv:b-1b3x4p) ([raw file](https://github.com/opensim-org/opensim-core/blob/dc892f0680bbeed45b12f07b8b3593711b37ecf5/OpenSim/Common/LatinHypercubeDesign.cpp#L568)):*
> ```cpp
>         design = computeRandomHypercube(numSamples, numVariables);
>         design -= SimTK::Test::randMatrix(numSamples, numVariables);
>         design /= numSamples;
> ```

consider moving this normalization step into `computeRandomHypercube()` (unless there is a use to having this function return a not-normalized matrix). seems like it's dependent on knowing that the output from that function returns a not-normalized hypercube that goes up to `numSamples`.

depending on possible use cases downstream, these two functions could also be combined into one function

**Review by nickbianco — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3573)* status: all files reviewed (commit messages unreviewed), 15 unresolved discussions (waiting on @carmichaelong)

___
*[`OpenSim/Common/CommonUtilities.h` line 177 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3573#-NgR73ng6OwYmH_2clzy:-NgeHsa37kWpVYdKhRlw:b-p8yc4t) ([raw file](https://github.com/opensim-org/opensim-core/blob/96a5f3f1adb351fd693e879e91cbad867e553fb6/OpenSim/Common/CommonUtilities.h#L177)):*
<details><summary><i>Previously, carmichaelong wrote…</i></summary><blockquote>

for consistency, should this be capital 'K'?
</blockquote></details>

I changed the capital K in the comment to 'k' for consistency with the rest fo the doc comments. The function signature has a capital K since it uses camel case.
___
*[`OpenSim/Common/LatinHypercubeDesign.h` line 56 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3573#-NgPw2TyErR06PWo9vSV:-NgeJRtg9IPQRKzMjMH5:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/96a5f3f1adb351fd693e879e91cbad867e553fb6/OpenSim/Common/LatinHypercubeDesign.h#L56)):*
<details><summary><i>Previously, carmichaelong wrote…</i></summary><blockquote>

a -> an
</blockquote></details>

Done.
___
*[`OpenSim/Common/LatinHypercubeDesign.h` line 57 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3573#-NgPw3jiAZarWub4PTsG:-NgeJhpj0KafX3VDa8Kg:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/96a5f3f1adb351fd693e879e91cbad867e553fb6/OpenSim/Common/LatinHypercubeDesign.h#L57)):*
<details><summary><i>Previously, carmichaelong wrote…</i></summary><blockquote>

i don't quite follow this sentence. perhaps it should be "... that can be used to generate designs that minimize the sum of inverse distances raised to a large exponent"?
</blockquote></details>

Done.
___
*[`OpenSim/Common/LatinHypercubeDesign.h` line 87 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3573#-NgZyqMe2JIhWbA4-wuF:-NgeK9AyA__BD42lC1My:bz4ddum) ([raw file](https://github.com/opensim-org/opensim-core/blob/96a5f3f1adb351fd693e879e91cbad867e553fb6/OpenSim/Common/LatinHypercubeDesign.h#L87)):*
<details><summary><i>Previously, carmichaelong wrote…</i></summary><blockquote>

I was confused at first and expected that it would be better for a "maximin" function to be larger. Looking at the code, it looks like you've (actively) added a negative sign so that a lower number is better. Perhaps the note as written here sounds like the "maximin" criterion inherently returns a negative number?
</blockquote></details>

Rephrased for clarity.
___
*[`OpenSim/Common/LatinHypercubeDesign.h` line 89 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3573#-NgPwv-N9ZFobW_EGKdM:-NgeKWGD2vLT8aUTP87X:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/96a5f3f1adb351fd693e879e91cbad867e553fb6/OpenSim/Common/LatinHypercubeDesign.h#L89)):*
<details><summary><i>Previously, carmichaelong wrote…</i></summary><blockquote>

Perhaps worth to emphasize that a user can't compare scores between the two criteria?
</blockquote></details>

Done.
___
*[`OpenSim/Common/LatinHypercubeDesign.h` line 98 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3573#-NgPx2xm5IarhQ3Cs-TX:-NgeKcDqEiTkuVUBHaN8:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/96a5f3f1adb351fd693e879e91cbad867e553fb6/OpenSim/Common/LatinHypercubeDesign.h#L98)):*
<details><summary><i>Previously, carmichaelong wrote…</i></summary><blockquote>

less -> fewer (in both cases)
</blockquote></details>

Done.
___
*[`OpenSim/Common/LatinHypercubeDesign.cpp` line 130 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3573#-Ng_yA3034NVWKkYt0D1:-NgeLpUj9toAo5U-95Hf:brfmeaw) ([raw file](https://github.com/opensim-org/opensim-core/blob/dc892f0680bbeed45b12f07b8b3593711b37ecf5/OpenSim/Common/LatinHypercubeDesign.cpp#L130)):*
<details><summary><i>Previously, carmichaelong wrote…</i></summary><blockquote>

what's the rationale for normalizing the designs outside of the `compute` functions?
</blockquote></details>

This is leftover from an intermediate implmentation I had, where I used previous designs as initial seeds. Moving the normalization inside the `compute` function since that is not longer needed.
___
*[`OpenSim/Common/LatinHypercubeDesign.cpp` line 268 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3573#-Ng_5e5aBv5vgFFWTidk:-NgeM7uP0Jg6Ns5eX7GQ:bs5fhm5) ([raw file](https://github.com/opensim-org/opensim-core/blob/dc892f0680bbeed45b12f07b8b3593711b37ecf5/OpenSim/Common/LatinHypercubeDesign.cpp#L268)):*
<details><summary><i>Previously, carmichaelong wrote…</i></summary><blockquote>

perhaps `numSeeds` -> `numBlocks`? this would be more in line with the paper and could make the code easier to read
</blockquote></details>

Yes, that makes more sense.
___
*[`OpenSim/Common/LatinHypercubeDesign.cpp` line 277 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3573#-Ng_fGDd4yALBFWHE3Le:-NgeMAF47PAa8VDJoECu:b-71ok20) ([raw file](https://github.com/opensim-org/opensim-core/blob/dc892f0680bbeed45b12f07b8b3593711b37ecf5/OpenSim/Common/LatinHypercubeDesign.cpp#L277)):*
<details><summary><i>Previously, carmichaelong wrote…</i></summary><blockquote>

for this section and the rest, i focused on translation from the paper's MATLAB code, and less on if it made sense on a higher level
</blockquote></details>

I did the same honestly. I verified against several different design sizes that I was getting the same solution as a the Matlab code. This could be added as a unit test if desired.
___
*[`OpenSim/Common/LatinHypercubeDesign.cpp` line 299 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3573#-Ng_ojAGEESxEZHy8-Pu:-NgeMix7BxvNcS2MkJXV:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/dc892f0680bbeed45b12f07b8b3593711b37ecf5/OpenSim/Common/LatinHypercubeDesign.cpp#L299)):*
<details><summary><i>Previously, carmichaelong wrote…</i></summary><blockquote>

if there the seed already has sufficient numbers of samples, can this part be skipped?
</blockquote></details>

Done.
___
*[`OpenSim/Common/LatinHypercubeDesign.cpp` line 377 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3573#-Ng_vTXl17JH_020Ibgj:-NgeNvm5Ef_UTm_zcI_p:bt2ibny) ([raw file](https://github.com/opensim-org/opensim-core/blob/dc892f0680bbeed45b12f07b8b3593711b37ecf5/OpenSim/Common/LatinHypercubeDesign.cpp#L377)):*
<details><summary><i>Previously, carmichaelong wrote…</i></summary><blockquote>

this section (Eliminate empty coordinates) differs quite a bit from the published MATLAB code. the MATLAB code is also a little opaque to me (i did a little bit of testing to get a sense of it though)

regardless of the MATLAB code, i'm reading this section that it will turn every column into: `[1, 2, 3, ... numSamples]'`, which doesn't seem to match the MATLAB code's intention
</blockquote></details>

Resolved via in-person discussion.
___
*[`OpenSim/Common/LatinHypercubeDesign.cpp` line 515 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3573#-Nga2T8X1i43inIk3Sdc:-NgeRibX1M1IAOJSPKPc:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/dc892f0680bbeed45b12f07b8b3593711b37ecf5/OpenSim/Common/LatinHypercubeDesign.cpp#L515)):*
<details><summary><i>Previously, carmichaelong wrote…</i></summary><blockquote>

flip to a less than (`<`) sign?
</blockquote></details>

Done.

**Review by nickbianco — COMMENTED** [review]
@carmichaelong thanks for the careful review! I've hopefully addressed all of your comments appropriately (the ESEA design works much better now), and have added some testing.

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3573#-:-NgenENLCHtdDiXnrXqD:bpwxtul)* status: 2 of 6 files reviewed, 15 unresolved discussions (waiting on @carmichaelong)

___
*[`OpenSim/Common/LatinHypercubeDesign.cpp` line 241 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3573#-Ng_0KhOCn0jqqUSSuj5:-Ngedghn51ZGTbl0Jxyf:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/dc892f0680bbeed45b12f07b8b3593711b37ecf5/OpenSim/Common/LatinHypercubeDesign.cpp#L241)):*
<details><summary><i>Previously, carmichaelong wrote…</i></summary><blockquote>

should this be `pow(1.0 / distance, m_phiDistanceExponent);`?
</blockquote></details>

Done.
___
*[`OpenSim/Common/LatinHypercubeDesign.cpp` line 567 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3573#-NgZstTN3adK39vlfwKj:-Nge_XKA734T7GFDBcpU:b-egz9ds) ([raw file](https://github.com/opensim-org/opensim-core/blob/dc892f0680bbeed45b12f07b8b3593711b37ecf5/OpenSim/Common/LatinHypercubeDesign.cpp#L567)):*
<details><summary><i>Previously, carmichaelong wrote…</i></summary><blockquote>

is adding a little bit of noise here intentional? if so, perhaps add that note in the comment a couple lines above.

also, looks like `randMatrix()` eventually calls `randReal()` which generates numbers between -1 and 1. since `computeRandomHypercube()` creates a matrix with numbers that are not normalized, will this noise be relatively larger for smaller hypercubes?
</blockquote></details>

It is intentionally applied to the non-normalized design. Each row in the design matrix essentially represents coordinates to the location of a sample in the hypercube space (i.e., in 2-D, the "grid"). I actually want to sample between 0 and 1 here, since that will be equivalent to randomly sampling around the midpoint between two indices in the grid. Without the random sampling, the design points will lie directly on the indices in the grid. (Hopefully that makes sense).
___
*[`OpenSim/Common/LatinHypercubeDesign.cpp` line 568 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3573#-NgZubCK-Tm-QbstIRzu:-NgedDza8VGcCufVs9-P:bxh1wop) ([raw file](https://github.com/opensim-org/opensim-core/blob/dc892f0680bbeed45b12f07b8b3593711b37ecf5/OpenSim/Common/LatinHypercubeDesign.cpp#L568)):*
<details><summary><i>Previously, carmichaelong wrote…</i></summary><blockquote>

consider moving this normalization step into `computeRandomHypercube()` (unless there is a use to having this function return a not-normalized matrix). seems like it's dependent on knowing that the output from that function returns a not-normalized hypercube that goes up to `numSamples`.

depending on possible use cases downstream, these two functions could also be combined into one function
</blockquote></details>

Per the comment above, I don't want to normalize in `computeRandomHypercube()` here. I also use `computeRandomHypercube()` to initialize the translational propagation algorithm, which needs an unnormalized design for each seed.

**Review by carmichaelong — CHANGES_REQUESTED** [review]
thanks @nickbianco, looks great. just two minor comments

> Reviewed 2 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3573#-:-NgfIgf25ZYynk4emQ_v:b-alxc5j)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @nickbianco)

___
*[`OpenSim/Common/LatinHypercubeDesign.h` line 251 at r4](https://reviewable.io/reviews/opensim-org/opensim-core/3573#-NgfIRyM15QUBozRIK4Z:-NgfIRyM15QUBozRIK4_:bnius1c) ([raw file](https://github.com/opensim-org/opensim-core/blob/f0163c4600a8ec939b5d124b57c3130bf7394843/OpenSim/Common/LatinHypercubeDesign.h#L251)):*
> ```objc
>      * Helper functions for computing random Latin hypercube designs.
>      */
>     static SimTK::Matrix computeRandomMatrix(
> ```

could be helpful for maintainability to just add a short (OK for developer) comment on the purpose of each of these 3 functions, including if it returns normalized or un-normalized values
___
*[`OpenSim/Common/LatinHypercubeDesign.cpp` line 299 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3573#-Ng_ojAGEESxEZHy8-Pu:-NgfF6X49hQJRbGVwxKC:bhol0oc) ([raw file](https://github.com/opensim-org/opensim-core/blob/dc892f0680bbeed45b12f07b8b3593711b37ecf5/OpenSim/Common/LatinHypercubeDesign.cpp#L299)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

also if `seed.nrow() > m_numSamples`, can you also skip to the resize step?

**Review by nickbianco — COMMENTED** [review]
@carmichaelong ready for review.

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3573#-:-NgfOtPI0hvVNd1w-HNB:b-qvrgpw)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @carmichaelong)

___
*[`OpenSim/Common/LatinHypercubeDesign.h` line 251 at r4](https://reviewable.io/reviews/opensim-org/opensim-core/3573#-NgfIRyM15QUBozRIK4Z:-NgfOsjA50WYRG7eGfbG:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/f0163c4600a8ec939b5d124b57c3130bf7394843/OpenSim/Common/LatinHypercubeDesign.h#L251)):*
<details><summary><i>Previously, carmichaelong wrote…</i></summary><blockquote>

could be helpful for maintainability to just add a short (OK for developer) comment on the purpose of each of these 3 functions, including if it returns normalized or un-normalized values
</blockquote></details>

Done.
___
*[`OpenSim/Common/LatinHypercubeDesign.cpp` line 299 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3573#-Ng_ojAGEESxEZHy8-Pu:-NgfN7rqBhQzU0-fn2sS:bpsd4dg) ([raw file](https://github.com/opensim-org/opensim-core/blob/dc892f0680bbeed45b12f07b8b3593711b37ecf5/OpenSim/Common/LatinHypercubeDesign.cpp#L299)):*
<details><summary><i>Previously, carmichaelong wrote…</i></summary><blockquote>

also if `seed.nrow() > m_numSamples`, can you also skip to the resize step?
</blockquote></details>

I prefer preventing this possibility with an exception macro (which I've now done).

**Review by carmichaelong — APPROVED** [review]
:lgtm: though looks like there's a merge conflict on `CHANGELOG.md` of all files

> Reviewed 1 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3573#-:-NgfUXxT0rZW4T0NKzy3:bw0bgy7)* status: 5 of 6 files reviewed, all discussions resolved (waiting on @nickbianco)

**Comment by nickbianco** [comment]
Thanks @carmichaelong! Windows failure is unrelated, merging.

**Pull request merged**
