### PR TITLE
included MocoOutputExtremumGoal functionality

### PR DESCRIPTION
**Pull request by nicos1993**
### Brief summary of changes
Within MocoOutputGoal.h/.cpp I, with the help of Reed and Nick, have included a new goal, MocoOutputGoalExtremum, it is very similar to the original MocoOutputGoal. The goal permits the integration of only positive or negative values from a model output.

### Testing I've completed
So far I have tested it locally on the walking_2d.cpp example and it is producing results as anticipated.

### CHANGELOG.md (choose one)
I think I need to update the CHANGELOG_MOCO.md to include the 'MocoOutputGoalExtremum'.

- - -
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3293)

### CODE REVIEW

**Review by nickbianco — CHANGES_REQUESTED** [review]
Nice addition @nicos1993! I have a handful of comments, mostly related to documentation.

> I think I need to update the CHANGELOG_MOCO.md to include the 'MocoOutputGoalExtremum'.

Yes, you should. I think we forgot to do this for `MocoContactImpulseTrackingGoal`. Could you update the change log for that addition too (with the appropriate date)?

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3293#-:-NBsp9jw8EzD-zbeE5Ia:b-d66r3n)* status: all files reviewed, 5 unresolved discussions (waiting on @nicos1993)

___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.h` line 197 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3293#-NBsh9x8CTVheCm0QqBy:-NBsh9x8CTVheCm0QqBz:b-nknj56) ([raw file](https://github.com/opensim-org/opensim-core/blob/212c4707a7b4a6b591ed738d353ab040a9e8790a/OpenSim/Moco/MocoGoal/MocoOutputGoal.h#L197)):*
> ```objc
> 
> /** This goal permits the integration of only positive or negative values from a
> model Output. This goal allows you to use model Outputs of type double, and a 
> ```

--> "...type double, or a single...."
___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.h` line 199 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3293#-NBshHCj2T-cwZg6P89H:-NBshHCj2T-cwZg6P89I:bjhjnco) ([raw file](https://github.com/opensim-org/opensim-core/blob/212c4707a7b4a6b591ed738d353ab040a9e8790a/OpenSim/Moco/MocoGoal/MocoOutputGoal.h#L199)):*
> ```objc
> model Output. This goal allows you to use model Outputs of type double, and a 
> single specified element from an Output of type SimTK::Vec3 and 
> SimTK::SpatialVec in the integrand of a goal. You can also specify the exponent
> ```

--> "...of type SimTK::Vec3 or SimTK::SpatialVec..."
___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.h` line 200 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3293#-NBskrgGEdvGyG34__ah:-NBskrgGEdvGyG34__ai:b-oxfzjr) ([raw file](https://github.com/opensim-org/opensim-core/blob/212c4707a7b4a6b591ed738d353ab040a9e8790a/OpenSim/Moco/MocoGoal/MocoOutputGoal.h#L200)):*
> ```objc
> single specified element from an Output of type SimTK::Vec3 and 
> SimTK::SpatialVec in the integrand of a goal. You can also specify the exponent
> of the value in the integrand via 'setExponent()'. */
> ```

You should include a description and math of how the log-exp function approximates the extremum and describe how the `extremum_scaler` applies to this approximation.
___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.h` line 225 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3293#-NBshfhX7RqUQc-tOHS7:-NBshfhX7RqUQc-tOHS8:b-h76gb6) ([raw file](https://github.com/opensim-org/opensim-core/blob/212c4707a7b4a6b591ed738d353ab040a9e8790a/OpenSim/Moco/MocoGoal/MocoOutputGoal.h#L225)):*
> ```objc
>     bool getDivideByMass() const { return get_divide_by_mass(); }
> 
>     /** Set the type of extremum (min or max) to be applied to the output
> ```

I'd prefer these settings to be full words, i.e., 'minimum' and 'maximum'. Include the quotes too to indicate that they are string arguments.
___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.h` line 233 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3293#-NBsnqMM9POyW5zXAaA7:-NBsnqMM9POyW5zXAaA8:bosf5mz) ([raw file](https://github.com/opensim-org/opensim-core/blob/212c4707a7b4a6b591ed738d353ab040a9e8790a/OpenSim/Moco/MocoGoal/MocoOutputGoal.h#L233)):*
> ```objc
> 
>     /** Set the scaling factor used for the extremum approximation. */
>     void setExtremumScaler(double extremum_scaler) {
> ```

Is this factor a smoothing term? Something more descriptive would be better, i.e., 'smoothing_factor', etc.

**Comment by nicos1993** [comment]
I will update for the MocoContactImpulseTrackingGoal for now. Will update for this once we resolve everything (?).

**Review by nickbianco — CHANGES_REQUESTED** [review]
Thanks for the updates! Just a few more small comments to address.

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3293#-:-NBy2Z9R5J-aWV9lAjc_:b-9qq5bn)* status: all files reviewed, 6 unresolved discussions (waiting on @nicos1993)

___
*[`CHANGELOG_MOCO.md` line 7 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3293#-NBy1wSt2cE9SeO2dGeW:-NBy1wSt2cE9SeO2dGeX:b-rryims) ([raw file](https://github.com/opensim-org/opensim-core/blob/be541411ff50f684d49dbcb029ba137a5ce4d30c/CHANGELOG_MOCO.md#L7)):*
> ```Markdown
> -----
> - 2022-09-07: Added MocoContactImpulseTrackingGoal.
> 			  
> ```

tabs --> spaces
___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.h` line 202 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3293#-NBy243V0sdjGOn-BM89:-NBy243V0sdjGOn-BM8A:b-c4q6fl) ([raw file](https://github.com/opensim-org/opensim-core/blob/be541411ff50f684d49dbcb029ba137a5ce4d30c/OpenSim/Moco/MocoGoal/MocoOutputGoal.h#L202)):*
> ```objc
> of the value in the integrand via 'setExponent()'. 
> 
> This goal performs an approximation to the extremum, minimum or maximum,
> ```

Consider saying explicitly that this is smooth approximation of the common "max()" and "min()" functions.
___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.h` line 216 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3293#-NBy1ml89pOSoEtZastt:-NBy1ml97ezQV0hSxAjD:bshuoe6) ([raw file](https://github.com/opensim-org/opensim-core/blob/be541411ff50f684d49dbcb029ba137a5ce4d30c/OpenSim/Moco/MocoGoal/MocoOutputGoal.h#L216)):*
> ```objc
> - \f$ v \f$: the output variable of choice.
> - \f$ w_v \f$: the weight for output variable \f$ v \f$.
> - \f$ B \f$: the approximate extremum to be taken (B = -1 for minimum;
> ```

If you want to use the beta symbol in LaTeX instead of "B", I believe it is `\beta`.
___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.h` line 222 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3293#-NBy-cFm4LgWBf1cHqIN:-NBy-cFnALlnnTWHh0pw:bsdwskx) ([raw file](https://github.com/opensim-org/opensim-core/blob/be541411ff50f684d49dbcb029ba137a5ce4d30c/OpenSim/Moco/MocoGoal/MocoOutputGoal.h#L222)):*
> ```objc
>   to be taken, whilst if it is set to < 1 the approximation is further 
>   from the true extremum (more smoothing). For \f$ v \f$ with magnitudes
>   of around 2500 it is recommended to set this value as 0.2 to prevent the
> ```

You mean values greater than ~2500?  Why 0.2 specifically? You could provide more info in the property description below too.
___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.h` line 284 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3293#-NBy0yP50kJW27lnYo1v:-NBy0yP50kJW27lnYo1w:b6vguer) ([raw file](https://github.com/opensim-org/opensim-core/blob/be541411ff50f684d49dbcb029ba137a5ce4d30c/OpenSim/Moco/MocoGoal/MocoOutputGoal.h#L284)):*
> ```objc
>     OpenSim_DECLARE_PROPERTY(smoothing_factor, double,
>             "The smoothing factor applied in the approximation of the "
>             " extremum function (Default extremum scaler = 1).");
> ```

--> "(default = 1)".

You could also make a comment here that it is recommended to reduce this value when the output value is large (i.e., > 2500).

**Review by nickbianco — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3293)* status: all files reviewed, 2 unresolved discussions (waiting on @nicos1993)

___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.h` line 223 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3293#-NC1CaMi0PxtFlBoaTvq:-NC1CaMi0PxtFlBoaTvr:bs7cilf) ([raw file](https://github.com/opensim-org/opensim-core/blob/32600a5f77b8fa3b26648ac74c92db121d3c02de/OpenSim/Moco/MocoGoal/MocoOutputGoal.h#L223)):*
> ```objc
>   to be taken, whilst if it is set to < 1 the approximation is further 
>   from the true extremum (more smoothing). For \f$ v \f$ with magnitudes
>   between 1-3000 during a simulation it is recommended to set this value
> ```

This is still confusing to me: wouldn't it be okay to use the default smoothing factor for values between 1-3000? I was expecting something along the line of "For output values with large magnitudes (i.e., > 2500), reduce the value of the smoothing parameter to avoid the exponential operator from producing Inf values."
___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.h` line 295 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3293#-NC1E3l3-JCufjCBT4Sc:-NC1E3l3-JCufjCBT4Sd:b-59e5md) ([raw file](https://github.com/opensim-org/opensim-core/blob/32600a5f77b8fa3b26648ac74c92db121d3c02de/OpenSim/Moco/MocoGoal/MocoOutputGoal.h#L295)):*
> ```objc
>             "smoothing_factor = 0.2; it returns 25.0335767. With output "
>             "variable = 25 and smoothing_factor = 1; it returns 25.0 "
>             "recurring.");
> ```

This is perhaps too much information for a property description. Considering something like my suggestion on the docs comment change above.

**Review by nickbianco — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3293)* status: all files reviewed, 6 unresolved discussions (waiting on @nicos1993)

___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.h` line 256 at r4](https://reviewable.io/reviews/opensim-org/opensim-core/3293#-NMAV05o8lKj2tsEmf0_:-NMAV05o8lKj2tsEmf0a:b-mg2c4q) ([raw file](https://github.com/opensim-org/opensim-core/blob/4f12023850b76585828d6c2b32d9f122071e5c79/OpenSim/Moco/MocoGoal/MocoOutputGoal.h#L256)):*
> ```objc
>     std::string getExtremumType() const { return get_extremum_type(); }
> 
>     /** Set the smoothing factor (Default = 1) used for the extremum
> ```

Make "default" lowercase, and put this parenthetical at the end of the sentence. Also, since the property is `double`, change `1` to `1.0`. 
___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.h` line 259 at r4](https://reviewable.io/reviews/opensim-org/opensim-core/3293#-NMAVFzn6HGwwA3ALxK9:-NMAVFzn6HGwwA3ALxKA:b-d1l4ro) ([raw file](https://github.com/opensim-org/opensim-core/blob/4f12023850b76585828d6c2b32d9f122071e5c79/OpenSim/Moco/MocoGoal/MocoOutputGoal.h#L259)):*
> ```objc
>     approximation. It is recommended to set this property to 0.2 to prevent
>     the calculation returning Inf in circumstances when the output may reach
>     large magnitudes (> 2000) during a simulation. */
> ```

It would be helpful to indicate that this value can be anywhere between [0.2, 1.0]. Consider something like "This value can be set between [0.2, 1.0]. For Outputs that may take on large values (> ~2000), it is recommended to set the smoother factor closer to 0.2.".
___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.h` line 289 at r4](https://reviewable.io/reviews/opensim-org/opensim-core/3293#-NMAXFWS3YtkGxd0JvLJ:-NMAXFWS3YtkGxd0JvLK:b-otilcs) ([raw file](https://github.com/opensim-org/opensim-core/blob/4f12023850b76585828d6c2b32d9f122071e5c79/OpenSim/Moco/MocoGoal/MocoOutputGoal.h#L289)):*
> ```objc
>             "potentially large magnitudes (> 2000) during a simulation "
>             "it is recommended to set this property to 0.2 to prevent "
>             "the calculation from reaching Inf.");
> ```

See comment above.
___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.cpp` line 232 at r4](https://reviewable.io/reviews/opensim-org/opensim-core/3293#-NMAUQQ0AvQOW2KJKhC3:-NMAUQQ0AvQOW2KJKhC4:buixlp0) ([raw file](https://github.com/opensim-org/opensim-core/blob/4f12023850b76585828d6c2b32d9f122071e5c79/OpenSim/Moco/MocoGoal/MocoOutputGoal.cpp#L232)):*
> ```cpp
>         const IntegrandInput& input, double& integrand) const {
>     OPENSIM_THROW_IF_FRMOBJ(
>             get_smoothing_factor() < 0.2 || get_smoothing_factor() > 1.0,
> ```

Make these `<= 0.2` and `>= 1.0`.

**Review by nickbianco — COMMENTED** [review]
Just a few more nit-picky comments to address, then we can merge.

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3293#-:-NMAXKrZDn14pkXdhIjj:b-q7sux9)* status: all files reviewed, 6 unresolved discussions (waiting on @nicos1993)

**Review by nickbianco — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3293)* status: all files reviewed, 5 unresolved discussions (waiting on @nicos1993)

___
*[`OpenSim/Moco/MocoGoal/MocoOutputGoal.h` line 223 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3293#-NC1CaMi0PxtFlBoaTvq:-NMAXYio0SiApayfCRHr:bsh9hql) ([raw file](https://github.com/opensim-org/opensim-core/blob/32600a5f77b8fa3b26648ac74c92db121d3c02de/OpenSim/Moco/MocoGoal/MocoOutputGoal.h#L223)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

This is still confusing to me: wouldn't it be okay to use the default smoothing factor for values between 1-3000? I was expecting something along the line of "For output values with large magnitudes (i.e., > 2500), reduce the value of the smoothing parameter to avoid the exponential operator from producing Inf values."
</blockquote></details>

Resolved with latest changes.

**Review by nickbianco — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3293#-:-NMAh130CSYvKpct6el6:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @nicos1993)

**Comment by nickbianco** [comment]
@nicos1993 actually, you should add an entry to the Moco changelog. Then were good to go.

**Pull request merged**
