### PR TITLE
hasColumnLabels() for DataTable

### PR DESCRIPTION
**Pull request by klshrinidhi**
Addressing #821.

### CODE REVIEW

**Comment by chrisdembia** [comment]
This looks good to me. What do you think about adding to the doxygen for `getColumnLabels()` that it throws an exception if there are no labels? You have nicely documented exceptions elsewhere. I know this is related to #821 and not this specific PR.

**Comment by klshrinidhi** [comment]
There is already a sentence in the documentation for `getColumnLabels()` that it throws if table has no column labels. You can see it [here in master](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Common/AbstractDataTable.h#L261).

**Comment by chrisdembia** [comment]
Oh oops! Thanks for pointing that out.

**Comment by klshrinidhi** [comment]
I will make some changes to provide a bit more meaningful exception and message for 'labels not found'. Will push the changes soon.

**Pull request merged**
