### PR TITLE
Added finalizeConnections() before the serialization of model to different examples

### PR DESCRIPTION
**Pull request by vinaym815**
Fixes issue #2526 

I have added finalizeConnections() to different C++ API examples before the model is serialized in them.

---
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2527)

### CODE REVIEW

**Comment by aymanhab** [comment]
@vinaym815 Please replace tabs with spaces as they causes ci to fail.

**Comment by vinaym815** [comment]
I think these changes shall suffice till changes to model.print() functions are not made.

**Comment by aymanhab** [comment]
I restarted the builds that were failing for unrelated reasons.

**Comment by aymanhab** [comment]
@aseth1 on a related note,  I ran into some other code that was working around a similar issue with finalizeFromProperties by calling print on a clone of the model 
https://github.com/opensim-org/opensim-core/blob/840bfac5d28a70a16335f441950bf669407031e2/OpenSim/Simulation/Test/testContactGeometry.cpp#L174

Do you think clone should call finalizeConnections() as well?

**Comment by aseth1** [comment]
@aymanhab we used clone to make sure that the non-const `print()` wasn't changing the model. Now that `print()` is const, there isn't a good reason to clone first IMHO. We can remove unnecessary clones. Note, that cloning is not the issue. If the original model topology changed (components added/removed) and you want those changes to be reflected in properties of Sockets, you must call finalizeConnections. In this case, the connections should be finalized before the `clone()`. The subsequent `print()` does not need to finalize to serialize since its properties are identical to the original.

**Comment by aymanhab** [comment]
The PR can be merged when the tests pass  but I'd leave this issue open until we move the discussion there and/or open issues as needed. Thanks for your contribution @vinaym815

**Comment by aymanhab** [comment]
Tests actually pass but uploading to sourceforge is broken (likely because of other admin/access issues). Merging

**Comment by jimmyDunne** [comment]
Thanks, @vinaym815 for contributing! Much appreciated :)

**Comment by vinaym815** [comment]
I just checked, their are other c++ examples with same command missing. Will add the same to them and submit a pull request.

**Pull request merged**
