### PR TITLE
Remove ContDerivMuscle_Deprecated

### PR DESCRIPTION
**Pull request by klshrinidhi**

### CODE REVIEW

**Comment by klshrinidhi** [comment]
This class seems to be using the variable `old_fiber_length` without initializing it.

**Comment by chrisdembia** [comment]
Can you add a note to CHANGELOG.md?

**Comment by klshrinidhi** [comment]
Updated *CHANGELOG.md*.

**Comment by aseth1** [comment]
@klshrinidhi can you resolve the conflict?

**Comment by klshrinidhi** [comment]
Resolved conflict.

**Comment by klshrinidhi** [comment]
All :white_check_mark: !!!

**Pull request merged**
