### PR TITLE
Descreamify cmake commands.

### PR DESCRIPTION
**Pull request by chrisdembia**
I ran a bash script that I found online to make cmake commands lower case.

I visually inspected every change, so I am very confident that these changes are safe.

I think this may be a good time to merge this change, if we agree we want it, since @aymanhab just finished a big merge.

Personally, I really like the result. Thanks @elen4 for suggesting.

I am not confident that I converted every single cmake command to lower case, but I think that's fine.

### CODE REVIEW

**Comment by sherm1** [comment]
Oh, that's really nice! Can you do that for Simbody too?

I'm good with merging this as soon as the builds complete!

**Comment by chrisdembia** [comment]
> Can you do that for Simbody too?

Would be my pleasure!

**Comment by chrisdembia** [comment]
@sherm1 would you like to merge this?

**Comment by sherm1** [comment]
Yes!

**Comment by chrisdembia** [comment]
Thank you

**Pull request merged**
