### PR TITLE
Wrapping performance and refactoring

### PR DESCRIPTION
**Pull request by aymanhab**
Fixes issue #<issue_number>

### CHANGELOG.md (choose one)

- no need to update because...
- updated.

---
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3114)

### CODE REVIEW

**Comment by aymanhab** [comment]
This can be reviewed and merged while localized before we go to more major refactoring, few macros removed. @carmichaelong

**Review by carmichaelong — CHANGES_REQUESTED** [review]
Thanks, looking good @aymanhab. Only some minor comments

> Reviewed 6 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3114#-:-Mqc4em79mi-uZndQoth:b-xf5oj8)* status: 6 of 7 files reviewed, 3 unresolved discussions (waiting on @aymanhab and @carmichaelong)

___
*[.github/workflows/continuous_integration.yml, line 199 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3114#-Mqax_5sEF-yPWSiRJnX:-Mqax_5sEF-yPWSiRJnY:bsp5rj0) ([raw file](https://github.com/opensim-org/opensim-core/blob/c95864043882afa6f0f70012ed1b3e626931c7be/.github/workflows/continuous_integration.yml#L199)):*
> ```YAML
> 
>     - name: Build dependencies
>       # if: steps.cache-dependencies.outputs.cache-hit != 'true'
> ```

I assume this is related to the github actions upgrade for mac os? If this line might get added back later, would be good to just add a comment to say when this should be uncommented (or if this line should be removed, could just remove it now)
___
*[OpenSim/Simulation/Model/GeometryPath.cpp, line 1062 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3114#-Mqc3a5uDLgKMSXn4xDR:-Mqc3a5uDLgKMSXn4xDS:bkqxzxz) ([raw file](https://github.com/opensim-org/opensim-core/blob/c95864043882afa6f0f70012ed1b3e626931c7be/OpenSim/Simulation/Model/GeometryPath.cpp#L1062)):*
> ```cpp
>         }
> 
>         if (kk == 0 && get_PathWrapSet().getSize() > 1) {
> ```

can use `wrapSetSize` again here
___
*[OpenSim/Simulation/Wrap/WrapMath.h, line 74 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3114#-Mqc2Rlk2HNqjQrgDwva:-Mqc2Rlk2HNqjQrgDwvb:bkj6nlo) ([raw file](https://github.com/opensim-org/opensim-core/blob/c95864043882afa6f0f70012ed1b3e626931c7be/OpenSim/Simulation/Wrap/WrapMath.h#L74)):*
> ```objc
>         SimTK::Vec3 pToLinePt = (linePt - point);
>         SimTK::Vec3 n = line.normalize();
>         return (pToLinePt - (~pToLinePt * n) * n).scalarNormSqr();
> ```

minor: could use `normSqr()` instead for consistency

**Review by aymanhab — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3114)* status: 4 of 7 files reviewed, 2 unresolved discussions (waiting on @carmichaelong)

___
*[OpenSim/Simulation/Model/GeometryPath.cpp, line 1062 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3114#-Mqc3a5uDLgKMSXn4xDR:-MqlsUVDA0HXlf20fy63:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/c95864043882afa6f0f70012ed1b3e626931c7be/OpenSim/Simulation/Model/GeometryPath.cpp#L1062)):*
<details><summary><i>Previously, carmichaelong wrote…</i></summary><blockquote>

can use `wrapSetSize` again here
</blockquote></details>

Done.
___
*[.github/workflows/continuous_integration.yml, line 199 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3114#-Mqax_5sEF-yPWSiRJnX:-Mqlrtde2jhoJZjv0n24:bpmj4lr) ([raw file](https://github.com/opensim-org/opensim-core/blob/c95864043882afa6f0f70012ed1b3e626931c7be/.github/workflows/continuous_integration.yml#L199)):*
<details><summary><i>Previously, carmichaelong wrote…</i></summary><blockquote>

I assume this is related to the github actions upgrade for mac os? If this line might get added back later, would be good to just add a comment to say when this should be uncommented (or if this line should be removed, could just remove it now)
</blockquote></details>

@carmichaelong The line will be added later.  The issue is that the cached build was made with earlier compiler. Will undo this change here and update the cache on master branch instead.

**Review by carmichaelong — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3114#-:-Mqp65vrAQxcBd2m1nS4:bnfp4nl)* status: 6 of 7 files reviewed, all discussions resolved (waiting on @carmichaelong)

**Comment by aymanhab** [comment]
Thanks @carmichaelong 👍

**Pull request merged**
