### PR TITLE
[doxygen] Use Q_PROPERTY to document properties.

### PR DESCRIPTION
**Pull request by chrisdembia**
This is the version of PR #318 that should be merged.

### CODE REVIEW

**Comment by chrisdembia** [comment]
The changes are mainly in doxygen-layout.xml and Property.h. Most of the other changes are just for removing `@name Property declarations` from headers.

[You can view the resulting output here.](http://stanford.edu/~dembia/opensim-better-property-docs-2/html/)

**Comment by chrisdembia** [comment]
FYI @aymanhab this only creates two small merge conflicts with `geometry_integration_tabs`.

**Comment by sherm1** [comment]
Code changes look good to me (I looked at the main changes and randomly sampled a few of the component edits). We might also consider whether to forgo the 80-character limit for Property descriptions to avoid the weird quoting in doxygen. A better alternative might be to ask Dimitri to fix doxygen to combine adjacent strings automatically like the compiler does.

**Comment by chrisdembia** [comment]
> A better alternative might be to ask Dimitri to fix doxygen to combine adjacent strings automatically like the compiler does.

Is the compiler supposed to do this for strings passed into macros? I created a small example with which I can submit a bug report:

```
#define MYMACRO(name, comment) \                                                
    /** comment */             \                                                
    int name;                                                                   
                                                                                
class Foo {                                                                     
public:                                                                         
    MYMACRO(bar, "protein" "bar")                                               
    /** the first letter of the alphabet. */                                    
    int a;                                                                      
};
```

produces:

screen shot 2015-06-09 at 10 06 37 pm

@sherm1 when is a proper compiler/preprocessor/parser supposed to combine adjacent strings?

**Comment by sherm1** [comment]
> when is a proper compiler/preprocessor/parser supposed to combine adjacent strings?

Hmmm. Macros are just text substitution so it is probably good that the strings don't get combined there in C++. But Dimitri must be doing his own preprocessing if he is doing substitutions within comments -- that doesn't happen normally; instead the comments are removed prior to macro substitution. But that would be a problem for doxygen since comments are meaningful to it. My thought is that we should ask him to make doxygen do the string combining when processing macro arguments.

**Comment by sherm1** [comment]
[Here](http://www.stack.nl/~dimitri/doxygen/manual/preprocessing.html) is a discussion about preprocessing in Doxygen. No mention of how it treats adjacent strings; I think that would be an improvement.

**Comment by chrisdembia** [comment]
I submitted a bug report for doxygen: https://bugzilla.gnome.org/show_bug.cgi?id=750890.

Let me know if this PR requires anything else before merging.

**Comment by sherm1** [comment]
I think it is ready to merge. It would be good to have one more person look at it -- @jimmyDunne, @jenhicks ?

**Comment by chrisdembia** [comment]
Thanks for reviewing @sherm1

**Comment by sherm1** [comment]
@chrisdembia, I think some of the examples in the long `Property.h` documentation for class `Property` are wrong now that you have improved the doxygen for properties. There is advice there on how to document properties, but this PR makes that obsolete.

**Comment by chrisdembia** [comment]
> @chrisdembia, I think some of the examples in the long Property.h documentation for class Property are wrong now that you have improved the doxygen for properties. There is advice there on how to document properties, but this PR makes that obsolete.

Thanks for noticing this. I tried to update the documentation; see [here](https://github.com/opensim-org/opensim-core/pull/478/files#diff-d9fca5b50e92ed47f903c4ffacd31a6eL51). What do you think?

**Comment by sherm1** [comment]
Looks great now, Chris. Is this ready to merge?

**Comment by chrisdembia** [comment]
> Looks great now, Chris. Is this ready to merge?

I agree with your earlier comment that it would be nice if @jimmyDunne or @jenhicks could check it out. Perhaps the best venue is in a future dev meeting?

**Comment by jenhicks** [comment]
@chrisdembia Sorry for the delay. Is the output link up to date? What are the changes in the doxygen output that I should check out (e.g., what classes)?

**Comment by chrisdembia** [comment]
Hey Jen; here's an updated output link: http://stanford.edu/~dembia/opensim-better-property-docs-2-20150723/

Changes to check out:
- Body http://stanford.edu/~dembia/opensim-better-property-docs-2-20150723/classOpenSim_1_1Body.html (expand all the "Properties inherited from" sections).
- Model http://stanford.edu/~dembia/opensim-better-property-docs-2-20150723/classOpenSim_1_1Model.html
- Coordinate http://stanford.edu/~dembia/opensim-better-property-docs-2-20150723/classOpenSim_1_1Coordinate.html (this is good because it has some list properties, like `range`).
- Probe http://stanford.edu/~dembia/opensim-better-property-docs-2-20150723/classOpenSim_1_1Probe.html#a3a1a1172575b6017db7e3e61b3287b6b because it also has a list property (initial_conditions_for_integration).
- Millard muscle http://stanford.edu/~dembia/opensim-better-property-docs-2-20150723/classOpenSim_1_1Millard2012EquilibriumMuscle.html, because it has so many methods. 
- See if the documentation for those properties make sense.
- Click a few of the links that start from those properties.
- Look at the layout of the class pages: there's a Properties section at the top, and there's also a section within Public member functions for "Property-related methods"; see if it looks okay.
- Perhaps peruse around some other classes as well.

Thank you @jenhicks !

**Comment by sherm1** [comment]
> Changes to check out

So beautiful! :joy:

**Comment by chrisdembia** [comment]
Ready for review.

**Comment by jenhicks** [comment]
Overall, looks great. A minor issue that I noticed:

When I click on "More ..." for Inherited properties, nothing happens.

**Comment by chrisdembia** [comment]
> When I click on "More ..." for Inherited properties, nothing happens.

Nice catch... I just did some clicking and this problem seems to be more general. On the 3.3 doxygen site, the "More..." link under "Public Member Functions inherited from..." also don't work: https://simtk.org/api_docs/opensim/api_docs/classOpenSim_1_1Actuator.html#afe9aa7fbd468f2bf57403688f09e1ba7

Those "More..." links don't work in Simbody's doxygen either.

The doxygen for this PR was built with doxygen 1.8.9.1; the current version is 1.8.10. I can try using 1.8.10 and if the issue still exists I'll file a doxygen bug report. However, I think this can be done separately from this PR.

**Comment by chrisdembia** [comment]
Based on the discussion in the dev meeting, I'll merge this now. Thanks for the reviews.

**Comment by chrisdembia** [comment]
I provided a bug report for the bug in doxygen that @jenhicks  found: https://bugzilla.gnome.org/show_bug.cgi?id=753574

**Pull request merged**
