### PR TITLE
Add synthetic IMU utility to SimulationUtilities

### PR DESCRIPTION
**Pull request by nickbianco**
Related issue #2982

### Brief summary of changes
- Added createSyntheticIMUAccelerationSignals() to SimulationUtilities
- Updated testMocoGoals to use new utility

### Testing I've completed
- Re-ran testMocoGoals

### Looking for feedback on...
- Utility name
- Implementation, specifically regarding future compatibility with a "SyntheticIMU" reporter

### CHANGELOG.md (choose one)

- updated.

---
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2988)

### CODE REVIEW

**Review by aymanhab — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2988)* status: all files reviewed, 3 unresolved discussions (waiting on @nickbianco)

___
*[CHANGELOG.md, line 11 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2988#-MYGynpnCqdeGcnSlZVp:-MYGynpo4PXkBIMX8Uk0:blot5nx) ([raw file](https://github.com/opensim-org/opensim-core/blob/31d79987c8b48c3b11704cc57a1915ff5f780d02/CHANGELOG.md#L11)):*
> ```Markdown
> ====
> - Fixed a bug with Actuation analysis that would lead to extra columns in the output when an actuator is disabled (Issue #2977).
> - Added createSyntheticIMUAccelerationSignals() to SimulationUtilities to generate "synthetic" IMU accelerations based on an existing model trajectory.
> ```

"based on passed in state trajectory" could be clearer?
___
*[OpenSim/Simulation/SimulationUtilities.cpp, line 402 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2988#-MYH4-Rq2GnPUmPnySyN:-MYH4-Rr5npz7HAZNlFt:b5qr265) ([raw file](https://github.com/opensim-org/opensim-core/blob/31d79987c8b48c3b11704cc57a1915ff5f780d02/OpenSim/Simulation/SimulationUtilities.cpp#L402)):*
> ```cpp
>     for (const auto& framePath : framePaths) {
>         outputPaths.push_back(framePath + "\\|linear_acceleration");
>     }
> ```

Is there a chance we can error-check/validate input framePaths, for example by either forcing the input to be std::vector<ComponentPath> or creating one inside the function? Just worry about typos, trailing string terminators etc. which the downstream code may not be robust to.
___
*[OpenSim/Simulation/SimulationUtilities.cpp, line 423 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2988#-MYH537r0EFvitZ58CUK:-MYH537s7hCKWXBrnWhp:b-b5x15x) ([raw file](https://github.com/opensim-org/opensim-core/blob/31d79987c8b48c3b11704cc57a1915ff5f780d02/OpenSim/Simulation/SimulationUtilities.cpp#L423)):*
> ```cpp
>             const auto& state = statesTraj.get(i);
>             model.realizeAcceleration(state);
>             SimTK::Vec3 accelIMU = ground.expressVectorInAnotherFrame(
> ```

Does the model need to have mass/inertia specified?

**Review by aymanhab — COMMENTED** [review]
Overall looks good, just checking if we can tighten the error checking.

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2988#-:-MYH5NwW057eNYsNbviE:b-n3hjw2)* status: all files reviewed, 3 unresolved discussions (waiting on @nickbianco)

**Review by nickbianco — COMMENTED** [review]
Sounds good, working on it now.

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2988#-:-MYH9OkE9rKdRco2PPxs:bsofosj)* status: all files reviewed, 3 unresolved discussions (waiting on @aymanhab)

___
*[CHANGELOG.md, line 11 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2988#-MYGynpnCqdeGcnSlZVp:-MYH8CTqEo21C2Q_7im7:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/31d79987c8b48c3b11704cc57a1915ff5f780d02/CHANGELOG.md#L11)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

"based on passed in state trajectory" could be clearer?
</blockquote></details>

Done.
___
*[OpenSim/Simulation/SimulationUtilities.cpp, line 402 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2988#-MYH4-Rq2GnPUmPnySyN:-MYH8fwV3ANGN6DlYwOJ:b-i61o98) ([raw file](https://github.com/opensim-org/opensim-core/blob/31d79987c8b48c3b11704cc57a1915ff5f780d02/OpenSim/Simulation/SimulationUtilities.cpp#L402)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

Is there a chance we can error-check/validate input framePaths, for example by either forcing the input to be std::vector<ComponentPath> or creating one inside the function? Just worry about typos, trailing string terminators etc. which the downstream code may not be robust to.
</blockquote></details>

I agree this should be improved. Did you mean "force the input to be std::string"?
___
*[OpenSim/Simulation/SimulationUtilities.cpp, line 423 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2988#-MYH537r0EFvitZ58CUK:-MYH8vAHBJ_wXMkwA8Ha:bc5jf2n) ([raw file](https://github.com/opensim-org/opensim-core/blob/31d79987c8b48c3b11704cc57a1915ff5f780d02/OpenSim/Simulation/SimulationUtilities.cpp#L423)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

Does the model need to have mass/inertia specified?
</blockquote></details>

Yes, since the `linear_acceleration` Output require realization to `Stage::Acceleration`, which relies on `Stage::Dynamics`, which relies on inertial properties.

**Review by aymanhab — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2988)* status: all files reviewed, 3 unresolved discussions (waiting on @aymanhab and @nickbianco)

___
*[OpenSim/Simulation/SimulationUtilities.cpp, line 402 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2988#-MYH4-Rq2GnPUmPnySyN:-MYHBfz8Du08jxvpIQJC:b-89qpsc) ([raw file](https://github.com/opensim-org/opensim-core/blob/31d79987c8b48c3b11704cc57a1915ff5f780d02/OpenSim/Simulation/SimulationUtilities.cpp#L402)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

I agree this should be improved. Did you mean "force the input to be std::string"?
</blockquote></details>

I meant that the input could be std::vector<ComponentPath> or we could create that from the std::vector<std:;string> I assume that the construction of a ComponentPath from std::string can do error checking so downstream code can safely work worry free.
___
*[OpenSim/Simulation/SimulationUtilities.cpp, line 423 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2988#-MYH537r0EFvitZ58CUK:-MYHCUVKDlxA8dKa_zJl:b8w4ibp) ([raw file](https://github.com/opensim-org/opensim-core/blob/31d79987c8b48c3b11704cc57a1915ff5f780d02/OpenSim/Simulation/SimulationUtilities.cpp#L423)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

Yes, since the `linear_acceleration` Output require realization to `Stage::Acceleration`, which relies on `Stage::Dynamics`, which relies on inertial properties.
</blockquote></details>

Great, can we document that or if possible check and throw if not feasible.

**Review by nickbianco — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2988)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @aymanhab)

___
*[OpenSim/Simulation/SimulationUtilities.cpp, line 402 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2988#-MYH4-Rq2GnPUmPnySyN:-MYHFpVX-4ZcsUhb5b_w:b-7d9qer) ([raw file](https://github.com/opensim-org/opensim-core/blob/31d79987c8b48c3b11704cc57a1915ff5f780d02/OpenSim/Simulation/SimulationUtilities.cpp#L402)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

I meant that the input could be std::vector<ComponentPath> or we could create that from the std::vector<std:;string> I assume that the construction of a ComponentPath from std::string can do error checking so downstream code can safely work worry free.
</blockquote></details>

I'm still not sure what you mean by the input being a std::vector; maybe a code snippet of what you're suggesting would be clearer.. I call analyze(), which requires a std::vector<std::string> input, so this error checking might be better off inside analyze (although that might get complicated with the regex stuff there). 

I've added some additional error checking.
___
*[OpenSim/Simulation/SimulationUtilities.cpp, line 423 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2988#-MYH537r0EFvitZ58CUK:-MYHHmKk1ocLu6QMli30:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/31d79987c8b48c3b11704cc57a1915ff5f780d02/OpenSim/Simulation/SimulationUtilities.cpp#L423)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

Great, can we document that or if possible check and throw if not feasible.
</blockquote></details>

Done.

**Review by aymanhab — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2988#-:-MYHWskN3sSRiS2OpcOi:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @nickbianco)

___
*[OpenSim/Simulation/SimulationUtilities.cpp, line 402 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2988#-MYH4-Rq2GnPUmPnySyN:-MYHWCG89wBaFVEER7bx:bkt0z4m) ([raw file](https://github.com/opensim-org/opensim-core/blob/31d79987c8b48c3b11704cc57a1915ff5f780d02/OpenSim/Simulation/SimulationUtilities.cpp#L402)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

I'm still not sure what you mean by the input being a std::vector; maybe a code snippet of what you're suggesting would be clearer.. I call analyze(), which requires a std::vector<std::string> input, so this error checking might be better off inside analyze (although that might get complicated with the regex stuff there). 

I've added some additional error checking.
</blockquote></details>

Looks fine now, sorry my comment came up looking incoherent because I used '<,>' without using the correct markup which messed up the display.!

**Comment by nickbianco** [comment]
Thanks @aymanhab.

**Pull request merged**
