### PR TITLE
Lines starting with hyphens (negative signs) were becoming bulleted lists.

### PR DESCRIPTION
**Pull request by tkuchida**
There might be more of these…

### CODE REVIEW

**Comment by sherm1** [comment]
Tom, what should we do with this PR?

**Comment by tkuchida** [comment]
>what should we do with this PR?

I would test and suggest merging, but doxygen isn't building for me. Anyone else getting <tt>Unexpected start tag `interfaces' found in scope='class/memberdef/'!</tt> when building doxygen on master? I haven't been able to find a solution.

**Comment by chrisdembia** [comment]
No (doxygen 1.8.6 on Linux).

**Comment by chrisdembia** [comment]
The error most certainly has to do with [this line](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/doc/doxygen-layout.xml#L107) in doxygen-config.xml

**Comment by chrisdembia** [comment]
Could have to do with this PR: https://github.com/opensim-org/opensim-core/pull/238/files

**Comment by chrisdembia** [comment]
With doxygen 1.8.9.1, I still don't get that error:

```
error: Tag file `(null)' does not exist or is not a file. Skipping it...
/home/fitze/repos/opensim/4/opensim-core/OpenSim/Common/Function.h:107: warning: explicit link request to 'Infinity' could not be resolv
ed
Built target doxygen
```

**Comment by tkuchida** [comment]
Thanks, @chrisdembia. Newest version of doxygen works.

**Comment by chrisdembia** [comment]
K we should update all occurences of "1.8.6" in the README.

**Comment by tkuchida** [comment]
This PR is old; the text I was fixing is no longer displayed in our doxygen. Closing.

**Comment by chrisdembia** [comment]
I'm not sure if this bug is fixed in doxygen but I suggest we just put the code in backticks: `-SimTK::Infinity`.

**Comment by tkuchida** [comment]
> I'm not sure if this bug is fixed in doxygen but I suggest we just put the code in backticks:

@chrisdembia Backticks don't avoid the problem (it renders like this: doxygenbug) and the bug hasn't been fixed in doxygen. I think "`<tt>-SimTK::Infinity</tt>`" is the best option.

**Comment by tkuchida** [comment]
>I think `"-<tt>SimTK::Infinity</tt>"` is the best option.

Actually, `` -`SimTK::Infinity` `` works and introduces less clutter.

**Comment by chrisdembia** [comment]
Do you anticipate making any further changes?

**Comment by tkuchida** [comment]
>Do you anticipate making any further changes?

Nope. Ready for review. I forgot the [ci skip] :scream:

**Comment by tkuchida** [comment]
Thanks @chrisdembia :frog:

**Pull request merged**
