### PR TITLE
Fix memory management with addJoint and prescribeControl methods in SWIG interface files.

### PR DESCRIPTION
**Pull request by aymanhab**
Fix crash adding Joint to model and assigning Control to Actuator as reported in issue #1204

### CODE REVIEW

**Comment by aymanhab** [comment]
Ready for review @chrisdembia this addresses issue #1204 and adds a Java test case that performs model building.

**Comment by chrisdembia** [comment]
Excellent. Feel free to merge when the tests pass.

**Comment by chrisdembia** [comment]
I restarted the appveyor builds.

**Comment by chrisdembia** [comment]
For some reason, AppVeyor isn't reflecting the fact that I restarted the builds.

**Comment by aymanhab** [comment]
Thanks much @chrisdembia

**Pull request merged**
