### PR TITLE
Move to VS2015.

### PR DESCRIPTION
**Pull request by chrisdembia**
I've created this PR in preparation for our move to VS2015. I think this PR can be used to mark our official move to VS2015 (so, not just yet).

I've updated the README instructions to say that Windows users need VS2015. When Simbody moves to VS2015, I'll also update the appveyor script so that it builds with VS2015.

### CODE REVIEW

**Comment by sherm1** [comment]
Do you want to make a similar PR with the appveyor change for Simbody, Chris? I think we are just about ready to make the switch.

**Comment by chrisdembia** [comment]
Gladly.

**Comment by sherm1** [comment]
Simbody's AppVeyor build is now using VS2015 (see PR simbody/simbody#425). OpenSim should follow suit today to avoid AppVeyor failures.

/cc @aymanhab, @aseth1, @klshrinidhi

**Comment by chrisdembia** [comment]
There is at least one issue to deal with before we can merge this:

```
CMake Warning at C:/Program Files (x86)/CMake/share/cmake-3.1/Modules/InstallRequiredSystemLibraries.cmake:424 (message):
  system runtime library file does not exist: 'C:/Program Files
  (x86)/Microsoft Visual Studio
  14.0/VC/redist/x64/Microsoft.VC140.CRT/msvcr140.dll'
Call Stack (most recent call first):
  CMakeLists.txt:277 (include)
```

**Comment by sherm1** [comment]
I'm confused about the C4275 warnings in AppVeyor (non-dll base class `std::exception` used for dll class `OpenSim::Exception`) because that warning is disabled in Exception.h [here](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Common/Exception.h#L37). I'm not seeing that in my local build but I'm not doing wrapping -- maybe this is SWIG-related?

**Comment by sherm1** [comment]
> There is at least one issue to deal with before we can merge this (redist library not available for VS2015)

That's just a warning so we could merge this if it is needed to get the build working and address the warning separately.

**Comment by chrisdembia** [comment]
> That's just a warning so we could merge this if it is needed to get the build working and address the warning separately.

True...

> I'm not seeing that in my local build but I'm not doing wrapping -- maybe this is SWIG-related?

Ah thanks...I was confused about this as well. I'll look into this eventually.

**Comment by sherm1** [comment]
Builds worked -- ready to merge IMO.

**Comment by sherm1** [comment]
I'm merging this change to use VS2015 on AppVeyor so the OpenSim 4.0 builds will continue to work. There are still some warnings to deal with.

**Comment by chrisdembia** [comment]
I read up on the CMake warning here:

http://www.cmake.org/cmake/help/v3.0/module/InstallRequiredSystemLibraries.html

This makes me think that we just don't need to address the warning. I didn't see the warning myself on my machine, and I don't think others have (Ajay didn't say anything).

**Comment by chrisdembia** [comment]
Also, I no longer see any of the Exception.h C4275 messages in appveyor, so I think there is nothing to do.

**Pull request merged**
