### PR TITLE
Feature ezc3d

### PR DESCRIPTION
**Pull request by chrisdembia**
This PR replaces #2695

---
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2728)

### CODE REVIEW

**Comment by chrisdembia** [comment]
Ready for review (everything in this PR has already been reviewed; this is just to merge it into master).

**Comment by chrisdembia** [comment]
Thank you, @aymanhab, and congratulations, @pariterre 🎆

**Comment by pariterre** [comment]
Yeah! Thanks again everyone!
If you need anything in the future, feel free to ask :)

**Comment by jimmyDunne** [comment]
Very exciting! Can't wait to use. Well done, Team 🍾

**Pull request merged**
