### PR TITLE
Removed memory leak tests (use libASAN/valgrind instead, #3459)

### PR DESCRIPTION
**Pull request by adamkewley**
Fixes issue #3459

### Brief summary of changes

- Removes tests that check for memory leaks
- The reason why they are problematic is because they indirectly measure leaks by checking the process's RSS/blk size. The tests fail if using a custom allocation method or memory analyzer
- E.g. the tests fail when using libASAN. Not because there are leaks (libASAN finds _many_ leaks among the tests - if you ask it to look for leaks), but because libASAN interrupts the plain `malloc` that these tests depend on

### Testing I've completed

- BEFORE: I built OpenSim with libASAN:

```bash
CXXFLAGS="-fsanitize=address" LDFLAGS="-fsanitize=address" cmake -S dependencies/ -B ../osim-deps-build -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=${PWD}/../osim-deps-install -DOPENSIM_WITH_CASADI=NO -DOPENSIM_WITH_TROPTER=NO

cmake --build ../osim-deps-build/ -j16 -v

CXXFLAGS="-fsanitize=address" LDFLAGS="-fsanitize=address" cmake -S . -B ../osim-build -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=${PWD}/../osim-install -DOPENSIM_WITH_CASADI=NO -DOPENSIM_WITH_TROPTER=NO -DOPENSIM_DEPENDENCIES_PATH=${PWD}/../osim-deps-install

cmake --build ../osim-build/ -j16 -v
```

- BEFORE: then I ran one of these tests:

```bash
# disable libASAN's leak detection, which causes many of the test suites
# (in addition to this explicit leak test) to fail because of actual leaks
export ASAN_OPTIONS=detect_leaks=0
CTEST_OUTPUT_ON_FAILURE=1 ctest -j16 -R testComponents
```

- BEFORE: the test fails because the memory usage is higher than expected:

```bash
Testing Output velocity, dependent on Velocity
Component Body, output velocity: ~[~[0,0,0],~[0,0,0]]
Testing for memory leaks from copying.
Body.clone() increased memory use by 0.0273%.
Testing for memory leaks from initSystem.
*******************************************************
FAILURE: Body
Body.initSystem() increased memory use by 1.42%.
Exceeds acceptable tolerance of 1.000000%.
 Instance size: 87844KB increased by 125072KB over 100 iterations = 1.423797%.
```

- AFTER: the test suite passes (because it isn't testing memory anymore :-)):

- SIDENOTE: you can make it--and many other test suites--fail by enabling libASAN's leak detection:

```bash
export ASAN_OPTIONS=detect_leaks=1
CTEST_OUTPUT_ON_FAILURE=1 ctest -j16 -R testComponents
# (many many leaks that the original test suite did not capture, e.g.):
Indirect leak of 384 byte(s) in 1 object(s) allocated from:
    #0 0x7fe31b34f1c7 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x7fe3183aeb3a in OpenSim::Constant::clone() const /home/adam/opensim-core/OpenSim/Common/Constant.h:45
    #2 0x7fe3183aeb3a in SimTK::ClonePtr<OpenSim::Function>::cloneOrNull(OpenSim::Function const*) /home/adam/osim-deps-install/simbody/include/simbody/SimTKcommon/internal/ClonePtr.h:312
    #3 0x7fe3183aeb3a in SimTK::ClonePtr<OpenSim::Function>::operator=(OpenSim::Function const&) /home/adam/osim-deps-install/simbody/include/simbody/SimTKcommon/internal/ClonePtr.h:178
    #4 0x7fe3183aeb3a in OpenSim::ObjectProperty<OpenSim::Function>::appendValueVirtual(OpenSim::Function const&) /home/adam/opensim-core/OpenSim/Common/Property.h:1188
    #5 0x7fe3183aeb3a in OpenSim::Property<OpenSim::Function>::appendValue(OpenSim::Function const&) /home/adam/opensim-core/OpenSim/Common/Property.h:482
    #6 0x7fe3183aeb3a in OpenSim::PropertyIndex OpenSim::Object::addProperty<OpenSim::Function>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, OpenSim::Function const&) /home/adam/opensim-core/OpenSim/Common/Object.h:956
    #7 0x7fe3183aeb3a in OpenSim::SignalGenerator::constructProperty_function(OpenSim::Function const&) /home/adam/opensim-core/OpenSim/Common/SignalGenerator.h:46
    #8 0x7fe3183aeb3a in OpenSim::SignalGenerator::constructProperties() /home/adam/opensim-core/OpenSim/Common/SignalGenerator.cpp:35
    #9 0xfffcae706cb  (<unknown module>)
Indirect leak of 152 byte(s) in 1 object(s) allocated from:
    #0 0x7fe31b34f1c7 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x55e7126bf8ad in bool OpenSim::Component::constructOutput<double>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::function<void (OpenSim::Component const*, SimTK::State const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, double&)>, SimTK::Stage const&, bool) /home/adam/opensim-core/OpenSim/Common/Component.h:2925
```

- SIDENOTE: which is to say, libASAN's leak analyzer is able to pick up leaks _much_ more comprehensively than OpenSim's custom method of doing so, so I'd recommend that any serious investigation into memory leaks uses that kind of tooling.

### CHANGELOG.md (choose one)

- updated.

- - -
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3462)

### CODE REVIEW

**Comment by adamkewley** [comment]
Alternatively, if there's opposition to the idea of dropping the tests outright, I think that PRing a change in which the tolerances are raised to, say, 5 % will at least cover libASAN's overhead.

**Review by nickbianco — APPROVED** [review]
LGTM, but I'd like a quick second opinion. @aymanhab, can you also take a look here?

**Comment by aymanhab** [comment]
No opposition to the idea of removal, this was a small fig leaf when we had no cycles for dedicated memory profiling. If the presence of these tests is an obstacle then I totally agree to remove, just need to document the alternatives above in an easy to find place so when new components (e.g. WrapSurfaces) are (re)written we can check/test without searching for this PR.

**Review by aymanhab — APPROVED** [review]
LGTM, just need to document the alternative elsewhere.

**Comment by adamkewley** [comment]
I'll see if I can find an appropriate home for documenting libASAN etc - if you have any ideas about where's best then feel free to point me in that direction and I can write it up

**Comment by aymanhab** [comment]
This confluence page may do the trick as it refers to checking for memory leaks!
https://github.com/opensim-org/opensim-core/blob/main/CONTRIBUTING.md

No reason for that to hold the PR though. Thank you @adamkewley

**Pull request merged**
