### PR TITLE
Handle apdm format7

### PR DESCRIPTION
**Pull request by aymanhab**
Fixes issue #2567 

### Brief summary of changes
Handle new layout of headers in APDM exported csv files, and beef up test case to include a file on the new format.

### Testing I've completed
Parsed files from user testing and from Johanna 

### CHANGELOG.md (choose one)

- no need to update because this part of OpenSense that has not been advertised yet.

The Doxygen for this PR can be viewed at http://myosin.sourceforge.net/?C=N;O=D; click the folder whose name is this PR's number.

---
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2568)

### CODE REVIEW

**Comment by aymanhab** [comment]
@jimmyDunne You should be able to test user files with this PR then we can pass on to Johanna.

**Comment by aymanhab** [comment]
@jimmyDunne all yours

**Comment by jimmyDunne** [comment]
Tested latest commit and works as intended!

**Comment by aymanhab** [comment]
Thanks @chrisdembia for the review and @jimmyDunne for testing. Merging.

**Pull request merged**
