### PR TITLE
Create CMake option for copying Simbody headers and libraries.

### PR DESCRIPTION
**Pull request by chrisdembia**
This is the next change in the progress towards #195 (for allowing for the proper installation on UNIX into a system directory (e.g., /usr/local)).

This PR introduces the cmake "OPENSIM_COPY_SIMBODY" variable that decides if Simbody libraries and headers are to be installed with OpenSim, and if (only on windows) Simbody libraries should be copied to the OpenSim build directory so that OpenSim tests can be run without needing to set PATH.

1. This does not affect the default behavior on Windows.
2. I've removed the cmake related to lapack, etc., since this actually only belongs in Simbody.
3. The `BUILD_USING_NAMESPACE` variable and related lines are removed.
4. The OpenSimConfig.cmake file now depends on OPENSIM_COPY_SIMBODY. If not copying, then we add Simbody's lib dir and include dir to OpenSim's. This allows people to build an opensim-dependent project without having to explicitly include Simbody's include dir, etc. Basically, this allows for:
```
include_directories(${OpenSim_INCLUDE_DIRS})
link_directories(${OpeSim_LIB_DIR})
```
regardless of your platform. If not copying, those variables actually also contain the Simbody paths.

I checked the following things for this PR.
- With OPENSIM_COPY_SIMBODY on, make sure layout of installation is the same as before this PR.
  - [x] windows
  - [x] linux
- With OPENSIM_COPY_SIMBODY off, make sure it's possible to build, test and install OpenSim.
  - [x] windows
  - [x] linux
- With OPENSIM_COPY_SIMBODY off, make sure it's possible to build and run a client OpenSim project.
  - [x] windows
  - [x] linux
- With OPENSIM_COPY_SIMBODY on, make sure it's possible to build and run a client OpenSim project.
  - [x] windows
  - [x] linux

### CODE REVIEW

**Comment by chrisdembia** [comment]
Hmmm...may need some work. Closing for now.

**Comment by chrisdembia** [comment]
Fixes #294.

**Comment by chrisdembia** [comment]
I'd like this to get merged soon. This change does not affect windows users and is a step towards being a better citizen on UNIX. I have also performed some necessary clean-up of the root CMakeLists.txt (removing some stuff that belongs only in Simbody).

Also, I tested this PR extensively (as mentioned in the original post).

**Comment by sherm1** [comment]
Chris, this looks good to me except for the removal of the "namespace" stuff. Can you explain that? We use the prefixed simbody libraries on Windows so that OpenSim and Simbody can coexist. Otherwise, an installation of OpenSim contains its own copy of Simbody DLLs and depending on `PATH` setting it can prevent a separate Simbody installation from functioning. It is kind of antisocial for OpenSim to copy in the Simbody libraries; by making then have funny names we avoid potential conflicts.

**Comment by chrisdembia** [comment]
> Can you explain that?

Nothing has changed with regard to the namespace functionality. The change is to how the namespace functionality is handled. The [namespacing of Simbody libraries happens with Simbody.](https://github.com/simbody/simbody/blob/master/CMakeLists.txt#L86) Right now, OpenSim's CMake is told *separately* what the namespace of the Simbody libraries were, thus the duplicated `BUILD_USING_NAMESPACE` variable in OpenSm. This was confusing and unnecessary; Simbody tells its clients what the names of its libraries are--including the namespace--via the [SimbodyConfig.cmake](https://github.com/simbody/simbody/blob/master/cmake/SimbodyConfig.cmake.in#L75); the `NS` variable is the namespace and is defined in the root CMakeLists.

Same goes for the Simbody math libs.

**Comment by sherm1** [comment]
> Nothing has changed with regard to the namespace functionality

Got it -- thanks!

**Comment by chrisdembia** [comment]
Thanks @sherm1.

**Pull request merged**
