### PR TITLE
Retire travis, appveyor as not maintained anymore

### PR DESCRIPTION
**Pull request by aymanhab**
Fixes issue #0

### Brief summary of changes
Removed reference to build status on readme file and removed corresponding yml files

### CHANGELOG.md (choose one)

- no need to update because internal

---
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2907)

### CODE REVIEW

**Comment by adamkewley** [comment]
If you're waiting on someone else to check this: it seems like a fair decent cleanup change.

Unsure why CI is failing on this PR. It doesn't seem to be related to removing the appveyor config, because the windows build does run, it just seems to fail for an unrelated C++ compilation issue?

**Comment by aymanhab** [comment]
Thanks @adamkewley Will merge it. I was hoping to fold in the fix to the windows build but that was caused by unrelated MSVC upgrade.

**Comment by aymanhab** [comment]
@adamkewley The failure on windows is due to a bug introduced in MSVC compiler update, unfortunately I can't find a way to rollback the github action, do you have access to a windows machine to help find a workaround? Thank you

**Comment by adamkewley** [comment]
I can have a quick look next time on Windows (probably next week, though). I imagine the easier fix will be to patch upstream (depending on PR velocity).

**Pull request merged**
