### PR TITLE
Fix memory leak with Coordinate::_lockFunction.

### PR DESCRIPTION
**Pull request by chrisdembia**
I added a comment to the code to describe why I made this change:

> This line was originally
in extendFinalizeFromProperties(), but this caused a memory leak since
 extendFinalizeFromProperties() is called once when the model is
 constructed from a file, and again when one calls Model::initSystem()
 (or whenever finalizing from properties multiple times without recreating
 the SimTK System).

By putting the allocation right next to the creation of the related PrescribedMotion, we should be able to avoid the leak.

I detected the leak in the process of trying to get `testInitState` to pass on OSX. I detected the leak with valgrind and also used valgrind to verify that the leak is now gone.

### CODE REVIEW

**Comment by chrisdembia** [comment]
@sherm1 says:

> A nicer way to do this I think would be to use an std::unique_ptr to hold the freshly-allocated Function object until its ownership can be transferred to the PrescribedMotion constraint. It would look something like this:

```
std::unique_ptr<Function> func(new Function()); // func has ownership
ReferencePtr<Function> funcref(func.get()); // keep a reference to Function object
Constraint::PrescribedMotion(func.release()); // take over ownership from func
```

**Comment by chrisdembia** [comment]
To reviewers: please don't merge this until the above change is made. Also, feel free to make the above change for me!

**Comment by sherm1** [comment]
> Also, feel free to make the above change for me!

OK, I did. Please review.

**Comment by sherm1** [comment]
Hmm. AppVeyor build died immediately; related to this morning's AppVeyor update? Chris, please see separate email.

**Comment by sherm1** [comment]
Added a commit to allow "deprecated-declaration" warnings to occur without error until we fix issue #528.

**Comment by sherm1** [comment]
I'm merging this now because it fixes the CI builds.

**Comment by chrisdembia** [comment]
Okay; @aseth1 definitely should look at these changes at some point.

**Comment by chrisdembia** [comment]
Thanks for doing this @sherm1 .

**Pull request merged**
