### PR TITLE
OPENSIM_COPY_DEPENDENCIES with wrapping

### PR DESCRIPTION
**Pull request by carmichaelong**
Fixes issue #2598 

### Brief summary of changes
Change CMakeLists to ensure OPENSIM_COPY_DEPENDENCIES is ON and warn user that it's on now if java or python wrapping is ON. Also make OPENSIM_COPY_DEPENDENCIES an advanced option.

### Testing I've completed
Local tests to see that correct output occurs in CMake when Configuring.

### Looking for feedback on...
- Does the logic make sense?
- Does the warning message make sense?
- Need more local testing?

### CHANGELOG.md (choose one)
- updated to note change to CMake interface

The Doxygen for this PR can be viewed at http://myosin.sourceforge.net/?C=N;O=D; click the folder whose name is this PR's number.

---
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2600)

### CODE REVIEW

**Comment by carmichaelong** [comment]
@chrisdembia Thanks for the feedback, didn't realize that case specifically. I pushed another commit to address your comment.

**Comment by chrisdembia** [comment]
Thanks @carmichaelong, LGTM. Based on our new 1-review policy, you can merge this after the tests pass.

**Comment by chrisdembia** [comment]
For the tests to pass, I think master needs to be merged into this branch.

**Comment by carmichaelong** [comment]
Sounds good. I did notice your PR last week that was aimed at fixing the test failures but didn't know it had been merged now. I'll get around to this today.

**Pull request merged**
