### PR TITLE
Make clamping of Coordinates invoked only if enforceConstraints is true

### PR DESCRIPTION
**Pull request by aymanhab**
Fixes issue #540 of gui
https://github.com/opensim-org/opensim-gui/issues/540
### Brief summary of changes
Moved the block to enforce Coordinate clamp range so it is executed only when enforceConstraints is true
### Testing I've completed
GUI playback doesn't enforce clamping on bouncing block model of GUI issue above
### Looking for feedback on...
If documentation needs update?

### CHANGELOG.md (choose one)

The Doxygen for this PR can be viewed at http://myosin.sourceforge.net/?C=N;O=D; click the folder whose name is this PR's number.

### CODE REVIEW

**Comment by chrisdembia** [comment]
Does the comment in the header need to be updated?

**Comment by aseth1** [comment]
The comment in the header:
```cpp
    /** Set the value of the Coordinate on to the state.
        Optional flag to enforce the constraints immediately (true by default),
        which can adjust all coordinate values in the state to satisfy model
        constraints. Use getValue(s) to see if/how the value was adjusted to
        satisfy the kinematic constraints. If setting multiple Coordinate values
        consecutively, e.g. in a loop, set the flag to false and then call
        Model::assemble(state) once all Coordinate values have been set.
        Alternatively, use Model::setStateVariableValues() to set all coordinate
        values and their speeds at once followed by Model::assemble(state).
        */
```
Did not mention clamping. The expectation from reading this is that the value should NOT change if enforceConsrtaints is false, which is now the case. Otherwise, we can update to describe that clamping adjust values if enforceConstraints is true. Preference @chrisdembia ?

**Comment by chrisdembia** [comment]
Thanks @aseth1; I think it would be good for the doxygen comment to mention that the clamping only occurs if `enforceConstraints == true`. Other than that, LGTM.

**Comment by aymanhab** [comment]
@aseth1 Please let me know if I need to update the comments in the header based on @chrisdembia review. Thanks

**Comment by chrisdembia** [comment]
I edited the doxygen comment.

**Comment by aseth1** [comment]
Since just a comment update, I am merging.

**Comment by aymanhab** [comment]
Thanks @aseth1 and @chrisdembia :+1:

**Pull request merged**
