### PR TITLE
Add support to change endpoint constraint bounds in scripting // fix failing tests when CasADi + Tropter are disabled

### PR DESCRIPTION
**Pull request by nickbianco**
Fixes issues #3322, #3281

### Brief summary of changes
- Added convenience methods `MocoGoal::setEndpointConstraintBounds()` and `MocoGoal::getEndpointConstraintBounds()`.
- Updated bindings to support `MocoConstraintInfo`.
- Converted tests in `testMocoGoals` and `testMocoInterface` to use `TEMPLATE_TEST_CASE` so that they do not fail when both CasADi and Tropter are disabled.
- Minor formatting clean-up in `testMocoInterface`.

### Testing I've completed
- Added tests to `testMocoGoals`.
- Ran tests for #3281 fix locally.

### CHANGELOG.md (choose one)

- updated.

- - -
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3371)

### CODE REVIEW

**Review by carmichaelong — CHANGES_REQUESTED** [review]
some minor comments throughout. one question for you: did you try using `StdVectorMocoBounds` in matlab or python locally too?

> Reviewed 2 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3371#-:-NMe_-NV30N8ilhXO7Na:bpef5ep)* status: 2 of 5 files reviewed, 3 unresolved discussions (waiting on @nickbianco)

___
*[`CHANGELOG_MOCO.md` line 7 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3371#-NMeZER302HYrvOrgu-q:-NMeZER302HYrvOrgu-r:b-j8a9g2) ([raw file](https://github.com/opensim-org/opensim-core/blob/c8a75dc16950570f0c7bf0788e5269eab05e0f23/CHANGELOG_MOCO.md#L7)):*
> ```Markdown
> -----
> - 2023-01-24: Added convenience methods `MocoGoal::setEndpointConstraintBounds` and
>               `MocoGoal::getEndpointConstraintBounds`.        
> ```

fyi: some stray spaces at the end of the line 
___
*[`OpenSim/Moco/Test/testMocoGoals.cpp` line 403 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3371#-NMeZlWCComaipALvQw_:-NMeZlWCComaipALvQwa:b-2ba4d0) ([raw file](https://github.com/opensim-org/opensim-core/blob/c8a75dc16950570f0c7bf0788e5269eab05e0f23/OpenSim/Moco/Test/testMocoGoals.cpp#L403)):*
> ```cpp
> }
> 
> TEMPLATE_TEST_CASE("Test MocoScaleFactor", "", MocoCasADiSolver) {
> ```

should this also test tropter?
___
*[`OpenSim/Moco/Test/testMocoGoals.cpp` line 914 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3371#-NMeZtlNC_12YlbBWZdg:-NMeZtlNC_12YlbBWZdh:b-2ba4d0) ([raw file](https://github.com/opensim-org/opensim-core/blob/c8a75dc16950570f0c7bf0788e5269eab05e0f23/OpenSim/Moco/Test/testMocoGoals.cpp#L914)):*
> ```cpp
> }
> 
> TEMPLATE_TEST_CASE("MocoOutputPeriodicityGoal and MocoOutputTrackingGoal", "",
> ```

should this also test tropter?
___
*[`OpenSim/Moco/Test/testMocoInterface.cpp` line 304 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3371#-NMeZwxH37ZgOLo5MS5A:-NMeZwxH37ZgOLo5MS5B:b-2ba4d0) ([raw file](https://github.com/opensim-org/opensim-core/blob/c8a75dc16950570f0c7bf0788e5269eab05e0f23/OpenSim/Moco/Test/testMocoInterface.cpp#L304)):*
> ```cpp
> /// Test that we can read in a Moco setup file, solve, edit the setup,
> /// re-solve.
> TEMPLATE_TEST_CASE("Serializing a MocoStudy", "", MocoCasADiSolver) {
> ```

should this also test tropter?

**Review by nickbianco — COMMENTED** [review]
@carmichaelong, ready for review. I added a bindings test for `StdVectorMocoBounds`. Let me know if you have any questions about the other changes (some of the tests needed some refactoring).

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3371#-:-NMgNWckAIaGC3eqoykQ:b-v7o1zz)* status: 2 of 6 files reviewed, 3 unresolved discussions (waiting on @carmichaelong and @nickbianco)

___
*[`OpenSim/Moco/Test/testMocoGoals.cpp` line 403 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3371#-NMeZlWCComaipALvQw_:-NMgNJvjEKXEdXcjwXMl:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/c8a75dc16950570f0c7bf0788e5269eab05e0f23/OpenSim/Moco/Test/testMocoGoals.cpp#L403)):*
<details><summary><i>Previously, carmichaelong wrote…</i></summary><blockquote>

should this also test tropter?
</blockquote></details>

Done.
___
*[`OpenSim/Moco/Test/testMocoGoals.cpp` line 914 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3371#-NMeZtlNC_12YlbBWZdg:-NMgNM_G1vmUcqo-gISs:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/c8a75dc16950570f0c7bf0788e5269eab05e0f23/OpenSim/Moco/Test/testMocoGoals.cpp#L914)):*
<details><summary><i>Previously, carmichaelong wrote…</i></summary><blockquote>

should this also test tropter?
</blockquote></details>

Done.
___
*[`OpenSim/Moco/Test/testMocoInterface.cpp` line 304 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3371#-NMeZwxH37ZgOLo5MS5A:-NMgNO460EuUoDzbqdmY:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/c8a75dc16950570f0c7bf0788e5269eab05e0f23/OpenSim/Moco/Test/testMocoInterface.cpp#L304)):*
<details><summary><i>Previously, carmichaelong wrote…</i></summary><blockquote>

should this also test tropter?
</blockquote></details>

Done.

**Comment by nickbianco** [comment]
@carmichaelong, I moved the test that was failing with `MocoTropterSolver` to a separate issue: https://github.com/opensim-org/opensim-core/issues/3374.

**Review by carmichaelong — APPROVED** [review]
:lgtm:

> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3371#-:-NMkjSsw7w8EeslP6t0H:bnfp4nl)* status: 3 of 6 files reviewed, all discussions resolved (waiting on @nickbianco)

**Comment by nickbianco** [comment]
Thank you @carmichaelong!

**Pull request merged**
