### PR TITLE
Test case to exercise OpenSense and OpenSenseRT

### PR DESCRIPTION
**Pull request by aymanhab**
Fixes issue #3056 

### CHANGELOG.md (choose one)

- no need to update because...
- updated.

---
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3199)

### CODE REVIEW

**Comment by aymanhab** [comment]
This is partly done since there are multiple pathways in the code but there's no reason to hold other testing because of that.

**Comment by aymanhab** [comment]
I'll merge this since it changes signatures (only to make correct signatures for OpenSenseRT). This exercises one constructor for InverseKinematicsSolver that uses an OrientationReference. 
@nickbianco Can you do a quick review if @carmichaelong isn't available? Thank you

**Review by nickbianco — CHANGES_REQUESTED** [review]
Look mostly good to me, Just one minor comment to address. Feel free to merge after that.

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3199#-:-N1uDAIcEvSWSW2ApwD5:b-45c0on)* status: all files reviewed, 1 unresolved discussion (waiting on @aymanhab and @carmichaelong)

___
*[`Bindings/Python/tests/test_opensense.py` line 20 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3199#-N1uCiX2BhsOL3cb6lXS:-N1uCiX2BhsOL3cb6lXT:b-o5t0p4) ([raw file](https://github.com/opensim-org/opensim-core/blob/091de138e280f2400a00b61013ff845887cd0604/Bindings/Python/tests/test_opensense.py#L20)):*
> ```Python
>         model = osim.Model(modelfile)
>         coordinates = model.getCoordinateSet();
>         imuPlacer = osim.IMUPlacer();
> ```

Is this `imuPlacer` supposed to be used for anything, or are we just testing that it instantiates properly?

**Comment by aymanhab** [comment]
This part only instantiate objects. If you prefer I can remove it. Later we'll beef the case to test streaming workflow

**Review by nickbianco — APPROVED** [review]
Nope, that's fine with me. Just trying to understand the test case.

LGTM.

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3199#-:-N1uqaX9DzFzOyr1zbyU:b-pg7y9v)* status: all files reviewed, 1 unresolved discussion (waiting on @aymanhab and @carmichaelong)

**Comment by aymanhab** [comment]
Awesome, thanks @nickbianco 👍

**Pull request merged**
