### PR TITLE
Appearance property comments.

### PR DESCRIPTION
**Pull request by chrisdembia**

### CODE REVIEW

**Comment by chrisdembia** [comment]
@aymanhab could you review?

**Comment by aymanhab** [comment]
Sure, looks better. Feel free to merge though I'm worried it may conflict with the Geometry/Appearnce PR #616 but feel free to merge when the tests pass.

**Comment by chrisdembia** [comment]
Thanks. We can wait until #616 gets merged.

**Comment by aymanhab** [comment]
@chrisdembia Please feel free to merge, now that #616 has been merged. Thanks

**Pull request merged**
