### PR TITLE
Keep doxygen quiet.

### PR DESCRIPTION
**Pull request by chrisdembia**
So we can actually read the warnings it produces.

### CODE REVIEW

**Comment by chrisdembia** [comment]
The console output it produces is mostly useless I think. The only advantage I see of producing that output is so you know something is actually happening; otherwise, it might seem like the process has frozen.

**Comment by tkuchida** [comment]
@chrisdembia For me to review this PR, do I need to pull from your repo (and build from scratch :cry:)?

**Comment by chrisdembia** [comment]
> @chrisdembia For me to review this PR, do I need to pull from your repo (and build from scratch )?

Yes-ish; no. You'd add my GitHub fork as a remote to your local repo and then check out my remote branch.

You would have to build the doxygen target, but would not need to compile any code. This PR only affects the doxygen target.

I think what's most important is whether or not people see any value in seeing all the output from doxygen.

**Comment by tkuchida** [comment]
Thanks for the :turtle:Git refresher.
:+1: I think it's more useful to see an unpolluted list of warnings.

**Comment by chrisdembia** [comment]
> I think it's more useful to see an unpolluted list of warnings.

Yay!

**Comment by sherm1** [comment]
>  I think it's more useful to see an unpolluted list of warnings.

I like it quiet too. I just tried it in Simbody and it showed me a warning that had been there forever but I never noticed before! I'm going to make the same change -- thanks.

**Pull request merged**
