### PR TITLE
Tweak logging for tools

### PR DESCRIPTION
**Pull request by chrisdembia**
Fixes issue #36 

### Brief summary of changes

- Removes excess newlines in RRA and CMC logging.
- Fix a bug in the logging of Scale and IK (we were missing an output variable).

### Testing I've completed

Ran the gait2354 pipeline.

### Looking for feedback on...

Do we like the modified logging output? Here's a snippet of the modified output:

```
[info] CMC::computeControls, t = 1.246
[info] CMC::computeControls, t = 1.247
[info] CMC::computeControls, t = 1.248
[info] CMC::computeControls, t = 1.249
[info] -------------------------------------------
[info] Finished tracking the specified kinematics:
[info] -------------------------------------------
[info]  -- Start time = Sat May 23 16:02:58 2020
[info]  -- Finish time = Sat May 23 16:03:07 2020
[info]  -- Elapsed time = 9.0 seconds.
[info] -------------------------------------------
[info] 
[info] Printing results of investigation subject01_walk1_RRA to ResultsRRA
[info] 
```

### CHANGELOG.md (choose one)

- updated...

---
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2776)

### CODE REVIEW

**Comment by chrisdembia** [comment]
Here's what the output looks like without this PR:

```
[info] CMC::computeControls, t = 1.246:
[info]
[info] CMC::computeControls, t = 1.247:
[info]
[info] CMC::computeControls, t = 1.248:
[info]
[info] CMC::computeControls, t = 1.249:
[info]
[info] -------------------------------------------
[info] Finished tracking the specified kinematics:
[info] -------------------------------------------
[info]  -- Start time = Sat May 23 16:02:58 2020

[info]  -- Finish time = Sat May 23 16:03:07 2020

[info]  -- Elapsed time = 9.0 seconds.
[info] -------------------------------------------
[info] 
[info] Printing results of investigation subject01_walk1_RRA to ResultsRRA
[info] 
```

I'm not sure if some of the newlines (surrounding the date/time output) were appearing on only certain platforms.

I'm flexible about the newlines after `computeControls()`; the main change that I want to keep is removing the colon, because otherwise it looks like some information is missing.

**Comment by chrisdembia** [comment]
Also, I hadn't realized this earlier, but an empty logging line like the following may look like a mistake to users:

```
[info]
```

**Comment by nickbianco** [comment]
The comparison is helpful, your changes look much better. The blank `[info]` lines don't look weird to me in the context of the rest of the formatted output, but that opinion might not hold for others.

**Comment by aymanhab** [comment]
I prefer removing the blank lines. I was wondering if the log line can be customized to include date/time so that users can tell how slow/fast the steps are.

**Comment by chrisdembia** [comment]
> I prefer removing the blank lines. I was wondering if the log line can be customized to include date/time so that users can tell how slow/fast the steps are.

The `opensim.log` file contains time stamps for each log line :). This is the ideal situation, I think: remove the time stamp clutter from the console output, but allow users to obtain the time stamps if they go to the file.

**Pull request merged**
