### PR TITLE
Porting the ConstantCurvatureJoint into the OpenSim codebase.

### PR DESCRIPTION
**Pull request by keenon**
This adds support for the ConstantCurvatureJoint to OpenSim.

### Brief summary of changes

- Adds `ConstantCurvatureJoint.cpp` and `ConstantCurvatureJoint.h` to `OpenSim/Simulation/`
- Adds unit tests and simulation code to `OpenSim/Tests/ConstantCurvatureExample/testConstantCurvature.cpp`

### Testing I've completed

Unit tests based on the outputs of the same joint in NimblePhysics, in `OpenSim/Tests/ConstantCurvatureExample/testConstantCurvature.cpp` methods `testJacobians1()`, `testJacobians2()`, and `testJacobians3()`.

Also, ran a simulation which produces the following GIF:

OpenSimConstantCurvature

### Looking for feedback on...

Whether I'm following the style for OpenSim code, testing, etc.

### CHANGELOG.md (choose one)

Unsure what to say there, or which version we're on. Would love feedback on this as well.

- - -
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3308)

### CODE REVIEW

**Comment by keenon** [comment]
Looks suspiciously like the CI for Ubuntu2004 is broken on some sort of Fortran issue, but I don't think that's related to these changes.

**Comment by aymanhab** [comment]
Yes @keenon the build failures are the same as the master branch before this PR so no need to worry about them for now.

**Review by aymanhab — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3308)* status: 3 of 7 files reviewed, 9 unresolved discussions (waiting on @keenon)

___
*[`OpenSim/Simulation/SimbodyEngine/ConstantCurvatureJoint.cpp` line 88 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3308#-NFj3S6I34KXYNdYjx4V:-NFj3S6I34KXYNdYjx4W:bunz6jm) ([raw file](https://github.com/opensim-org/opensim-core/blob/7a5f1773db4d6a25b9c95800eda05838c47fb40c/OpenSim/Simulation/SimbodyEngine/ConstantCurvatureJoint.cpp#L88)):*
> ```cpp
>   // | r20 r21 r22 |   | -cx*sy+cy*sx*sz   cz*sx   cx*cy+sx*sy*sz |
>   // +-           -+   +-                                        -+
> ```

I suspect there's a constructor for the SimTK::Rotation class that does the same and you get a Rotation rather than a generic Mat33, highly recommend making use of the Rotation class that has been written and optimized for use everywhere in OpenSim and Simbody.

**Comment by aymanhab** [comment]
@keenon I started a pass through the files last week and noted documentation and header-guard minor issues, but also noted that some of the math can reuse the SimTK::Rotation class that we use extensively. Since this has the potential for material code change I will stop reviewing pending your thoughts/feedback. Sure excited to have your contributions into opensim 👍

**Review by nickbianco — CHANGES_REQUESTED** [review]
> Reviewed 3 of 7 files at r1, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3308)* status: all files reviewed, 13 unresolved discussions (waiting on @aymanhab and @keenon)

___
*[`OpenSim/Simulation/SimbodyEngine/ConstantCurvatureJoint.h` line 107 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3308#-NFj1lvD1L5qXLt_Nb27:-NYUuVUE-qqki8sLhBM8:b-2k9w3p) ([raw file](https://github.com/opensim-org/opensim-core/blob/7a5f1773db4d6a25b9c95800eda05838c47fb40c/OpenSim/Simulation/SimbodyEngine/ConstantCurvatureJoint.h#L107)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

If the code compiles without this deprecated constructor I'd remove it.
</blockquote></details>

Is this constructor still needed or useful? If so, I wouldn't describe it as "deprecated".
___
*[`OpenSim/Simulation/SimbodyEngine/ConstantCurvatureJoint.h` line 177 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3308#-NFj2WtKC4namcO4r0Nt:-NYUuMN5702D-yqBF5tp:bwbra68) ([raw file](https://github.com/opensim-org/opensim-core/blob/7a5f1773db4d6a25b9c95800eda05838c47fb40c/OpenSim/Simulation/SimbodyEngine/ConstantCurvatureJoint.h#L177)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

Fix to match header guard
</blockquote></details>

This header guard comment still needs to be addressed.
___
*[`OpenSim/Simulation/SimbodyEngine/ConstantCurvatureJoint.h` line 12 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3308#-NYUw4j6DrbuvLY4MGv4:-NYUw4j6DrbuvLY4MGv5:b8hl4kx) ([raw file](https://github.com/opensim-org/opensim-core/blob/b09640d4ebc01bbea82d81bf994751a629fff06c/OpenSim/Simulation/SimbodyEngine/ConstantCurvatureJoint.h#L12)):*
> ```objc
>  * through the Warrior Web program.                                           *
>  *                                                                            *
>  * Copyright (c) 2022 Stanford University and the Authors                     *
> ```

You could update the copyright year everywhere.
___
*[`OpenSim/Simulation/SimbodyEngine/ConstantCurvatureJoint.cpp` line 49 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3308#-NFj2uqv7B21WsuuwrFT:-NYUvDp36ADsEmbiS07C:b-vzy1m7) ([raw file](https://github.com/opensim-org/opensim-core/blob/7a5f1773db4d6a25b9c95800eda05838c47fb40c/OpenSim/Simulation/SimbodyEngine/ConstantCurvatureJoint.cpp#L49)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

We typically don't use std::cout but use log so we can control the level of details and potentially redirect.
</blockquote></details>

As Ayman suggests, it would be best to replace these `std::cout`s with the corresponding calls using `OpenSim::Logger` (i.e., `log_warn("ConstraintCurvatureJoint position outside...")`).
___
*[`OpenSim/Tests/ConstantCurvatureExample/testConstantCurvature.cpp` line 2 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3308#-NYUuyZS9CjuVyHFK6Sd:-NYUuyZS9CjuVyHFK6Se:b-5ak96x) ([raw file](https://github.com/opensim-org/opensim-core/blob/b09640d4ebc01bbea82d81bf994751a629fff06c/OpenSim/Tests/ConstantCurvatureExample/testConstantCurvature.cpp#L2)):*
> ```cpp
> /* -------------------------------------------------------------------------- *
>  *                    OpenSim:  testREADME.cpp                                *
> ```

--> testConstantCurvature.cpp
___
*[`OpenSim/Tests/ConstantCurvatureExample/testConstantCurvature.cpp` line 42 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3308#-NYUv681AAVq5K9i5k2r:-NYUv681AAVq5K9i5k2s:bf5bh05) ([raw file](https://github.com/opensim-org/opensim-core/blob/b09640d4ebc01bbea82d81bf994751a629fff06c/OpenSim/Tests/ConstantCurvatureExample/testConstantCurvature.cpp#L42)):*
> ```cpp
>  * 5. Copy your gif over to OpenSim/doc/images, and commit it to the
>  *    repository.
>  */
> ```

The comments and license blurb above should be updated to reflect these tests.
___
*[`OpenSim/Tests/ConstantCurvatureExample/testConstantCurvature.cpp` line 346 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3308#-NYUxDC60DHbxDdVY3ub:-NYUxDC60DHbxDdVY3uc:bcsaerw) ([raw file](https://github.com/opensim-org/opensim-core/blob/b09640d4ebc01bbea82d81bf994751a629fff06c/OpenSim/Tests/ConstantCurvatureExample/testConstantCurvature.cpp#L346)):*
> ```cpp
>     return 0;
> };
> /// [README]
> ```

This line can be removed.

**Review by nickbianco — COMMENTED** [review]
All looks pretty good! Just some minor formatting stuff needed so we conform with the OpenSim standards. 

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3308#-:-NYUxnSD2uZ9tYN-TOFh:ba7z9td)* status: all files reviewed, 13 unresolved discussions (waiting on @aymanhab and @keenon)

**Review by nickbianco — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3308)* status: all files reviewed, 14 unresolved discussions (waiting on @aymanhab and @keenon)

___
*[`OpenSim/Tests/ConstantCurvatureExample/testConstantCurvature.cpp` line 42 at r4](https://reviewable.io/reviews/opensim-org/opensim-core/3308#-NYV3BI497GyZGR1xZHV:-NYV3BI497GyZGR1xZHW:bei5n54) ([raw file](https://github.com/opensim-org/opensim-core/blob/7da636d4ba354f4158b93497eed5f390d2347035/OpenSim/Tests/ConstantCurvatureExample/testConstantCurvature.cpp#L42)):*
> ```cpp
>  * 5. Copy your gif over to OpenSim/doc/images, and commit it to the
>  *    repository.
>  */
> ```

This whole block of comments isn't relevant to these tests (this is leftover from testREADME). I'd replace it with a brief summary of what the tests below cover.

**Review by nickbianco — COMMENTED** [review]
One more quick comment to address.

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3308#-:-NYV3Mra2RpB8ksoXq2e:b-8f63xd)* status: all files reviewed, 14 unresolved discussions (waiting on @aymanhab and @keenon)

**Review by nickbianco — CHANGES_REQUESTED** [review]
Sorry, one more thing I missed in the last review.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3308#-:-NYVo79A7_wwQ4Fs88bP:b-x7wum9)* status: 6 of 7 files reviewed, 15 unresolved discussions (waiting on @aymanhab and @keenon)

___
*[`OpenSim/Tests/ConstantCurvatureExample/testConstantCurvature.cpp` line 2 at r5](https://reviewable.io/reviews/opensim-org/opensim-core/3308#-NYVnuI69GtTpiTb1KqX:-NYVnuI69GtTpiTb1KqY:b-t3qltk) ([raw file](https://github.com/opensim-org/opensim-core/blob/3761a3982addb5bdff49fa9ae539d360caea4388/OpenSim/Tests/ConstantCurvatureExample/testConstantCurvature.cpp#L2)):*
> ```cpp
> /* -------------------------------------------------------------------------- *
>  *                    OpenSim:  testREADME.cpp                                *
> ```

`testREADME.cpp` should be updated to `testConstantCurvature.cpp`

**Review by nickbianco — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3308)* status: all files reviewed, 15 unresolved discussions (waiting on @aymanhab and @keenon)

**Review by aymanhab — CHANGES_REQUESTED** [review]
LGTM, just a few minor comments, I trust @nickbianco will make sure they are addressed. Excited to see your contributions to the OpenSim  code base @keenon 

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3308#-:-NYZNop5BGFvSaXFQr2s:b8iked8)* status: all files reviewed, 11 unresolved discussions (waiting on @keenon and @nickbianco)

___
*[`OpenSim/Simulation/SimbodyEngine/ConstantCurvatureJoint.h` line 77 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3308#-NFj1Stl1gC4TL_kF93C:-NYZJTLR3AXMjCUv9vEA:b1c1x2t) ([raw file](https://github.com/opensim-org/opensim-core/blob/7a5f1773db4d6a25b9c95800eda05838c47fb40c/OpenSim/Simulation/SimbodyEngine/ConstantCurvatureJoint.h#L77)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

Any reason for this ordering? Is it in sync with other joints?
</blockquote></details>

BallJoint has a different ordering 
https://github.com/opensim-org/opensim-core/blob/ab5bccb265c9de178cceaa95612d36a2eb52dbb9/OpenSim/Simulation/SimbodyEngine/BallJoint.h#L79 and Ellipsoid
Can we somehow emphasize in the documentation/doxygen the rationale  (especially in python/matlab users will likely use the more confusing unsigned numbers rather than names/enums)
___
*[`OpenSim/Simulation/SimbodyEngine/ConstantCurvatureJoint.h` line 107 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3308#-NFj1lvD1L5qXLt_Nb27:-NYZKTcRDcgHcvrWLU5z:bw8wcgl) ([raw file](https://github.com/opensim-org/opensim-core/blob/7a5f1773db4d6a25b9c95800eda05838c47fb40c/OpenSim/Simulation/SimbodyEngine/ConstantCurvatureJoint.h#L107)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

Is this constructor still needed or useful? If so, I wouldn't describe it as "deprecated".
</blockquote></details>

Easy to test if the code compiles without, doesn't seem like it would be a problem to remove this "convenience" constructor.
___
*[`OpenSim/Simulation/SimbodyEngine/ConstantCurvatureJoint.cpp` line 88 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3308#-NFj3S6I34KXYNdYjx4V:-NYZMVq-BKgbBMlGDndp:bn9rlcl) ([raw file](https://github.com/opensim-org/opensim-core/blob/7a5f1773db4d6a25b9c95800eda05838c47fb40c/OpenSim/Simulation/SimbodyEngine/ConstantCurvatureJoint.cpp#L88)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

I suspect there's a constructor for the SimTK::Rotation class that does the same and you get a Rotation rather than a generic Mat33, highly recommend making use of the Rotation class that has been written and optimized for use everywhere in OpenSim and Simbody.
</blockquote></details>

I assume no such constructor exists in here https://github.com/simbody/simbody/blob/3c3ad5a50a6fdbf91a72ea3801b52ab43336243f/SimTKcommon/Mechanics/include/SimTKcommon/internal/Rotation.h#L111
___
*[`OpenSim/Simulation/SimbodyEngine/ConstantCurvatureJoint.cpp` line 41 at r5](https://reviewable.io/reviews/opensim-org/opensim-core/3308#-NYZGb0I99LeI50_nQ4q:-NYZGb0I99LeI50_nQ4r:bwr5l9d) ([raw file](https://github.com/opensim-org/opensim-core/blob/3761a3982addb5bdff49fa9ae539d360caea4388/OpenSim/Simulation/SimbodyEngine/ConstantCurvatureJoint.cpp#L41)):*
> ```cpp
> 
> #ifndef M_PI
> #define M_PI 3.14159
> ```

Any reason to use a different PI than SimTK's

**Review by nickbianco — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3308)* status: all files reviewed, 11 unresolved discussions (waiting on @aymanhab and @keenon)

___
*[`OpenSim/Simulation/SimbodyEngine/ConstantCurvatureJoint.h` line 77 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3308#-NFj1Stl1gC4TL_kF93C:-NY_89sO0kWMYroyOAeh:b-o7m0q4) ([raw file](https://github.com/opensim-org/opensim-core/blob/7a5f1773db4d6a25b9c95800eda05838c47fb40c/OpenSim/Simulation/SimbodyEngine/ConstantCurvatureJoint.h#L77)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

BallJoint has a different ordering 
https://github.com/opensim-org/opensim-core/blob/ab5bccb265c9de178cceaa95612d36a2eb52dbb9/OpenSim/Simulation/SimbodyEngine/BallJoint.h#L79 and Ellipsoid
Can we somehow emphasize in the documentation/doxygen the rationale  (especially in python/matlab users will likely use the more confusing unsigned numbers rather than names/enums)
</blockquote></details>

Keenon added Doxygen comments to explain the ordering.
___
*[`OpenSim/Simulation/SimbodyEngine/ConstantCurvatureJoint.h` line 107 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3308#-NFj1lvD1L5qXLt_Nb27:-NY_8Dv22BdzRwLaraih:b-t693ge) ([raw file](https://github.com/opensim-org/opensim-core/blob/7a5f1773db4d6a25b9c95800eda05838c47fb40c/OpenSim/Simulation/SimbodyEngine/ConstantCurvatureJoint.h#L107)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

Easy to test if the code compiles without, doesn't seem like it would be a problem to remove this "convenience" constructor.
</blockquote></details>

It's fine to leave this in, I think.
___
*[`OpenSim/Simulation/SimbodyEngine/ConstantCurvatureJoint.cpp` line 88 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3308#-NFj3S6I34KXYNdYjx4V:-NY_8QUz72v9-AccDePo:b-kr1492) ([raw file](https://github.com/opensim-org/opensim-core/blob/7a5f1773db4d6a25b9c95800eda05838c47fb40c/OpenSim/Simulation/SimbodyEngine/ConstantCurvatureJoint.cpp#L88)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

I assume no such constructor exists in here https://github.com/simbody/simbody/blob/3c3ad5a50a6fdbf91a72ea3801b52ab43336243f/SimTKcommon/Mechanics/include/SimTKcommon/internal/Rotation.h#L111
</blockquote></details>

The usage here is fine, I think.

**Review by nickbianco — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3308#-:-NY_D2BbBY-e3uM0GY9d:bnfp4nl)* status: all files reviewed, 11 unresolved discussions (waiting on @aymanhab and @keenon)

**Pull request merged**
