### PR TITLE
Remove kinematics_for_external_loads property 

### PR DESCRIPTION
**Pull request by aymanhab**
Remove properties from from ExternalLoads object and remove usage in AbstractTool and DynamicsTool. 

Fixes issue https://github.com/opensim-org/opensim-gui/issues/348

### CHANGELOG.md (choose one)

- no need to update because...
- updated...

The Doxygen for this PR can be viewed at http://myosin.sourceforge.net/?C=N;O=D; click the folder whose name is this PR's number.

---
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2770)

### CODE REVIEW

**Comment by chrisdembia** [comment]
https://github.com/opensim-org/opensim-core/issues/2334

**Comment by aymanhab** [comment]
Thanks @chrisdembia This PR predates the change to logging so log_ functions were not available then. Will update accordingly. Generally we don't keep track if a warning is issued while upgrading and i don't think we will because the upgrade is per object not per file/document.

**Comment by chrisdembia** [comment]
@aymanhab I don't know why this keeps happening but the diff contains changes that are already in master.

**Comment by aymanhab** [comment]
@chrisdembia the two warnings are on two different control paths  of if/else so they can't both be true AFAIK 😄 

I'll look into the diffs issue.

**Comment by aymanhab** [comment]
Running IAA in 3.3 without kinematics for external loads gives identical results to branch with the fix as expected. I can post plots but visibly the totals are indistinguishable which is rather expected if we didn't introduce a bug elsewhere.

**Comment by aymanhab** [comment]
Based on feedback and diffs above this seems ready to go (separate GUI PR will remove it from the application), main issue that I'd like feedback on is whether we upgrade file version number (corresponding to XML schema change). It's included here already but has the side effect that new files/models saved moving forward will not be backward compatible with 4.0 or 4.1, this is needed so that saved external loads files don't have the removed properties but comes with this  inconvenience. Thoughts @carmichaelong @jenhicks @nickbianco 
We can skip this and rely on the warning each time the file is opened and on documentation instead.

**Comment by aymanhab** [comment]
@jenhicks @carmichaelong @aseth1 Any feedback on this so we can move on? Thank you

**Comment by jenhicks** [comment]
My initial inclination is to keep backwards compatibility, but I am open to other thoughts.

**Comment by aymanhab** [comment]
Thanks @jenhicks I tend to agree, particularly that ExternalLoads are saved to separate files typically so losing backward compatibility for model files feels like an overreach. I will undo the version change unless I hear otherwise from reviewers.

**Comment by aymanhab** [comment]
@carmichaelong one more look and will merge if no objections when you have a chance, thanks

**Comment by aymanhab** [comment]
Approved in dev meeting by @carmichaelong, Merging.

**Pull request merged**
