### PR TITLE
Corner cases opensense

### PR DESCRIPTION
**Pull request by aymanhab**
Fixes issue #2190 

### Brief summary of changes
Handle error conditions in InverseKinematicsSolver and IMUPlacer and bubble errors up into exceptions for using by scripting and GUI. 

### CHANGELOG.md (choose one)

- no need to update because...
- updated.

---
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2894)

### CODE REVIEW

**Comment by aymanhab** [comment]
@carmichaelong These are the core side fixes to handle end cases (no matching frames by name etc.)

**Review by carmichaelong — CHANGES_REQUESTED** [review]
@aymanhab Thanks, I've left some comments but overall looks pretty good

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2894#-:-MJmUQui6vrpln5r82Ui:bekn3c8)* status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @aymanhab)

___
*[OpenSim/Simulation/InverseKinematicsSolver.cpp, line 100 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2894#-MJmRFYBALWDOE2-IN95:-MJmRFYC-C_dx2DZyOlo:bdba8yd) ([raw file](https://github.com/opensim-org/opensim-core/blob/c4145f6a526010f67cc5bb1c9881f8f9ceac1973/OpenSim/Simulation/InverseKinematicsSolver.cpp#L100)):*
> ```cpp
>             log_error("InverseKinematicsSolver: No orientation data available from source "
>                       "provided.");
>             throw Exception("InverseKinematicsSolver: No sensor data available "
> ```

error above and in this Exception refer to the data in two different ways (`orientation data` and `sensor data`), probably just pick whichever one you think is clearer to the user?

Also, message might by cryptic for a user since this message generically refers to `source`. I'm guessing it might be this way because at this point we don't know if the user provided either a Table or a file as input? I think this is OK as long as the front of the message is clear.
___
*[OpenSim/Simulation/InverseKinematicsSolver.cpp, line 119 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2894#-MJmRtcS72FSoNY6J7jC:-MJmRtcS72FSoNY6J7jD:br7c3tv) ([raw file](https://github.com/opensim-org/opensim-core/blob/c4145f6a526010f67cc5bb1c9881f8f9ceac1973/OpenSim/Simulation/InverseKinematicsSolver.cpp#L119)):*
> ```cpp
>                             "correspond to any model frames.");
>         }
>         if (cnt < 4)
> ```

Why a threshold of 4?
___
*[OpenSim/Simulation/InverseKinematicsSolver.cpp, line 343 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2894#-MJmSQig0s7a93OfvhCG:-MJmSQig0s7a93OfvhCH:b-8mz5yp) ([raw file](https://github.com/opensim-org/opensim-core/blob/c4145f6a526010f67cc5bb1c9881f8f9ceac1973/OpenSim/Simulation/InverseKinematicsSolver.cpp#L343)):*
> ```cpp
> {
>     if (osensorIndex >= 0 && 
>         osensorIndex < _orientationAssemblyCondition->getNumOSensors()) {
> ```

Perhaps we can give the contributor clearer credit? Can we merge their PR in first?
___
*[OpenSim/Simulation/OpenSense/IMUPlacer.h, line 88 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2894#-MJmU6PlDsDWIZ5CXPMI:-MJmU6PlDsDWIZ5CXPMJ:b-seskig) ([raw file](https://github.com/opensim-org/opensim-core/blob/c4145f6a526010f67cc5bb1c9881f8f9ceac1973/OpenSim/Simulation/OpenSense/IMUPlacer.h#L88)):*
> ```objc
>      Optionally visualize the model post calibration.
>      */
>     bool run(bool visualizeResults = false) SWIG_DECLARE_EXCEPTION;
> ```

(More for my learning) Why was this added in here? Did a specific wrapping issue come up?
___
*[OpenSim/Simulation/OpenSense/IMUPlacer.cpp, line 188 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2894#-MJmSln-EJQAY9HOpZ0H:-MJmSln-EJQAY9HOpZ0I:bew8csy) ([raw file](https://github.com/opensim-org/opensim-core/blob/c4145f6a526010f67cc5bb1c9881f8f9ceac1973/OpenSim/Simulation/OpenSense/IMUPlacer.cpp#L188)):*
> ```cpp
>     if (cnt < 1) {
>         log_error("IMUPlacer: Calibration data does not "
>                   "correspond to any model frames.");
> ```

Could be good to add explicit directions here since it seems like the code above is a little particular and the user may not be aware of those restrictions based on this message alone.

Ideally would include (and correct me if I'm getting something wrong here): 1) data column names need to be in form `(bodyName)_imu`, 2) bodyName must match corresponding body name on model. This might be tough to fit in this error message too, so if there's a better place for this, feel free to point elsewhere.

**Review by aymanhab — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2894)* status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @carmichaelong)

___
*[OpenSim/Simulation/InverseKinematicsSolver.cpp, line 100 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2894#-MJmRFYBALWDOE2-IN95:-MJmo-ud7gbPyoB8saom:b-45qpbu) ([raw file](https://github.com/opensim-org/opensim-core/blob/c4145f6a526010f67cc5bb1c9881f8f9ceac1973/OpenSim/Simulation/InverseKinematicsSolver.cpp#L100)):*
<details><summary><i>Previously, carmichaelong wrote…</i></summary><blockquote>

error above and in this Exception refer to the data in two different ways (`orientation data` and `sensor data`), probably just pick whichever one you think is clearer to the user?

Also, message might by cryptic for a user since this message generically refers to `source`. I'm guessing it might be this way because at this point we don't know if the user provided either a Table or a file as input? I think this is OK as long as the front of the message is clear.
</blockquote></details>

Agreed, changed to user facing "Orientations" rather than internal names "sensor". Yes we don't know if file or table so "source" serves both ways
___
*[OpenSim/Simulation/InverseKinematicsSolver.cpp, line 119 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2894#-MJmRtcS72FSoNY6J7jC:-MJmoHkH5fwWqzm8Pa6v:bjw77pd) ([raw file](https://github.com/opensim-org/opensim-core/blob/c4145f6a526010f67cc5bb1c9881f8f9ceac1973/OpenSim/Simulation/InverseKinematicsSolver.cpp#L119)):*
<details><summary><i>Previously, carmichaelong wrote…</i></summary><blockquote>

Why a threshold of 4?
</blockquote></details>

It's just a warning and follows the Markers workflow, but not sure it's useful warning, likely users have more but maybe 2 is the bare minimum. Your call.
___
*[OpenSim/Simulation/InverseKinematicsSolver.cpp, line 343 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2894#-MJmSQig0s7a93OfvhCG:-MJmodd3DtkbIyqdy_Yv:b-gn52j4) ([raw file](https://github.com/opensim-org/opensim-core/blob/c4145f6a526010f67cc5bb1c9881f8f9ceac1973/OpenSim/Simulation/InverseKinematicsSolver.cpp#L343)):*
<details><summary><i>Previously, carmichaelong wrote…</i></summary><blockquote>

Perhaps we can give the contributor clearer credit? Can we merge their PR in first?
</blockquote></details>

I was going to do that in changelog which is not included yet and so we get some cycles testing it before merging. 
___
*[OpenSim/Simulation/OpenSense/IMUPlacer.h, line 88 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2894#-MJmU6PlDsDWIZ5CXPMI:-MJmow0DAXrUBxncwdvY:b-y0akgw) ([raw file](https://github.com/opensim-org/opensim-core/blob/c4145f6a526010f67cc5bb1c9881f8f9ceac1973/OpenSim/Simulation/OpenSense/IMUPlacer.h#L88)):*
<details><summary><i>Previously, carmichaelong wrote…</i></summary><blockquote>

(More for my learning) Why was this added in here? Did a specific wrapping issue come up?
</blockquote></details>

The signature on the Java side includes whether the method throws exception and so you get to handle it in code cleanly rather than uncaught exceptions that could crash if not caught.
___
*[OpenSim/Simulation/OpenSense/IMUPlacer.cpp, line 188 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2894#-MJmSln-EJQAY9HOpZ0H:-MJmpmdgBKF_NSaEyrYq:blkiccf) ([raw file](https://github.com/opensim-org/opensim-core/blob/c4145f6a526010f67cc5bb1c9881f8f9ceac1973/OpenSim/Simulation/OpenSense/IMUPlacer.cpp#L188)):*
<details><summary><i>Previously, carmichaelong wrote…</i></summary><blockquote>

Could be good to add explicit directions here since it seems like the code above is a little particular and the user may not be aware of those restrictions based on this message alone.

Ideally would include (and correct me if I'm getting something wrong here): 1) data column names need to be in form `(bodyName)_imu`, 2) bodyName must match corresponding body name on model. This might be tough to fit in this error message too, so if there's a better place for this, feel free to point elsewhere.
</blockquote></details>

column names may or may not include "_imu" though the test cases do, so not very strictly enforced but we can enforce and tighten the message. Please suggest reasonable not too verbose alternative.

**Review by carmichaelong — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2894)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @aymanhab and @carmichaelong)

___
*[OpenSim/Simulation/InverseKinematicsSolver.cpp, line 119 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2894#-MJmRtcS72FSoNY6J7jC:-MJmuXjMA02bFXeFR-fi:b-vdtxus) ([raw file](https://github.com/opensim-org/opensim-core/blob/c4145f6a526010f67cc5bb1c9881f8f9ceac1973/OpenSim/Simulation/InverseKinematicsSolver.cpp#L119)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

It's just a warning and follows the Markers workflow, but not sure it's useful warning, likely users have more but maybe 2 is the bare minimum. Your call.
</blockquote></details>

Ah thanks for the context. I'm OK with this as is, or maybe (since we're not quite sure about all use cases yet) we could use `log_info()` and always give the number of frames found to track (this could be added after the previous for loop).

Sorry to throw another wrench in, but I'm also realizing that `frames` here clashes with the notion of `frames` in marker based IK as time points. Perhaps just changing to "model frames" helps this enough?
___
*[OpenSim/Simulation/OpenSense/IMUPlacer.cpp, line 188 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2894#-MJmSln-EJQAY9HOpZ0H:-MJmx26x1NsJ9yQYXdCw:b-k2y3ck) ([raw file](https://github.com/opensim-org/opensim-core/blob/c4145f6a526010f67cc5bb1c9881f8f9ceac1973/OpenSim/Simulation/OpenSense/IMUPlacer.cpp#L188)):*
> ```
> auto ix = imuName.rfind("_imu");
> ```
Hm, I thought this would return `string::npos` if it can't find and would skip this loop? If it is enforced/tightened, maybe could add to the current message something like "Column names must formatted as (bodyname)_imu"?

**Review by aymanhab — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2894)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @carmichaelong)

___
*[OpenSim/Simulation/InverseKinematicsSolver.cpp, line 119 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2894#-MJmRtcS72FSoNY6J7jC:-MJn3xD38BXixjPY-W1d:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/c4145f6a526010f67cc5bb1c9881f8f9ceac1973/OpenSim/Simulation/InverseKinematicsSolver.cpp#L119)):*
<details><summary><i>Previously, carmichaelong wrote…</i></summary><blockquote>

Ah thanks for the context. I'm OK with this as is, or maybe (since we're not quite sure about all use cases yet) we could use `log_info()` and always give the number of frames found to track (this could be added after the previous for loop).

Sorry to throw another wrench in, but I'm also realizing that `frames` here clashes with the notion of `frames` in marker based IK as time points. Perhaps just changing to "model frames" helps this enough?
</blockquote></details>

Done.
___
*[OpenSim/Simulation/OpenSense/IMUPlacer.cpp, line 188 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2894#-MJmSln-EJQAY9HOpZ0H:-MJn5D9u2OL04AhHbhGu:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/c4145f6a526010f67cc5bb1c9881f8f9ceac1973/OpenSim/Simulation/OpenSense/IMUPlacer.cpp#L188)):*
<details><summary><i>Previously, carmichaelong wrote…</i></summary><blockquote>

> ```
> auto ix = imuName.rfind("_imu");
> ```
Hm, I thought this would return `string::npos` if it can't find and would skip this loop? If it is enforced/tightened, maybe could add to the current message something like "Column names must formatted as (bodyname)_imu"?
</blockquote></details>

Done.

**Review by carmichaelong — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2894)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @aymanhab and @carmichaelong)

___
*[OpenSim/Simulation/InverseKinematicsSolver.cpp, line 119 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2894#-MJmRtcS72FSoNY6J7jC:-MJn6o4a3QTZegdyGEAg:b-7j6ef6) ([raw file](https://github.com/opensim-org/opensim-core/blob/c4145f6a526010f67cc5bb1c9881f8f9ceac1973/OpenSim/Simulation/InverseKinematicsSolver.cpp#L119)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I think I stuffed too many asks in one post, sorry. I'd also remove the `if` statement so that this is always sent to `log_info()`. LGTM after this

**Review by aymanhab — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2894)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @carmichaelong)

___
*[OpenSim/Simulation/InverseKinematicsSolver.cpp, line 119 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2894#-MJmRtcS72FSoNY6J7jC:-MJn9iaY2ZwRovEuStfH:bb6un1j) ([raw file](https://github.com/opensim-org/opensim-core/blob/c4145f6a526010f67cc5bb1c9881f8f9ceac1973/OpenSim/Simulation/InverseKinematicsSolver.cpp#L119)):*
<details><summary><i>Previously, carmichaelong wrote…</i></summary><blockquote>

I think I stuffed too many asks in one post, sorry. I'd also remove the `if` statement so that this is always sent to `log_info()`. LGTM after this
</blockquote></details>

Done

**Review by aymanhab — COMMENTED** [review]
Ready for final review

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2894#-:-MK0XiJpCIfKto3TY37S:bsy6x6j)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @carmichaelong)

**Review by carmichaelong — APPROVED** [review]
Thanks @aymanhab. LGTM. I can test interaction with GUI after the GUI side daily build

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2894#-:-MK0yIw01tNIBUu5SlJm:bwtns0d)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @carmichaelong)

**Comment by aymanhab** [comment]
Thanks @carmichaelong 👍

**Pull request merged**
