### PR TITLE
Cleanup opensense command line options

### PR DESCRIPTION
**Pull request by aseth1**
Fixes issue #https://github.com/opensim-org/BananaPhone/issues/23#issuecomment-494106971

### Brief summary of changes
- remove "advanced/experimental" options for generating IMU frames and computing orientations from marker data.
- rename -S(Setup) to -IK(InverseKinematis) to be consistent with other opensense command-line operations.
- format help text 
### Testing I've completed
- was able to run all listed options from the command-line

### Looking for feedback on...
- comments on Help text

---
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2472)

### CODE REVIEW

**Comment by jenhicks** [comment]
@aseth1 Thanks! The updates look good to me ... just one comment/question: 

The advanced/experimental options are still available, correct? Is there a way to preserve the documentation for them in some way (maybe in comments) for so we still have a copy of it somewhere?

**Comment by aseth1** [comment]
@jenhicks good idea. I restored the advanced/experimental options help within comments.

**Comment by jimmyDunne** [comment]
The options look great 

image

**Comment by jimmyDunne** [comment]
Tested all the calls and everything seems to work great. Merged.

**Comment by aseth1** [comment]
Thank you @jenhicks and @jenhicks for the super-fast review!

**Pull request merged**
