### PR TITLE
Get rid of TwoFrameLinker::scale() warning on clang.

### PR DESCRIPTION
**Pull request by chrisdembia**
For a while now, clang has given a warning in TwoFrameLinker/WeldConstraint about `TwoFrameLinker::scale()` not being marked as `override`. The base class `Constraint` has a virtual `scale()` function, and this was implemented for WeldConstraint via `TwoFrameLinker::scale()`--in this case, it would make sense to mark `TwoFrameLinker::scale()` as `override`. However, not all base classes of `TwoFrameLinker` have a `scale()` function (e.g., Force, for BushingForces).

This PR renames `TwoFrameLinker::scale()` to `TwoFrameLinker::scaleFrames()`, and `WeldConstraint::scale()` calls `TwoFrameLinker::scaleFrames()`. This gets rid of the warning. I also added notes to the TwoFrameLinker doxygen to help future developers make use of the renamed `scaleFrames()` function.

### CODE REVIEW

**Comment by aseth1** [comment]
This solution seems fine to me. :+1:

**Comment by aseth1** [comment]
still looking for a quick secondary review - @aymanhab @carmichaelong?

**Comment by carmichaelong** [comment]
LGTM

**Comment by chrisdembia** [comment]
Thank you.

**Pull request merged**
