### PR TITLE
Move DeGrooteFregly2016Muscle from Moco to OpenSim

### PR DESCRIPTION
**Pull request by nickbianco**
Addresses issue #2714 

### Brief summary of changes
- Brought in the DeGrooteFregly2016Muscle class files from Moco
- Updated header files for bindings

### Testing I've completed
- Nothing yet, this PR is for review the meat of the DGF muscle code.

### Looking for feedback on...
- We rely on many utilities in Moco to use this class (e.g., `createVectorLinspace()`, `writeTableToFile`, etc) that are not included currently in this PR. Some of these utilities might fit better in a PR to master (e.g., `format()`, which is related to logging stuff).

### CHANGELOG.md (choose one)

- no need to update because...merging to feature branch.

---
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2793)

### CODE REVIEW

**Comment by nickbianco** [comment]
@carmichaelong I requested your review since you've been working on the Millard muscle recently, but I could see this PR having another reviewer -- up to you.

**Comment by chrisdembia** [comment]
@nickbianco can you include the relevant test cases from Moco that test the muscle without Moco?

**Comment by aymanhab** [comment]
I'd like to take a look once changes are complete to get a sense of what's involved with the new muscle model. Also do we know if the muscle shows up in GUI, or how it interacts with Tools etc. Thanks

**Comment by chrisdembia** [comment]
> I think we can wait to merge this PR until #2808 is merged so we can build this branch and run the tests

Sounds good.

BTW, catch.hpp is already on opensim-core's master branch. See testFunctions.cpp.

**Comment by chrisdembia** [comment]
The tests fail because the symbol `OpenSim::DeGrooteFregly2016Muscle::m_minNormTendonForce` is not defined.

**Comment by nickbianco** [comment]
Thanks @carmichaelong.

**Pull request merged**
