### PR TITLE
testForces to catch2

### PR DESCRIPTION
**Pull request by AllisonJohn**
Fixes issue #3555

### Brief summary of changes
each test function -> catch2 test case

### Testing I've completed
tests pass

### CHANGELOG.md (choose one)

- no need to update because... internal

- - -
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3847)

### CODE REVIEW

**Review by nickbianco — CHANGES_REQUESTED** [review]
Looks good! Same comment about using anonymous namespaces, plus two style comments.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3847#-:-O1SWAlP8JggHtzUlKeF:b-essmdv)* status: all files reviewed, 3 unresolved discussions (waiting on @AllisonJohn)

___
*[`OpenSim/Simulation/Test/testForces.cpp` line 44 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3847#-O1SVdBn-0IaxRA-RK0M:-O1SVdBn-0IaxRA-RK0N:bob9z0l) ([raw file](https://github.com/opensim-org/opensim-core/blob/8591740894c964fef812cd31396d316c333b5bd1/OpenSim/Simulation/Test/testForces.cpp#L44)):*
> ```cpp
> #include "SimTKcommon/internal/Xml.h"
> #include <ctime> // clock(), clock_t, CLOCKS_PER_SEC
> ```

In general, I would leave any blank lines between include statements as-is. There's no standardization for this in OpenSim (yet), but for now we'll just keep any existing formatting.
___
*[`OpenSim/Simulation/Test/testForces.cpp` line 54 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3847#-O1SVPYoBIMl3_ysobr8:-O1SVPYoBIMl3_ysobr9:bnq1d3h) ([raw file](https://github.com/opensim-org/opensim-core/blob/cc432ba45db4d90dae2eeb478b1a373935420723/OpenSim/Simulation/Test/testForces.cpp#L54)):*
> ```cpp
> //==============================================================================
> // Common Parameters for the simulations are just global.
> const static double integ_accuracy = 1.0e-4;
> ```

minor: move shared variables and functions to an anonymous namespace.
___
*[`OpenSim/Simulation/Test/testForces.cpp` line 1176 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3847#-O1SVYfr2J9EOKuRAnEV:-O1SVYfr2J9EOKuRAnEW:b-4lz8y5) ([raw file](https://github.com/opensim-org/opensim-core/blob/cc432ba45db4d90dae2eeb478b1a373935420723/OpenSim/Simulation/Test/testForces.cpp#L1176)):*
> ```cpp
> // Simple simulation of bouncing ball with dissipation should generate contact
> // forces that settle to ball weight.
> ```

Remove extra line.

**Review by AllisonJohn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3847)* status: all files reviewed, 2 unresolved discussions (waiting on @nickbianco)

___
*[`OpenSim/Simulation/Test/testForces.cpp` line 44 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3847#-O1SVdBn-0IaxRA-RK0M:-O1SnMpFA6GDmKVYZD7B:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/8591740894c964fef812cd31396d316c333b5bd1/OpenSim/Simulation/Test/testForces.cpp#L44)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

In general, I would leave any blank lines between include statements as-is. There's no standardization for this in OpenSim (yet), but for now we'll just keep any existing formatting.
</blockquote></details>

Done.
___
*[`OpenSim/Simulation/Test/testForces.cpp` line 1176 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3847#-O1SVYfr2J9EOKuRAnEV:-O1Sp4_P800Gb-jjlBRK:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/cc432ba45db4d90dae2eeb478b1a373935420723/OpenSim/Simulation/Test/testForces.cpp#L1176)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Remove extra line.
</blockquote></details>

Done.

**Review by nickbianco — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3847)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AllisonJohn)

___
*[`OpenSim/Simulation/Test/testForces.cpp` line 1176 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3847#-O1SVYfr2J9EOKuRAnEV:-O1TA05mA4hdk466H6rf:bhxm6kg) ([raw file](https://github.com/opensim-org/opensim-core/blob/cc432ba45db4d90dae2eeb478b1a373935420723/OpenSim/Simulation/Test/testForces.cpp#L1176)):*
<details><summary><i>Previously, AllisonJohn wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I'm still seeing a blank line here.

**Review by nickbianco — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3847)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AllisonJohn)

**Pull request merged**
