### PR TITLE
Upgrade lepton; fix vs2013 warnings.

### PR DESCRIPTION
**Pull request by chrisdembia**
Incorporates changes made via https://github.com/pandegroup/openmm/pull/799

Before merging, we should make sure the vs2013 warnings in appveyor are gone.

### CODE REVIEW

**Comment by chrisdembia** [comment]
Fixes #284.

**Comment by chrisdembia** [comment]
Yay! the warnings (in appveyor) are gone! Ready for review.

**Comment by sherm1** [comment]
Looks good to me.

**Comment by chrisdembia** [comment]
Thanks @sherm1 . Any other takers?

**Comment by aymanhab** [comment]
Looks fine and no warnings on appvoyer. merging. Thanks @chrisdembia

**Comment by chrisdembia** [comment]
Thanks Ayman.

**Comment by aymanhab** [comment]
No problem and thanks for the fix Chris. Problem is that build on travis is
now failing due to another commit that changed min version of CMake (even
though github claimed merge can be done safely), are you looking into this
or is there a fix in the pipe?

Thanks,
-Ayman

**Comment by chrisdembia** [comment]
Yes; #351 fixes that.

**Pull request merged**
