### PR TITLE
Have Lepton and simmFileWriter use the OPENSIM_ADD_LIBRARY macro.

### PR DESCRIPTION
**Pull request by chrisdembia**
For uniformity with the cmake for other libraries.

I changed the location of Lepton headers from `sdk/include/lepton` to `sdk/include/Lepton`, but this does not affect users since they are given an "include directory" via OpenSimConfig.cmake of `sdk/include/Lepton/include`.

This is the next step in my work towards allowing users to install OpenSim into `/usr/local/` on UNIX.

### CODE REVIEW

**Comment by aymanhab** [comment]
@chrisdembia Anything for me to check or review here?

**Comment by chrisdembia** [comment]
Would love a review! The tests pass and it seems like the tests still compile simmFileWriter and Lepton, so in my opinion this can be merged. The only place I think an error could have occurred is with the ADD_DEFINITIONS, which are now being taken care of by the OPENSIM_ADD_LIBARARY cmake function.

**Comment by aymanhab** [comment]
Since build is the one and only relevant operation to validate the changes and that works I'll go ahead and merge.

**Comment by chrisdembia** [comment]
Thanks!

**Pull request merged**
