### PR TITLE
Update readme animation

### PR DESCRIPTION
**Pull request by aymanhab**
Fixes issue #3327 
### CHANGELOG.md (choose one)

- no need to update because internal

- - -
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3336)

### CODE REVIEW

**Comment by aymanhab** [comment]
For your review @tkuchida or @jenhicks

**Comment by aymanhab** [comment]
The mp4 file used to create the gif was added but is not used, just in case more tweaking is needed.

**Comment by tkuchida** [comment]
Is it possible to crop out the black bars or make them white?

**Comment by aymanhab** [comment]
Done, thanks  @tkuchida & @jenhicks

**Comment by jenhicks** [comment]
The update looks good to me. Thanks @aymanhab

**Pull request merged**
