### PR TITLE
[Moco] Add option to enforce path constraints at mesh interval midpoints

### PR DESCRIPTION
**Pull request by nickbianco**
Fixes issue #3133 

### Brief summary of changes
- Added property 'enforce_path_constraint_midpoints' to `MocoCasADiSolver`, which tells the solver to enforce `MocoPathConstraint`s at mesh interval midpoints when using Hermite-Simpson collocation.
- Updated `MocoInverse` documentation.

### Testing I've completed
- Added a test to `testMocoInverse`.

### CHANGELOG.md (choose one)

- updated.

---
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3137)

### CODE REVIEW

**Review by carmichaelong — CHANGES_REQUESTED** [review]
Looks great overall, and added test is nice. Just a few minor comments on comments.

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3137#-:-MvqvBQl9M12-l-nAtCU:bjj3puk)* status: all files reviewed, 3 unresolved discussions (waiting on @nickbianco)

___
*[OpenSim/Moco/MocoCasADiSolver/CasOCSolver.h, line 121 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3137#-Mv_ztUR34L11xT0LEm4:-Mv_ztUR34L11xT0LEm5:b4c7o4u) ([raw file](https://github.com/opensim-org/opensim-core/blob/05d504c81b3d123add7dcadcc2863f7c57113e44/OpenSim/Moco/MocoCasADiSolver/CasOCSolver.h#L121)):*
> ```objc
>     /// @note Only applies to Hermite-Simpson collocation.
>     /// @note Does not apply to implicit dynamics residuals, as these are
>     ///       always enforce at mesh interval midpoints.
> ```

enforce -> enforced
___
*[OpenSim/Moco/MocoCasADiSolver/CasOCTranscription.h, line 328 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3137#-MvaMNCb7EiwctXNuFMj:-MvaMNCb7EiwctXNuFMk:bqy7vam) ([raw file](https://github.com/opensim-org/opensim-core/blob/05d504c81b3d123add7dcadcc2863f7c57113e44/OpenSim/Moco/MocoCasADiSolver/CasOCTranscription.h#L328)):*
> ```objc
> 
>         // Hermite-Simpson sparsity pattern for mesh intervals 0, 1 and 2
>         // (* indicates when path constraint midpoints are enforced):
> ```

perhaps a small addition to be super clear: "indicates additional entry when path constraint midpoints are enforced" (i'm not 100% sold on the word "entry" though)
___
*[OpenSim/Moco/MocoCasADiSolver/CasOCTranscription.cpp, line 1124 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3137#-MvaW0IQCRKgJzy-YKkA:-MvaW0IQCRKgJzy-YKkB:b-bkcou9) ([raw file](https://github.com/opensim-org/opensim-core/blob/05d504c81b3d123add7dcadcc2863f7c57113e44/OpenSim/Moco/MocoCasADiSolver/CasOCTranscription.cpp#L1124)):*
> ```cpp
>             }
>         }
>         ss << "Path constraint values at each mesh point:" << std::endl;
> ```

if i'm understanding the terminology correctly, i think this string needs to be updated mesh point -> grid point or path constraint point(?)

**Review by nickbianco — COMMENTED** [review]
Thanks @carmichaelong, easy updates.

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3137#-:-MvtmEwy-hCmYiMgF6Gy:banhcav)* status: 5 of 8 files reviewed, 3 unresolved discussions (waiting on @carmichaelong)

___
*[OpenSim/Moco/MocoCasADiSolver/CasOCSolver.h, line 121 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3137#-Mv_ztUR34L11xT0LEm4:-Mvtm8v73tUx6qdVNc4j:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/05d504c81b3d123add7dcadcc2863f7c57113e44/OpenSim/Moco/MocoCasADiSolver/CasOCSolver.h#L121)):*
<details><summary><i>Previously, carmichaelong wrote…</i></summary><blockquote>

enforce -> enforced
</blockquote></details>

Done.
___
*[OpenSim/Moco/MocoCasADiSolver/CasOCTranscription.h, line 328 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3137#-MvaMNCb7EiwctXNuFMj:-MvtlmCb-sjpqntNHyAh:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/05d504c81b3d123add7dcadcc2863f7c57113e44/OpenSim/Moco/MocoCasADiSolver/CasOCTranscription.h#L328)):*
<details><summary><i>Previously, carmichaelong wrote…</i></summary><blockquote>

perhaps a small addition to be super clear: "indicates additional entry when path constraint midpoints are enforced" (i'm not 100% sold on the word "entry" though)
</blockquote></details>

Done.
___
*[OpenSim/Moco/MocoCasADiSolver/CasOCTranscription.cpp, line 1124 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3137#-MvaW0IQCRKgJzy-YKkA:-MvtmE0NCPMBj0OV0_iT:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/05d504c81b3d123add7dcadcc2863f7c57113e44/OpenSim/Moco/MocoCasADiSolver/CasOCTranscription.cpp#L1124)):*
<details><summary><i>Previously, carmichaelong wrote…</i></summary><blockquote>

if i'm understanding the terminology correctly, i think this string needs to be updated mesh point -> grid point or path constraint point(?)
</blockquote></details>

Done.

**Review by carmichaelong — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3137#-:-MvuYETP95dyTiqyIG-P:bnfp4nl)* status: 5 of 8 files reviewed, all discussions resolved (waiting on @carmichaelong)

**Comment by nickbianco** [comment]
Thanks @carmichaelong!

**Pull request merged**
