### PR TITLE
Add Log.h, LogSink.h.

### PR DESCRIPTION
**Pull request by chrisdembia**
# Brief summary of changes

This PR adds infrastructure for logging with spdlog, including adding a JavaLogSink to log OpenSim messages through Java., and a command-line option for controlling the log level.

### Testing I've completed

Ran ctests.

### Looking for feedback on...

Naming of classes

### CHANGELOG.md (choose one)

- no need to update because...it's part of a larger feature

The Doxygen for this PR can be viewed at http://myosin.sourceforge.net/?C=N;O=D; click the folder whose name is this PR's number.

---
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2596)

### CODE REVIEW

**Comment by aymanhab** [comment]
Looks great @chrisdembia 
On the naming, do you think Log should be changed to Logger, it feels like the Log would be the name of the product of this class not the class itself but maybe others could chime in as well.

**Comment by chrisdembia** [comment]
@aymanhab you make a great point. I went with `Log` because it's shorter, and we will have commands like `Logger::info()` appearing everywhere throughout the code. 

What do you think about `info()` being a free function in the OpenSim namespace? That way, we can simply use `info("blah")`? If so, then I will gladly change `Log` to `Logger`.

**Comment by aymanhab** [comment]
@chrisdembia I agree with the free function (or a macro) so we don't have widespread changes once done with this round.

**Comment by chrisdembia** [comment]
Well it seems that the MSVC regex library is struggling to handle the updated documentation strings. I don't have an MSVC environment setup. @aymanhab would you be willing to help debug this?

**Comment by aymanhab** [comment]
Sure, will do.

**Comment by chrisdembia** [comment]
Thank you 🙇

**Comment by aymanhab** [comment]
@chrisdembia will try back in the office since my laptop has VS2019 which fails much earlier due to docopt build errors.

**Comment by chrisdembia** [comment]
Okay sounds good.

**Comment by aymanhab** [comment]
@chrisdembia Building locally with my VS 2017 shows no failures at all! Note that the reported failures on appveyor are in tests (that do not exercise the new code AFAICT, and after compilation/linking is done i.e. they are runtime errors). This is likely msvc version/patch dependent but I'll keep investigating.

**Comment by chrisdembia** [comment]
Ah I think it has to do with the amount of RAM available to the process?

**Comment by aymanhab** [comment]
@chrisdembia I realized that the failures only happen for cases that invoke opensim-cmd from CMake. I undid the change to opensim-cmd and the tests continue to fail but I still think these are related to the changes in opensim-cmd.

**Comment by chrisdembia** [comment]
@aymanhab we could roll back the new command-line flag. As-is, users cannot control the debug level for the command-line tools.

**Comment by aymanhab** [comment]
@chrisdembia I attempted that earlier and somehow it didn't help, maybe I missed one place. Feel free to do/try it.

**Comment by chrisdembia** [comment]
@aymanhab okay I'm trying it now.

**Comment by aymanhab** [comment]
Latest test failures are unrelated so this can be merged to the branch, LGTM.

**Comment by chrisdembia** [comment]
Thanks @aymanhab

**Pull request merged**
