### PR TITLE
Update CI to use MacOS 12

### PR DESCRIPTION
**Pull request by nickbianco**
Fixes issue #<issue_number>

### CHANGELOG.md (choose one)

- no need to update because...
- updated.

- - -
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3604)

### CODE REVIEW

**Comment by nickbianco** [comment]
@aymanhab, @AlbertoCasasOrtiz, I noticed the recent Mac builds have been failing because package installs with Homebrew were taking a very long time (4+ hours). MacOS 11 is no longer officially supported, so I'm testing the CI using MacOS 12.

**Comment by aymanhab** [comment]
Sounds good @nickbianco will keep an eye. One thing to keep in mind is that regardless of github position, we need to check if the build runs on osx11 machines (as some users maybe stuck there).

**Comment by nickbianco** [comment]
@aymanhab, the change seems to be working as intended (aside from some minor failures in `testMocoInverse`, which I can address). Do we know anyone still using MacOS 11? The official EOL was in September, so I'd say it's reasonable to upgrade to the oldest version still supported by Apple.

**Comment by aymanhab** [comment]
@nickbianco I think 3 yrs is long enough lag for users to upgrade, so I wouldn't hold development progress for these rare cases.  There're other CMake variables related to osx version that may allow this build to still run on earlier versions anyway, so I'm good with the change once tests are passing. 👍

**Comment by nickbianco** [comment]
Merging, thanks @aymanhab.

**Pull request merged**
