### PR TITLE
Build SIMM_TRANSLATOR on Travis

### PR DESCRIPTION
**Pull request by chrisdembia**
There are numerous errors currently; simmTranslator does not compile on Linux.

---
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/278)

### CODE REVIEW

**Comment by chrisdembia** [comment]
There's at least one person here at ISB TGCS who is using a SIMM model that they import into OpenSim for visualization. So perhaps we should address this.

**Comment by nickbianco** [comment]
Closing since this PR is almost 10 years old with no activity.

**Comment by aymanhab** [comment]
Fine, we should also remove the cmake flag to reduce the clutter

**Comment by nickbianco** [comment]
@aymanhab I opened an issue (https://github.com/opensim-org/opensim-core/issues/3876), since I think this warrants a bit of discussion.

**Pull request closed without merging**
