### PR TITLE
Event triggered delay

### PR DESCRIPTION
**Pull request by mitkof6**
@chrisdembia 

The event triggered delay. The system under simulation is the GolgiTendon. There are different inputs (ConstantInput, StepInput). BlockComponentAnalysis records the input output of all components that are derived form BlockComponent. DelaySignal is a component that has input/output delayed with a trigger witness function.

I have added two results of the simulation, one is the correct response and one is the wrong and a plot. For you to simulate the wrong scenario comment the line 47 in the DelaySignal where I add the eventTrigger. As you may exhibit the result is not so wrong (the peak value is not correct it should be 1 because the event wasn't localized) but we were lucky with the integration stepping. I have seen far worse results than that.

### CODE REVIEW

**Comment by mitkof6** [comment]
I draw an example image to explain the problem.

Image

The integrator steps at 0, 0.3, 1.2. At 1.2 it detects that the state must be changed because the input has changed. Although it is not known when exactly the input has changed an so the response will be wrong. The correct result is marked with red, where the Integrator has localized when the event will occur and compute the new state.

**Comment by chrisdembia** [comment]
Thanks @mitkof6 for posting this. I have to keep thinking about this.

**Comment by chrisdembia** [comment]
@mitkof6 thanks for showing me this code. I think I understand the scenario. My concern is that the event trigger is used for a specific use case, and thus does not belong in the Delay class. The requirement of having an event trigger is really unique to the discontinuity of the step input. In general, a Delay's input and output won't be the same. Such an event trigger could unnecessarily slow down the simulation of a sinusoid, since in general the input and output are not the same but every so often they cross, causing unnecessary localization.

How about a special type of Delay component, a StepDelay or something like that, that combines both your `StepInput` and a `Delay` as subcomponents, as well as an `TriggeredEvent`? Do you see any issues with this?

We intend to have an OpenSim component for events as well.

I also want to say that if you are interested in developing operator components for OpenSim, we should talk about the best way to proceed, perhaps over Skype. We would definitely appreciate the contribution.

**Comment by mitkof6** [comment]
@chrisdembia Sorry I just saw this post. Yes, I would like to help. I have already implemented many Simulink style components, which of course are not very generic, but specific for my needs. We can have a Skype (username mitkof6). Your morning time is my evening.

> How about a special type of Delay component, a StepDelay or something like that, that combines both your StepInput and a Delay as subcomponents, as well as an TriggeredEvent? Do you see any issues with this?

Yes, this seems to help in the organization of the components. I have some other issues that have encountered during the development that I have done.

**Comment by chrisdembia** [comment]
Great! I'll email you.

**Pull request closed without merging**
