### PR TITLE
[WIP] Made pennation model into a subcomponent in Millard2012EquilibriumMuscle

### PR DESCRIPTION
**Pull request by tkuchida**
Analogous to changes made in Thelen2003Muscle (#827). Also removed deprecated methods.

### CODE REVIEW

**Comment by tkuchida** [comment]
Test failures are the same as those reported in #784 (which were previously only seen on my local 32-bit build).

**Comment by chrisdembia** [comment]
Is the failure at all related to this warning:

```
WARNING: Millard2012AccelerationMuscle initialization exception caught:
Exception caught in Millard2012AccelerationMuscle::calcMuscleDynamicsInfo
of extobl_l
SimTK Exception thrown at MuscleFixedWidthPennationModel.cpp:297:
  Error detected by Simbody method MuscleFixedWidthPennationModel::calc_DPennationAngle_DfiberLength: Fiber length is below the lower bound for this muscle.
  (Required condition 'fiberLength > m_parallelogramHeight' was not met.)
```

**Comment by tkuchida** [comment]
@chrisdembia are you getting that warning on your local build? Travis and AppVeyor are reporting lots of warnings. It's unclear where the issue is; I encountered it (#784) a while ago.

**Comment by tkuchida** [comment]
Re-implemented on new branch; closing.

**Pull request closed without merging**
