### PR TITLE
Clean up CI script, add Mac arm64 and Ubuntu 22 builds

### PR DESCRIPTION
**Pull request by nickbianco**
Fixes issue #3944

### Brief summary of changes

- Updates `continuous_integration.yml` to include separate jobs for Mac x64 and Arm64 architectures. 
- Removed the "no Moco" Ubuntu job and replaced it with an Ubuntu 22 job.
- Fixed a compiler error in `WrapEllipsoid` related to indexing a Mat44 that was causing the Ubuntu 22 job to fail.

### Testing I've completed

Ran the CI, and ran both the Windows and Mac performance analysis workflows.

### CHANGELOG.md (choose one)

- no need to update because...CI updates.

### Performance analysis

Platform: Mac, GitHub Actions runner

|                           Test Name | lhs [secs] | stderr [secs] | rhs [secs] | stderr [secs] | Speedup |
| ----------------------------------- | ---------- | ------------- | ---------- | ------------- | ------- |
|                               Arm26 |       0.35 |          0.72 |       0.36 |          0.78 |    0.97 |
| ToyDropLanding_function_based_paths |       3.57 |          0.00 |       3.59 |          0.00 |    0.99 |
|          passive_dynamic_noanalysis |       1.12 |          0.00 |       1.13 |          0.00 |    0.99 |
|                      ToyDropLanding |       3.92 |          0.00 |       3.93 |          0.00 |    1.00 |
|                            Gait2354 |       0.21 |          0.00 |       0.21 |          0.00 |    1.00 |
|      ToyDropLanding_fbp_stepwisereg |       3.63 |          0.00 |       3.63 |          0.00 |    1.00 |
|                     passive_dynamic |       1.71 |          0.00 |       1.71 |          0.00 |    1.00 |
|                    MocoSquatToStand |       3.45 |          0.00 |       3.46 |          0.00 |    1.00 |
|            ToyDropLanding_nomuscles |       0.20 |          0.00 |       0.20 |          0.00 |    1.00 |
| ellipsoid_wrap_function_based_paths |       1.09 |          0.00 |       1.08 |          0.00 |    1.00 |
|                      ellipsoid_wrap |       1.28 |          0.00 |       1.28 |          0.00 |    1.00 |
|                     MocoSlidingMass |       0.57 |          0.00 |       0.57 |          0.00 |    1.00 |
|                      RajagopalModel |       3.14 |          0.00 |       3.14 |          0.00 |    1.00 |

- - -
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3946)

### CODE REVIEW

**Comment by aymanhab** [comment]
@nickbianco For the record the LD_LIBRARY_PATH changes appear to have been lost before the python tests are run on ubuntu.

**Comment by nickbianco** [comment]
Installing the Mac Arm64 build into a local conda environment fails. @aymanhab, thoughts? Looks like the rpaths are not being set correctly?

```
Python 3.10.15 (main, Oct  3 2024, 02:24:49) [Clang 14.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import opensim as osim
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/nbianco/miniconda3/envs/zmp/lib/python3.10/site-packages/opensim/__init__.py", line 18, in <module>
    from .simbody import *
  File "/Users/nbianco/miniconda3/envs/zmp/lib/python3.10/site-packages/opensim/simbody.py", line 10, in <module>
    from . import _simbody
ImportError: dlopen(/Users/nbianco/miniconda3/envs/zmp/lib/python3.10/site-packages/opensim/_simbody.so, 0x0002): Library not loaded: @rpath/libosimExampleComponents.dylib
  Referenced from: <35EB33C3-F08F-3BC8-A249-794230C5E39D> /Users/nbianco/miniconda3/envs/zmp/lib/python3.10/site-packages/opensim/_simbody.so
  Reason: tried: '/Users/nbianco/miniconda3/envs/zmp/lib/python3.10/site-packages/opensim/libosimExampleComponents.dylib' (no such file), '/Users/nbianco/miniconda3/envs/zmp/lib/python3.10/site-packages/opensim/../../../sdk/lib/libosimExampleComponents.dylib' (no such file), '/Users/runner/work/opensim-core/opensim-core-install/sdk/lib/libosimExampleComponents.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/runner/work/opensim-core/opensim-core-install/sdk/lib/libosimExampleComponents.dylib' (no such file), '/Users/nbianco/miniconda3/envs/zmp/lib/python3.10/site-packages/opensim/../../../sdk/Simbody/lib/libosimExampleComponents.dylib' (no such file), '/Users/runner/work/opensim-core/opensim-core-install/sdk/Simbody/lib/libosimExampleComponents.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/runner/work/opensim-core/opensim-core-install/sdk/Simbody/lib/libosimExampleComponents.dylib' (no such file), '/Users/nbianco/miniconda3/envs/zmp/lib/python3.10/site-packages/opensim/libosimExampleComponents.dylib' (no such file), '/Users/nbianco/miniconda3/envs/zmp/lib/python3.10/site-packages/opensim/../../../sdk/lib/libosimExampleComponents.dylib' (no such file), '/Users/runner/work/opensim-core/opensim-core-install/sdk/lib/libosimExampleComponents.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/runner/work/opensim-core/opensim-core-install/sdk/lib/libosimExampleComponents.dylib' (no such file), '/Users/nbianco/miniconda3/envs/zmp/lib/python3.10/site-packages/opensim/../../../sdk/Simbody/lib/libosimExampleComponents.dylib' (no such file), '/Users/runner/work/opensim-core/opensim-core-install/sdk/Simbody/lib/libosimExampleComponents.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/runner/work/opensim-core/opensim-core-install/sdk/Simbody/lib/libosimExampleComponents.dylib' (no such file), '/Users/nbianco/miniconda3/envs/zmp/bin/../lib/libosimExampleComponents.dylib' (no such file), '/Users/nbianco/miniconda3/envs/zmp/bin/../lib/libosimExampleComponents.dylib' (no such file)
```

**Comment by aymanhab** [comment]
@nickbianco Conda makes some assumptions about layout. When we build conda package, the conda build system modifies rpaths accordingly. I'd test installing in non conda environment using setup.py etc. but not sure conda would work out of the box. I'd also test java/matlab
Just let me know what you want me to try/test to get this over the finish line

**Comment by nickbianco** [comment]
Yeah, it looks like `python -m pip install .` doesn't install the `.dylib`s anywhere in the conda environment. I'll try a different install approach and see what I get.

**Comment by nickbianco** [comment]
@aymanhab, this is ready for review. I didn't test the "Build GUI" workflow; let me know if you'd like that tested as well.

**Comment by aymanhab** [comment]
Would be good to test just for completeness though it has no dependencies on ci scripts.

**Comment by nickbianco** [comment]
@aymanhab, the GUI build job fails, I think because a personal access token needs to be added or updated. It's up to you if you consider that blocking here.

**Comment by aymanhab** [comment]
Thanks for trying it out @nickbianco Definitely not blocking, will review accordingly.

**Review by aymanhab — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3946#-:-O9zp1oc8gTvmApfzyVc:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nickbianco)

**Comment by nickbianco** [comment]
As discussed, the Ubuntu 22 failure is unrelated and the GUI build job will be resolved in a future PR.

Thanks @aymanhab!

**Pull request merged**
