### PR TITLE
Fix "missing override" warnings

### PR DESCRIPTION
**Pull request by chrisdembia**
I chose to move `assign()` up to the `Object` class. I hid it from doxygen since it was previously hidden from doxygen.

### CODE REVIEW

**Comment by sherm1** [comment]
/review. Looks good to me.

**Comment by chrisdembia** [comment]
Thanks @sherm1 . @aymanhab could you take a quick look?

**Comment by sherm1** [comment]
@aymanhab says assign() isn't being used in Java and can be removed. Then merge?

**Comment by chrisdembia** [comment]
@aymanhab let me know when you've checked the GUI; then I'll remove the method. Low priority.

**Comment by aymanhab** [comment]
@chrisdembia Found that assign is used only once in the GUI, however considering the lack of an operator with similar assignment semantics in scripting, I'd keep it around. So, the change in this PR is fine. Will merge.

**Comment by chrisdembia** [comment]
Thanks @aymanhab

**Pull request merged**
