### PR TITLE
Use `std::make_unique` in wrapper function

### PR DESCRIPTION
**Pull request by alexbeattie42**
### Brief summary of changes

Now that OpenSim uses `c++14` use `std::make_unique` instead of the custom implementation

### CHANGELOG.md (choose one)

- updated.

- - -
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3979)

### CODE REVIEW

**Comment by nickbianco** [comment]
Ideally, we could just remove this free function and replace all usages of `OpenSim::make_unique` in the codebase with `std::make_unique`.

**Comment by adamkewley** [comment]
Looks good to me. If @alexbeattie42 is finished then this should just be merged as-is, and if new instances pop up then re-PRing would also be fine.

**Comment by nickbianco** [comment]
@alexbeattie42 feel free to ask for a review when this PR is ready to go. (Same goes for the others you've recently opened, so we don't end up with a bunch of stale PRs.)

**Review by alexbeattie42 — COMMENTED** [review]
@nickbianco and @adamkewley I have now added a changelog entry and the PR should have all instances of `OpenSim::make_unique` switched to `std::make_unique`. It is ready for review.

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3979#-:-OEDIY2a8M-I1bvI6zFP:bfpm0mb)* status: 0 of 37 files reviewed, all discussions resolved

**Comment by adamkewley** [comment]
No need to review, seems simple enough. Thanks @alexbeattie42 :+1:

**Pull request merged**
