### PR TITLE
Split targets into VS folders.

### PR DESCRIPTION
**Pull request by chrisdembia**
I added some changes to cmake so that the targets are split up into categories. I basically took the prefix in the project names and made them into folders. Here's what the solution explorer looks like with these changes:

image

The only downside I see is that unexperienced users may have trouble finding "INSTALL", which might be the only target they're interested in.

### CODE REVIEW

**Comment by sherm1** [comment]
That looks good. Does it help in XCode also?

**Comment by chrisdembia** [comment]
Seems like it does:

image


I got the idea from @tgeijten

**Comment by sherm1** [comment]
Nice!

**Comment by chrisdembia** [comment]
@aseth1, @aymanhab do you guys like the change or should we close the PR?

**Comment by aymanhab** [comment]
@chrisdembia I like the fact that when working on a single test or library that I can collapse the lists and find my target easily. Would be best if INSTALL can be pulled out but if not that's still an improvement. I wouldn't worry about unexperienced developers building from source, they'll hit other hurdles before they get to install!

**Comment by chrisdembia** [comment]
Thanks for looking @aymanhab . I investigated if INSTALL could be pulled out and I could not find a way :/

**Comment by aymanhab** [comment]
No big deal, can we easily add a group/Folder for Scripting as it used to be hard to locate these Wrapping projects in the long list, or I can add it myself separately.

Thanks again @chrisdembia

**Comment by chrisdembia** [comment]
Oh good idea. I'll do it.

**Comment by aseth1** [comment]
I second Ayman's sentiment. I welcome the organization. If the default view is that the list is fully expanded (which very much resembles the current flat list) then finding INSTALL isn't any more difficult than it is now. I wouldn't let that hold back this change. Thanks @chrisdembia.

**Comment by chrisdembia** [comment]
Great. I added wrapping folders. This is ready to merge.

**Comment by aymanhab** [comment]
Great, thanks @chrisdembia

**Comment by chrisdembia** [comment]
Thanks @aymanhab

**Pull request merged**
