### PR TITLE
Expose simbody matter subsystem

### PR DESCRIPTION
**Pull request by aymanhab**
@chrisdembia It would be good to add a test case to exercise this class to make sure the wiring is correct, ideally from Python or Java, then we can remove the WIP specification.

### CODE REVIEW

**Comment by chrisdembia** [comment]
+1. Okay; would you like me to do that?

**Comment by chrisdembia** [comment]
This change is also worth mentioning in the release notes.

**Comment by aymanhab** [comment]
@chrisdembia Yes please, that would be awesome, when you have a chance. Thanks,

**Comment by chrisdembia** [comment]
@aymanhab I have added a fairly simple python test.

**Comment by aymanhab** [comment]
Looks good and test timeout is unrelated (actually the failure is when wrapping is off), thanks @chrisdembia Merging.

**Comment by chrisdembia** [comment]
Woohoo! This will be great for scripting users who want to write advanced algorithms.

**Pull request merged**
