### PR TITLE
Avoid "Policy CMP0054 is not set" warning in CMake when using examples

### PR DESCRIPTION
**Pull request by tkuchida**
See https://cmake.org/cmake/help/v3.8/policy/CMP0054.html. Identical lines in [this file](https://github.com/opensim-org/opensim-core/blob/master/CMakeLists.txt#L296) do not have quotes.

The Doxygen for this PR can be viewed at http://myosin.sourceforge.net/?C=N;O=D; click the folder whose name is this PR's number.

### CODE REVIEW

**Comment by chrisdembia** [comment]
PR https://github.com/opensim-org/opensim-core/pull/1680 removes the need for this.

**Comment by tkuchida** [comment]
> PR https://github.com/opensim-org/opensim-core/pull/1680 removes the need for this.

Thank you; I didn't know PR #1680 existed.

**Comment by tkuchida** [comment]
…that is, I neglected to check whether this issue had been addressed in any of the pending PRs.

**Comment by chrisdembia** [comment]
We could still potentially merge this. I don't know what the timeline is for #1680.

**Pull request closed without merging**
