### PR TITLE
Handful of small changes to python wrapping.

### PR DESCRIPTION
**Pull request by chrisdembia**
1. On Linux, the python wrapper is no longer optimized. This decreases the
memory requirements and build time a little.
2. Added __str__() methods to Vec and Vector, allowing someone to `print myvec`
in python to see the contents of a vector.
3. Created two iterators for Set's, allowing both of the following use cases:
```python
for force in model.getForceSet():
    print force.getName()
```
```python
for name, musc in model.getMuscles().items():
    print name, musc.get_max_isometric_force()
```
4. Allow python indexing into Vec3's and Vector's: `v = Vec3(1,2,3); v[0]`.
5. Allow the python length function on Vec3's and Vector: `len(v) == v.size()`.
6. Better exception handling. Previously, if OpenSim threw an exception, the
python session would crash. Now, it gracefully continues. This wraps **every**
function call in a try-catch block though.
7. Got rid of the swig warnings, largely by just silencing them.
8. Removed OpenSimContext for python wrapping, since it's not used.
9. I added tests corresponding to the changes I made.

The wrapping is slightly slower now, but I think that's fine.

I wanted to also add in support for the ComponentList iterator, but I realize
that we'll need some design discussion about it.

It's very important that we document these changes for our users. I know we've mentioned it but I think it's time to break off a new copy of confluence for 4.0 so that we can start writing new documentation.

/cc @aymanhab

### CODE REVIEW

**Comment by chrisdembia** [comment]
Here's some documentation that we should eventually put on confluence, related to the changes I've made:

We've added some python flavor to our python wrapping:
1. You can access elements of `Vec3` and `Vector` using brackets `[]`:
```python
v = opensim.Vec3(1, 2, 3)
v[0] = 1.5 + v[1]
w = opensim.Vector(5, 1.5)
w[0] = 3 * w[1]
```
2. You can iterate over elements of any `Set`. There are two iterators: one that treats the `Set` like a python list, and another that treats the `Set` like a python dict:
```python
model = opensim.Model("my_model.osim")
for force in model.getForceSet():
    print force.getName()
for name, muscle in model.getMuscles():
    print name, muscle.get_max_isometric_force
```
3. You can use the built-in python function `len()` on `Vec`'s and `Vector_`'s:
```python
w = opensim.Vector(5)
if len(w) < 5:
    raise Exception()
```
4. You can print the contents of a `Vec` or `Vector_` to a string:
```python
>>> v = opensim.Vec3(1, 2, 3)
>>> print v
~[1,2,3]
```

**Comment by aymanhab** [comment]
@chrisdembia The changes and convenience look good but I'd prefer we wait until the geometry branch merge PR #417 since it does wrap the iterators and also because it makes the python and java wrapping interface files more consistent. We should discuss afterwards. Another thing to balance is the need for separate documentation/conversion between Matlab, Python and C++ code/examples due to varying capabilities of target languages.

**Comment by chrisdembia** [comment]
Oh definitely, let's wait then. I was unaware about the changes in the geometry branch.

**Comment by chrisdembia** [comment]
@aseth1 and I were discussing python iterators.

@aseth1 suggested having a switch inside of the python version of `Component::getComponentList(string)` (doesn't exist now) that checks the string type and returns the proper list on the C++ side. This would be an alternative to creating many methods like `Model::getBodyList()`.

I don't know if I'd tackle that for this PR though.

@aymanhab I'll try to update this PR soon and then we can discuss if we want to keep any of the changes here.

**Comment by chrisdembia** [comment]
Seems like my changes substantially increase the build time on Appveyor...hmm..

**Comment by chrisdembia** [comment]
I'll remove the python exception handling for now.

I'll revisit SWIG_DECLARE_EXCEPTION so it's defined differently for java vs swig, and I'll see if we can move those `throw` annotations to the java swig interface file.

I'll consider rolling back some of the other changes.

**Comment by aymanhab** [comment]
Awesome, thanks @chrisdembia

**Comment by chrisdembia** [comment]
@aymanhab this is ready for review again. I left in most of the new pythonic interface stuff because upon reflection, most of it is very basic and python users would expect that functionality.

As for the set iterators, I left those in for now but we should revisit soon.

I rolled back my changes to exception handling but now there is different behavior for python vs java. 

I also disabled python testing on appveyor for now.

In my opinion, the biggest benefit of this PR is that you can run the python tests directly through cmake (ctest) now.

I'd like to merge this soon so if you would prefer that I exclude certain things, I will do so.

**Comment by chrisdembia** [comment]
I also got rid of the override/final macros used with swig.

**Comment by aymanhab** [comment]
@chrisdembia Please revive this when you have time.

**Comment by chrisdembia** [comment]
@aymanhab I'm just waiting for tests to pass; otherwise, this is ready for review.

**Comment by chrisdembia** [comment]
The tests fail on appveyor. I'll need to address that.

**Comment by chrisdembia** [comment]
I figured out the issue causing the failure on windows. The _opensim library is installed into the wrong place in the build tree. I tried working on a solution but I couldn't get it working and got frustrated. I'd like to touch base in person, @aymanhab .

**Comment by chrisdembia** [comment]
@aymanhab I tried to modify the PATH and changed some build output dirs to fix the python tests on appveyor but they are still failing. I don't know what to do... https://ci.appveyor.com/project/opensim-org/opensim-core/build/1607

```
======================================================================
ERROR: test_swig_additional_interface (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_swig_additional_interface
Traceback (most recent call last):
  File "C:\Python27\lib\unittest\loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "C:\Python27\lib\unittest\loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "C:\projects\opensim-core\Bindings\Python\tests\test_swig_additional_interface.py", line 9, in <module>
    import opensim as osim
  File "opensim\__init__.py", line 1, in <module>
    from opensim import *
  File "opensim\opensim.py", line 28, in <module>
    _opensim = swig_import_helper()
  File "opensim\opensim.py", line 24, in swig_import_helper
    _mod = imp.load_module('_opensim', fp, pathname, description)
ImportError: DLL load failed: %1 is not a valid Win32 application.
```

**Comment by chrisdembia** [comment]
Here's some information about that (confusing) error from stackoverflow: http://stackoverflow.com/questions/14629818/importerror-dll-load-failed-1-is-not-a-valid-win32-application

**Comment by aymanhab** [comment]
@chrisdembia Do you know what version of VS was used to build the python on AppVeyor? maybe the problem is trying to mix different runtime(s). At least with a dump of this info we can try to reproduce locally or on a VM. Also can we download the result of the build to see if it's environment/Path issue which we can tweak and test vs. bad dll?

**Comment by chrisdembia** [comment]
> Do you know what version of VS was used to build the python on AppVeyor?

Definitely not VS 2015. Either VS 2008 or VS 2010. On the master branch, the python tests pass on AppVeyor. The issue is just trying to run the python tests from the build tree. A dump of some sort would be really helpful; I don't know how to produce a better dump than the one you see above, though it's probably possible. 



> Also can we download the result of the build to see if it's environment/Path issue which we can tweak and test vs. bad dll?

Best is to use that Remote Desktop feature I mentioned. I've used it before so I know it should work. BTW you can put that line anywhere in the appveyor script, depending on at what point in the script's execution you want to interfere.

**Comment by chrisdembia** [comment]
I may try to spend some time Remote Desktopping into the appveyor machine if I can.

**Comment by aymanhab** [comment]
Good point about tests passing ruling out bad dll or conflicts,  I would check dlls are in expected place including Simtk and lapack and _opensim, then dump PATH inside the python shell.

**Comment by aymanhab** [comment]
Awesome :+1:

**Comment by chrisdembia** [comment]
Thanks @aymanhab

**Pull request merged**
