### PR TITLE
ezc3d Release 1.3.6

### PR DESCRIPTION
**Pull request by pariterre**
This includes Type 1 and 3 force platforms and LABELS2 implementation

---
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2873)

### CODE REVIEW

**Comment by adamkewley** [comment]
Sorry for not giving feedback on this sooner.

This seems straightforward enough. I'd be happy to merge it because it isn't causing CI errors and just seems like a straight upgrade in functionality. The only concern I can see is that `git diff Release_1.3.2..Release_1.3.6` reveals a fair amount of changes that might need to be scanned. A quick glance, though, shows that most of the diff is just formatting stuff and files being moved around.

I'm guessing this is a safe merge, someone with more experience (e.g. @aymanhab )? Assuming our downstream test suite exercises C3D files?

**Comment by pariterre** [comment]
@adamkewley 
The main issue is not exactly this, it is what is being discussed in #2860
FYI, ezc3d is now 1.3.7

**Comment by pariterre** [comment]
@adamkewley , @carmichaelong @aymanhab 
In my understanding, this PR is fair representation of what we discuss! 
Therefore, it should be ready to merge (as long as `continuous-integration/travis-ci/pr — The Travis CI build could not complete due to an error` is expected to fail)
Thanks!

**Review by aymanhab — APPROVED** [review]
LGTM Thanks @pariterre

**Comment by carmichaelong** [comment]
Weird, the two jobs that failed to pass on travis had all tests pass but returned a failure on some lines related to sourceforge. I wouldn't worry about the failure too much.

**Comment by aymanhab** [comment]
@carmichaelong These failures are due to the PR coming from a fork which is not handled by the travis script so they are expected.

**Comment by carmichaelong** [comment]
Ah, I see, thanks @aymanhab

**Pull request merged**
