### PR TITLE
[appveyor] Use prebuilt Simbody binaries.

### PR DESCRIPTION
**Pull request by chrisdembia**
### Brief summary of changes

- Turn warnings into errors, so we catch them before they enter the code base.
- Use NuGet feed to get simbody (to save time).

### CODE REVIEW

**Comment by chrisdembia** [comment]
I terminated the Travis builds because they are unnecessary.

**Comment by chrisdembia** [comment]
Yes... as I should have expected, there were warnings that are now errors.

**Comment by chrisdembia** [comment]
The issue is now that the compiling the bindings generates many warnings.

**Comment by chrisdembia** [comment]
I've rolled back the "turn warnings into errors" part of this PR so that we can get the benefits using prebuilt Simbody binaries for now.

**Comment by chrisdembia** [comment]
This can now be reviewed. The AppVeyor tests pass (and the builds are now a few minutes shorter).

**Comment by tkuchida** [comment]
LGTM, though I was unable to confirm 9iv11sycwdny.

**Comment by chrisdembia** [comment]
> 9iv11sycwdny

❓

**Comment by tkuchida** [comment]
> ❓ 

In appveyor.yml (line 87), you refer to `simbody-9iv11sycwdny`. I looked through [the list of commits in the simbody repo](https://github.com/simbody/simbody/commits/master) but was unable to find a tag that either started with "9iv" or ended with "dny". I don't know where else to look for this ID (I guess it's something nuget assigns) and don't have time to solve this puzzle right now. I wasn't able to confirm that the ID is correct but I assume you and Ajay know what's going on.

**Comment by chrisdembia** [comment]
Thanks @tkuchida; I added a comment. 

How are PRs for continuous integration supposed to get merged if people claim they are not qualified to review them?

**Comment by tkuchida** [comment]
> How are PRs for continuous integration supposed to get merged if people claim they are not qualified to review them?

I clearly don't know enough about the CI machinery to review this PR. There are others on the team who know more than I do and would be able to provide an expert review.

**Pull request merged**
