### PR TITLE
Update for ezc3d (reading Kistler's c3d)

### PR DESCRIPTION
**Pull request by pariterre**
Fixes issue #<issue_number>

### CHANGELOG.md (choose one)

- no need to update because...
- updated.

- - -
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3609)

### CODE REVIEW

**Comment by aymanhab** [comment]
@pariterre Thanks for this PR, can you add an entry for the changelog describing the change and what issues (relevant to OpenSim community) that it fixes? Thanks

**Comment by pariterre** [comment]
@aymanhab 
Done :)

**Review by aymanhab — APPROVED** [review]
:lgtm: Thanks @pariterre 

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3609#-:-NjIuxXWCRMeZV9dUbBL:bqofnos)* status: 1 of 2 files reviewed, all discussions resolved

**Review by aymanhab — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3609#-:-NjIv9AJBcgAZfME9L8J:bnfp4nl)* status: 1 of 2 files reviewed, all discussions resolved

**Pull request merged**
