### PR TITLE
Example hopper with device

### PR DESCRIPTION
**Pull request by klshrinidhi**
​​Merging this branch with `master` produces conflicts in `Component.h` and `ComponentOutput.h`. I resolved the conflict by choosing Ajay's version in the branch `example_hopper_with_device`. The merged version does not compile with wrapping ON. The wrapper code produces errors in `Component.h`. Without wrapping, merge passes all tests.

### CODE REVIEW

**Comment by aseth1** [comment]
@klshrinidhi sorry I didn't see that you had opened the PR already. I pushed my latest changes but they should not affect any merging you have done. I have only edited the example since I left the lab.

@chrisdembia can you take a look the wrapping issue? I would err on merging anyways and resolve the wrapping in another PR, unless that will break the GUI for @aymanhab.  

We are expecting people to be able to pull what they need for tomorrow starting at 10pm (although we could get everyone to update in the morning if we have to.)

**Comment by aymanhab** [comment]
@aseth1 & @klshrinidhi it all depends on the failure, if it's in python wrapping or due to limited memory on travis then we can get away with it, if not then we need to troubleshoot/evaluate.

**Comment by aymanhab** [comment]
By the hackathon time we probably should have all tests passing on all platforms (even if excluding wrapping) since we'll be showing users how to make changes, and may do some of our own and we'll need some assurance from integrated builds/tests.

**Comment by klshrinidhi** [comment]
The error is in Python wrapping. This may not be the only error. It is the first one.

**Comment by chrisdembia** [comment]
> @chrisdembia can you take a look the wrapping issue?

I'm looking into this now.

**Comment by chrisdembia** [comment]
> I resolved the conflict by choosing Ajay's version in the branch example_hopper_with_device.

@klshrinidhi I'm having trouble discerning the diff for this merge by looking at the commits in this PR. Could you tell me which code was conflicting in this merge?

**Comment by chrisdembia** [comment]
I just pushed a merge conflict. Python tests pass locally for me.

**Comment by chrisdembia** [comment]
@klshrinidhi are you looking at the java wrapping failure on windows?

**Comment by chrisdembia** [comment]
Ah I think the issue is taht @aseth1 made `findComponent()` public; we should just hide it from swig for now.

**Comment by aseth1** [comment]
> Ah I think the issue is taht @aseth1 made findComponent() public;

Yes I did a while back and forgot it was on this branch- sorry guys! But is a useful utility, especially since path names may not be obvious to people.

**Comment by aymanhab** [comment]
@chrisdembia Should I try to work off this branch now or do you expect more changes before pushing to master?

**Comment by chrisdembia** [comment]
I'm running tests locally, and I'll push the minor changes pretty soon. I don't expect more changes to the API, but who knows!

I'll comment again in a few minutes when the tests finish locally.

**Comment by chrisdembia** [comment]
OK the tests pass locally; I'm pushed. I only tested on OSX though, and the failure is on Windows. It will take about 40 minutes to learn if the fix works on Windows. So, I suppose it's up to you, if you have 40 minutes! I would think that the master build is sufficient for the GUI (though this branch is required for simulating the hopper device, since it adds support for nested models when computing controls. but I don't expect people's hackathon projects to require nesting models).

**Comment by aymanhab** [comment]
Thanks @chrisdembia I'll grab the branch now and see how the GUi build goes. I think pushing and cleaning the build environment is a higher priority than having a functional GUI build first thing in the morning, especially that I don't know how the GUI will handle nested models/components and all the new functionality introduced in the API but never exercised in models before tonight! So, feel free to push when testing is done and I'll see what I can do.

**Comment by chrisdembia** [comment]
I pushed.

**Comment by aymanhab** [comment]
Thanks @chrisdembia

**Pull request merged**
