### PR TITLE
Update version to 4.5

### PR DESCRIPTION
**Pull request by aymanhab**
Fixes issue #0
### Brief summary of changes
Upgrade opensim release version to 4.5 to handle downstream effects,  branching and tagging to follow

### CHANGELOG.md (choose one)

- no need to update because...
- updated.

- - -
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3624)

### CODE REVIEW

**Comment by aymanhab** [comment]
@nickbianco would be good to merge this version change so we can get the version correctly downstream in conda packages and the gui

**Review by nickbianco — APPROVED** [review]
LGTM.

Just double checking: you're not creating the `4.5` tag yet, correct? Since we have a few more changes to merge.

**Comment by aymanhab** [comment]
Indeed no tag yet, we typically create a branch for fixes post release candidate and then create a tag when all is frozen/finalized.

**Comment by aymanhab** [comment]
Indeed no tag yet, we typically create a branch for fixes post release candidate and then create a tag when all is frozen/finalized.

**Pull request merged**
