### PR TITLE
Removed "auto" from user-facing code

### PR DESCRIPTION
**Pull request by tkuchida**
## Main changes
Removed "auto" from examples and example code in doxygen to avoid encouraging its use (and potential misuse), per discussion in #1209.

## Minor changes
1. Suppressed compiler warnings about unsigned ints.
2. Corrected headers in hopper example.

## Omissions
This PR does not repair the hopper example, which is again broken on master; noted in #1205. The hopper example should be added as a test so it doesn't keep breaking (see #1128).

### CODE REVIEW

**Comment by klshrinidhi** [comment]
I don't think removing `auto` is going to solve the problem of users *unintentionally* making a copy of objects. This feature (`auto`) is considered very helpful, currently widely used and there are few instances where `auto` is the required. C++ standard is moving more toward using *automatic typed deduction*.

I think the solution here is to make a section somewhere (the currently unused Wiki on github or somewhere else) that lists the most common mistakes found and enlightening users about the right use of this feature `auto`.

**Comment by klshrinidhi** [comment]
Another solution requiring architectural changes is to write classes (Components) using some variation of the PIMPL idiom. This will make it very cheap to perform copies and maintain references (or pointers) to original.

**Comment by chrisdembia** [comment]
In my opinion, we should do both: avoid `auto` in examples and list common mistakes in documentation. Of course, in the code base, we should use `auto` as we please.

If we can figure out a "poor man's" PIMPL, that would be good too.

**Comment by klshrinidhi** [comment]
I don't think it sends the right message if often end typing long names in examples and internally use `auto`. OpenSim is not the only way for a user to learn C++. One could have learned about `auto` somewhere else too.

**Comment by aymanhab** [comment]
@klshrinidhi we need to keep in mind who are our users (or developers) and you have seen them in the dev week, very capable biomechanists, beginner/intermediate C++ at best. If using auto causes mysterious errors/issues that could be a show stopper. Learning C++ to the latest standard is not an option, unfortunately. An improved Matlab interface would probably fit them better but we're trying to hit the middle ground that lets us develop without hindering others.

**Comment by chrisdembia** [comment]
> An improved Matlab interface would probably fit them better

I agree that this is probably the best way to solve problems related to the complexity of C++ for our users. On the other hand, those writing new components will probably not be able to use MATLAB.

**Comment by tkuchida** [comment]
I think the most compelling reasons for removing `auto` in the examples are :one: to explicitly show the object types when it might not be immediately obvious otherwise (e.g., [here](https://github.com/opensim-org/opensim-core/pull/1214/files#diff-273445e80413bbe09be2b325b103d89eR254)) and :two: so that the C++ code parallels the scripting code.

**Comment by chrisdembia** [comment]
> so that the C++ code parallels the scripting code.

In scripting, there are no types on the left hand side of the equals sign `=`. So, this would only increase the parallel to Java code.

**Comment by chrisdembia** [comment]
> to explicitly show the object types when it might not be immediately obvious otherwise

This is definitely good for examples. There are cases where I do think it is fine to use auto in examples (like [here](https://github.com/opensim-org/opensim-core/pull/1214/files#diff-27aff0ebd0924330bf42bcf1069558adR125)): 

```
 auto* reporter = new ConsoleReporter();
```

The type is more or less obvious.

**Comment by chrisdembia** [comment]
I do prefer `auto* rep = new Blah()` over `auto rep = new Blah()`.

**Comment by aymanhab** [comment]
Sorry if my comment about similarity to scripting was a bit misleading, so let me clarify. It is true that you don't need to declare the type of object on lhs in python and Matlab (while you do in Java due to static typing), however, if the actual class underneath the handle is not wrapped in SWIG then you're dead in the water and can't use the handle you have. So, if we try to reproduce examples in python or Matlab, it will be easier to troubleshoot and to reproduce these examples if they don't use 'auto' or use it only in places where the class is obvious as described above by @chrisdembia .

**Comment by tkuchida** [comment]
> use it only in places where the class is obvious

Ok, I can revert back to `auto` in cases like `auto* blah = new Blah();`. Any other cases?

**Comment by tkuchida** [comment]
Merged master and reverted back to "auto" in situations where the class is obvious.

**Comment by tkuchida** [comment]
This appears to be a controversial issue that requires more discussion before implementing. The issue is already being tracked as part of #1209.

**Pull request closed without merging**
