### PR TITLE
[readme] brew python issues with cmake.

### PR DESCRIPTION
**Pull request by chrisdembia**
There's a bug with cmake/homebrew when OSX users have installed python via homebrew. I've tried to help people who get stuck in this situation. I also changed "Mac" to "OSX" since I think "OSX" is more accurate ('mac' refers to the hardware and the OS, but I really want to refer to the OS).

### CODE REVIEW

**Comment by aymanhab** [comment]
@chrisdembia This looks fine, but I'm wondering if this's consistent with CMake conventions (Apple vs. Mac OSX) or if there're other places that need to adjust. Any thoughts?

**Comment by chrisdembia** [comment]
Good point. The cmake documentation uses a mix of APPLE, MAC and MACOSX. MACOSX is used most frequently in their documentation. I don't have a strong preference for if we use `APPLE` or `MACOSX` in cmake; I think we use `APPLE`.

**Comment by aymanhab** [comment]
Thanks @chrisdembia I'd then suggest we change the word OSX to Mac OSX which seems like a reasonable less cryptic name to show in docs and then merge.

**Comment by chrisdembia** [comment]
@aymanhab I addressed your comment; please re-review and merge if ready.

**Pull request merged**
