### PR TITLE
[WIP] Redesigned column label methods and ConsoleReporter headers

### PR DESCRIPTION
**Pull request by tkuchida**
### Summary
DevProp #1226 and its subsequent implementation in #1279 addressed issue #1221; remaining concerns were raised in #1284 and summarized in #1287. This PR addresses the following pieces of #1287:
- Renamed `getLongLabel()` to `getLabel()`, and removed `getShortLabel()`.
- Now using full paths for column headers in ConsoleReporter and splitting over multiple lines.

### Benefit to users
- Default headers in ConsoleReporter are guaranteed to be informative.

### Exclusions
- Does not address design concerns raised in #1287 about whether aliases should be local or global, or stored with Outputs or Inputs.
- ConsoleReporter will never truncate paths (truncation can result in ambiguous headers). Each column header is either the full path or the alias that was provided by the user; additional flexibility does not seem necessary.

### Suggested reviewers
- @aseth1, @klshrinidhi

### CODE REVIEW

**Comment by klshrinidhi** [comment]
:+1: 

Have you checked if these changes affect Python/Java tests ? If this branch is up-to-date with master, the CI tests will help catch any issues.

**Comment by tkuchida** [comment]
> Have you checked if these changes affect Python/Java tests ?

Yes, I updated a Python test ([test_connectors_inputs_outputs.py](https://github.com/opensim-org/opensim-core/pull/1316/files#diff-f4c4befa552bfc9d7da845ea9d57e05f)).

> If this branch is up-to-date with master, the CI tests will help catch any issues.

I think #1278 was merged after the last commit on this branch. I will merge master and resolve any test failures. This might take a few days as Travis seems to be backlogged.

**Comment by klshrinidhi** [comment]
> I think #1278 was merged after the last commit on this branch. I will merge master and resolve any test failures. This might take a few days as Travis seems to be backlogged. 

Yes. I was thinking about my PRs when I made that comment. Both #1278 and #1265 add Python/Java tests that may be affected. If you merge master into this branch, I can help with fixing any Python/Java tests.

**Comment by klshrinidhi** [comment]
#1265 is also merged to master. Can you merge master again ?

**Comment by klshrinidhi** [comment]
Tests pass on my machine (after merge). No change required to Python/Java tests.
So it is just about waiting for CI.

**Comment by tkuchida** [comment]
Great. Thanksss for tesssting. :snake:

**Comment by aseth1** [comment]
Unless @klshrinidhi has additional concerns, feel free to merge when tests finsih.

**Comment by klshrinidhi** [comment]
I don't have any more comments. Go ahead.

**Comment by tkuchida** [comment]
Didn't notice the tests had passed. Thanks for merging, @aseth1.

**Comment by chrisdembia** [comment]
> Didn't notice the tests had passed.

It's becoming a rare thing for the CI to function well :/

**Pull request merged**
