### PR TITLE
Add a Python optimization example that uses cma package

### PR DESCRIPTION
**Pull request by tkuchida**
### Brief summary of changes
A Python example that demonstrates how to run an optimization using the cma package and avoiding repeated calls to `initSystem()`. As configured, the optimizer takes about 3 minutes to run on a standard laptop (Intel i7, Windows 10, Python 2.7). Thanks to @akshaypatel1811 for the assist.

### Testing I've completed
Works on Spyder, Python 2.7 🐍

### CHANGELOG.md (choose one)

- no need to update because... ~adding an example~
- updated... per reviewer request

The Doxygen for this PR can be viewed at http://myosin.sourceforge.net/?C=N;O=D; click the folder whose name is this PR's number.

---
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2604)

### CODE REVIEW

**Comment by chrisdembia** [comment]
I think it could be nice to update the CHANGELOG for this one.

**Comment by tkuchida** [comment]
> I think it could be nice to update the CHANGELOG for this one.

Ok, will add under "Other Changes" after "Added Matlab example…"

**Comment by tkuchida** [comment]
___
*[Bindings/Python/examples/dynamic_walker_example_optimization.py, line 47 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2604#-LrvQG1h6FLelMlfgxBu:-Lrz9cMs0f9LHNPacECC:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/5529496ace93cf369c6ef95061c7140dcae064ed/Bindings/Python/examples/dynamic_walker_example_optimization.py#L47)):*
<details><summary><i>Previously, chrisdembia (Christopher Dembia) wrote…</i></summary><blockquote>

An import like this is usually done at the top of the file.
</blockquote></details>

Done.

**Comment by jimmyDunne** [comment]
Awesome! Thanks, @tkuchida & @akshaypatel1811!

**Pull request merged**
