### PR TITLE
Add components of PATH to search path for visualizer.

### PR DESCRIPTION
**Pull request by klshrinidhi**
Fixes issue #1572

### Brief summary of changes
Add the paths in `PATH` to the search path for visualizer.

### CODE REVIEW

**Comment by klshrinidhi** [comment]
Tested on Windows:
* Install OpenSim dependencies to directory `opensim_dependencies_install`.
* Install OpenSim to directory `opensim_install`.
* Rename Simbody install directory `opensim_dependencies_install\simbody` to something else.
* Add directory `opensim_install\bin` to `PATH`.
* Go to `opensim_install\sdk\python` and start python3.4.
* Run the following:
 ```
import os
import sys
sys.path.append(os.path.join(os.getcwd(), 'opensim'))
import opensim
m = opensim.Model()
m.setUseVisualizer(True)
m.initSystem()
```
The shows the visualizer window, meaning the path to the visualizer binary was found.

**Comment by chrisdembia** [comment]
Awesome. Could you add doxygen documentation that describes this new behavior? Then I think this can be merged.

**Comment by tkuchida** [comment]
Please also note on #1684 the 4.0-related changes that we will need to make to the ["Scripting in Python" Confluence page](http://simtk-confluence.stanford.edu:8080/display/OpenSim/Scripting+in+Python) (e.g., Python version number and the `sys.path.append` stuff). :snake:

**Comment by klshrinidhi** [comment]
Added documentation to class description.

**Comment by chrisdembia** [comment]
> I've added an item to #1684 re. the 4.0-related changes that we will need to make to the "Scripting in Python" Confluence page (e.g., Python version number and the sys.path.append stuff). 🐍

Thanks @tkuchida. It seems like the python bindings work with python3, which is great (I hadn't known this before); we should definitely document this. In general, the python bindings should not require any *specific* version of python (that is, python 3.4 and 3.6 should both work). So the documentation should be that the python bindings can be built from source for both python 2 and python 3 (most likely, the binary release will only be for python 2), but I think we should not need to say which specific version of python 2 or 3 is necessary (or perhaps we could say "2.7 or greater"). 

The `sys.path` call should only be necessary because @klshrinidhi chose not to install the python package system-wide; I don't think we should encourage users to use this mechanism. They should instead run `python setup.py install` from the `sdk/python` directory; [our instructions](http://simtk-confluence.stanford.edu:8080/display/OpenSim/Scripting+in+Python) already mention this.

**Comment by tkuchida** [comment]
Thanks @chrisdembia. I've added your comments to #1684.

**Pull request merged**
