### PR TITLE
Specify/modify the underlying IMU World to OpenSim ground rotation for OpenSense

### PR DESCRIPTION
**Pull request by aseth1**
Fixes issue #2463

### Brief summary of changes
- Added another optional argument to `OpenSense::convertQuaternionsToRotations` which is the assumed sensor world to opensim transform.  It has a default that works for most IMUs with Z-axis up (gravity) and X is the magnetic north direction.

### Testing I've completed
- test produce the same result as before with the default argument.

### Looking for feedback on...
- testing with marker-based orientations

---
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2501)

### CODE REVIEW

**Comment by aseth1** [comment]
@jimmyDunne and @malborno, Hannah is testing this fix. The code should be straightforward to review. Instead of just assuming the IMU world to OpenSim ground rotation, you can optionally set it as the final argument to the `convertQuaternionsToRotations ` utility function.

**Comment by aymanhab** [comment]
@aseth1 Any update on the testing? Thanks

**Comment by aseth1** [comment]
I believe the utility works as expected. The Rotation is applied. The issue is that we cannot find the correct Rotation that enables direct comparison if IMU vs Marker-based, but I think that is a separate issue.

**Comment by aymanhab** [comment]
Thanks @aseth1

**Pull request merged**
