### PR TITLE
Add `examplePolynomialPathFitter.py` + update `exampleMocoTrack` and `exampleMocoInverse`

### PR DESCRIPTION
**Pull request by nickbianco**
Fixes issue #3584

### Brief summary of changes
This PR primarily adds the new `examplePolynomialPathFitter.py` which demonstrates how to use the new `PolynomialPathFitter` class with sample walking data. I've made several other minor bug fixes and additions related to this example:

- Added the helper function `loadCoordinateValuesAndValidateModel` to `PolynomialPathFitter` so the model and data loading logic could be used in the static function `evaluateFunctionBasedPaths`.
- `exampleMocoInverse.cpp` and `exampleMocoInverse.cpp` and their Matlab/Python scripting counterparts have been updated to use the set of `FunctionBasedPath`s produced from `examplePolynomialPathFitter.py`. I've made some tweaks to improve these examples in other ways, including a new scaled model from AddBiomechanics.
- Various other minor changes include `.gitignore` and `cmake` updates.

### Testing I've completed
Ran all examples locally.

### CHANGELOG.md (choose one)

- updated.

- - -
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3607)

### CODE REVIEW

**Review by carmichaelong — CHANGES_REQUESTED** [review]
A few other notes:

1. high level on the examples based on in-person chat:
- not sure if it's best to completely remove an example that doesn't use function based paths, but we don't want to keep around two examples.
- we do want to highlight that function based paths should be "default"
- consider adding some extra comments and an if statement where the default is to use function based paths, but you can go back to geometry based paths if you want

2. in running one of the examples in matlab, the code in `osimMocoTrajectoryReport.m` threw an error. It looks like these two lines use `col_label` while other lines surrounding use `colLabel`. Link: https://github.com/opensim-org/opensim-core/blob/main/Bindings/Java/Matlab/Utilities/osimMocoTrajectoryReport.m#L468C36-L468C36

3. for the visualization of `exampleMocoTrack.m`, no bones show up. looks like the cmake file didn't copy geometry files previously too, so this maybe isn't a new problem?

4. since i'm on an arm-based mac, i haven't tested the .py example files

> Reviewed 18 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3607#-:-NjFTX2y6o4EqE3gOcnF:beuhccs)* status: all files reviewed, 6 unresolved discussions (waiting on @nickbianco)

___
*[`Bindings/Java/Matlab/examples/Moco/example3DWalking/exampleMocoTrack.m` line 145 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3607#-NjFTNqj4s8zOO6LTb_H:-NjFTNqj4s8zOO6LTb_I:bjwhx56) ([raw file](https://github.com/opensim-org/opensim-core/blob/724515cac62fc6398edc79f2fb7047497b6d63cc/Bindings/Java/Matlab/examples/Moco/example3DWalking/exampleMocoTrack.m#L145)):*
> ```objc
> modelProcessor.append(ModOpScaleActiveFiberForceCurveWidthDGF(1.5));
> % Use a function-based representation for the muscle paths.
> modelProcessor.append(ModOpReplacePathsWithFunctionBasedPaths(
> ```

this line needs `...` at the end to wrap with the next line
___
*[`Bindings/Python/examples/PolynomialPathFitter/examplePolynomialPathFitter.py` line 51 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3607#-NjEG3yg7d4hLgF2uSfM:-NjEG3yg7d4hLgF2uSfN:bv7g15g) ([raw file](https://github.com/opensim-org/opensim-core/blob/724515cac62fc6398edc79f2fb7047497b6d63cc/Bindings/Python/examples/PolynomialPathFitter/examplePolynomialPathFitter.py#L51)):*
> ```Python
> #
> # The fitter will randomly sample around the coordinate values provided in the
> # table to generate model  configurations for which to compute path lengths and
> ```

looks like two spaces between `model` and `configurations`
___
*[`Bindings/Python/examples/PolynomialPathFitter/examplePolynomialPathFitter.py` line 58 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3607#-NjEHJuS6t26wNmqjCn0:-NjEHJuS6t26wNmqjCn1:beyp4i) ([raw file](https://github.com/opensim-org/opensim-core/blob/724515cac62fc6398edc79f2fb7047497b6d63cc/Bindings/Python/examples/PolynomialPathFitter/examplePolynomialPathFitter.py#L58)):*
> ```Python
> model.initSystem()
> tableProcessor = osim.TableProcessor('coordinates.sto')
> tableProcessor.append(osim.TabOpAppendCoupledCoordinateValues())
> ```

perhaps add a note here why this is useful? could users think that fitting the independent coordinates should be sufficient? what happens if you don't fit the coupled/dependent coordinates too?
___
*[`Bindings/Python/examples/PolynomialPathFitter/examplePolynomialPathFitter.py` line 85 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3607#-NjEI_h6EQDo83sjTN6q:-NjEI_h6EQDo83sjTN6r:b-klyozz) ([raw file](https://github.com/opensim-org/opensim-core/blob/724515cac62fc6398edc79f2fb7047497b6d63cc/Bindings/Python/examples/PolynomialPathFitter/examplePolynomialPathFitter.py#L85)):*
> ```Python
> # Set the maximum order of the polynomials used to fit the path lengths
> # and moment arms. Higher order polynomials might lead to a better fit,
> # but could decrease performance in the final model.
> ```

i assume performance here means speed and not accuracy? and what is the difference between the "final model" and some other (not final) model?
___
*[`OpenSim/Actuators/PolynomialPathFitter.cpp` line 1276 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3607#-NjFOYXnEJlrmYLHKaPs:-NjFOYXnEJlrmYLHKaPt:bhxlsui) ([raw file](https://github.com/opensim-org/opensim-core/blob/724515cac62fc6398edc79f2fb7047497b6d63cc/OpenSim/Actuators/PolynomialPathFitter.cpp#L1276)):*
> ```cpp
>         const MomentArmMap& momentArmMap) {
> 
>     // Remove entries from the table that are not in the moment arm map.
> ```

looks like some of the changes above to how `momentArmMap` is populated changed it to have a (geometry) path's name and coordinate name rather than (component) path. what was the rationale for this change? is it better to do this just to clean up what these files look like to the user (or some other reasons for this change)?
___
*[`OpenSim/Examples/Moco/example3DWalking/README.txt` line 19 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3607#-NjEDdvh5ND5nJXewnWO:-NjEDdvh5ND5nJXewnWP:b-6mgpcr) ([raw file](https://github.com/opensim-org/opensim-core/blob/724515cac62fc6398edc79f2fb7047497b6d63cc/OpenSim/Examples/Moco/example3DWalking/README.txt#L19)):*
> ```help
> Lai et al. 2017. The subtalar, mtp, and wrist coordinates have been replaced with
> WeldJoints and residual actuators have been added to the pelvis. The model was
> fit to the marker trajectories and ground reaction forces using AddBiomechanics.
> ```

maybe add website here or ref to paper? i.e., either:
- `AddBiomechanics (https://addbiomechanics.org/)`
- `AddBiomechanics (Werling et al. 2023)`

**Review by nickbianco — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3607)* status: 8 of 18 files reviewed, 6 unresolved discussions (waiting on @carmichaelong)

___
*[`Bindings/Java/Matlab/examples/Moco/example3DWalking/exampleMocoTrack.m` line 145 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3607#-NjFTNqj4s8zOO6LTb_H:-NjJ8FcaDy4TFAnVpp2d:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/724515cac62fc6398edc79f2fb7047497b6d63cc/Bindings/Java/Matlab/examples/Moco/example3DWalking/exampleMocoTrack.m#L145)):*
<details><summary><i>Previously, carmichaelong wrote…</i></summary><blockquote>

this line needs `...` at the end to wrap with the next line
</blockquote></details>

Done.
___
*[`Bindings/Python/examples/PolynomialPathFitter/examplePolynomialPathFitter.py` line 51 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3607#-NjEG3yg7d4hLgF2uSfM:-NjJ8mRZ-tgqZL0mNvuI:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/724515cac62fc6398edc79f2fb7047497b6d63cc/Bindings/Python/examples/PolynomialPathFitter/examplePolynomialPathFitter.py#L51)):*
<details><summary><i>Previously, carmichaelong wrote…</i></summary><blockquote>

looks like two spaces between `model` and `configurations`
</blockquote></details>

Done.
___
*[`Bindings/Python/examples/PolynomialPathFitter/examplePolynomialPathFitter.py` line 58 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3607#-NjEHJuS6t26wNmqjCn0:-NjJKR404b2oj2F-yXIi:b-7xiq5a) ([raw file](https://github.com/opensim-org/opensim-core/blob/724515cac62fc6398edc79f2fb7047497b6d63cc/Bindings/Python/examples/PolynomialPathFitter/examplePolynomialPathFitter.py#L58)):*
<details><summary><i>Previously, carmichaelong wrote…</i></summary><blockquote>

perhaps add a note here why this is useful? could users think that fitting the independent coordinates should be sufficient? what happens if you don't fit the coupled/dependent coordinates too?
</blockquote></details>

I changed how tables are loaded inside `PolynomialPathFitter`, so these lines are no longer necessary.
___
*[`Bindings/Python/examples/PolynomialPathFitter/examplePolynomialPathFitter.py` line 85 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3607#-NjEI_h6EQDo83sjTN6q:-NjJKopIDvOARpz_TBaw:b-ya4zpv) ([raw file](https://github.com/opensim-org/opensim-core/blob/724515cac62fc6398edc79f2fb7047497b6d63cc/Bindings/Python/examples/PolynomialPathFitter/examplePolynomialPathFitter.py#L85)):*
<details><summary><i>Previously, carmichaelong wrote…</i></summary><blockquote>

i assume performance here means speed and not accuracy? and what is the difference between the "final model" and some other (not final) model?
</blockquote></details>

Improved the comment.
___
*[`OpenSim/Actuators/PolynomialPathFitter.cpp` line 1276 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3607#-NjFOYXnEJlrmYLHKaPs:-NjJKyUSEV6GeXopkKoU:b-645isd) ([raw file](https://github.com/opensim-org/opensim-core/blob/724515cac62fc6398edc79f2fb7047497b6d63cc/OpenSim/Actuators/PolynomialPathFitter.cpp#L1276)):*
<details><summary><i>Previously, carmichaelong wrote…</i></summary><blockquote>

looks like some of the changes above to how `momentArmMap` is populated changed it to have a (geometry) path's name and coordinate name rather than (component) path. what was the rationale for this change? is it better to do this just to clean up what these files look like to the user (or some other reasons for this change)?
</blockquote></details>

This was actually a bug in `evaluateFunctionBasedPaths` that I didn't catch until making the example. The changes above reflect the behavior in the rest of `PolynomialPathFitter`. 
___
*[`OpenSim/Examples/Moco/example3DWalking/README.txt` line 19 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3607#-NjEDdvh5ND5nJXewnWO:-NjJLNik-qgJU8xB7OpF:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/724515cac62fc6398edc79f2fb7047497b6d63cc/OpenSim/Examples/Moco/example3DWalking/README.txt#L19)):*
<details><summary><i>Previously, carmichaelong wrote…</i></summary><blockquote>

maybe add website here or ref to paper? i.e., either:
- `AddBiomechanics (https://addbiomechanics.org/)`
- `AddBiomechanics (Werling et al. 2023)`
</blockquote></details>

Done.

**Review by nickbianco — COMMENTED** [review]
Thanks @carmichaelong! I just pushed a bunch of changes. 

1. We mostly discussed this in person, but I think the changes below are good. The examples haven't fundamentally changes, they're just faster and produce higher quality results. The comments around adding the `FunctionBasedPath`s should be informative enough.

2./3. Working on fixes for these.

4. I can retest the Python examples when we're done reviewing. Working on a Matlab version of the new example for you to test.

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3607#-:-NjJMzGhC1zb4DksWpHK:bou5pto)* status: 8 of 18 files reviewed, 6 unresolved discussions (waiting on @carmichaelong)

**Review by nickbianco — COMMENTED** [review]
@carmichaelong, ready for review.

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3607#-:-NjK0cXKATWzD9wgcKM-:bzarhxw)* status: 7 of 26 files reviewed, 6 unresolved discussions (waiting on @carmichaelong)

**Comment by carmichaelong** [comment]
Thanks, I'd like to try out the example in MATLAB before finalizing the review but looks like CI won't work on a branch with merge conflicts (TIL)?

**Comment by nickbianco** [comment]
@carmichaelong -- fixed the merge conflict!

**Review by carmichaelong — CHANGES_REQUESTED** [review]
finished testing the matlab examples. two small changes and this will be good to go

> Reviewed 6 of 10 files at r2, 12 of 13 files at r3.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3607#-:-NjP8MK62-ZEvnOQlNjL:bjblude)* status: 24 of 26 files reviewed, 2 unresolved discussions (waiting on @nickbianco)

___
*[`Bindings/Java/Matlab/examples/PolynomialPathFitter/examplePolynomialPathFitter.m` line 118 at r4](https://reviewable.io/reviews/opensim-org/opensim-core/3607#-NjLyswU7YBa2Y-ewdNx:-NjLyswU7YBa2Y-ewdNy:b-dkqur9) ([raw file](https://github.com/opensim-org/opensim-core/blob/58f7735ee9f4cfbcc6e0521efcd1bbe3583b5048/Bindings/Java/Matlab/examples/PolynomialPathFitter/examplePolynomialPathFitter.m#L118)):*
> ```objc
> % Depending on size of the errors, you may want to adjust the wrapping
> % geometry in the original model and re-run the fitter.
> plotPathLengths(resultsDir,modelName);
> ```

consider adding an extra space  before `modelName`
___
*[`Bindings/Java/Matlab/examples/PolynomialPathFitter/examplePolynomialPathFitter.m` line 203 at r4](https://reviewable.io/reviews/opensim-org/opensim-core/3607#-NjOhG48EdIB9VlCEEQp:-NjOhG48EdIB9VlCEEQq:bjt4ek5) ([raw file](https://github.com/opensim-org/opensim-core/blob/58f7735ee9f4cfbcc6e0521efcd1bbe3583b5048/Bindings/Java/Matlab/examples/PolynomialPathFitter/examplePolynomialPathFitter.m#L203)):*
> ```objc
>                     'LineWidth', 3, 'Color', originalColor);
>                 xlim([times(1), times(end)]);
>                 title(label, 'FontSize', 10, 'Interpreter', 'none');
> ```

`label` -> `char(label)`

matlab was throwing an error here because it didn't know how to deal with an object of type `String

**Review by nickbianco — COMMENTED** [review]
@carmichaelong, ready for review.

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3607#-:-NjPJkEO21o15seEMoAr:bzarhxw)* status: 24 of 26 files reviewed, 2 unresolved discussions (waiting on @carmichaelong)

___
*[`Bindings/Java/Matlab/examples/PolynomialPathFitter/examplePolynomialPathFitter.m` line 118 at r4](https://reviewable.io/reviews/opensim-org/opensim-core/3607#-NjLyswU7YBa2Y-ewdNx:-NjPJZGg6pEeCvOy5540:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/58f7735ee9f4cfbcc6e0521efcd1bbe3583b5048/Bindings/Java/Matlab/examples/PolynomialPathFitter/examplePolynomialPathFitter.m#L118)):*
<details><summary><i>Previously, carmichaelong wrote…</i></summary><blockquote>

consider adding an extra space  before `modelName`
</blockquote></details>

Done.
___
*[`Bindings/Java/Matlab/examples/PolynomialPathFitter/examplePolynomialPathFitter.m` line 203 at r4](https://reviewable.io/reviews/opensim-org/opensim-core/3607#-NjOhG48EdIB9VlCEEQp:-NjPJcFJBijc98okyePZ:b-nnjldn) ([raw file](https://github.com/opensim-org/opensim-core/blob/58f7735ee9f4cfbcc6e0521efcd1bbe3583b5048/Bindings/Java/Matlab/examples/PolynomialPathFitter/examplePolynomialPathFitter.m#L203)):*
<details><summary><i>Previously, carmichaelong wrote…</i></summary><blockquote>

`label` -> `char(label)`

matlab was throwing an error here because it didn't know how to deal with an object of type `String
</blockquote></details>

Fixed this by converting when it's retreived from the vector above.

**Review by carmichaelong — APPROVED** [review]
matlab example worked out of box. only saw one minor typo in a comment so i'm approving this now. feel free to change that and do a ci skip and merge

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3607#-:-NjTc1lI7cumXmN6DFEa:bk7qtp9)* status: all files reviewed, 1 unresolved discussion (waiting on @nickbianco)

___
*[`Bindings/Java/Matlab/examples/PolynomialPathFitter/examplePolynomialPathFitter.m` line 117 at r5](https://reviewable.io/reviews/opensim-org/opensim-core/3607#-NjTbs3u3hlusKW4fDUe:-NjTbs3u3hlusKW4fDUf:b40mcok) ([raw file](https://github.com/opensim-org/opensim-core/blob/b7bd53be747366611c04291b2101c5f60b04b1d7/Bindings/Java/Matlab/examples/PolynomialPathFitter/examplePolynomialPathFitter.m#L117)):*
> ```objc
> % errors in a few muscles (e.g., /forceset/gaslat_r and /forceset/glmax1_r).
> % Errors like these usually arise from the fitting process struggling with
> % discontinuities due from wrapping geometry issues in the original model.
> ```

`due from` to `due to` (or `from`)?

**Comment by nickbianco** [comment]
Thanks @carmichaelong!

**Pull request merged**
