### PR TITLE
[WIP] Support muscle wrapping parallelism // include PathWrapSet in DGF's replaceMuscles

### PR DESCRIPTION
**Pull request by nickbianco**
TODO merge #2904 before merging this PR

Fixes issue #2677 

### Brief summary of changes

Muscle wrapping in OpenSim does not currently support parallelism due to the use of shared workspace memory in the low-level Mtx class, which implements static functions for common matrix operations. This PR proposes a solution to support muscle wrapping by removing the shared workspace used by some of the Mtx functions and instead allocating memory within each function as needed. The memory is still heap-allocated, since Mtx uses relies on C++ arrays of variable length, but the memory is allocated and deallocated within each function call, and therefore should be thread-safe. 

### Testing I've completed

TODO

### CHANGELOG.md (choose one)

- no need to update because...
- updated.

---
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2906)

### CODE REVIEW

**Comment by nickbianco** [comment]
@aymanhab @carmichaelong while this PR is WIP and needs #2904 to be merged first, I'd appreciate any feedback you have for the proposed fix.

**Comment by aymanhab** [comment]
@nickbianco at the risk of making this larger than desired, is there a reason not to throw away all references to the C style allocation/deallocation and replace it with high level objects/classes SimTK::Mat33, Vec3,....? It's also not clear that muscle wrapping is the one and only issue blocking parallelization (were you able to parallelize computations for models with no muscle wrapping?)

**Comment by adamkewley** [comment]
The functions you're changing are called *a lot* by the wrapping implementations iirc (eg they can easily be 15 % perf, alone) - unless I'm mixing this up with wrapmath (will check later). 

Either way, editing the matrix multiplication implementation to perform a fresh heap allocation every time is likely to have perf issues. It will kill L1 caching and thrash the memory allocator when called in a tight loop. The way to make something that relies on static mutable state thread-safe is to either use a mutex (if sharing would be preferable) or use thread_local allocation (best here, probably).

On another note, if you're wanting to use opensim in a multithreaded context, beware. It definitely wasn't engineered with that in mind and all it'll take is some component somewhere mis-copying an internal computation helper that's normally used to help a single-thread, or shared static state (here) for a problem to pop up.

**Comment by nickbianco** [comment]
@aymanhab we've not had any issues with parallelization until introducing muscle wrapping. We use separate copies of the problem OpenSim model in each thread and that's worked pretty well for us.

I think a solution that utilizes the SimTK matrix types is probably the way to go. I wanted to try something simple first, but I suspected performance issues as @adamkewley says. We don't want to make wrapping slower, as it is already somewhat costly.

**Comment by nickbianco** [comment]
Closing this PR since I started fresh on a new branch. Refer to #2910.

**Pull request closed without merging**
