### PR TITLE
Update MotionType enum for easy use from scripts

### PR DESCRIPTION
**Pull request by aymanhab**
Fixes issue #3324

### Testing I've completed
Compiled, generated doxygen

### CHANGELOG.md (choose one)
- updated.

- - -
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3365)

### CODE REVIEW

**Review by tkuchida — COMMENTED** [review]
Looks right by comparison with [BallJoint.h#L79](https://github.com/opensim-org/opensim-core/blob/a01cf545485e8bc1f6e50b29ddeab229677de2c5/OpenSim/Simulation/SimbodyEngine/BallJoint.h#L79). To confirm, is the doxygen still built automatically when CI is run?

**Comment by aymanhab** [comment]
Thanks @tkuchida, doxygen is not regenerated automatically but here's the screen capture from the local doxygen build
Screenshot 2023-01-23 091630

**Comment by aymanhab** [comment]
@tkuchida anything else needed so we can merge this PR? Thank you

**Review by tkuchida — APPROVED** [review]
:+1: 🐧

**Comment by aymanhab** [comment]
Thanks @tkuchida 🥇

**Pull request merged**
