### PR TITLE
testAssemblySolver to catch2

### PR DESCRIPTION
**Pull request by AllisonJohn**
Fixes issue #3555

### Brief summary of changes
Made catch cases that point to test functions. I didn't directly convert the functions to test cases this time since the model file parameter can be changed.

### Testing I've completed
tests pass

### CHANGELOG.md (choose one)

- no need to update because... internal

- - -
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3845)

### CODE REVIEW

**Review by nickbianco — CHANGES_REQUESTED** [review]
Looks good, just two minor requests related to the helper functions.  

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3845#-:-O1SPOUwBxcWKKDLc4Hl:biwqtu9)* status: all files reviewed, 2 unresolved discussions (waiting on @AllisonJohn)

___
*[`OpenSim/Simulation/Test/testAssemblySolver.cpp` line 39 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3845#-O1SOyf07VCOs7nS9aVA:-O1SOyf07VCOs7nS9aVB:b-2uwnd7) ([raw file](https://github.com/opensim-org/opensim-core/blob/434b0490ec3ecf4be83894618becf0bcb30ca637/OpenSim/Simulation/Test/testAssemblySolver.cpp#L39)):*
> ```cpp
> using namespace std;
> 
> void instrumentSetStateValues(const string& modelFile)
> ```

Move all shared test functions to an anonymous namespace.
___
*[`OpenSim/Simulation/Test/testAssemblySolver.cpp` line 445 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3845#-O1SOUR2AYx-kDsuxB2i:-O1SOUR37P5l9fmAID1h:bdf8kzj) ([raw file](https://github.com/opensim-org/opensim-core/blob/434b0490ec3ecf4be83894618becf0bcb30ca637/OpenSim/Simulation/Test/testAssemblySolver.cpp#L445)):*
> ```cpp
> 
> TEST_CASE("CoordinateCouplerCompoundFunction") {
>     testCoordinateCouplerCompoundFunction();
> ```

Since this function doesn't take an argument, you could remove it and move it contents inside the test case.

**Review by AllisonJohn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3845)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @nickbianco)

___
*[`OpenSim/Simulation/Test/testAssemblySolver.cpp` line 39 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3845#-O1SOyf07VCOs7nS9aVA:-O1SSLNZ5jxQr-nOJVXa:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/434b0490ec3ecf4be83894618becf0bcb30ca637/OpenSim/Simulation/Test/testAssemblySolver.cpp#L39)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Move all shared test functions to an anonymous namespace.
</blockquote></details>

Done.
___
*[`OpenSim/Simulation/Test/testAssemblySolver.cpp` line 445 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3845#-O1SOUR2AYx-kDsuxB2i:-O1SSPi-CDrrVGx9cMzN:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/434b0490ec3ecf4be83894618becf0bcb30ca637/OpenSim/Simulation/Test/testAssemblySolver.cpp#L445)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Since this function doesn't take an argument, you could remove it and move it contents inside the test case.
</blockquote></details>

Done.

**Review by nickbianco — CHANGES_REQUESTED** [review]
One more minor request.

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3845#-:-O1SXXFoA6iczaJpoB9z:b-kt568a)* status: all files reviewed, 1 unresolved discussion (waiting on @AllisonJohn)

___
*[`OpenSim/Simulation/Test/testAssemblySolver.cpp` line 346 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3845#-O1SXSzgD6Tnpddr8WYW:-O1SXSzhAOat4N-ZIO0A:bbaibes) ([raw file](https://github.com/opensim-org/opensim-core/blob/4da6ac2cb3eb7d4520f0ac037296fb2cc4c1e167/OpenSim/Simulation/Test/testAssemblySolver.cpp#L346)):*
> ```cpp
> //==========================================================================================================
> // Test Cases
> //==========================================================================================================
> ```

minor: this banner could be removed.

**Review by nickbianco — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3845)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AllisonJohn)

**Pull request merged**
