### PR TITLE
Rotation swig changes

### PR DESCRIPTION
**Pull request by aymanhab**
Fixes issue #0

### Brief summary of changes
Expose constructor of SimTK::Rotation from SimTK::Quaternion 

### Testing I've completed
Used the conversion in Matlab script

### CHANGELOG.md (choose one)

- no need as this is mostly internal, and is readily documented for the C++ side of the API

The Doxygen for this PR can be viewed at http://myosin.sourceforge.net/?C=N;O=D; click the folder whose name is this PR's number.

---
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2594)

### CODE REVIEW

**Comment by aymanhab** [comment]
@jimmyDunne Does this branch have other changes on your side? The Matlab code you sent me uses it already.

**Comment by aymanhab** [comment]
@chrisdembia This was requested by @jimmyDunne to allow creation of Quaternions from Rotations and vice versa. Should be useful in general as we delve into the IMU world. Should be rather quick to review. Thank you.

**Comment by jimmyDunne** [comment]
Thanks, @aymanhab! I have been using this update through Matlab and it has been great! 5 Stars, would recommend ;)

**Comment by chrisdembia** [comment]
Nice!

**Comment by aymanhab** [comment]
Thanks @chrisdembia for the quick turnaround, and @jimmyDunne for testing.

**Pull request merged**
