### PR TITLE
[WIP] Move matlab files

### PR DESCRIPTION
**Pull request by jimmyDunne**
Moved (merged) files from sandbox to Bindings/Java/Matlab and deleted extraneous files. 

Moved pendulum model to Tests and updated relevant CMake file

(Chris) Fixed Cmake file in Matlab Tests that solved a Current Directory issue.

### CODE REVIEW

**Comment by chrisdembia** [comment]
@jimmyDunne these scripts will be really great for users. I would have accept the PR, but it's a WIP so I would like to wait to see your other changes.

However, there are a few things that would be great to address:

1) For createActuatorsFile.m and plotMuscleFLCurves.m, if the documentation of the function goes after the "function ..." line, then `help createActuatorsFile` will show the documentation in the MATLAB command window.

2) createActuatorsFile.m: indentation does not seem consistent (see line 120).

3) createActuatorsFile.m line 98: `if strcmp(joint.getConcreteClassName(), 'CustomJoint') | strcmp(joint.getConcreteClassName(), 'FreeJoint')` Is there a reason for the single `|` instead of the short-circuiting `||`?

4) createActuatorsFile.m line 7 typo: `coordiantes`

5) plotMuscleFLCurves.m: it would be helpful if the description at the top provides a little more information: for example, you could state that the script is interactive: the script will prompt you for what it needs. It would also be great to explain exactly why the range of possible fiber lengths is approximate for multiarticular muscles.

6) I think adding these scripts warrants mention in the CHANGELOG. The scripts will be very helpful to users and they would probably be happy to learn of their presence.

**Comment by jimmyDunne** [comment]
Closing and will sort out some other time.

**Comment by jenhicks** [comment]
@jimmyDunne It would be great to make these scripts available to users. What is the plan to complete this PR?

**Comment by jimmyDunne** [comment]
I am working on it. Just prefer to do another PR since I have made additional changes that would otherwise require a PR into this PR — to complicated.

**Comment by jenhicks** [comment]
Sounds good! Thanks.

**Pull request closed without merging**
