### PR TITLE
No Java wrapping on ci machines until we split it.

### PR DESCRIPTION
**Pull request by aymanhab**
This PR removes the building of Java Bindings but keeps the Python Bindings and tests on. This's temporary but reasonable compromise until we can get more resources on ci machines or investigate splitting the Java wrapping into modules. The green checkmark should be restored with this PR.

### CODE REVIEW

**Comment by aymanhab** [comment]
@chrisdembia Please review and let me know if you agree (I left the flags there but set to OFF so they're easy to restore). Thanks.

**Comment by chrisdembia** [comment]
I'm fine with this but @klshrinidhi should chime in too since I think he's exploring a fix?

**Comment by klshrinidhi** [comment]
I am currently working on generating multiple CXX files instead of one huge file.

Until then, we can turn OFF Java wrapping. 
But the turning OFF wrapping in the matrix on Travis will turn OFF both Python and Java wrapping. I have made the appropriate changes to keep Python wrapping ON.
Also, we don't need to turn OFF Java wrapping on Appveyor. It seems to work fine on Appveyor.

**Comment by aymanhab** [comment]
Thanks @klshrinidhi Will wait for the build to succeed then merge.

For splitting we need to discuss the details and plan (outside this PR).

**Comment by klshrinidhi** [comment]
Sounds good.

**Comment by chrisdembia** [comment]
Builds failing.

**Comment by aymanhab** [comment]
Failures don't seem to be clearly related, could be because builds with wrapping take too long. First commit on this branch passed all tests except for not finishing Python testing on Appveyor. Just restarted the failures.

**Comment by klshrinidhi** [comment]
Looks like Travis is :green_apple: :green_book: :green_heart:.
Appveyor should concur because we didn't change anything for it.

**Comment by aseth1** [comment]
Nice to see all the all green again. In it goes!

**Pull request merged**
