### PR TITLE
IMUDataReporter tests for compute_accelerations_without_forces()

### PR DESCRIPTION
**Pull request by nickbianco**
### Brief summary of changes
Add testing to check that `IMUDataRepoter::compute_accelerations_without_forces()` computes the correct accelerations when enabled. These changes also include some refactoring of `IMUDataReporter` to get things working.

### Testing I've completed
Added tests to `testAnalyzeTool.cpp` and `testMocoInverse.cpp`.

### CHANGELOG.md (choose one)

- no need to update because...adding tests.
- updated.

---
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3058)

### CODE REVIEW

**Review by aymanhab — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3058)* status: all files reviewed, 4 unresolved discussions (waiting on @nickbianco)

___
*[Applications/Analyze/test/testAnalyzeTool.cpp, line 110 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3058#-MgT6a_x4vFnntDcUh3K:-MgT6a_z7C7YqJnD-0em:b-nobfew) ([raw file](https://github.com/opensim-org/opensim-core/blob/6f4b7086bc50172708f3b9923e591a3e608c1605/Applications/Analyze/test/testAnalyzeTool.cpp#L110)):*
> ```cpp
> //
> //    cout << "Done" << endl;
>     return EXIT_SUCCESS;
> ```

why was that commented out? if parts fail do we get a summary elsewhere?
___
*[Applications/Analyze/test/testAnalyzeTool.cpp, line 385 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3058#-MgT7-uq-i-wQPh5eZ0e:-MgT7-uq-i-wQPh5eZ0f:b-w7s3zo) ([raw file](https://github.com/opensim-org/opensim-core/blob/6f4b7086bc50172708f3b9923e591a3e608c1605/Applications/Analyze/test/testAnalyzeTool.cpp#L385)):*
> ```cpp
>     auto& q1 = j1.updCoordinate();
>     q1.setValue(s, 0.0);
> ```

Looking back,  it's unnecessary to use "upd" methods, all these components are const, we're just modifying the state "s" otherwise the state s is "stale" and shouldn't be used. 
___
*[Applications/Analyze/test/testAnalyzeTool.cpp, line 504 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3058#-MgU-C-YD1d_x4CnE8ao:-MgU-C-YD1d_x4CnE8ap:b-z04teu) ([raw file](https://github.com/opensim-org/opensim-core/blob/6f4b7086bc50172708f3b9923e591a3e608c1605/Applications/Analyze/test/testAnalyzeTool.cpp#L504)):*
> ```cpp
>         q0.setValue(state, 0.0);
>         q1.setValue(state, 0.0);
> ```

same comment as above, use get instead of upd
___
*[OpenSim/Analyses/IMUDataReporter.cpp, line 149 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3058#-MgT8-Dy1jjwxiBOHt6f:-MgT8-Dy1jjwxiBOHt6g:b-mcb53c) ([raw file](https://github.com/opensim-org/opensim-core/blob/6f4b7086bc50172708f3b9923e591a3e608c1605/OpenSim/Analyses/IMUDataReporter.cpp#L149)):*
> ```cpp
>     if(!proceed()) return(0);
> 
>     if (_model == nullptr)
> ```

this is an error condition that should throw rather than return -1 quietly waiting for somebody else to check. _model is in base class so the framework should guarantee it's not nullptr

**Comment by aymanhab** [comment]
Nice job simplifying the reporter @nickbianco Had only minor comments. I also think the list of _imuComponents isn't used anymore by the datareporter so could be removed altogether.
Done with this review.
Building and testing GUI now to see how it plays.

**Comment by nickbianco** [comment]
@aymanhab thanks for the review. I'm still working on these tests as I'm getting accelerations that look _almost_ correct but with small errors throughout, and some not-so-small errors at the endpoints of the trajectory. Trying to isolate whether or not it's an issue with the AnalyzeTool or something else.

**Review by nickbianco — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3058)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @aymanhab)

___
*[Applications/Analyze/test/testAnalyzeTool.cpp, line 110 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3058#-MgT6a_x4vFnntDcUh3K:-MgwYyHy6Ldx9sBe1Wg3:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/6f4b7086bc50172708f3b9923e591a3e608c1605/Applications/Analyze/test/testAnalyzeTool.cpp#L110)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

why was that commented out? if parts fail do we get a summary elsewhere?
</blockquote></details>

Done.
___
*[Applications/Analyze/test/testAnalyzeTool.cpp, line 385 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3058#-MgT7-uq-i-wQPh5eZ0e:-MgwZSl10KIB65sXffoY:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/6f4b7086bc50172708f3b9923e591a3e608c1605/Applications/Analyze/test/testAnalyzeTool.cpp#L385)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

Looking back,  it's unnecessary to use "upd" methods, all these components are const, we're just modifying the state "s" otherwise the state s is "stale" and shouldn't be used. 
</blockquote></details>

Done.
___
*[Applications/Analyze/test/testAnalyzeTool.cpp, line 504 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3058#-MgU-C-YD1d_x4CnE8ao:-MgwZe26BxCCNdhvjdgn:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/6f4b7086bc50172708f3b9923e591a3e608c1605/Applications/Analyze/test/testAnalyzeTool.cpp#L504)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

same comment as above, use get instead of upd
</blockquote></details>

Done.
___
*[OpenSim/Analyses/IMUDataReporter.cpp, line 149 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3058#-MgT8-Dy1jjwxiBOHt6f:-MgwZwPLApCQ5uyIP-XL:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/6f4b7086bc50172708f3b9923e591a3e608c1605/OpenSim/Analyses/IMUDataReporter.cpp#L149)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

this is an error condition that should throw rather than return -1 quietly waiting for somebody else to check. _model is in base class so the framework should guarantee it's not nullptr
</blockquote></details>

Done.

**Review by nickbianco — COMMENTED** [review]
@aymanhab Ready for review.

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3058#-:-Mgwg2Zg9z8uvSCdgb3l:b5jmv2c)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @aymanhab)

**Review by aymanhab — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3058)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nickbianco)

**Comment by aymanhab** [comment]
@nickbianco Thanks for the changes, the code changes looking good now but the test fails, is that expected? Just let us know so we can investigate/fix before merging. Thank you

**Review by nickbianco — COMMENTED** [review]
Thanks @aymanhab. Just pushed a change that should fix the test.

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3058#-:-Mh-pQ9L3o-XeYVvz7bu:b-3ys5pl)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @aymanhab)

**Comment by aymanhab** [comment]
The test MocoInverse fails on linux but succeeds locally (on linux/ubuntu as well). So will merge to create a build/candidate while investigating.

**Review by aymanhab — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3058)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nickbianco)

**Pull request merged**
