### PR TITLE
OpenSimConfig.cmake does not contain hardcoded abs paths.

### LINKED ISSUE #323: OpenSimConfig.cmake assumes an install directory.
Right now, we have a mechanism for people who want to use OpenSim as a library for their own C++ project: OpenSimConfig.cmake.

However, this mechanism only works if OpenSim is installed in the location specified during the build process. This is fine for people building from source, b/c they know their install directory ahead of time (during building).

However, when we distribute OpenSim binaries as part of a release, we don't know where users will choose to install OpenSim (perhaps `C:/myApps/OpenSim`). I did not account for this when I created the OpenSimConfig.cmake. 

Therefore, we need an additional mechanism, likely a FindOpenSim.cmake file, that OpenSim users can use.

### PR DESCRIPTION
**Pull request by chrisdembia**
Fixes #323. See https://github.com/simbody/simbody/pull/339 for discussion.

### CODE REVIEW

**Comment by chrisdembia** [comment]
I should have mentioned; this also increases our CMake requirement to 2.8.8, as we just did for Simbody.

**Comment by chrisdembia** [comment]
To get travis working again, this needs to be merged. Can I interest anyone in reviewing this?

**Comment by sherm1** [comment]
I looked at the code which looks fine, but didn't have a chance to try it. Chris, have you tested it for OpenSim? If so, I'd be OK with merging it and fixing later if necessary since Travis is broken at the moment anyway. Anyone else?

**Comment by chrisdembia** [comment]
Yes I tested (by moving the installation dir.) on Ubuntu.

**Comment by aymanhab** [comment]
@chrisdembia Seems relatively benign. If it passes on Travis and appvoyer has the correct version of CMake then we should be good.

**Comment by sherm1** [comment]
OK, I'll merge it. We should perform a Windows test sometime soon though!

**Comment by chrisdembia** [comment]
Thanks to both of you!

**Pull request merged**
