### PR TITLE
Bodykinematics header fix

### PR DESCRIPTION
**Pull request by carmichaelong**
Fixes issue #2842 and other undocumented issues

### Brief summary of changes
- Update header to note whether angular velocities and accelerations are given in local or ground frame
- Update inDegrees to match output
- Add a test that uses BodyKinematics

### Testing I've completed
- Added test
- Inspected output files for correct header output

---
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2991)

### CODE REVIEW

**Comment by carmichaelong** [comment]
@aymanhab Do you have any spare cycles to build and test this locally? I tried a few things to try to fix, but it's hard to track down since it's passing locally for me and only failing on CI. Things I've tried:
- Fixed some variable naming
- Changed PlanarJoint to FreeJoint in the test
- Explicitly allocated memory on the heap for the analyses just in case

**Comment by aymanhab** [comment]
Sure @carmichaelong I'll take a look.

**Comment by aymanhab** [comment]
@carmichaelong Issue has been fixed, osx failure is unrelated and sporadic.

**Comment by carmichaelong** [comment]
Thanks @aymanhab, that fix makes sense. Do you want to review the rest? I think it should be a quick review

**Review by aymanhab — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2991)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @carmichaelong)

___
*[Applications/Analyze/test/testAnalyzeTool.cpp, line 277 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/2991#-MYuRPs5BipHUOCkZjy0:-MYuRPs5BipHUOCkZjy1:b-9oz0ih) ([raw file](https://github.com/opensim-org/opensim-core/blob/203dbff9bb77a77927702277cca6a71abc60fe5f/Applications/Analyze/test/testAnalyzeTool.cpp#L277)):*
> ```cpp
>     // Rotate child frame so that planar rotational joint is about
>     // the body's local X axis, and the ground's Z axis
>     FreeJoint* joint = new FreeJoint("joint",
> ```

Is this a left over comment from a different joint type? Maybe clarify the test intentions
___
*[Applications/Analyze/test/testAnalyzeTool.cpp, line 289 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/2991#-MYuRo8I-uFi2JeElwcV:-MYuRo8I-uFi2JeElwcW:b-pc3j2g) ([raw file](https://github.com/opensim-org/opensim-core/blob/203dbff9bb77a77927702277cca6a71abc60fe5f/Applications/Analyze/test/testAnalyzeTool.cpp#L289)):*
> ```cpp
>     BodyKinematics* bodyKinematicsGround = new BodyKinematics(&model);
>     bodyKinematicsGround->setName("ground");
>     bodyKinematicsGround->setExpressResultsInLocalFrame(false);
> ```

Not sure if this is allowed to have components with same name "ground" but maybe clearer to rename to "localKinematics", "groundKinematics" if not too much work.
___
*[OpenSim/Analyses/BodyKinematics.cpp, line 204 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/2991#-MYuSaAUDzKrvE2jgI4G:-MYuSaAUDzKrvE2jgI4H:b-1lvqis) ([raw file](https://github.com/opensim-org/opensim-core/blob/203dbff9bb77a77927702277cca6a71abc60fe5f/OpenSim/Analyses/BodyKinematics.cpp#L204)):*
> ```cpp
>         strcat(descrip, "\nAngular velocities and accelerations are");
>         strcat(descrip, " expressed in the ground frame axes.\n");
>     }
> ```

Probably can remove the trailing "axes"

**Review by aymanhab — COMMENTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2991)* status: all files reviewed, 3 unresolved discussions (waiting on @carmichaelong)

**Review by carmichaelong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2991)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @aymanhab)

___
*[Applications/Analyze/test/testAnalyzeTool.cpp, line 277 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/2991#-MYuRPs5BipHUOCkZjy0:-MYud8vZ3ohGxQfvEAm1:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/203dbff9bb77a77927702277cca6a71abc60fe5f/Applications/Analyze/test/testAnalyzeTool.cpp#L277)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

Is this a left over comment from a different joint type? Maybe clarify the test intentions
</blockquote></details>

Done.
___
*[Applications/Analyze/test/testAnalyzeTool.cpp, line 289 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/2991#-MYuRo8I-uFi2JeElwcV:-MYud9FOCLAI_cnA-RWU:bvwz0vi) ([raw file](https://github.com/opensim-org/opensim-core/blob/203dbff9bb77a77927702277cca6a71abc60fe5f/Applications/Analyze/test/testAnalyzeTool.cpp#L289)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

Not sure if this is allowed to have components with same name "ground" but maybe clearer to rename to "localKinematics", "groundKinematics" if not too much work.
</blockquote></details>

Done. Just added "BodyKinematics" so that it's still easy to differentiate in the test folder
___
*[OpenSim/Analyses/BodyKinematics.cpp, line 204 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/2991#-MYuSaAUDzKrvE2jgI4G:-MYueMP80Tq87cErqvwO:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/203dbff9bb77a77927702277cca6a71abc60fe5f/OpenSim/Analyses/BodyKinematics.cpp#L204)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

Probably can remove the trailing "axes"
</blockquote></details>

Done.

**Review by aymanhab — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2991)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @carmichaelong)

**Comment by carmichaelong** [comment]
Thanks @aymanhab

**Pull request merged**
