### PR TITLE
[Moco] Adding MocoInitialOutputGoal, MocoFinalOutputGoal, and MocoOutputTrackingGoal

### PR DESCRIPTION
**Pull request by nickbianco**
Fixes issue #3061

### Brief summary of changes

- Added new `MocoGoal`s -- `MocoInitialOutputGoal`, `MocoFinalOutputGoal`, `MocoOutputTrackingGoal`
- All new goals and `MocoOutputGoal` unified under base class `MocoOutputBase`
- All new goals and `MocoOutputGoal` support both cost and endpoint constraint modes
- Print description virtual method implemented for all goals
- Fix to make sure `analyze_<T>` includes all `Model`-level `Output`s

### Testing I've completed
TODO

### Looking for feedback on...

1.  Should one `MocoOutputGoal` object support multiple `Output`s? Would require changing the interface (i.e., `addOutputGroup()`).
2. How to handle exponent in `MocoOutputTrackingGoal`. 

### CHANGELOG.md (choose one)

- no need to update because...
- updated.

---
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3142)

### CODE REVIEW

**Comment by nickbianco** [comment]
@carmichaelong, this still needs a little work, but feel free to start reviewing.

**Review by carmichaelong — COMMENTED** [review]
Thanks @nickbianco, I looked at everything and the code overall looks good at this point. Some responses to the feedback questions:

> Should one MocoOutputGoal object support multiple Outputs? Would require changing the interface (i.e., addOutputGroup()).

I'd vote no for now. I think for most cases this will work well, especially since you may want to provide different weights to different outputs, and this avoids an interface change.

> How to handle exponent in MocoOutputTrackingGoal.

I would have expected that the exponent would refer to the outside exponent rather than the values on the inside, i.e.: (value_sim - value_track)^(exponent). I think this would be the exponent most users may want to fiddle with rather than exponents for the values themselves. I suppose in theory you could add another variable to tweak exponents for the values themselves if needed (this could be left out for now in this PR, and then added later without breaking interfaces if users want that extra knob)

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3142#-:-N-PAGU86JMljhxexHbs:bwvdli8)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @nickbianco)

**Comment by nickbianco** [comment]
Thanks @carmichaelong! I took the advice above and added two new modules: `MocoOutputPeriodicityGoal` and `MocoOutputConstraint`. The latter derives from `MocoPathConstraint`, but is essentially the same structure as `MocoOutputBase`/`MocoOutputGoal`. Drawing the line for the scope of this PR here.

Ready for review.

**Review by carmichaelong — CHANGES_REQUESTED** [review]
@nickbianco this is looking really good. Had one super minor (ignorable) comment. It would be great to also add some test coverage too.

> Reviewed 1 of 4 files at r1, 10 of 12 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3142#-:-N0Yz_qfBFHLnUJZL9pM:btzfs3s)* status: 12 of 13 files reviewed, 1 unresolved discussion (waiting on @aymanhab and @nickbianco)

___
*[`OpenSim/Moco/MocoOutputConstraint.cpp` line 33 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3142#-N0YZvgY0xC3gTTinSE_:-N0YZvgZCd4gxueXT2Bm:b-wubx3p) ([raw file](https://github.com/opensim-org/opensim-core/blob/385418bb1679eea9a3ed49db2cb3e738709ccf3d/OpenSim/Moco/MocoOutputConstraint.cpp#L33)):*
> ```cpp
>     OPENSIM_THROW_IF_FRMOBJ(get_output_path().empty(), Exception,
>             "No output_path provided.");
>     std::string componentPath;
> ```

could also use `std::string componentPath, outputName, channelName, alias;`

**Comment by nickbianco** [comment]
Thanks @carmichaelong! I've added some testing for the new MocoGoals.

Ready for review.

**Review by carmichaelong — CHANGES_REQUESTED** [review]
Thanks, the tests look great. One minor comment, and then I also restarted the Windows test because the build step failed.

> Reviewed 1 of 12 files at r2, 2 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3142#-:-N1QDQhoCtXin0MGAn-b:bcp62kg)* status: 13 of 14 files reviewed, 1 unresolved discussion (waiting on @aymanhab and @nickbianco)

___
*[`OpenSim/Moco/Test/testMocoGoals.cpp` line 948 at r4](https://reviewable.io/reviews/opensim-org/opensim-core/3142#-N1QAbX15hAOSsEqrFzW:-N1QAbX28AceisDuDd6J:b-hnc5lz) ([raw file](https://github.com/opensim-org/opensim-core/blob/6eea43f65cab052658fd3cfec2519a17a609dd9a/OpenSim/Moco/Test/testMocoGoals.cpp#L948)):*
> ```cpp
>         auto& solverTracking = studyTracking.initSolver<MocoCasADiSolver>();
>         solverTracking.set_num_mesh_intervals(10);
>         MocoSolution solutionTracking = studyTracking.solve().unseal();
> ```

Is `unseal()` needed here, or was it just for debugging while creating the test?

**Review by nickbianco — COMMENTED** [review]
Fixed the build issue (I think) and addressed your last comment.

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3142#-:-N1WdriE0AFhLyrJfn5u:b-ikw863)* status: 13 of 14 files reviewed, 1 unresolved discussion (waiting on @aymanhab and @carmichaelong)

___
*[`OpenSim/Moco/Test/testMocoGoals.cpp` line 948 at r4](https://reviewable.io/reviews/opensim-org/opensim-core/3142#-N1QAbX15hAOSsEqrFzW:-N1WdoZe5xB7ADLEAtFZ:b-4grvzq) ([raw file](https://github.com/opensim-org/opensim-core/blob/6eea43f65cab052658fd3cfec2519a17a609dd9a/OpenSim/Moco/Test/testMocoGoals.cpp#L948)):*
<details><summary><i>Previously, carmichaelong wrote…</i></summary><blockquote>

Is `unseal()` needed here, or was it just for debugging while creating the test?
</blockquote></details>

Good catch! Removed.

**Review by carmichaelong — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3142#-:-N1ZeQVc60P64NGA4LZa:bnfp4nl)* status: 13 of 14 files reviewed, all discussions resolved (waiting on @aymanhab)

**Review by aymanhab — APPROVED** [review]
Approved based on @carmichaelong detailed review. Thanks @nickbianco and @carmichaelong 👍

**Pull request merged**
