### PR TITLE
Data adapters wrapping

### PR DESCRIPTION
**Pull request by klshrinidhi**
Wrapping DataAdapter and its derived classes to allow access from Python/Java.

See [Bindings/Python/tests/test_DataAdapter.py](https://github.com/opensim-org/opensim-core/blob/data_adapters_wrapping/Bindings/Python/tests/test_DataAdapter.py).

### CODE REVIEW

**Comment by chrisdembia** [comment]
Looks good to me! @aymanhab do you plan to review this?

**Comment by aymanhab** [comment]
Not immediately but I'll need to merge with it later today since I'm
touching the same files. Merge as you see fit. Thanks

**Comment by chrisdembia** [comment]
OK then @klshrinidhi do you want to merge it when the tests pass?

**Comment by chrisdembia** [comment]
:fireworks:

**Pull request merged**
