### PR TITLE
Add bindings support, `analyze` utilities, and test coverage for `TimeSeriesTable_<SimTK::Rotation>`

### PR DESCRIPTION
**Pull request by nickbianco**
Fixes issue #3925

### Brief summary of changes
`TimeSeriesTable_<SimTK::Rotation>` is [available in C++ API](https://github.com/opensim-org/opensim-core/blob/37e40e1dd300ea81ba9aa5c6392b034b67609449/OpenSim/Common/TimeSeriesTable.h#L553), but had limited support in scripting, and almost no test coverage. This PR addresses both of those issues and also adds the scripting friendly `analyzeMocoTrajectoryRotation` to compute tables from `Output`s of type `SimTK::Rotation`. 

As a bonus, but related change, `MocoStudy::analyze<T>()` is now templatized, so Moco users need not search for the utility functions when computing non-`double` type `Output`s. For backwards-compatibility, the non-templatized `MocoStudy::analyze()` is still available as a simple wrapper to the new templatized version. Finally, wrappers in the bindings were added for specific template arguments of `analyze<T>`, so that they are available in scripting. 

### Testing I've completed
Updated `testDataTable.cpp`, `test_DataTable.py`, and `TestTables.java`.

### Looking for feedback on...

One drawback of using `TimeSeriesTable_<SimTK::Rotation>` is that certain methods are not supported simply because Simbody types are not available (e.g., `averageRow` fails because `SimTK::RowVector_<SimTK::Rotation>` does not exist). Making `TimeSeriesTable_<SimTK::Rotation>` more accessible probably makes it more likely for users to encounter this edge case.

### CHANGELOG.md (choose one)

- updated.

- - -
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3940)

### CODE REVIEW

**Review by aymanhab — CHANGES_REQUESTED** [review]
One minor clarification but otherwise LGTM :+1: . 
Maybe unrelated and I understand analyze has been used extensively by Moco it just jumps out as a generic name that could mislead users. Maybe a non templatized analyzeMocoTrajectory would open the door to retiring the old generic name in favor of the more specific  name that reflects functionality.

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3940#-:-O9LFG6S7B8P20sVSjhe:b-3mpcw3)* status: all files reviewed, 2 unresolved discussions (waiting on @nickbianco)

___
*[`Bindings/moco.i` line 142 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3940#-O9LEDgmE35qJn6kDNte:-O9LEDgn--3Ne801Jrp-:bgorh1x) ([raw file](https://github.com/opensim-org/opensim-core/blob/de972247e42618aef96f75d27b2e2c01892a6d29/Bindings/moco.i#L142)):*
> ```SWIG
> %include <OpenSim/Moco/MocoStudy.h>
> %template(analyzeVec3) OpenSim::MocoStudy::analyze<SimTK::Vec3>;
> %template(analyzeSpatialVec) OpenSim::MocoStudy::analyze<SimTK::SpatialVec>;
> ```

Was this intentional (the addition of SpatialVec)? Would it expose users to other issues downstream?
___
*[`OpenSim/Moco/MocoStudy.h` line 179 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3940#-O9LFAOBEsk4jW4AM6A7:-O9LFAOBEsk4jW4AM6A8:b-83sjoh) ([raw file](https://github.com/opensim-org/opensim-core/blob/de972247e42618aef96f75d27b2e2c01892a6d29/OpenSim/Moco/MocoStudy.h#L179)):*
> ```objc
>             get_problem().createRep().getModelBase(), traj, outputPaths);
>     }
> ```

Nice!

**Review by nickbianco — COMMENTED** [review]
We have three ways to access the analyze utilities:
- `MocoStudy::analyze<T>()`, which calls...
- `MocoUtilities::analyzeMocoTrajectory<T>()`, which calls...
- `SimulationUtilities::analyze<T>()`

The `SimulationUtilities` version is the most generic and contains all of the actual analysis code. The previous utilities are just convenience methods for converting a `MocoTrajectory` to the tables that `SimulationUtilities::analyze<T>()`. I think it's okay that `MocoStudy::analyze<T>()` does have "MocoTrajectory" somewhere in the name, since it is implied (and stated directly in the docs) that you should be working with a `MocoTrajectory`.

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3940#-:-O9Qe_fM3z5pk_Du8T5t:b-xptacj)* status: 8 of 9 files reviewed, 2 unresolved discussions (waiting on @aymanhab)

___
*[`Bindings/moco.i` line 142 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3940#-O9LEDgmE35qJn6kDNte:-O9QeJ8q5igRzRTdLB8g:b-lnfwq7) ([raw file](https://github.com/opensim-org/opensim-core/blob/de972247e42618aef96f75d27b2e2c01892a6d29/Bindings/moco.i#L142)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

Was this intentional (the addition of SpatialVec)? Would it expose users to other issues downstream?
</blockquote></details>

Yes, this was intentional. This allows users to compute SpatialVec quantities directly from a MocoStudy, rather than having to dig up the utilities functions. Previously, we only allowed double Output analyses through MocoStudy.
___
*[`OpenSim/Moco/MocoStudy.h` line 179 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3940#-O9LFAOBEsk4jW4AM6A7:-O9QeYBV1YZSQ7EWje9U:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/de972247e42618aef96f75d27b2e2c01892a6d29/OpenSim/Moco/MocoStudy.h#L179)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

Nice!
</blockquote></details>

Done.

**Review by aymanhab — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3940#-:-O9QoeNhAWXTyCERhIlo:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @nickbianco)

**Comment by nickbianco** [comment]
Thanks @aymanhab!

**Pull request merged**
