### PR TITLE
Update continuous_integration.yml to re-enable java tests on windows

### PR DESCRIPTION
**Pull request by aymanhab**
Reenable java tests on windows

Fixes issue #<issue_number>

### CHANGELOG.md (choose one)

- no need to update because...
- updated.

- - -
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3885)

### CODE REVIEW

**Comment by aymanhab** [comment]
@nickbianco I think nothing changed there, windows2019 successfully builds/runs java tests and windows2022 builds but fails to load the libraries

**Comment by aymanhab** [comment]
Try to address issue #3806 apparently the "recommened" solution was to a remove a dll from the jdk installation, what a mess!

**Comment by nickbianco** [comment]
> Try to address issue https://github.com/opensim-org/opensim-core/issues/3806 apparently the "recommened" solution was to a remove a dll from the jdk installation, what a mess!

Yikes.

**Comment by nickbianco** [comment]
@aymanhab, do you want to merge this to have the Java tests enabled for Windows 2019 for now?

**Comment by aymanhab** [comment]
Yes I think it's good to run the javs tests on some windows environment

**Comment by aymanhab** [comment]
Thanks @nickbianco

**Pull request merged**
