### PR TITLE
Add `MocoOutputBoundConstraint` class

### PR DESCRIPTION
**Pull request by AllisonJohn**
Fixes issue #3857

### Brief summary of changes
Combined MocoOutputConstraint with MocoControlBoundConstraint
Added a couple of tests but will add more

### Testing I've completed
added to testMocoConstraints.cpp

### CHANGELOG.md (choose one)

- updated.

- - -
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3859)

### CODE REVIEW

**Review by AllisonJohn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3859)* status: 0 of 8 files reviewed, 1 unresolved discussion

___
*[`OpenSim/Moco/MocoOutputBoundConstraint.cpp` line 2 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3859#-O2k0bxX5Z-y30kWCLYe:-O2k0bxX5Z-y30kWCLYf:bb6gchm) ([raw file](https://github.com/opensim-org/opensim-core/blob/7083c57f181ec38ca508370953c4223eae22db5a/OpenSim/Moco/MocoOutputBoundConstraint.cpp#L2)):*
> ```cpp
> /* -------------------------------------------------------------------------- *
> * OpenSim: MocoOutputBoundConstraint.h                                        *
> ```

.cpp

**Review by nickbianco — CHANGES_REQUESTED** [review]
Another nice addition! Mostly minor stuff to address.

> Reviewed 4 of 8 files at r1, 3 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3859#-:-O2kSg4OAVablY8wTBmm:b-6901yk)* status: all files reviewed, 9 unresolved discussions (waiting on @AllisonJohn)

___
*[`OpenSim/Moco/MocoOutputBoundConstraint.h` line 6 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3859#-O2kHiQ-8hFkZncDzGOy:-O2kHiQ-8hFkZncDzGOz:undefined) ([raw file](https://github.com/opensim-org/opensim-core/blob/56694dd24800150f12f88ec0eab6b0c202cb8296/OpenSim/Moco/MocoOutputBoundConstraint.h#L6)):*
> ```objc
> * OpenSim: MocoOutputBoundConstraint.h                                        *
>  * -------------------------------------------------------------------------- *
>  * Copyright (c) 2019 Stanford University and the Authors                     *
> ```





_Suggestion:_
```objc
 * OpenSim: MocoOutputBoundConstraint.h                                       *
 * -------------------------------------------------------------------------- *
 * Copyright (c) 2024 Stanford University and the Authors                     *
```
___
*[`OpenSim/Moco/MocoOutputBoundConstraint.h` line 36 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3859#-O2kHsLnDgv1RmKRZJQk:-O2kHsLnDgv1RmKRZJQl:bb7lc5i) ([raw file](https://github.com/opensim-org/opensim-core/blob/56694dd24800150f12f88ec0eab6b0c202cb8296/OpenSim/Moco/MocoOutputBoundConstraint.h#L36)):*
> ```objc
> The first Output is always on the left hand side of the operation and the second
> Output on the right hand side. The two Outputs can be different quantities, but
> they must be the same type.
> ```

nit:



_Suggestion:_
```objc
they must have the same type.
```
___
*[`OpenSim/Moco/MocoOutputBoundConstraint.h` line 64 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3859#-O2kORM48AxW9VRckqXh:-O2kORM48AxW9VRckqXi:undefined) ([raw file](https://github.com/opensim-org/opensim-core/blob/56694dd24800150f12f88ec0eab6b0c202cb8296/OpenSim/Moco/MocoOutputBoundConstraint.h#L64)):*
> ```objc
>     MocoOutputBoundConstraint() { constructProperties(); }
> 
>     /** Set the absolute path to the output in the model to be used in this path
> ```





_Suggestion:_
```objc
    /** Set the absolute path to the Output in the model to be used in this path
```
___
*[`OpenSim/Moco/MocoOutputBoundConstraint.h` line 71 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3859#-O2kOXCd8TtqhdZTIs2D:-O2kOXCd8TtqhdZTIs2E:undefined) ([raw file](https://github.com/opensim-org/opensim-core/blob/56694dd24800150f12f88ec0eab6b0c202cb8296/OpenSim/Moco/MocoOutputBoundConstraint.h#L71)):*
> ```objc
>     /** Set the absolute path to the optional second Output in the model to be
>     used in this path constraint. The format is "/path/to/component|output_name".
>     This Output should have the same  type as the first Output. If providing a
> ```





_Suggestion:_
```objc
    This Output should have the same type as the first Output. If providing a
```
___
*[`OpenSim/Moco/MocoOutputBoundConstraint.h` line 115 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3859#-O2kOtm40zu-6lThU_Xb:-O2kOtm40zu-6lThU_Xc:undefined) ([raw file](https://github.com/opensim-org/opensim-core/blob/56694dd24800150f12f88ec0eab6b0c202cb8296/OpenSim/Moco/MocoOutputBoundConstraint.h#L115)):*
> ```objc
>     const Function& getUpperBound() const { return get_upper_bound(); }
> 
>     /// Should the output be constrained to be equal to the lower bound (rather
> ```





_Suggestion:_
```objc
    /// Should the Output be constrained to be equal to the lower bound (rather
```
___
*[`OpenSim/Moco/MocoOutputBoundConstraint.h` line 127 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3859#-O2kP9zGAUcb6hIVVVU4:-O2kP9zGAUcb6hIVVVU5:bd6uzr6) ([raw file](https://github.com/opensim-org/opensim-core/blob/56694dd24800150f12f88ec0eab6b0c202cb8296/OpenSim/Moco/MocoOutputBoundConstraint.h#L127)):*
> ```objc
> 
>     void calcPathConstraintErrorsImpl(
>             const SimTK::State&, SimTK::Vector&) const override;
> ```

nit: remove blank line



_Suggestion:_
```objc
    void initializeOnModelImpl(
            const Model&, const MocoProblemInfo&) const override;
    void calcPathConstraintErrorsImpl(
            const SimTK::State&, SimTK::Vector&) const override;
```
___
*[`OpenSim/Moco/MocoOutputBoundConstraint.cpp` line 4 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3859#-O2kPoRb6kVvz3wL_16k:-O2kPoRb6kVvz3wL_16l:undefined) ([raw file](https://github.com/opensim-org/opensim-core/blob/56694dd24800150f12f88ec0eab6b0c202cb8296/OpenSim/Moco/MocoOutputBoundConstraint.cpp#L4)):*
> ```cpp
> * OpenSim: MocoOutputBoundConstraint.cpp                                      *
>  * -------------------------------------------------------------------------- *
>  * Copyright (c) 2019 Stanford University and the Authors                     *
> ```





_Suggestion:_
```cpp
 * Copyright (c) 2024 Stanford University and the Authors                     *
```
___
*[`OpenSim/Moco/MocoOutputBoundConstraint.cpp` line 262 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3859#-O2kQiEZ2Ui8J7VTeP5i:-O2kQiEZ2Ui8J7VTeP5j:blokvrt) ([raw file](https://github.com/opensim-org/opensim-core/blob/56694dd24800150f12f88ec0eab6b0c202cb8296/OpenSim/Moco/MocoOutputBoundConstraint.cpp#L262)):*
> ```cpp
>     double value = 0;
>     if (m_data_type == Type_double) {
>         value = static_cast<const Output<double>*>(m_output.get())
> ```

Use `getOutput()` here?
___
*[`OpenSim/Moco/MocoOutputBoundConstraint.cpp` line 314 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3859#-O2kR9kPDy8xx5YcrAPL:-O2kR9kPDy8xx5YcrAPM:bbcxzhi) ([raw file](https://github.com/opensim-org/opensim-core/blob/56694dd24800150f12f88ec0eab6b0c202cb8296/OpenSim/Moco/MocoOutputBoundConstraint.cpp#L314)):*
> ```cpp
>                             [m_index1][m_index2];
>             double value2 = getSecondOutput<SimTK::SpatialVec>().getValue(state)
>                             [m_index1][m_index2];
> ```

I guess I should have made this suggestion on one of the previous PRs, but I think I would prefer stylewise breaking these lines at `getValue()`:



_Suggestion:_
```cpp
            double value1 = getOutput<SimTK::SpatialVec>()
                            .getValue(state)[m_index1][m_index2];
            double value2 = getSecondOutput<SimTK::SpatialVec>()
                            .getValue(state)[m_index1][m_index2];
```

**Review by AllisonJohn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3859)* status: 1 of 9 files reviewed, 7 unresolved discussions (waiting on @nickbianco)

___
*[`OpenSim/Moco/MocoOutputBoundConstraint.h` line 6 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3859#-O2kHiQ-8hFkZncDzGOy:-O2kVRh61eQWjWN8Fay3:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/56694dd24800150f12f88ec0eab6b0c202cb8296/OpenSim/Moco/MocoOutputBoundConstraint.h#L6)):*
> ```objc
> * OpenSim: MocoOutputBoundConstraint.h                                        *
>  * -------------------------------------------------------------------------- *
>  * Copyright (c) 2019 Stanford University and the Authors                     *
> ```

Done.
___
*[`OpenSim/Moco/MocoOutputBoundConstraint.h` line 64 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3859#-O2kORM48AxW9VRckqXh:-O2kV_vz9WMl3VLuU6iV:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/56694dd24800150f12f88ec0eab6b0c202cb8296/OpenSim/Moco/MocoOutputBoundConstraint.h#L64)):*
> ```objc
>     MocoOutputBoundConstraint() { constructProperties(); }
> 
>     /** Set the absolute path to the output in the model to be used in this path
> ```

Done.
___
*[`OpenSim/Moco/MocoOutputBoundConstraint.h` line 71 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3859#-O2kOXCd8TtqhdZTIs2D:-O2kVccdAcJFBmjxlYWd:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/56694dd24800150f12f88ec0eab6b0c202cb8296/OpenSim/Moco/MocoOutputBoundConstraint.h#L71)):*
> ```objc
>     /** Set the absolute path to the optional second Output in the model to be
>     used in this path constraint. The format is "/path/to/component|output_name".
>     This Output should have the same  type as the first Output. If providing a
> ```

Done.
___
*[`OpenSim/Moco/MocoOutputBoundConstraint.h` line 115 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3859#-O2kOtm40zu-6lThU_Xb:-O2kVhH4521AOkMZqdgz:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/56694dd24800150f12f88ec0eab6b0c202cb8296/OpenSim/Moco/MocoOutputBoundConstraint.h#L115)):*
> ```objc
>     const Function& getUpperBound() const { return get_upper_bound(); }
> 
>     /// Should the output be constrained to be equal to the lower bound (rather
> ```

Done.
___
*[`OpenSim/Moco/MocoOutputBoundConstraint.cpp` line 4 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3859#-O2kPoRb6kVvz3wL_16k:-O2kVl4H1u3dt7GgkpTn:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/56694dd24800150f12f88ec0eab6b0c202cb8296/OpenSim/Moco/MocoOutputBoundConstraint.cpp#L4)):*
> ```cpp
> * OpenSim: MocoOutputBoundConstraint.cpp                                      *
>  * -------------------------------------------------------------------------- *
>  * Copyright (c) 2019 Stanford University and the Authors                     *
> ```

Done.
___
*[`OpenSim/Moco/MocoOutputBoundConstraint.cpp` line 262 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3859#-O2kQiEZ2Ui8J7VTeP5i:-O2kWmzn4ewsTju7wQzl:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/56694dd24800150f12f88ec0eab6b0c202cb8296/OpenSim/Moco/MocoOutputBoundConstraint.cpp#L262)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Use `getOutput()` here?
</blockquote></details>

Done.
___
*[`OpenSim/Moco/MocoOutputBoundConstraint.cpp` line 314 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3859#-O2kR9kPDy8xx5YcrAPL:-O2kWx7z63gKbq6fNDRp:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/56694dd24800150f12f88ec0eab6b0c202cb8296/OpenSim/Moco/MocoOutputBoundConstraint.cpp#L314)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

I guess I should have made this suggestion on one of the previous PRs, but I think I would prefer stylewise breaking these lines at `getValue()`:
</blockquote></details>

Done.

**Review by nickbianco — APPROVED** [review]
> Reviewed 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3859)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AllisonJohn)

**Pull request merged**
