### PR TITLE
A mechanism for tests to share files (e.g., model files)

### PR DESCRIPTION
**Pull request by chrisdembia**
This is a followup to #496, taking Sherm's feedback into consideration.

### CODE REVIEW

**Comment by sherm1** [comment]
Oh, I like those CamelCaseFunctions! Not sure why, though.

**Comment by chrisdembia** [comment]
I like them too; they grew on me.

**Comment by elen4** [comment]
Hi @sherm1, I don't know of any clear convention for capitalizations in CMake macro names, they are left to personal taste. In my limited experience, I have always used underscores, and IMHO camel case does not make much sense in a case-insensitive language (although I usually like it). The only "reference" I found is this post:http://public.kitware.com/pipermail/cmake-developers/2011-November/014160.html . From what I get, CMake developers have moved to camel case themselves (well, actually a mixture of camel case and underscores). Personally, I would at least separate the OpenSim prefix from the rest of the command so that it's easier to spot the actual command name, but it's just personal taste (or habit :smiley:)
@chrisdembia: CONTRIBUTING.md needs to be updated as it still suggests to use the OPENSIM_COPY_SHARED_TEST_FILES macro. Also, in the macro implementation, I like `file(COPY ...)` more than `configure_file(... COPYONLY)`, but it's again a matter of personal taste (I find it clearer)

**Comment by chrisdembia** [comment]
> ersonally, I would at least separate the OpenSim prefix from the rest of the command so that it's easier to spot the actual command name, but it's just personal taste (or habit )

I like this idea.



> I like file(COPY ...) more than configure_file(... COPYONLY), but it's again a matter of personal taste (I find it clearer)

I agree with you but I am using `configure_file` for a specific reason.  With `configure_file`, if I modify the source file, it is re-copied (to the build dir). Do you know that `file(COPY` will do the same? I suppose I could just try.

**Comment by elen4** [comment]
> With configure_file, if I modify the source file, it is re-copied (to the build dir). Do you know that file(COPY will do the same?

As far as I know, yes it does, and also documentation for the `file` command seems to indicate the same: *Copying preserves input file timestamps, and optimizes out a file if it exists at the destination with the same timestamp*. Testing doesn't hurt, though :smile: 

On a side note, I forgot: :+1: for unscreamifying all the files!

**Comment by sherm1** [comment]
Thanks, Elena!

**Comment by chrisdembia** [comment]
I'll merge this after tests pass. I realize I previously introduced a bug into the cmake files in which testComponents was excluded from the tests.

**Comment by chrisdembia** [comment]
Thanks @sherm1 and @elen4 for reviewing.

**Pull request merged**
