### PR TITLE
A few tweaks to `MocoExpressionBasedParameterGoal`

### PR DESCRIPTION
**Pull request by nickbianco**
### Brief summary of changes

A handful of changes made to some aspects of `MocoExpressionBasedParameterGoal` that I noticed while using this as a reference for `ExpressionBasedFunction`. I've also opted to change the property `variable_names` to simply `variables`.

### Testing I've completed

Ran the existing tests in `testMocoGoals.cpp`.

### CHANGELOG.md (choose one)

- no need to update because...tweaks to existing goal.

- - -
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3893)

### CODE REVIEW

**Review by AllisonJohn — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3893)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @nickbianco)

___
*[`OpenSim/Moco/MocoGoal/MocoExpressionBasedParameterGoal.h` line 79 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3893#-O5FyGJY5KhK3OX5LgfU:-O5FyGJY5KhK3OX5LgfV:bdnjkl6) ([raw file](https://github.com/opensim-org/opensim-core/blob/d23d002ae367783d60d11733c03263be29e6f9d8/OpenSim/Moco/MocoGoal/MocoExpressionBasedParameterGoal.h#L79)):*
> ```objc
>     }
> 
>     /** Set the mathematical expression to minimize or constraint. Variable 
> ```

constraint -> constrain
Maybe it should say arithmetic instead of mathematical too

**Review by nickbianco — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3893)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @AllisonJohn)

___
*[`OpenSim/Moco/MocoGoal/MocoExpressionBasedParameterGoal.h` line 79 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3893#-O5FyGJY5KhK3OX5LgfU:-O5G-R5pDVc-KYd8pH-k:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/d23d002ae367783d60d11733c03263be29e6f9d8/OpenSim/Moco/MocoGoal/MocoExpressionBasedParameterGoal.h#L79)):*
<details><summary><i>Previously, AllisonJohn wrote…</i></summary><blockquote>

constraint -> constrain
Maybe it should say arithmetic instead of mathematical too
</blockquote></details>

Done.

**Review by AllisonJohn — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3893#-:-O5FzF-lDiey5st4DVod:bnfp4nl)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @nickbianco)

___
*[`OpenSim/Moco/MocoGoal/MocoExpressionBasedParameterGoal.cpp` line 78 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3893#-O5PwbcZEJksDqLDr30E:-O5PwbcZEJksDqLDr30F:b-z1192r) ([raw file](https://github.com/opensim-org/opensim-core/blob/9082f72d13a0b3b073b48b63e867537ffcfbc118/OpenSim/Moco/MocoGoal/MocoExpressionBasedParameterGoal.cpp#L78)):*
> ```cpp
>     } catch (Lepton::Exception& ex) {
>         const std::string msg = ex.what();
>         std::string undefinedVar = msg.substr(32, msg.size() - 32);
> ```

The reason I had the if statement before is that I thought there could be other types of errors that are not for undefined variables? So I think this change could make it seem like there was an undefined variable when there really isn't.

**Review by AllisonJohn — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3893)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @nickbianco)

___
*[`OpenSim/Moco/MocoGoal/MocoExpressionBasedParameterGoal.cpp` line 78 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3893#-O5PwbcZEJksDqLDr30E:-O5PxJDZ4qZhx4QzQ4IT:b-fwudn6) ([raw file](https://github.com/opensim-org/opensim-core/blob/9082f72d13a0b3b073b48b63e867537ffcfbc118/OpenSim/Moco/MocoGoal/MocoExpressionBasedParameterGoal.cpp#L78)):*
<details><summary><i>Previously, AllisonJohn wrote…</i></summary><blockquote>

The reason I had the if statement before is that I thought there could be other types of errors that are not for undefined variables? So I think this change could make it seem like there was an undefined variable when there really isn't.
</blockquote></details>

oops I didn't mean to approve

**Review by nickbianco — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3893)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @AllisonJohn)

___
*[`OpenSim/Moco/MocoGoal/MocoExpressionBasedParameterGoal.cpp` line 78 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3893#-O5PwbcZEJksDqLDr30E:-O5Q4uHX7Ogb6313fkn7:b-hap962) ([raw file](https://github.com/opensim-org/opensim-core/blob/9082f72d13a0b3b073b48b63e867537ffcfbc118/OpenSim/Moco/MocoGoal/MocoExpressionBasedParameterGoal.cpp#L78)):*
<details><summary><i>Previously, AllisonJohn wrote…</i></summary><blockquote>

oops I didn't mean to approve
</blockquote></details>

Ah, good point. I've added it back and also added a similar if-statement to `ExpressionBasedFunction` while I was at it.

**Review by AllisonJohn — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3893)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nickbianco)

**Comment by nickbianco** [comment]
Windows failure is unrelated, merging.

Thanks @AllisonJohn!

**Pull request merged**
