### PR TITLE
Update simbody commit hash to include typo fix (second attempt)

### PR DESCRIPTION
**Pull request by chrisdembia**
I updated the simbody dependency commit hash to incorporate a typo fix.

### CODE REVIEW

**Comment by chrisdembia** [comment]
Thanks @tkuchida

**Comment by chrisdembia** [comment]
This PR also fixes an issue that was causing all Linux travis-ci builds to fail.

**Comment by aymanhab** [comment]
LGTM. I'll merge to fix CI failures even though I don't totally understand the .travis file changes.

**Comment by chrisdembia** [comment]
Thanks @aymanhab . I copied the fix from here: https://github.com/travis-ci/travis-ci/issues/4631

> It's worth mentioning that to get CMake to install from the george-edison precise backports you have to explicitly install cmake-data along with cmake, otherwise apt-get will try to install the wrong version of cmake-data.

**Pull request merged**
