### PR TITLE
[WIP] Updating hopper example for Dev Week

### PR DESCRIPTION
**Pull request by tkuchida**
**In progress…**

Updated hopper example to work with post-hackathon Frame-related changes and to address some of the feedback in #876.

### CODE REVIEW

**Comment by chrisdembia** [comment]
Are you expecting a review yet? Seems difficult to review an XML document like this. I'd say we should just merge it. Also, no need to run CI, as CI skips the sandbox stuff.

**Comment by aymanhab** [comment]
@tkuchida Is this file on the latest format (correctly)? Can you roundtrip save and load it?

**Comment by tkuchida** [comment]
> Are you expecting a review yet?

@chrisdembia: No, I just wanted to create a PR to help me track progress on this branch. My understanding is that PRs with titles prefixed by "[WIP]" and "[DNM]" (do not merge) are works-in-progress and are not open for review. Please let me know if I am mistaken. I can't find a rule about this in [CONTRIBUTING.md](https://github.com/opensim-org/opensim-core/blob/master/CONTRIBUTING.md#making-a-pull-request-pr).

> Also, no need to run CI, as CI skips the sandbox stuff.

@chrisdembia: Sorry, I forgot to skip. I have canceled all builds.

> Is this file on the latest format (correctly)?

@aymanhab: Yes, this model file is now 30506-compliant. On master, the version number in this model file is 30505, but the model does not actually comply with the 30505 standard (frame-related changes that affected serialization were made after the model was created under 30505, but `XMLDocument::LatestVersion` in XMLDocument.cpp remained 30505 and the model file was not updated to the _new_ 30505 standard).

> Can you roundtrip save and load it?

@aymanhab: Loading and re-saving the file has no effect; it is 30506-compliant and does not trigger any `updateFromXMLNode()` code.

**Comment by chrisdembia** [comment]
> Please let me know if I am mistaken.

You're not mistaken; I just wanted to make sure.

**Comment by tkuchida** [comment]
It was decided that the model should be generated programmatically; closing.

**Pull request closed without merging**
