### PR TITLE
[cmake] Fix LIB_DIR for windows.

### PR DESCRIPTION
**Pull request by chrisdembia**
Fixes a part of #738.

@klshrinidhi @sherm1 please review.

### CODE REVIEW

**Comment by sherm1** [comment]
Looks good to me, Chris.

**Comment by klshrinidhi** [comment]
:+1:

**Comment by chrisdembia** [comment]
Thank you.

**Comment by sherm1** [comment]
I tested this change on Windows 8.1 with VS 2015. It correctly found the lib directory. I did not check whether it is still working on Linux and OSX but by eye I think it is fine.

**Pull request merged**
