### PR TITLE
Convert testJoints to catch2

### PR DESCRIPTION
**Pull request by AllisonJohn**
Fixes issue #3555 

### Brief summary of changes
made catch2 test cases from test functions

### Testing I've completed
The 24 tests pass

### CHANGELOG.md (choose one)

- no need to update because... internal

- - -
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3843)

### CODE REVIEW

**Review by nickbianco — CHANGES_REQUESTED** [review]
Looks good overall, just one minor request to put shared variables and functions in an anonymous namespace.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3843#-:-O1SNkTJCFz8HueRilsI:b-kmptor)* status: all files reviewed, 1 unresolved discussion (waiting on @AllisonJohn)

___
*[`OpenSim/Simulation/SimbodyEngine/Test/testJoints.cpp` line 315 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3843#-O1SMN7yB0X7iyNHDtM4:-O1SMN7yB0X7iyNHDtM5:bhyxa9i) ([raw file](https://github.com/opensim-org/opensim-core/blob/b98d4a0ba3d2a293641fdc7c0ccb8c8086fe00e1/OpenSim/Simulation/SimbodyEngine/Test/testJoints.cpp#L315)):*
> ```cpp
> //==========================================================================================================
> 
> void testEquivalentBodyForceForGenForces(Model& model) {
> ```

Similar to the other tests, let's put all shared variables and helper classes/functions in an anonymous namespace so that they're only visible to these tests:

```c++
namespace {
    const static double integ_accuracy = 1.0e-6;
   // rest of the variables here

    class MultidimensionalFunction : public OpenSim::Function {

    // rest of the class here

    };

    void testEquivalentBodyForceForGenForces(Model& model) {

    // rest of the function here

    }
}

```

**Review by nickbianco — COMMENTED** [review]
Edit: one more comment about header formatting.

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3843#-:-O1SWV1WAp4xvOXA_sGf:b-7aasii)* status: all files reviewed, 2 unresolved discussions (waiting on @AllisonJohn)

___
*[`OpenSim/Simulation/SimbodyEngine/Test/testJoints.cpp` line 72 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3843#-O1SWNP9DwkZEMRqZW7m:-O1SWNP9DwkZEMRqZW7n:b-ub18n9) ([raw file](https://github.com/opensim-org/opensim-core/blob/8591740894c964fef812cd31396d316c333b5bd1/OpenSim/Simulation/SimbodyEngine/Test/testJoints.cpp#L72)):*
> ```cpp
> #include <OpenSim/Simulation/SimbodyEngine/WeldJoint.h>
> #include <OpenSim/Simulation/Test/SimulationComponentsForTesting.h>
> ```

nit: Leave any existing header formatting in place. We will standardize this later.

**Review by nickbianco — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3843)* status: all files reviewed, 2 unresolved discussions (waiting on @AllisonJohn)

**Review by nickbianco — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3843#-:-O1SaW63BdOMQhDVQI8A:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @AllisonJohn)

**Review by AllisonJohn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3843)* status: all files reviewed, 1 unresolved discussion (waiting on @nickbianco)

___
*[`OpenSim/Simulation/SimbodyEngine/Test/testJoints.cpp` line 315 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3843#-O1SMN7yB0X7iyNHDtM4:-O1SaaWK7z42Uvu6RTE_:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/b98d4a0ba3d2a293641fdc7c0ccb8c8086fe00e1/OpenSim/Simulation/SimbodyEngine/Test/testJoints.cpp#L315)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Similar to the other tests, let's put all shared variables and helper classes/functions in an anonymous namespace so that they're only visible to these tests:

```c++
namespace {
    const static double integ_accuracy = 1.0e-6;
   // rest of the variables here

    class MultidimensionalFunction : public OpenSim::Function {

    // rest of the class here

    };

    void testEquivalentBodyForceForGenForces(Model& model) {

    // rest of the function here

    }
}

```
</blockquote></details>

Done.

**Pull request merged**
