### PR TITLE
update files with <external_loads_model_kinematics_file> tag

### PR DESCRIPTION
**Pull request by carmichaelong**
Partly fixes issue https://github.com/opensim-org/opensim-gui/issues/1221

### Brief summary of changes
Update opensim-core files that have the <external_loads_model_kinematics_file> tag to a newer file version.

### Testing I've completed
Local testing worked on Windows

### CHANGELOG.md (choose one)
- no need to update because a note about this is in CHANGELOG.md already

---
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2884)

### CODE REVIEW

**Review by aymanhab — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2884)* status: all files reviewed, 3 unresolved discussions (waiting on @carmichaelong)

___
*[Applications/Analyze/test/subject01_Setup_StaticOptimization.xml, line 46 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2884#-MIY4ZNFExunXSZCBQlP:-MIY4ZNFExunXSZCBQlQ:bdtug6s) ([raw file](https://github.com/opensim-org/opensim-core/blob/b51fe1b650992476a01610b481191597e936b7f3/Applications/Analyze/test/subject01_Setup_StaticOptimization.xml#L46)):*
> ```XML
> 		<coordinates_file>subject01_walk1_ik.mot</coordinates_file>
> 		
> 		<lowpass_cutoff_frequency_for_coordinates>-1</lowpass_cutoff_frequency_for_coordinates>
> ```

Was that file saved in latest GUI? should be removed from code if so
___
*[Applications/CMC/test/subject01_externalForces.xml, line 5 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2884#-MIY6_wA-mgQH4eV1D81:-MIY6_wA-mgQH4eV1D82:b494cm) ([raw file](https://github.com/opensim-org/opensim-core/blob/b51fe1b650992476a01610b481191597e936b7f3/Applications/CMC/test/subject01_externalForces.xml#L5)):*
> ```XML
> 	<ExternalLoads name="Ex2">
> 		<defaults>
> 			<Scale>
> ```

If the test runs without these defaults, we should remove the defaults block altogether.
___
*[Applications/RRA/test/subject01_externalForces.xml, line 6 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2884#-MIY7AHMDjiAmRTr3Q9a:-MIY7AHMDjiAmRTr3Q9b:b-fmpce0) ([raw file](https://github.com/opensim-org/opensim-core/blob/b51fe1b650992476a01610b481191597e936b7f3/Applications/RRA/test/subject01_externalForces.xml#L6)):*
> ```XML
> 		<defaults>
> 			<ControlLinear name="default">
> 				<is_model_control>true</is_model_control>
> ```

Again would remove defaults block if unnecessary

**Review by adamkewley — COMMENTED** [review]
I had a quick look through these. It all looks great, thank you @carmichaelong .

Most of my comments are nitpicky stylistic things that you can take or leave. The only one I think is significant is rounding some of the reformatted decimal numbers back to something easier to read (e..g `3.020000000000002 --> 3.02`).

The other comments + questions should be seen more like "i'm trying to understand why this is like this" rather than as serious questions you must address. Maybe I'm pointing something out--at least, how little I know about the internals--and that might prompt you to realize something is wrong (probably not).

As for dropping the external_loads stuff (main focus of this?) and upgrading the files, the only thing I'd keep in mind is how this affects regression testing long-term. Having old files in the test suite might be useful because it might ensure that, as OpenSim moves forward, there's still backwards compatibility with older files (which are likely to be lying around on the internet and people's hard drives longer than executable binaries). Unless this is removing a feature we now no longer support and plan to break.

**Comment by adamkewley** [comment]
Sorry @aymanhab , didn't know you were concurrently looking through this! The review UI in GitHub hidden that info!

**Review by carmichaelong — COMMENTED** [review]
@aymanhab @adamkewley Thanks for the detailed review. I removed some of the unnecessary defaults that were added to some files and made sure tests passed. This cleaned up quite a bit of @adamkewley's comments too. I also tried to respond to some of the curiosity comments from @adamkewley within that (tl;dr I'm also not an expert in the underlying code there yet, but I'm happy to dive into the details or provide context when helpful, so please feel free to keep asking those questions!)

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2884#-:-MIvBpG93bPqMuitEwDh:b-a7toql)* status: 9 of 13 files reviewed, 10 unresolved discussions (waiting on @adamkewley and @aymanhab)

___
*[Applications/Analyze/test/subject01_Setup_StaticOptimization.xml, line 46 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2884#-MIY4ZNFExunXSZCBQlP:-MIv9azhBpmFJST7j4S9:b4bfiw5) ([raw file](https://github.com/opensim-org/opensim-core/blob/b51fe1b650992476a01610b481191597e936b7f3/Applications/Analyze/test/subject01_Setup_StaticOptimization.xml#L46)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

Was that file saved in latest GUI? should be removed from code if so
</blockquote></details>

Yes, saved using OpenSim 4.2-2020-09-02-8bd2ec0. A quick way to reproduce this is open any model, then open Static Optimization tool, and save the setup file. The tag for `lowpass_cutoff_frequency_for_coordinates` appears
___
*[Applications/CMC/test/subject01_externalForces.xml, line 5 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2884#-MIY6_wA-mgQH4eV1D81:-MIv9oyQ8qFvfj1lc_6s:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/b51fe1b650992476a01610b481191597e936b7f3/Applications/CMC/test/subject01_externalForces.xml#L5)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

If the test runs without these defaults, we should remove the defaults block altogether.
</blockquote></details>

Done.
___
*[Applications/CMC/test/subject01_externalForces.xml, line 79 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2884#-MIWRrqRU3bQBfpiinpN-r1-79:-MIv9rkJ5Vm93mNa1kuN:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/b51fe1b650992476a01610b481191597e936b7f3/Applications/CMC/test/subject01_externalForces.xml#L79)):*
<details><summary><i>Previously, adamkewley (Adam Kewley) wrote…</i></summary><blockquote>

`max_control` was in the source (unsure if you did this deliberately - just pointing it out)
</blockquote></details>

Done.
___
*[Applications/CMC/test/subject01_externalForces.xml, line 109 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2884#-MIWRrqRU3bQBfpiinpN-r1-109:-MIv9tR-76CAxt_WPeK5:b-8y4z89) ([raw file](https://github.com/opensim-org/opensim-core/blob/b51fe1b650992476a01610b481191597e936b7f3/Applications/CMC/test/subject01_externalForces.xml#L109)):*
<details><summary><i>Previously, adamkewley (Adam Kewley) wrote…</i></summary><blockquote>

I'm guessing whatever conversion script/process you're using has converted `string` -> `float` -> `string`? Not a big deal, but I'd maybe truncate the numbers back (see other decimals in the diff - similar issue)
</blockquote></details>

Sorry, I think I should have provided a little more detail in how these were converted. I used the GUI to convert all the files. 

One file was inverse dynamics setup file (Applications/Analyze/test/subject01_Setup_InverseDynamics.xml) and one file was a static optimization setup file (Applications/Analyze/test/subject01_Setup_StaticOptimization.xml). These were converted by opening them in the corresponding tools and saving out the setup file, with some minor changes after (e.g., I think the times were changed in one case).

The remaining files were all external loads files, and there's a "Convert files..." option under the Tools dropdown in the GUI that I used to convert the remaining files.

I might be wrong about this, but I believe we've seen files save out with these numbers with OpenSim 4.0+, so this behavior might be more than just behavior with conversion tools.
___
*[Applications/ID/test/subject01_walk1_grf.xml, line 21 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2884#-MIWRrqRU3bQBfpiinpS-r1-21:-MIvAo126mANsp0fJRUL:b-9d8f1z) ([raw file](https://github.com/opensim-org/opensim-core/blob/b51fe1b650992476a01610b481191597e936b7f3/Applications/ID/test/subject01_walk1_grf.xml#L21)):*
<details><summary><i>Previously, adamkewley (Adam Kewley) wrote…</i></summary><blockquote>

This is completely fine. Purely out of curiosity, is this just something you prefer (stylistically) or a side-effect of a script you're using? Again, go with whatever you prefer (keep it - it'll save you an edit).

Over the years of programming, I've encountered a bit of SGML, HTML, and XML - it's interesting to see how the styles change over time (e.g. if it's a script doing this, then the script writer as a preference):

https://www.youtube.com/watch?v=RH0o-QjnwDg
</blockquote></details>

This was done automatically. I actually also prefer `<data_source_name />`, so thanks for catching this!
___
*[Applications/RRA/test/subject01_externalForces.xml, line 6 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2884#-MIY7AHMDjiAmRTr3Q9a:-MIvAykK9pFnSkjKOodU:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/b51fe1b650992476a01610b481191597e936b7f3/Applications/RRA/test/subject01_externalForces.xml#L6)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

Again would remove defaults block if unnecessary
</blockquote></details>

Done.
___
*[Applications/RRA/test/subject01_externalForces.xml, line 22 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2884#-MIWRrqRU3bQBfpiinpT-r1-22:-MIvB0S15hrO5AmfqARM:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/b51fe1b650992476a01610b481191597e936b7f3/Applications/RRA/test/subject01_externalForces.xml#L22)):*
<details><summary><i>Previously, adamkewley (Adam Kewley) wrote…</i></summary><blockquote>

Again, completely fine. I'm guessing OpenSim supports both strings (`Inf` and `infinity`) for parsing an IEE754 infinity? I personally prefer the pre-PR syntax (`infinity`) for its dumb unambiguousness, but I wouldn't bother changing this unless you felt the same.
</blockquote></details>

Done.
___
*[Applications/RRA/test/subject01_externalForces.xml, line 44 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2884#-MIWRrqRU3bQBfpiinpT-r1-44:-MIvB1Aq2W-vavWPVVKs:b-jg73sr) ([raw file](https://github.com/opensim-org/opensim-core/blob/b51fe1b650992476a01610b481191597e936b7f3/Applications/RRA/test/subject01_externalForces.xml#L44)):*
<details><summary><i>Previously, adamkewley (Adam Kewley) wrote…</i></summary><blockquote>

Just so I know, is the reason that `-0` is used here because the direction vector is used in something that might be sensitive to that (e.g. it ends up being piped into complex quaternion arithmetic or something)?
</blockquote></details>

I'm not actually familiar enough with the underlying code as to why exactly these end up having negatives, but you are correct that this is definitely a vector whose numbers do need to indicate positive/negative values
___
*[Applications/RRA/test/subject01_externalForces.xml, line 72 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2884#-MIWRrqRU3bQBfpiinpT-r1-72:-MIvBoAmEsYFPiBJ0I0b:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/b51fe1b650992476a01610b481191597e936b7f3/Applications/RRA/test/subject01_externalForces.xml#L72)):*
<details><summary><i>Previously, adamkewley (Adam Kewley) wrote…</i></summary><blockquote>

The new version is a definite improvement if the implementation's defaulting engine correctly defaults no-name, scaling (`[1, 1, 1]`) etc. 👍 

Again, though, the rotational parts of the `transform` element is using `-0` and (again) I'm guesing this was because the maths may have relied on quarternions to performs the rotations (or something vague like that), or because the old file just had scar tissue 🤷 
</blockquote></details>

Done.
___
*[Applications/RRA/test/subject01_externalForces.xml, line 134 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2884#-MIWRrqRU3bQBfpiinpT-r1-134:-MIvBk2mBt2W5lIRmlnr:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/b51fe1b650992476a01610b481191597e936b7f3/Applications/RRA/test/subject01_externalForces.xml#L134)):*
<details><summary><i>Previously, adamkewley (Adam Kewley) wrote…</i></summary><blockquote>

The whitespace cleanups are very appreciated, this file still has some dangling. Don't bother cleaning them up if you have something better to do - just pointing it out in case you realize later and it causes sleepless nights dreaming about the extra byte every downstream has to load ;)
</blockquote></details>

Done.

**Review by aymanhab — APPROVED** [review]
> Reviewed 3 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2884)* status: 12 of 13 files reviewed, 8 unresolved discussions (waiting on @adamkewley, @aymanhab, and @carmichaelong)

___
*[Applications/Analyze/test/subject01_Setup_StaticOptimization.xml, line 46 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2884#-MIY4ZNFExunXSZCBQlP:-MIwsmiCAdWuyOe_BfuX:b-mj2tnw) ([raw file](https://github.com/opensim-org/opensim-core/blob/b51fe1b650992476a01610b481191597e936b7f3/Applications/Analyze/test/subject01_Setup_StaticOptimization.xml#L46)):*
<details><summary><i>Previously, carmichaelong wrote…</i></summary><blockquote>

Yes, saved using OpenSim 4.2-2020-09-02-8bd2ec0. A quick way to reproduce this is open any model, then open Static Optimization tool, and save the setup file. The tag for `lowpass_cutoff_frequency_for_coordinates` appears
</blockquote></details>

cutoff_frequency_for_coordinates is unrelated , sorry about the confusion

**Review by aymanhab — APPROVED** [review]
LGTM

**Comment by carmichaelong** [comment]
___
*[Applications/Analyze/test/subject01_Setup_StaticOptimization.xml, line 46 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2884#-MIY4ZNFExunXSZCBQlP:-MIyqmdI8ZSDyJbuoeLO:b8pyq0v) ([raw file](https://github.com/opensim-org/opensim-core/blob/b51fe1b650992476a01610b481191597e936b7f3/Applications/Analyze/test/subject01_Setup_StaticOptimization.xml#L46)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

cutoff_frequency_for_coordinates is unrelated , sorry about the confusion
</blockquote></details>

No worries. It used the default value (-1). I could go either way on leaving as is or putting it back in.

**Review by adamkewley — COMMENTED** [review]
> Reviewed 9 of 13 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2884)* status: all files reviewed, 8 unresolved discussions (waiting on @adamkewley and @aymanhab)

**Review by adamkewley — APPROVED** [review]
LGTM, if this is held up on that

**Comment by carmichaelong** [comment]
Thanks @aymanhab and @adamkewley!

**Pull request merged**
