### PR TITLE
Enhance configureOpenSim.m, update CHANGELOG.

### PR DESCRIPTION
**Pull request by chrisdembia**
This PR addresses part of #978, and finishes some enhancements to configureOpenSim.m mentioned in #1044 (also related: #701). Some of these changes were motivated by @aseth1 who reported that the script was not working for him, perhaps because he had previous versions of OpenSim configured with MATLAB.

A primary concern of this PR is that this script will work for users who previously had OpenSim 3.3 configured with MATLAB.

- Mention renaming of buildinfo.txt in changelog (#978).
- Running configureOpenSim now puts @jimmyDunne's utilities on the MATLAB path.
- Remove the need for administrator privileges for users with MATLAB 2012b or later who do not have previous installations of OpenSim.
- Gives verbose messages to help users troubleshoot issues (e.g., if they need administrator privileges).
- No longer adds OpenSim's bin dir to the MATLAB path; this was unnecessary.
- Removed the dependency on the OPENSIM_HOME environment variable, and no longer asks the user for the OpenSim install dir.
- Tell Windows users to update their Windows PATH.
- Handle the situation where users are running MATLAB in a headless mode (e.g., ssh to a cluster), where they would not be able to see msgbox prompts.
- Instead of erasing previous OpenSim installations from classpath.txt, etc., only comment out old entries.

I did extensive testing on macOS and Windows:
- I ensured that previous versions of OpenSim configured with MATLAB are properly commented out.
- I ensured that this script gives proper messages if administrator privileges are needed.
- I ensured the check for 64-bit vs 32-bit still works.
- I ensured that the behavior for pre-2012b MATLAB versions works.

I am confident that the script works as intended.

I did not test on Linux, but I believe the number of people using MATLAB with OpenSim on Linux is fairly small. Since the script works for macOS, it is likely to work on Linux as well.

### CODE REVIEW

**Comment by chrisdembia** [comment]
It would be great if we could merge this. I did extensive testing and we can revisit if users run into issues.

**Comment by chrisdembia** [comment]
@aseth1 I think you mentioned you could test this locally.

**Comment by chrisdembia** [comment]
@apoorvar found an issue with the script; the script uses `strip()` which was introduced in MATLAB 2016b. I will find an alternative function to use.

**Comment by apoorvar** [comment]
In the 'searchForOpenSimString' function, I changed the following (in bold):
    [Cnrows, **~**] = cellfun(@size, C**, 'UniformOutput', false**);
    for i = 1:Cnrows**{1}**
        if isempty(strfind(lower(C{1}{i}), 'opensim')) || ...
                **any(regexpi(C{1}{i}, '^\s*#') == 1)**

My file is attached. It seems to work ok on my version of Matlab (R2015b), but I'm not sure what/if anything was introduced in 2015 and/or was deprecated in later versions.

[configureOpenSim.txt](https://github.com/opensim-org/opensim-core/files/866702/configureOpenSim.txt)

**Comment by chrisdembia** [comment]
Thank you @apoorvar; I have incorporated your changes. 

@tkuchida , I would like the configureOpenSim function to work with 2007b. If I prepare a Windows binary for you, could you test the function? If so, do you have 32-bit or 64-bit MATLAB?

**Comment by tkuchida** [comment]
> I would like the configureOpenSim function to work with 2007b. If I prepare a Windows binary for you, could you test the function?

Sure, but I will need to install 2007b first.

**Comment by chrisdembia** [comment]
Don't install a different MATLAB! Did you say you have 2007a, then?

**Comment by tkuchida** [comment]
Yes, I have _a_ but I can download :bee: if we need it for testing.

**Comment by chrisdembia** [comment]
@tkuchida thank you for troubleshooting this with me. I have decided to go with supporting 2008a and later for now. I was able to obtain MATLAB 2008a for Windows and I was able to successfully use OpenSim bindings, configured using this PR.

We can update the script as necessary.

I think this is ready to be merged; the CI builds do not test the configureOpenSim script and can be ignored.

Suggested reviewers: @tkuchida @aseth1 .

**Comment by chrisdembia** [comment]
Thank you @tkuchida

**Comment by chrisdembia** [comment]
@aseth1 could you review this? The script worked for you, and it also worked with 2008a on Windows. We can make changes in the future if we run into problems.

**Comment by carmichaelong** [comment]
This worked for me with 2014b on a Windows 64-bit build. I agree that we can make more changes in the future and that it's important to get this in for now, so I will go ahead and merge.

**Comment by chrisdembia** [comment]
Wooho!! Thank you @carmichaelong :)

**Pull request merged**
