### PR TITLE
Inverse kinematics solver doxygen update

### PR DESCRIPTION
**Pull request by aseth1**
Render the IK objective and constraint functions as Latex style equations.

### CODE REVIEW

**Comment by chrisdembia** [comment]
The doxygen will be uploaded to http://myosin.sourceforge.net/724 when the travis-ci/pr test is done.

**Comment by chrisdembia** [comment]
I'm happy to merge this b/c it's better than it was, but the equation could still be improved. For example, what's `Wm`?

**Comment by sherm1** [comment]
Equations look beautiful (evaluating just form, not content).

**Comment by aseth1** [comment]
> I'm happy to merge this b/c it's better than it was, but the equation could still be improved. For example, what's Wm?

Good point, I will address that.

**Pull request merged**
