### PR TITLE
Use metis5 to build on apple silicon

### PR DESCRIPTION
**Pull request by aymanhab**
Fixes issue #0

### Brief summary of changes

Use metis 5.1.0 which is apple silicon aware so we can compile the native libraries as well as create conda packages on apple silicon. This branch was used locally to create the arm64 conda packages for opensim 4.5.1

### Testing I've completed
Ran couple moco related scripts that launch moco casadi solver.

### CHANGELOG.md (choose one)
- Will update once we decide to merge

- - -
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3856)

### CODE REVIEW

**Comment by aymanhab** [comment]
@nickbianco would be good to run the profiler on the PR to see if performance is affected. Also this PR doesn't touch the windows branch of the build system since the full ipopt stack is downloaded from the authors directly.

**Comment by nickbianco** [comment]
As discussed, it's not possible to run the benchmarking suite since `main` will not be able to build on Arm64.

**Comment by aymanhab** [comment]
I just uploaded osx-64 conda packages to opensim_admin account. Known issue is that mumps failed to compile as x86 library, I'm investigating.

**Comment by aymanhab** [comment]
All osx-64 packages have been successfully created and uploaded to opensim_admin account (including mumps and tropter). Ready for review.

**Comment by nickbianco** [comment]
@aymanhab, I think you want to change the base branch back to `main` here?

**Comment by aymanhab** [comment]
Thanks  @nickbianco I did convert the PR to merge into main and the changes are now much smaller tho the latest edits to comments that I made based on your review  on the 451 branch maybe lost. We can merge this or alternatively merge the 451 branch to main. The differences are trivial. Your call

**Comment by nickbianco** [comment]
@aymanhab I think merging `opensim_451` to `main` makes the most sense.

**Pull request closed without merging**
