### PR TITLE
Allow for 180 heading correction

### PR DESCRIPTION
**Pull request by aseth1**
Fixes issue #2447, #2455, #2456

### Brief summary of changes
Initial heading correction implementation was assuming that a correction >90 degrees was due to the user inadvertently specifying the negative of the IMU axis (as the heading direction) and so we were doing another 180 degree correction. Of course in reality we do have instances where the pelvis is actually oriented ~180 from the OpenSim +X direction and so the model was being oriented backwards compared to the data.  The fix was to remove that assumption and trust the correct axis is specified as forward (#2447).

If the model is set on the Study, it takes precedence over the model file specified in the properties (#2455).

The output filename is now set to be the input filename prepended with "ik_" without any attempt to shorten, which was causing the output file to no longer be unique (#2456). For every unique input file you will get a similarly unique output file.

### Testing I've completed
Add a test where two calibration poses are known to have their pelvis headings opposite (180 degrees) from one another. The resulting calibrated model should be relatively the same (besides small offsets in IMU registration) and we test both models on a dynamic (hip joint center) trial. The resulting kinematics are compared and passes if the solutions are with 10degrees of each other.

### Looking for feedback on...
- since we are doing tracking twice and comparing solutions I removed the previous tracking "test" that simply ran tracking with no comparison.
- we could add a regression test that is more stringent to flag us if the model kinematics change from the current result

### CHANGELOG.md (choose one)
- no need to update because this is a bug fix

---
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2459)

### CODE REVIEW

**Comment by aseth1** [comment]
@jimmyDunne please give it a whirl!

**Comment by jimmyDunne** [comment]
I tested this and all the changes that were made seem to work great on my machine. The coordinate heading issue is resolved and I testing using multiple, different,  initial calibration headings with equal success. The model setting is great and I can now use setModel() without specifiying a path to a model. Finally, the IK output is now just using a prepended 'IK_'.

**Comment by aymanhab** [comment]
@aseth1 Can you look into the test failures before merging? Thanks

**Comment by aseth1** [comment]
@aymanhab I incorrectly assumed that vector of tolerances limits the number of comparisons (i.e. 23 for the lower extremity) but that isn't the case. The tolerances must be the same size as the number of columns being compared. I made that change to the test.

**Comment by aseth1** [comment]
Thanks @aymanhab and @jimmyDunne !

**Pull request merged**
