### PR TITLE
[travis] Upload doxygen for pull requests.

### PR DESCRIPTION
**Pull request by chrisdembia**

### CODE REVIEW

**Comment by chrisdembia** [comment]
This PR is now ready for review. I can discuss what it does in the dev meeting.

Basically you can now view the doxygen for each PR online. For this PR, the doxygen is at http://myosin.sourceforge.net/629/.

You can get a list of all doxygen pages for our pull requests at http://myosin.sourceforge.net/. I created a sourceforge project "myosin" to host our development PR doxygen there.

**Comment by chrisdembia** [comment]
I'll merge this myself soon.

**Comment by tkuchida** [comment]
The quote "Any sufficiently advanced technology is indistinguishable from magic" comes to mind. This is great :crystal_ball:

**Comment by sherm1** [comment]
Looks great. Ready to merge IMO.

**Comment by chrisdembia** [comment]
Thanks for reviewing; and thanks to @aseth1 for the idea.

**Comment by jenhicks** [comment]
Cool! Thanks Chris.

**Pull request merged**
