### PR TITLE
Fix MocoPathConstraint error for MocoCasADiSolver // update Metis patch

### PR DESCRIPTION
**Pull request by nickbianco**
Fixes issue where MocoCasADiSolver incorrectly accessed the path constraint errors vector when using multiple MocoPathConstraints (no issue, discovered recently).

### Brief summary of changes
- In MocoPathConstraint, calcPathConstraintErrors() now becomes calcPathConstraintErrorsView(), as it accepts the entire path constraint errors vector and creates a view into the portion of that vector belonging to *this* MocoPathConstraint.
- In MocoPathConstraint, calcPathConstraintErrors() now computes the constraint errors for *this* MocoPathConstraint (this is convenient for MocoCasADiSolver, since we create individual functions for each constraints that leads to improved problem sparsity).
- Updated MocoProblemRep::calcPathConstraintErrors() to use MocoPathConstraint::calcPathConstraintErrorsView().
- Updated the patch for Metis to use the COIN-OR tarball as our mirror was causing issues.

### Testing I've completed
- Added a new test that solves a double pendulum problem with multiple MocoPathConstraints.

### CHANGELOG.md (choose one)

- no need to update because...bug fix.
- updated.

---
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2904)

### CODE REVIEW

**Comment by nickbianco** [comment]
The Windows CI build fails for what seems to be an already fixed issue: https://developercommunity.visualstudio.com/content/problem/953628/c-c2100-illegal-indirection-with-stdc-latest-after.html.

**Review by aymanhab — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2904)* status: all files reviewed, 5 unresolved discussions (waiting on @nickbianco)

___
*[.idea/misc.xml, line 6 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/2904#-MNUar-xCgFM11WZw06g:-MNUar-y0-RcEm-8mRZ0:b-bh1r) ([raw file](https://github.com/opensim-org/opensim-core/blob/f8e5e473bee4e885850b77af27f418fa8e290aec/.idea/misc.xml#L6)):*
> ```XML
>     <contentRoot DIR="$PROJECT_DIR$/.." />
>   </component>
>   <component name="CidrRootsConfiguration">
> ```

Should this file be under source control? File paths seem to be referencing specific machine/environment
___
*[dependencies/CMakeLists.txt, line 318 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/2904#-MNUb8g65Hfnc7bhablQ:-MNUb8g65Hfnc7bhablR:bza3ewb) ([raw file](https://github.com/opensim-org/opensim-core/blob/f8e5e473bee4e885850b77af27f418fa8e290aec/dependencies/CMakeLists.txt#L318)):*
> ```CMake
>         # PATCH_COMMAND cd <SOURCE_DIR>/ThirdParty/Metis && patch < ${CMAKE_SOURCE_DIR}/get.Metis.patch
>         #       COMMAND cd <SOURCE_DIR>/ThirdParty/Metis && ./get.Metis
>         ExternalProject_Add(ipopt
> ```

Can we get a high-level description of what's going on with Metis/MUMPS?
___
*[OpenSim/Moco/MocoConstraint.h, line 193 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/2904#-MNUer402soERc252ZaE:-MNUer402soERc252ZaF:b73fau) ([raw file](https://github.com/opensim-org/opensim-core/blob/f8e5e473bee4e885850b77af27f418fa8e290aec/OpenSim/Moco/MocoConstraint.h#L193)):*
> ```objc
> 
>         // This vector shares writable, borrowed space from the *errors* vector
>         // (provided by the MocoProblem) to the elements for which this
> ```

Can you clarify this borrowed space, theseErrors seems like a copy AFAICT
___
*[OpenSim/Moco/Test/testMocoActuators.cpp, line 254 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/2904#-MNUfBmaBgUtslPHuM6y:-MNUfBmaBgUtslPHuM6z:b-f30fdz) ([raw file](https://github.com/opensim-org/opensim-core/blob/f8e5e473bee4e885850b77af27f418fa8e290aec/OpenSim/Moco/Test/testMocoActuators.cpp#L254)):*
> ```cpp
>                 solutionTrajOpt, {{"states", states}, {"controls", controls}});
>         CHECK(error < 0.1);
>     }
> ```

What's the rationale for increasing tolerance?
___
*[Vendors/tropter/tests/test_double_pendulum.cpp, line 420 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/2904#-MNUfS5H7BXMBk1nYldX:-MNUfS5H7BXMBk1nYldY:b-3nxent) ([raw file](https://github.com/opensim-org/opensim-core/blob/f8e5e473bee4e885850b77af27f418fa8e290aec/Vendors/tropter/tests/test_double_pendulum.cpp#L420)):*
> ```cpp
>         OCPDerivativesComparison<DoublePendulumCoordinateTracking> c;
>         c.num_mesh_intervals = 10;
>         c.findiff_hessian_step_size = 1e-5;
> ```

Why was this added now? Default?

**Review by nickbianco — COMMENTED** [review]
The Windows runner was updated to use Visual Studio version 16.8 (from version 16.7) recently: https://github.com/actions/virtual-environments/releases. Unfortunately, I don't think there's a way to revert to 16.7 without a self-hosted Windows runner

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2904#-:-MNVBqGh769OtKOzj-6S:b-4a1pd5)* status: all files reviewed, 5 unresolved discussions (waiting on @nickbianco)

**Review by nickbianco — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2904)* status: 5 of 9 files reviewed, 5 unresolved discussions (waiting on @aymanhab and @nickbianco)

___
*[.idea/misc.xml, line 6 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/2904#-MNUar-xCgFM11WZw06g:-MN_03Tc-lMngRtD1UqB:b12tx47) ([raw file](https://github.com/opensim-org/opensim-core/blob/f8e5e473bee4e885850b77af27f418fa8e290aec/.idea/misc.xml#L6)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

Should this file be under source control? File paths seem to be referencing specific machine/environment
</blockquote></details>

I've removed the file from source control.
___
*[dependencies/CMakeLists.txt, line 318 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/2904#-MNUb8g65Hfnc7bhablQ:-MN_08ClEoD6UOrUMnUM:b-491n1s) ([raw file](https://github.com/opensim-org/opensim-core/blob/f8e5e473bee4e885850b77af27f418fa8e290aec/dependencies/CMakeLists.txt#L318)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

Can we get a high-level description of what's going on with Metis/MUMPS?
</blockquote></details>

Turns out the original changes I made didn't work (and weren't even necessary). I just need to add flag to clang to not treat certain warnings as errors=
___
*[OpenSim/Moco/Test/testMocoActuators.cpp, line 254 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/2904#-MNUfBmaBgUtslPHuM6y:-MN_0dvp09cDY6qDWr07:bd6vnpa) ([raw file](https://github.com/opensim-org/opensim-core/blob/f8e5e473bee4e885850b77af27f418fa8e290aec/OpenSim/Moco/Test/testMocoActuators.cpp#L254)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

What's the rationale for increasing tolerance?
</blockquote></details>

This test was barely failing (~0.055). The CMC controls are a little noisy anyway, so I loosened the tolerance slightly.
___
*[Vendors/tropter/tests/test_double_pendulum.cpp, line 420 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/2904#-MNUfS5H7BXMBk1nYldX:-MN_0OuWBAjWHx6gEXzR:bq54sh0) ([raw file](https://github.com/opensim-org/opensim-core/blob/f8e5e473bee4e885850b77af27f418fa8e290aec/Vendors/tropter/tests/test_double_pendulum.cpp#L420)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

Why was this added now? Default?
</blockquote></details>

This derivative check was barely failing. I'm removing this change and rerunning CI again to see if the issue persists (I have no issues locally).

**Review by nickbianco — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2904)* status: 5 of 9 files reviewed, 5 unresolved discussions (waiting on @aymanhab)

___
*[OpenSim/Moco/MocoConstraint.h, line 193 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/2904#-MNUer402soERc252ZaE:-MN_3ZzVDAql2PgbVw8p:b-o0655p) ([raw file](https://github.com/opensim-org/opensim-core/blob/f8e5e473bee4e885850b77af27f418fa8e290aec/OpenSim/Moco/MocoConstraint.h#L193)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

Can you clarify this borrowed space, theseErrors seems like a copy AFAICT
</blockquote></details>

It is not a copy. Any changes to the values of theseErrors will change the values of errors (hence "shares"). If you're wondering, the boolean argument is just there to avoid method overload conflicts in Simbody.

**Review by aymanhab — APPROVED** [review]
> Reviewed 5 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2904)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nickbianco)

**Review by aymanhab — APPROVED** [review]
:lgtm: Thanks @nickbianco 

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2904#-:-MNen1FH2Sn10_uk6zDC:b-wk1sl7)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nickbianco)

**Comment by nickbianco** [comment]
Thanks @aymanhab. Merging this, we'll fix the Windows CI stuff on the feature branch.

**Pull request merged**
