### PR TITLE
Add locale requirements to linux build script

### PR DESCRIPTION
**Pull request by ksomml**
Fixes issue https://github.com/opensim-org/opensim-core/issues/3924

### Brief summary of changes

Added locale changes into the build script so numeric formatting is correct when using TimeSeriesTable.h

### Testing I've completed

Tested locally with a separate shell script. A restart after locale changes is recommended if locale changes have been applied due to different settings instead of directly using OpenSim after installation.

### Looking for feedback on...

/

### CHANGELOG.md (choose one)

- no need to update because the change only affects the build script

- - -
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3934)

### CODE REVIEW

**Comment by halleysfifthinc** [comment]
I don't think this is the best long-term solution. This PR just masks the locale problem; anyone who installs a pre-built linux artifact on a system with a comma decimal locale will still encounter this issue because the locale change here is system specific/dependent and isn't fixing the root cause.

**Comment by ksomml** [comment]
That is true, mainly wanted to get attention to this issue. I do not know how to fix the issue at its root cause.

**Comment by alexbeattie42** [comment]
There are a few problems with this change:


1. Installing opensim should not override the system locale settings to `en_US.UTF-8`. This would create a very unexpected problem for everyone who does not use `en_US.UTF-8` (ex. people who are not in the United States). 
3. Executing arbitrary Sudo system configuration specific commands in a build script should be avoided. If it can't the user should be well aware of what it is doing.

**Comment by ksomml** [comment]
Then I believe this pull request can be closed, though the issue https://github.com/opensim-org/opensim-core/issues/3924 will still remain. I might take a look to see if i could fix it, but I believe someone more experienced is more likely to find the root cause of this.

**Comment by aymanhab** [comment]
Agreed that build scripts shouldn't make global changes to either Locale or Path in order to avoid unintended side-effects, so closing the PR but thanks for bringing the issue to the forefront @ksomml and for the feedback @alexbeattie42 and @halleysfifthinc

**Pull request closed without merging**
