### PR TITLE
[appveyor] TreatWarningsAsErrors

### PR DESCRIPTION
**Pull request by chrisdembia**
This change should cause warnings on appveyor to be treated as errors, so they don't go unnoticed.

The Travis build failed b/c I cancelled it.

### CODE REVIEW

**Comment by sherm1** [comment]
GitHub says this branch has conflicts.

**Comment by chrisdembia** [comment]
I resolved the conflict.

**Comment by sherm1** [comment]
build failures?

**Comment by chrisdembia** [comment]
The build failures are unrelated.

**Comment by chrisdembia** [comment]
Thank you.

**Pull request merged**
