### PR TITLE
Cleanup cmake for examples, and other misc cmake cleanup

### PR DESCRIPTION
**Pull request by chrisdembia**
I have cleaned up the cmake used for example files, using the OpenSimConfig.cmake file.

On Ubuntu, I made sure the examples installation all compile and execute without errors (for ones with an executable). I have not tested that on windows.

### CODE REVIEW

**Comment by aseth1** [comment]
@jimmyDunne have you had a chance to try the cleaned-up CMakeLists? Feel free to merge if you have.

**Comment by jimmyDunne** [comment]
Sorry everyone, I didnt see my name tagged inthis until now. I will test this week on my two systems and merge if works. Sorry again

**Comment by jimmyDunne** [comment]
@aseth1 @chrisdembia 

I built (release) and ran tests without error

**Comment by chrisdembia** [comment]
Thanks @jimmyDunne.

**Pull request merged**
