### PR TITLE
testForward and testScale were not linking SimTK libs in debug. ...

### PR DESCRIPTION
**Pull request by aseth1**
Added SimTK libs to CMakeLists.txt.

### CODE REVIEW

**Comment by chrisdembia** [comment]
My fault... I think I had removed those. My understanding was that since the other libraries depended on SimTK libraries that we didn't need to link to SimTK libraries explicitly.

Looks good.

**Comment by sherm1** [comment]
Looks harmless, but it makes me wonder why it works in Release but not in Debug -- in Release it wasn't listing the Simbody libs explicitly either.

**Comment by chrisdembia** [comment]
> but it makes me wonder why it works in Release but not in Debug -- in Release it wasn't listing the Simbody libs explicitly either.

I created an issue to look into this.

**Comment by aymanhab** [comment]
Could very well be some of those simtk asserts, or errchk macros that
expand to nothing in release but require the libraries in debug.

**Pull request merged**
