### PR TITLE
Small updates to the Custom Static Optimization lab

### PR DESCRIPTION
**Pull request by nickbianco**
Fixes issue #3430

### Brief summary of changes
Updated the `CustomStaticOptimization` scripting example for this spring's ME/BIOE 485 class at Stanford. Updates include:
- Provide the commands to disable muscle dynamics, to avoid confusion.
- Provide the code for setting the coordinate values and add a comment to lead the students to fill in the code for setting the coordinate  speeds.

### Testing I've completed
None yet.

### Looking for feedback on...
Anything that might improve the lab for the class.

### CHANGELOG.md (choose one)

- no need to update because...small update to the scripting example

- - -
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3436)

### CODE REVIEW

**Comment by nickbianco** [comment]
@nicos1993, I couldn't select you as a reviewer, but feel free to leave any feedback you'd like here.

**Comment by nicos1993** [comment]
@nickbianco will take a look now!

**Comment by nicos1993** [comment]
Looks good to me, both changes.

**Review by carmichaelong — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3436)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nickbianco)

**Pull request merged**
