### PR TITLE
Building OpenSim in less than a minute with unity build

### PR DESCRIPTION
**Pull request by mitkof6**
I tested building OpenSim using unity build. The libraries folder builds within 30s on my computer. There is a cmake function that can generate a single compilation unit containing all cpp files per library. I have added this option in the main cmake file so you can choose to build with unity build or without. Also, I have changed OpenSimAddLibrary function. Because all cpp files are included into a single cpp file, there were redefinition and ambiguous issues, which I tried to correct. It is possible to further speed up the compilation if we add all test*.cpp files into a single compilation unit, but I am not sure if there is a why to bypass multiple redefinition of the main function.

### CODE REVIEW

**Comment by mitkof6** [comment]
@chrisdembia Regarding #682 I have uploaded a working version using unity builds. The compile time is very good! For some reason, the checks failed.

**Comment by chrisdembia** [comment]
The checks fail because of the BTK dependency. Did you try building with BTK locally? BTK uses Eigen, and that conflicts with SimTK's Eigen.

**Comment by chrisdembia** [comment]
A build time of 30 seconds is very impressive. Thanks for trying this; I'm surprised it worked! I think we'll have to discuss if supporting unity builds is desirable. One of the tradeoffs is that it means we cannot use `using` declarations as much in cpp files.

As for tests, I don't think there is a need to make a unity build for the tests; it's best to have those all as separate executables so they can be run individually.

**Comment by mitkof6** [comment]
> The checks fail because of the BTK dependency. Did you try building with BTK locally? BTK uses Eigen, and that conflicts with SimTK's Eigen.

Yes I tried building with dependencies and it worked for me. 

> One of the tradeoffs is that it means we cannot use using declarations as much in cpp files.

From the changes that I made, it seems that there are only some classes that are in conflict, so if we rename or use OpenSim:: it will not be a problem.

**Comment by chrisdembia** [comment]
Even if you build the dependencies (that is, BTK, using @klshrinidhi's superbuild), I think you must set the CMake variable `WITH_BTK` to ON to use BTK with OpenSim. Did you do that too?

**Comment by mitkof6** [comment]
I built superbuild, but I didn't build with btk. I will check.

**Comment by chrisdembia** [comment]
@mitkof6 before working on this any further, it might be good to wait until some of us can discuss in our next development meeting if we would like unity builds.

**Comment by mitkof6** [comment]
@chrisdembia it seems that the only "problematic" file is C3DFileAdapter.cpp when building btk + unity build.

> before working on this any further, it might be good to wait until some of us can discuss in our next development meeting if we would like unity builds.

Just some comments:
1) There is also a problem when we change a single .cpp, the whole library will have to build again. To bypass this we can have an extra flag that will build some libraries with unity build, and other without (the current working).

2) It is possible to have a workaround solution when we have building  problems, like the case with C3D. We can have an exclude list which will not add some .cpp files (these will be built normally).

**Comment by mitkof6** [comment]
@chrisdembia I have added support to exclude sources from unity build that may be in conflict when added in a single .cpp. I intended to do it for my projects, so I commuted in case you decide to use unity builds. Tests pass, the speedup is good, but most of the time is spent in building and testing the tests. I would suggest to specify build type Release for travis and appveyor. This could help if you want the checks to finish as fast as possible.

**Comment by chrisdembia** [comment]
Thank you. We use the same optimization level (O2) for both Release and RelWithDebInfo; do you think there would still be a difference in the speed of the tests? @sherm1 found that O3 was only 2% faster than O2, which is why we changed Release to use O2. We also found that with MSVC, the time to compile as 32-bit is *much* shorter than for 64-bit. @sherm1 said he thinks the two compilers are different, so maybe the 32-bit one has been more optimized.

**Comment by klshrinidhi** [comment]
@mitkof6 
We still haven't decided if we want to have unity build facility in OpenSim. We are yet to meet and go over the pros and cons of unity build in terms of usability and maintainability long-term because this is a major change. We are hesitant because we have not seen big C/C++ projects adopt this technique. My advice would be to hold off working on this until we have a decision.

**Comment by mitkof6** [comment]
>do you think there would still be a difference in the speed of the tests?

I tested with travis, but no major improvement. It may depend on the underlying resource that are employed for testing. Proper measurements should be carried on the same machine both for Windows and Linux.  

>My advice would be to hold off working on this until we have a decision. 

Ok.

**Comment by chrisdembia** [comment]
@mitkof6 we discussed this PR recently, and we decided to not merge it. Some of the reasons were that we still would not feel comfortable using unity builds for continuous integration or distribution, and that it requires programmers to account for unnecessary constraints when writing their cpp files. Thanks for submitting the PR. We definitely want to improve build time, and we are definitely interested in other PRs that may improve build time (for example, using http://include-what-you-use.org/).

**Comment by mitkof6** [comment]
> Some of the reasons were that we still would not feel comfortable using unity builds for continuous integration or distribution, and that it requires programmers to account for unnecessary constraints when writing their cpp files.

Sure, a fair reason. If I stumble upon anything useful I will let you know.

**Pull request closed without merging**
