### PR TITLE
Fix doxygen 43

### PR DESCRIPTION
**Pull request by aymanhab**
Fixes issue #0

### Brief summary of changes
Include Tropter, minor fixes to avoid doxygen errors/warnings on newly added MocoGoals
### Testing I've completed
Created Doxygen
### CHANGELOG.md (choose one)

- no need to update because internal

---
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3037)

### CODE REVIEW

**Comment by aymanhab** [comment]
@nickbianco For your review.

**Comment by aymanhab** [comment]
@carmichaelong you can review this as all the changes are safe, doxygen related. I can produce doxygen and send separately if needed, main material change is that Tropter is now documented in Doxygen.

**Comment by carmichaelong** [comment]
@aymanhab Sure, would you be willing to send over Doxygen? That would be very helpful for me so I don't have to switch branch and generate it too.

**Comment by aymanhab** [comment]
Here's a link 
https://drive.google.com/file/d/1SPb54ydtfiHgf40znudG89HvjQKp7Jvs/view?usp=sharing

**Review by carmichaelong — APPROVED** [review]
LGTM. Checked that some Tropter related classes and functions now appear that don't show up in the 4.2 doxygen

**Comment by aymanhab** [comment]
Thanks @carmichaelong 👍

**Pull request merged**
