### PR TITLE
Visualization utils

### PR DESCRIPTION
**Pull request by aymanhab**
Fixes issue #2717 

### Brief summary of changes
Moved an incarnation of Moco method to SimulationUtilities, renamed method to visualizeModelMotion to be specific in anticipation of additional methods. 
 
### Looking for feedback on...
Naming, 
I also plan to move visualization of data to DataVisualizer class for mocap and imu data. All will be accessible through extension of opensim-cmd
### CHANGELOG.md (choose one)

- no need to update because...
- updated...

The Doxygen for this PR can be viewed at http://myosin.sourceforge.net/?C=N;O=D; click the folder whose name is this PR's number.

---
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2722)

### CODE REVIEW

**Comment by aymanhab** [comment]
@chrisdembia @carmichaelong @nickbianco thoughts on the naming and plan in description

**Comment by chrisdembia** [comment]
Fantastic! What additional methods do you anticipate? This could help us give feedback on naming. Perhaps we can discuss in today's standup meeting.

**Comment by aymanhab** [comment]
Definitely would be good to discuss in meeting. As of now we have a separate utility program to visualizeModel, this could be moved there and the utility can be removed altogether.

**Comment by aymanhab** [comment]
@chrisdembia Also found another incarnation of the method that takes TimeSeriesTable, which signature did you find more convenient/used in Moco?

**Comment by chrisdembia** [comment]
> @chrisdembia Also found another incarnation of the method that takes TimeSeriesTable, which signature did you find more convenient/used in Moco?

We use both.

**Comment by aseth1** [comment]
@aymanhab @chrisdembia it would be great if there was a proposal to visualize "Experimental" data (using representative components) with a Model that is being simulated. For example, how would one use the `DataVisualizer` (I would call it DataPreviewer) with the IKSolver to visualize IK motion with both model (with its Markers) AND  `ExperimentalMarker's? It would also be great to run a forward simulation and visualize external forces applied to the feet or hands. If we can visualize model(s) and experimental data together, then previewing becomes trivial since that is just the case where there is no model.

**Comment by chrisdembia** [comment]
Is this still a work in progress?

**Comment by aymanhab** [comment]
@chrisdembia i wanted to move the methods into DataVisualizer class (to parallel ModelVisualizer) rather than in global namespace. As of now this is just a refactoring of existing code, we can get this reviewed and merged before introducing new functionality.

**Comment by aymanhab** [comment]
This document summarizes the status and naming issues we discussed
https://docs.google.com/document/d/104b6NpkI7c9DwiYzuDKArkmd6g8gSu-XlMi3R6eVmNU/edit?usp=sharing

**Comment by aymanhab** [comment]
Ready for review, particularly feedback on method names, before adding new functionality. Thanks @chrisdembia @nickbianco @carmichaelong for the feedback on this PR and earlier on the proposal.

**Comment by aymanhab** [comment]
Thanks @chrisdembia

**Pull request merged**
