### PR TITLE
Update continuous_integration.yml

### PR DESCRIPTION
**Pull request by aymanhab**
try build without cache on windows2022

Fixes issue #<issue_number>

### CHANGELOG.md (choose one)

- no need to update because...
- updated.

- - -
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3800)

### CODE REVIEW

**Comment by nickbianco** [comment]
This change makes me realize we never re-enabled building Tropter in the CI. We should do that before releasing 4.5.1.

**Comment by nickbianco** [comment]
I spent a few minutes combing through the Windows2022 CI build to see why the Java tests are failing. I found a handful of warnings like this:

```
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(254,5): warning MSB8064: Custom build for item "D:\a\opensim-core\opensim-core\build\CMakeFiles\135376c083fa22587c7525f5ca96e9f6\java_moco.cxx.rule" succeeded, but specified dependency "d:\a\opensim-core\opensim-core\build\bindings\java\opensimjni\" does not exist. This may cause incremental build to work incorrectly. [D:\a\opensim-core\opensim-core\build\Bindings\Java\OpenSimJNI\osimJavaJNI.vcxproj]
```

Not sure what to make of it yet though.

**Comment by aymanhab** [comment]
Some more investigation:
1. Same warnings appear in windows2019 build that succeeds
2. Last successful 2022 build was using the old runner image before migration to 202406XX versions.
3. I suspect this has to do with the runtime conflict that was introduced, trying some workarounds

**Comment by nickbianco** [comment]
@aymanhab close?

**Pull request closed without merging**
