### PR TITLE
Fix bugs in hopper example

### PR DESCRIPTION
**Pull request by tkuchida**
Minor bug fixes originally included in #1214.

### CODE REVIEW

**Comment by klshrinidhi** [comment]
Maybe this should wait until #1233 is merged (or not).

**Comment by klshrinidhi** [comment]
Maybe this should wait until #1233 is merged (or not).

**Comment by chrisdembia** [comment]
Yes I think this should wait for #1233. I am reviewing #1233 now.

**Comment by chrisdembia** [comment]
Yes I think this should wait for #1233. I am reviewing #1233 now.

**Comment by tkuchida** [comment]
Merged master; all that remains are trivial changes.

**Comment by klshrinidhi** [comment]
:+1:

**Pull request merged**
