### PR TITLE
WIP: Review readme

### PR DESCRIPTION
**Pull request by AlbertoCasasOrtiz**
Fixes issue #3178

Link to the new README.md file: https://github.com/opensim-org/opensim-core/blob/review_readme/README.md

### Brief summary of changes

 - Added **OpenSim logo**.
 - Added new **auto-updated badges** at the top and in the headers of some sections.
   - **Badges added**: last release, license, platforms supported, and contributors.
 - **Clicking on a badge** takes you to specific sites (e.g., clicking on the last release badge takes you to the releases page).
 - Updated **blurry ZenHub badge**.
 - **Media formatted** using HTML.
 - Added **documentation section** pointing to confluence webpages and GitHub wiki pages.
 - Added **releases section**, pointing to releases and indicating the latest release.
 - Build instructions now point to **new build instructions** in GitHub wiki pages.
 - Added **contribute section**, describing how new users can contribute and collaborate, and linking to the Developer's guidelines and thecode of conduct.
 - Added **license section** pointing to the full license, acknowledgments (third-party licenses) and Notice.
 - Added a subsection in license with information on **how to acknowledge OpenSim**.

### Testing I've completed

 - Used Grammarly to detect typos.
 - Checked that every link is working properly.

### Looking for feedback on...

 - Review the texts to detect and correct typos, better explain everything, detect broken links... etc.
 - Sections and/or information that should be added/removed to the readme.md file.

### CHANGELOG.md (choose one)

- no need to update because this is a change in the readme.

- - -
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3313)

### CODE REVIEW

**Review by carmichaelong — CHANGES_REQUESTED** [review]
Thanks for the quick first pass through after our chat. I've added a few more minor comments throughout

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3313#-:-NGJhgFR6--9bHOIpT3Z:b-syv4o)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @AlbertoCasasOrtiz)

___
*[`README.md` line 4 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3313#-NGJf4GHART7skIHAfHl:-NGJf4GHART7skIHAfHm:bjfrwwz) ([raw file](https://github.com/opensim-org/opensim-core/blob/3db06f0ff5620c5ef76936432a1f2351b5017590/README.md#L4)):*
> ```Markdown
> <p align=center>
>     <a href="https://opensim.stanford.edu/">
>         OpenSim Logo
> ```

This OpenSim logo seems to have a transparent background, rather than white. This makes it tough to see when the website is in dark mode. Could make a logo that has a white background instead.
___
*[`README.md` line 62 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3313#-NGJfaSC6vgFUHhpzI7O:-NGJfaSC6vgFUHhpzI7P:b9qy1fa) ([raw file](https://github.com/opensim-org/opensim-core/blob/3db06f0ff5620c5ef76936432a1f2351b5017590/README.md#L62)):*
> ```Markdown
>   - [Download page](https://simtk.org/frs/?group_id=91)
>   - [Scripting in the GUI](https://simtk-confluence.stanford.edu:8443/display/OpenSim/Scripting+in+the+GUI)
> - **Scripting**
> ```

Consider something like "MATLAB and Python Scripting" instead
___
*[`README.md` line 63 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3313#-NGJfii3CxZtjWOHUqnI:-NGJfii3CxZtjWOHUqnJ:b-8ontng) ([raw file](https://github.com/opensim-org/opensim-core/blob/3db06f0ff5620c5ef76936432a1f2351b5017590/README.md#L63)):*
> ```Markdown
>   - [Scripting in the GUI](https://simtk-confluence.stanford.edu:8443/display/OpenSim/Scripting+in+the+GUI)
> - **Scripting**
>   - [Build Instructions](https://github.com/opensim-org/opensim-core/wiki/Build-Instructions)
> ```

Maybe remove the "Build Instructions" line here? Since most MATLAB and Python users won't be looking to build C++ libraries. Happy to discuss further too
___
*[`README.md` line 66 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3313#-NGJg8qUDgd4HftxonlO:-NGJg8qUDgd4HftxonlP:bmqhuxt) ([raw file](https://github.com/opensim-org/opensim-core/blob/3db06f0ff5620c5ef76936432a1f2351b5017590/README.md#L66)):*
> ```Markdown
>   - [Setup Instructions](https://simtk-confluence.stanford.edu:8443/display/OpenSim/Scripting)
> - **C++ Development**
>   - [Build Instructions](https://github.com/opensim-org/opensim-core/wiki/Build-Instructions)
> ```

A few more words here could mean we can remove the "Build instructions" section below since it's the same link. For instance, perhaps:

`[Build Instructions](https://github.com/opensim-org/opensim-core/wiki/Build-Instructions) for Windows, macOS, and Linux (Ubuntu and Debian)`

AND/OR

Use the badge that you have below that show the platforms
___
*[`README.md` line 69 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3313#-NGJfueZBs1eWLvS4T-C:-NGJfueZBs1eWLvS4T-D:blef00f) ([raw file](https://github.com/opensim-org/opensim-core/blob/3db06f0ff5620c5ef76936432a1f2351b5017590/README.md#L69)):*
> ```Markdown
>   - [Developer's Guide](https://simtk-confluence.stanford.edu:8443/display/OpenSim/Developer%27s+Guide)
>   - [API Reference](https://simtk.org/api_docs/opensim/api_docs)
> - **Looking for help?**
> ```

Nice addition to add "Looking for Help" here. This is repeated a little bit below too in the "Contribute" section, but I think that's OK
___
*[`README.md` line 86 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3313#-NGJgfHcCqDE2n3Qyxmm:-NGJgfHcCqDE2n3Qyxmn:b-g0lm44) ([raw file](https://github.com/opensim-org/opensim-core/blob/3db06f0ff5620c5ef76936432a1f2351b5017590/README.md#L86)):*
> ```Markdown
> This repository contains releases for OpenSim 4.x. You can find all of the OpenSim's releases in the [Releases](https://github.com/opensim-org/opensim-core/releases) page of this repository.
> 
> ## Build instructions [platforms](https://github.com/opensim-org/opensim-core/wiki/Build-Instructions)
> ```

See comments above in the Download and Setup -> C++ Development section that could allow us to remove this section.

**Review by AlbertoCasasOrtiz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3313)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @carmichaelong)

___
*[`README.md` line 62 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3313#-NGJfaSC6vgFUHhpzI7O:-NGNhIdC44LU05vSwzYv:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/3db06f0ff5620c5ef76936432a1f2351b5017590/README.md#L62)):*
<details><summary><i>Previously, carmichaelong wrote…</i></summary><blockquote>

Consider something like "MATLAB and Python Scripting" instead
</blockquote></details>

Done.
___
*[`README.md` line 66 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3313#-NGJg8qUDgd4HftxonlO:-NGNhWAn0poFblpYhozg:b-6ps1ij) ([raw file](https://github.com/opensim-org/opensim-core/blob/3db06f0ff5620c5ef76936432a1f2351b5017590/README.md#L66)):*
<details><summary><i>Previously, carmichaelong wrote…</i></summary><blockquote>

A few more words here could mean we can remove the "Build instructions" section below since it's the same link. For instance, perhaps:

`[Build Instructions](https://github.com/opensim-org/opensim-core/wiki/Build-Instructions) for Windows, macOS, and Linux (Ubuntu and Debian)`

AND/OR

Use the badge that you have below that show the platforms
</blockquote></details>

I like the idea of adding the platforms here or a badge. I think we should keep the "Build Instructions" section since some users (including me) look directly for it when they arrive to a repository.

**Review by AlbertoCasasOrtiz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3313)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @carmichaelong)

___
*[`README.md` line 69 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3313#-NGJfueZBs1eWLvS4T-C:-NGNiPSXB5ZuJdtoDxYW:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/3db06f0ff5620c5ef76936432a1f2351b5017590/README.md#L69)):*
<details><summary><i>Previously, carmichaelong wrote…</i></summary><blockquote>

Nice addition to add "Looking for Help" here. This is repeated a little bit below too in the "Contribute" section, but I think that's OK
</blockquote></details>

Done.

**Review by AlbertoCasasOrtiz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3313)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @carmichaelong)

___
*[`README.md` line 63 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3313#-NGJfii3CxZtjWOHUqnI:-NGNiRSHDS12Cnggk9FI:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/3db06f0ff5620c5ef76936432a1f2351b5017590/README.md#L63)):*
<details><summary><i>Previously, carmichaelong wrote…</i></summary><blockquote>

Maybe remove the "Build Instructions" line here? Since most MATLAB and Python users won't be looking to build C++ libraries. Happy to discuss further too
</blockquote></details>

Done.

**Review by AlbertoCasasOrtiz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3313)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @carmichaelong)

___
*[`README.md` line 4 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3313#-NGJf4GHART7skIHAfHl:-NGNnLea0dtTiIQO4I3-:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/3db06f0ff5620c5ef76936432a1f2351b5017590/README.md#L4)):*
<details><summary><i>Previously, carmichaelong wrote…</i></summary><blockquote>

This OpenSim logo seems to have a transparent background, rather than white. This makes it tough to see when the website is in dark mode. Could make a logo that has a white background instead.
</blockquote></details>

Done.

**Review by aymanhab — CHANGES_REQUESTED** [review]
Looks good, much cleaner. Minor suggestions to address.

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3313#-:-NGOF2jd0OJ2ExowB6a3:b-rmpy2c)* status: all files reviewed, 2 unresolved discussions (waiting on @AlbertoCasasOrtiz and @carmichaelong)

___
*[`README.md` line 51 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3313#-NGOEYBa4oqlnJ0InXtS:-NGOEYBa4oqlnJ0InXtT:b-n8iyxt) ([raw file](https://github.com/opensim-org/opensim-core/blob/c5b53677ec443ce158e1eb691b291681aca945eb/README.md#L51)):*
> ```Markdown
>  - OpenSim's command-line applications (inverse kinematics, computed muscle control, etc.).
>  - OpenSim's Java and Python wrapping.
>  
> ```

Replace Wrapping with Bindings, also may need to mention Conda package to promote use-case for developers using conda

**Review by AlbertoCasasOrtiz — COMMENTED** [review]
Thanks to both of you. I have addressed all of the issues and comments. Please let me know if I should change something else.

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3313#-:-NGrI4K0EnMPnvWrctDz:b-uk7kjg)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @aymanhab and @carmichaelong)

**Review by AlbertoCasasOrtiz — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3313#-:-NGrIPCu3MLKrKPY4yvz:bnfp4nl)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @aymanhab and @carmichaelong)

**Review by carmichaelong — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3313#-:-NGrIcwp8FpttL4wC7JC:bnfp4nl)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @aymanhab)

**Review by aymanhab — APPROVED** [review]
LGTM, thanks @albertocasasortiz  I'd just remove the port number for confluence (remove :8443 from simtk-confluence urls) as it is now automatically redirected. On the forum we intentionally remove the port number when we post links to keep the port number internal. After that please feel free to merge.

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3313#-:-NGrPpNLC8GEGo4-_BUl:b-2qqdv9)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @AlbertoCasasOrtiz)

**Review by AlbertoCasasOrtiz — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3313#-:-NGr_xgQ7CB7WG-mt9o4:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @aymanhab)

**Pull request merged**
