### PR TITLE
Update to latest CasADi interface for specifying Jacobian sparsity

### PR DESCRIPTION
**Pull request by nickbianco**
Fixes issue #3801

### Brief summary of changes
Updates Moco's CasADi-based optimal control library to use the most recent interface for specifying Jacobian sparsity. Previously, CasADi functions expected `get_jacobian_sparsity()` to return the full sparsity pattern for the function. Now, the interface requires implementing `get_jac_sparsity(casadi_int oind, casadi_int iind, bool symmetric)` which should return the sparsity for a given output index (`oind`) and input index (`iind`); we ignore the `symmetric` flag.

This PR also updates the CasADi version to 3.6.5, now that we use the latest Jacobian sparsity interface.

### Testing I've completed
Checked that `exampleMocoInverse` produced the same number of non-zero elements in the Jacobian as in CasADi 3.5.5. 

### CHANGELOG.md (choose one)

- updated.

[perf-win]

- - -
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3807)

### CODE REVIEW

**Review by aymanhab — CHANGES_REQUESTED** [review]
Requested a minor comment for future maintenance, otherwise LGTM. Would it make sense to add a test case that checks/bounds the number of 0s or some other measure of sparsity as you expertly observed so that we can catch future changes easily?

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3807#-:-O-7Dr9mCr45gLV-fC22:b5ry997)* status: all files reviewed, 1 unresolved discussion (waiting on @nickbianco)

___
*[`OpenSim/Moco/MocoCasADiSolver/CasOCFunction.cpp` line 223 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3807#-O-7D_U05uUDvF44Kxsy:-O-7D_U05uUDvF44Kxsz:b2dsacl) ([raw file](https://github.com/opensim-org/opensim-core/blob/6b198b9d34a709feeb052103961baf06b3ee8a6e/OpenSim/Moco/MocoCasADiSolver/CasOCFunction.cpp#L223)):*
> ```cpp
>     } else if (i == 11) {
>         // TODO: We should find a way to actually compute the integral
>         // from fullPoint. Or, make the integral an optimizatio           
> ```

Not sure how these scale up/down or interpretation of i value, would be good to have a link/pointer if possible

**Review by nickbianco — COMMENTED** [review]
There's not really an easy way to extract the number of non-zeros in the problem constraint Jacobian, so unfortunately that kind of test is a bit difficult to write. The existing tests passing (weird Windows shenanigans aside) seems to indicate that everything is working properly. It's unlikely that problem sparsity would change again unless CasADi changes the Jacobian sparsity API again.

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3807#-:-O-7d9Ze9Fb3cON3oVQc:b-9pjtgc)* status: all files reviewed, 1 unresolved discussion (waiting on @aymanhab)

___
*[`OpenSim/Moco/MocoCasADiSolver/CasOCFunction.cpp` line 223 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3807#-O-7D_U05uUDvF44Kxsy:-O-7bek7-JDSuFpl3fmz:b-xpj461) ([raw file](https://github.com/opensim-org/opensim-core/blob/6b198b9d34a709feeb052103961baf06b3ee8a6e/OpenSim/Moco/MocoCasADiSolver/CasOCFunction.cpp#L223)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

Not sure how these scale up/down or interpretation of i value, would be good to have a link/pointer if possible
</blockquote></details>

Can you elaborate? I'm not sure what you mean.

**Review by aymanhab — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3807)* status: all files reviewed, 1 unresolved discussion (waiting on @nickbianco)

___
*[`OpenSim/Moco/MocoCasADiSolver/CasOCFunction.cpp` line 223 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3807#-O-7D_U05uUDvF44Kxsy:-O-7jQYJ3ZLqf5V5jTFJ:b-gabk5k) ([raw file](https://github.com/opensim-org/opensim-core/blob/6b198b9d34a709feeb052103961baf06b3ee8a6e/OpenSim/Moco/MocoCasADiSolver/CasOCFunction.cpp#L223)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Can you elaborate? I'm not sure what you mean.
</blockquote></details>

There's an if else with 11 different conditions, where these come from? Will these change to 20 conditions down the road? Just trying to understand or leave a trace behind for the next developer/maintainer. Sorry about the brevity

**Review by nickbianco — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3807)* status: all files reviewed, 1 unresolved discussion (waiting on @aymanhab)

___
*[`OpenSim/Moco/MocoCasADiSolver/CasOCFunction.cpp` line 223 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3807#-O-7D_U05uUDvF44Kxsy:-O-8HvDX03p5tFXtRnO7:b-yb3t0w) ([raw file](https://github.com/opensim-org/opensim-core/blob/6b198b9d34a709feeb052103961baf06b3ee8a6e/OpenSim/Moco/MocoCasADiSolver/CasOCFunction.cpp#L223)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

There's an if else with 11 different conditions, where these come from? Will these change to 20 conditions down the road? Just trying to understand or leave a trace behind for the next developer/maintainer. Sorry about the brevity
</blockquote></details>

The if-else logic is for returning a subset of the inputs for a CasADi function. This change was needed because Jacobian sparsity is now required to be provided for each input-output pair of a function. Therefore, this needed to be updated accordingly.

**Comment by aymanhab** [comment]
@nickbianco Thanks, if there's nothing more that can be done to document this logic then let me know and I'll approve the PR.

**Comment by nickbianco** [comment]
@aymanhab I added some comments to document the sparsity changes. I think this is sufficient since this changes are pretty low-level.

**Review by aymanhab — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3807#-:-O-ChWAk-rFEE27bnrET:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nickbianco)

**Comment by nickbianco** [comment]
Thanks @aymanhab! I'm cleaning up the experimenting that I was doing with the CI here. I'll merge after verifying that the Mac and Ubuntu's are passing and that the Windows failures are unrelated to the present changes.

**Comment by nickbianco** [comment]
CI cleaned up and test failures unrelated. Merging.

**Comment by aymanhab** [comment]
🥇

**Pull request merged**
