### PR TITLE
Build data adapter examples

### PR DESCRIPTION
**Pull request by aymanhab**
Fixes issue #2673

### Brief summary of changes
Change examples to use 4.1 API and incorporate into build structure so that they stay in sync with API.
### CHANGELOG.md (choose one)

- no need to update because...
- updated...

The Doxygen for this PR can be viewed at http://myosin.sourceforge.net/?C=N;O=D; click the folder whose name is this PR's number.

---
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2680)

### CODE REVIEW

**Comment by aymanhab** [comment]
This PR should take care of the stale source that was detected in #2673, now it compiles and was manually tested. MOTFileAdapter was removed since it was obsoleted earlier in 4.0.

**Comment by aymanhab** [comment]
@carmichaelong when you have a chance, can you review? Thanks

**Comment by carmichaelong** [comment]
Tested the examples locally, LGTM. Thanks!

**Comment by aymanhab** [comment]
Thanks @carmichaelong

**Pull request merged**
