### PR TITLE
[WIP] Updates to hopper example for Dev Week

### PR DESCRIPTION
**Pull request by tkuchida**
(Not ready for review)
Addresses part of #876

### CODE REVIEW

**Comment by aymanhab** [comment]
@tkuchida I worry about checking updated .osim files that have most up to date contents when the document version number at the top of the file is not updated as this may mess up future conversion. If we're close to done with xml changes, I'd update the XML document version number before saving so we can see what model files go through the version upgrade successfully.

**Comment by tkuchida** [comment]
@aymanhab I don't understand your concern. The version number was originally set to 30505 for the hackathon, but changes were made to the way models are defined (in particular, adding frames to joints) without incrementing the version. Thus, the version number in this file was 30505 (and, consequently, `updateFromXMLNode()` was not triggered) but the file did not conform to the 30505 standard. I manually changed the version number to 30504, loaded it, then saved it. What would you like me to do instead?

**Comment by aymanhab** [comment]
@tkuchida My concern is that version 30505 is a moving target now that we agreed upon (mainly @aseth1, @chrisdembia  and I) because so many changes are occurring with the understanding that we will not commit or honor files written in this continuously changing version. The invariant we try to keep is that the version number at the top of the file is consistent with the code that wrote it. I think we're close enough to the devweek that we can change the number in XMLDocument.cpp to be 30506 and let the conversion code kick in rather than subvert it by changing the header manually only to be surprised later.

**Comment by tkuchida** [comment]
> I think we're close enough to the devweek that we can change the number in XMLDocument.cpp to be 30506 and let the conversion code kick in rather than subvert it by changing the header manually only to be surprised later.

That sounds fine, but please discuss on a separate thread. For now, I'm just trying to get the example working again on master so I can start updating it.

**Comment by tkuchida** [comment]
Addressing XML document number first at @aymanhab's request.

**Pull request closed without merging**
