### PR TITLE
Add gfortan to Mac CI build

### PR DESCRIPTION
**Pull request by nickbianco**
### Brief summary of changes

Add gfortran to CI for Mac build.

### CHANGELOG.md (choose one)

- no need to update because...CI fix.
- updated.

---
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2920)

### CODE REVIEW

**Review by aymanhab — APPROVED** [review]
LGTM, thanks @nickbianco

**Comment by adamkewley** [comment]
Out of curiosity @nickbianco is gfortran a new runtime dependency? The other deps seem like build ones. 

Main thing to consider is that brew isn't available on typical Mac targets, so downstream will need to package gfortran for opensim to work on a clean Mac (unsure how much post-package testing is done on clean apple machines)

**Comment by nickbianco** [comment]
We need gfortran to build Ipopt on Mac. I now realize that gfortran should come included with the gcc homebrew package, so not sure why this issue occured.

**Comment by chrisdembia** [comment]
CMake copies the necessary gfortran libraries into Moco’s installation. The cmake scripts need to be updated whenever the gfortran version updates bc we hardcode a version.

Yes it’s important to make sure that users don’t need to have gfortran installed.

-Chris

**Pull request merged**
