### PR TITLE
Remove extraneous setObjectIsUpToDateWithProperties

### PR DESCRIPTION
**Pull request by aseth1**
Made `Object::setObjectIsUpToDateWithProperties()` protected and removed extraneous calls from Model and StaticOptimization. Remaining uses are by Millard muscle components that are actively being fixed by @tkuchida  #366, so I've left those in, for the time being.

### CODE REVIEW

**Comment by chrisdembia** [comment]
> removed extraneous calls from Model and StaticOptimization

How do you know those calls were extraneous?

**Comment by aseth1** [comment]
@chrisdembia I had added the calls before the Component took responsibility, which made it duplicated on Model. For SO, I tested with and without the call and the results were identical, so I am concluding it was unnecessary.

**Comment by chrisdembia** [comment]
Okay, this looks good then.

**Comment by tkuchida** [comment]
:+1:

**Pull request merged**
