### PR TITLE
Fix 32 bit segfault failure of C3DFileAdapter.

### PR DESCRIPTION
**Pull request by klshrinidhi**
Fixing problem discovered by @tkuchida in PR #912.
When compiled for 32-bit binaries with MSVC, `C3DFileAdapter::extendRead` function `segfaults` due to incorrect use of `std::vector<Eigen::Matrix<...>>`. This fix removes its use altogether to avoid the problem.

### CODE REVIEW

**Comment by chrisdembia** [comment]
Cool; to verify the fix, could you merge #912 into this branch and un-exclude the tests?

**Comment by klshrinidhi** [comment]
I would want this PR to go into master, not #912. So maybe I can merge that branch into this just for testing and then undo it before merging into master.

I tested the fix on a 32-bit build with MSVC locally.

**Comment by chrisdembia** [comment]
Sounds good. Thanks.

**Comment by chrisdembia** [comment]
Okay the 32-bit build passed on appveyor (both branch and pr); you wanted to remove the appveyor changes before merging?

**Comment by tkuchida** [comment]
```
OPENSIM_TESTS_TO_EXCLUDE: "Java_TestBasics_Release"
PYTHON_TESTS_TO_EXCLUDE: "test_C3DFileAdapter"
```
These tests are still failing (even the python test)?

**Comment by tkuchida** [comment]
> These tests are still failing (even the python test)?

Nevermind, I'll investigate on #912.

**Comment by klshrinidhi** [comment]
Reverted the changes from branch in #912. 
Ready to merge now.

**Comment by chrisdembia** [comment]
Thanks for the fix.

**Pull request merged**
