### PR TITLE
Update testStorage.cpp to use catch (#3555)

### PR DESCRIPTION
**Pull request by adamkewley**
Relates to #3555

### Brief summary of changes

- RTFCM

### CHANGELOG.md (choose one)

- no need to update because it would bore people senseless

- - -
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3557)

### CODE REVIEW

**Review by nickbianco — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3557)* status: all files reviewed, 2 unresolved discussions (waiting on @adamkewley)

___
*[`OpenSim/Common/Test/testStorage.cpp` line 24 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3557#-NeZX58j1iNBX3cSFjHH:-NeZX58j1iNBX3cSFjHI:b-jsmuqa) ([raw file](https://github.com/opensim-org/opensim-core/blob/ff7250bf80f489e8694ad41a6ea6512c97a856d6/OpenSim/Common/Test/testStorage.cpp#L24)):*
> ```cpp
> 
> #include <OpenSim/Common/Storage.h>
> #include <OpenSim/Auxiliary/auxiliaryTestFunctions.h>
> ```

I think this include is no longer necessary?
___
*[`OpenSim/Common/Test/testStorage.cpp` line 177 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3557#-NeZVjAe4_vysYPTU37J:-NeZVjAe4_vysYPTU37K:b-x8kyy5) ([raw file](https://github.com/opensim-org/opensim-core/blob/ff7250bf80f489e8694ad41a6ea6512c97a856d6/OpenSim/Common/Test/testStorage.cpp#L177)):*
> ```cpp
>     SimTK_TEST(sto.getStateIndex("/jointset/hip/hip_flexion/speed") == 1);
>     SimTK_TEST(sto.getStateIndex("/forceset/soleus/activation") == 2);
>     SimTK_TEST(sto.getStateIndex("/forceset/soleus/fiber_length") == 3);
> ```

If we're converting everything to `catch`, I'm inclined to use the built-in macros (i.e.,`CHECK`, `REQUIRE`, etc.). The SimTK macros might have some nice options for some numerical tests that `catch` doesn't support though.

**Comment by adamkewley** [comment]
I'll dump the includes.

For the assertions, they fall under what if I've labeled as phase 3 of the epic. The reason why changing the assertions was seperated was to minimize the diff/changeset at each step of the process (it's easier to review "this functionally changes nothing but how the tests are named and ran" than "this changes both how the tests are ran *and* the test content itself needs to be scrutinized for logical equivalence")

**Comment by nickbianco** [comment]
Ah, I see now. Sounds good and carry on!

**Comment by adamkewley** [comment]
@nickbianco - I couldn't remove the `auxiliaryTestFunctions.h` because it's still used for the `_ASSERT` stuff, but it should be removed during the phase when we start upgrading assertions to `Catch2`.

I'll merge this for now because I believe the PR otherwise is within expectations etc

**Pull request merged**
