### PR TITLE
Fix paths in Matlab Hopper_Device example.

### PR DESCRIPTION
**Pull request by chrisdembia**
This PR fixes an issue raised in https://app.zenhub.com/workspace/o/opensim-org/opensim-core/issues/2276 by updating paths and calling `finalizeConnections()` appropriately.

---
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2348)

### CODE REVIEW

**Comment by chrisdembia** [comment]
I also added a fix for OpenSimCreateTugOfWar

No need to wait for CI to pass because we do not test Matlab examples.

**Comment by carmichaelong** [comment]
LGTM. I'm okay with merging as is, unless you wanted me to specifically test too?

**Comment by chrisdembia** [comment]
Thanks @carmichaelong. I don't request that you test locally.

**Comment by chrisdembia** [comment]
Thanks.

**Pull request merged**
