### PR TITLE
[WIP] Avoid repeated assembly in StatesTrajectory::createFromStatesStorage()

### PR DESCRIPTION
**Pull request by chrisdembia**
### Brief summary of changes

This PR avoids repeatedly assembling the states (via `Coordinate::setValue()`) within `StatesTrajectory::createFromStatesStorage()`. The repeated assemblies were causing `createFromStatesStorage()` to take many minutes to run for the Rajagopal 2016 model (with 2 coordinate coupler constraints), and this PR fixes this performance issue.

### Testing I've completed

Ran ctests.

### Looking for feedback on...

 There are multiple options for how we can avoid assembling repeatedly, which I discussed with @tkuchida this week. This is related to #1884 (this PR is a workaround for #1884).

1. Have `Coordinate::CoordinateStateVariable::setValue()` pass `false` for the `enforceConstraints` parameter of `Coordinate::setValue()`. We would edit the documentation of `Component::setStateVariableValues()` to say that users must call `model.assemble()`, etc. on their own to enforce the constraints.
2. Have `Component::setStateVariableValues()` take a `enforceConstraints` parameter, and enforce the constraints only after setting all state variable values. This could be achieved by giving `Component` a virtual function that `Model` would implement by calling `assemble()`. I don't really like this idea. How is a generic component supposed to know how to enforce constraints?
3. Permit users to have a way to set state variable values without using `Component::setStateVariableValues()`. That is, help users use `State::updY()` directly. Then users can call `assemble()` on their own. I see 2 options:

    1. provide a method that gives the names of the state variables in the order of `State::getY()`.
    2. Implement `Component::StateVariable::getSystemYIndex()` and expose these global indices to users, perhaps via `Component::getSystemYIndices()` (similar to `Component::getStateVariableNames()`).

(I've copied these options to #1884.)

In this PR, I've chosen to go with 3(i). I think we should do 3(i) regardless of how we solve #1884. I also like option 1.

I don't actually want to merge this PR yet. Rather, I want to discuss the options and to get opinions about my implementation of `createSystemYIndices()`. If we like `createSystemYIndices()`, then I would want to move it to `Model`.

### CHANGELOG.md (choose one)

- no need to update because...StatesTrajectory is new to 4.0.

The Doxygen for this PR can be viewed at http://myosin.sourceforge.net/?C=N;O=D; click the folder whose name is this PR's number.

### CODE REVIEW

**Comment by aymanhab** [comment]
@chrisdembia This is the essence of the issue we ran into before ISB where states play smoothly in the GUI (since they don't assemble at least for a model with no constraints) while coordinates force assembly and lead to choppy playback. We need to coordinate so that GUI can leverage your work on this Issue.

**Comment by aymanhab** [comment]
I do prefer option 3 as well as most flexible, I may have asked for it earlier (use case in the GUI you may have a motion that changes only a few state variables, being able to selectively set these would be great).

**Comment by aseth1** [comment]
My preference is to not expose `systemYindices` to users. To me that is "passing-the-buck" to do the book-keeping. I am totally OK with us getting and managing indices internally so that `Component::setStateVariableValues()` is super fast by doing a an `updY()` internally with the states in order or `Component::getStateVariableNames()`. Then users can maintain a an Array (or std::vector) of state values (say in MATLAB) and update quickly without having to know anything about system state Y indices.

**Comment by chrisdembia** [comment]
>  To me that is "passing-the-buck" to the user to do the book-keeping.

Makes sense, but you could also view it as a function for advanced users who are trying to get rid of all possible overhead during direct collocation. I'll do some testing to see if we can get by with simply speeding up` setStateVariableValues()`.

**Comment by aseth1** [comment]
If you maintain the indices internally to reorder *stateVariableValues* `Vector` to match `state.updY()` `Vector`, then  reordering should be negligible fixed cost especially if no new allocations are required. If we expose and further facilitate accessing `State` entries directly then users are likely to do it more, and once they have code that depends on `Y` and `Z` order they are higher risk of their code breaking and lose the advantages of using OpenSim for context.

**Comment by chrisdembia** [comment]
@aseth1 has an alternative fix in #1911.

**Comment by chrisdembia** [comment]
I'm not deleting the branch yet becase it might still be useful.

**Pull request closed without merging**
