### PR TITLE
Check for NaN or -ve mass specification and follow as invalid inertia

### PR DESCRIPTION
**Pull request by aymanhab**
Fixes issue #3130 

### Brief summary of changes
Expanded try-block that used to throw if bad inertia is specified to include check for NaN or -ve mass specification.

### Testing I've completed
None other than stepping through the code with bad model.

### Looking for feedback on...
Should we throw for consistency of handling of inertia as opposed to allowing loading models and catch downstream which would be wider spread and unsustainable AFAICT.

### CHANGELOG.md (choose one)

---
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3182)

### CODE REVIEW

**Comment by aymanhab** [comment]
@adamkewley can you review this PR to make sure it doesn't cause problems to the "Creator" codebase? If mass was not specified it was initialized to NaN causing problems to downstream tools while bad inertia was throwing. This PR makes NaN or -ve mass also throw which is more consistent rather than sprinkling checks downstream. Alternatively we can make Body constructor set 0 mass instead of NaN.

**Comment by adamkewley** [comment]
The behavior is fine for me, probably :wink: - I'll handle any downstream errors separately.

Implementation-wise, I'd recommend:

- Only checking if `m >= 0.0`. Any negative values *and* `NaN` will be caught by `m >= 0.0`. `NaN` is special edge-case that always compares false with all relational and comparison operators (incl. `NaN == NaN`). The literal `0` should ideally be avoided, because it's an `int` literal that relies on automatic promotion for comparison with a `double`. The promotion is well-defined from C, but it is advisable to use the direct comparison.

- Perform the check *and then* handle any error cases. The new implementation unconditionally allocates the error message string (`msg`), even if there is no error. Something like this would work around that:

```c++
if (m >= 0.0) {
    // allocate the error message + exception state in here
    // throw
}
```

- Pry the not-SimTK checks out of the `try` block and throw from outside it if there's a component-specific throwing macro available in OpenSim (e.g: [OPENSIM_THROW_FRMOBJ](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Common/Exception.h#L85)). Ideally, only surround the throwing part of the call with a `try...catch` block (I'm assuming the original `try...catch` exists to handle the exception thrown by `SimTK::MassProperties{...}`). The current implementation will `throw` from your new check followed by the exception being immediately be re-caught, followed by a further string append (of redundant information) and re-thrown.

**Review by aymanhab — COMMENTED** [review]
Thanks for the quick turnaround and suggestions. I'll remove the explicit NaN check as you suggested. I prefer not to change where/who throws/catches so that clients are not affected and the change is minimal. Switching to OPENSIM_THROW_IF_FROMOBJ takes care of the allocation issue though the exception may look different from Inertia error. 

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3182#-:-N-U0xP93K3I6lRJji9J:b17n9w3)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @adamkewley and @carmichaelong)

**Comment by adamkewley** [comment]
No prob.

It might be that you end up needing `!(m >= 0.0)` wherever, which might end up looking uglier than the `isnan`: whatever works best - it's only a small change

**Comment by aymanhab** [comment]
@adamkewley is this good to go? Thanks

**Comment by adamkewley** [comment]
Yes, it looks fine :)

**Comment by aymanhab** [comment]
Thanks @adamkewley

**Pull request merged**
