### PR TITLE
Register ExpressionBasedCoordinateForce

### PR DESCRIPTION
**Pull request by mitkof6**
Fixes issue #<issue_number>

Register ExpressionBasedCoordinateForce so that it can be used in the GUI.

### CHANGELOG.md (choose one)

- no need to update because...
- updated...

The Doxygen for this PR can be viewed at http://myosin.sourceforge.net/?C=N;O=D; click the folder whose name is this PR's number.

### CODE REVIEW

**Comment by chrisdembia** [comment]
This is great. I restarted the builds that are failing.

**Comment by chrisdembia** [comment]
We can ignore the CI failures; they are unrelated.

**Comment by carmichaelong** [comment]
LGTM

**Comment by tkuchida** [comment]
For reference: user reported on [Forum topic 9238](https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=91&t=9238).

**Comment by chrisdembia** [comment]
Thanks @mitkof6

**Pull request merged**
