### PR TITLE
Revert refactoring of the Pad function that was breaking CMC 

### PR DESCRIPTION
**Pull request by aymanhab**
Fixes issue #2950

### Brief summary of changes
Restore functionality of Signal::Pad to 4.1 status

### CHANGELOG.md (choose one)

- no need to update because internal

---
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2962)

### CODE REVIEW

**Comment by aymanhab** [comment]
@nickbianco and @carmichaelong Can you review this change so we try to get all the pieces of 4.2 in one build for testing? Thank you

**Comment by nickbianco** [comment]
@aymanhab could you reference the commit that you pulled this version of Pad from?

**Comment by aymanhab** [comment]
84954d59fbe62a30d9a6683e72c6159ea8e0b4e7 on 6/29/2020

**Comment by nickbianco** [comment]
The commit you sent is after the changes to `Pad`. However, on that commit it looks like we do check if the pad size is invalid: https://github.com/opensim-org/opensim-core/blob/84954d59fbe62a30d9a6683e72c6159ea8e0b4e7/OpenSim/Common/Signal.cpp#L407. 

For the CMC example, should we not just change the size of the pad applied rather than rolling back these (seemingly good) changes?

**Comment by aymanhab** [comment]
We could change the pad size but that will change the results for potentially all CMC examples and user cases since the pad size is hardcoded. Not sure we want to do this at this stage but I'm open to discussion.

**Comment by nickbianco** [comment]
Oh dang, I thought it was just for that example.

**Comment by nickbianco** [comment]
Well in that case it's not worth potentially breaking other examples right now. Can we should create an issue to remind us to come back and properly address the padding size issue within CMC? The recent changes to padding should be reimplemented eventually, don't want to lose them with this PR.

**Review by nickbianco — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2962)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aymanhab)

**Review by nickbianco — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2962#-:-MUQ3qO_5TQtekPIkIla:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aymanhab)

**Comment by nickbianco** [comment]
Feel free to merge after creating the issue mentioned above and the tests pass.

**Comment by aymanhab** [comment]
Thanks for the review @nickbianco 👍 I created the issue. Still working on the tests will merge after the tests are there and pass.

**Pull request merged**
