### PR TITLE
[Moco] Automatic variable scaling

### PR DESCRIPTION
**Pull request by nickbianco**
### Brief summary of changes
Introduce a setting for MocoCasADiSolver to automatically scale optimization variables based on variable bounds.

### Testing I've completed
Created `exampledVariableScaling.cpp` to demonstrate the effect of variable scaling.

### CHANGELOG.md (choose one)

- updated.

---
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3095)

### CODE REVIEW

**Review by carmichaelong — CHANGES_REQUESTED** [review]
Code comments discussed on Zoom left on relevant lines.

> Reviewed 4 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3095#-:-MuwkDf-6BY0Moga4h5Y:bfihmcf)* status: 4 of 9 files reviewed, 2 unresolved discussions (waiting on @carmichaelong and @nickbianco)

___
*[OpenSim/Moco/MocoCasADiSolver/CasOCTranscription.h, line 100 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3095#-Muwk1gJ-AsaYSRnBgzN:-Muwk1gJ-AsaYSRnBgzO:b-hsij0z) ([raw file](https://github.com/opensim-org/opensim-core/blob/716e1badbc5a84659fa7b825253c13d81024c09e/OpenSim/Moco/MocoCasADiSolver/CasOCTranscription.h#L100)):*
> ```objc
> 
>     template <typename TRow, typename TColumn>
>     void setScalingUsingBounds(Var key, const TRow& rowIndices,
> ```

Change function name to something like `setVariableScaling`
___
*[OpenSim/Moco/MocoCasADiSolver/CasOCTranscription.h, line 267 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3095#-MuwkAk6EH-j6cDIEpEr:-MuwkAk6EH-j6cDIEpEs:b-dljhyp) ([raw file](https://github.com/opensim-org/opensim-core/blob/716e1badbc5a84659fa7b825253c13d81024c09e/OpenSim/Moco/MocoCasADiSolver/CasOCTranscription.h#L267)):*
> ```objc
>     }
> 
>     // TODO scale/unscale guess!
> ```

Comment can be removed now

**Review by nickbianco — COMMENTED** [review]
Thanks @carmichaelong. Let's just leave the scaling example as-is.

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3095#-:-MuxMuYwBiUyt2GgFHV1:btxmjxu)* status: 4 of 9 files reviewed, 2 unresolved discussions (waiting on @carmichaelong)

___
*[OpenSim/Moco/MocoCasADiSolver/CasOCTranscription.h, line 100 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3095#-Muwk1gJ-AsaYSRnBgzN:-MuxMi165RZil6Lpt3eb:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/716e1badbc5a84659fa7b825253c13d81024c09e/OpenSim/Moco/MocoCasADiSolver/CasOCTranscription.h#L100)):*
<details><summary><i>Previously, carmichaelong wrote…</i></summary><blockquote>

Change function name to something like `setVariableScaling`
</blockquote></details>

Done.
___
*[OpenSim/Moco/MocoCasADiSolver/CasOCTranscription.h, line 267 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3095#-MuwkAk6EH-j6cDIEpEr:-MuxMiHxAegyqUdIb02G:b9e2iy1) ([raw file](https://github.com/opensim-org/opensim-core/blob/716e1badbc5a84659fa7b825253c13d81024c09e/OpenSim/Moco/MocoCasADiSolver/CasOCTranscription.h#L267)):*
<details><summary><i>Previously, carmichaelong wrote…</i></summary><blockquote>

Comment can be removed now
</blockquote></details>

I turned this into a more descriptive comment.

**Review by carmichaelong — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3095#-:-Mv5XV8X2G_J6T1loNPJ:bnfp4nl)* status: 4 of 9 files reviewed, all discussions resolved (waiting on @carmichaelong)

**Comment by nickbianco** [comment]
Thanks @carmichaelong.

**Pull request merged**
