### PR TITLE
logging for applications

### PR DESCRIPTION
**Pull request by carmichaelong**
Part of #36

### Brief summary of changes
Use spdlog in Applications folder.

### Testing I've completed
Ran some of the executables without arguments, saw a different behavior in the help section with the `[warning]` tag:
```
[2020-05-13 10:25:30.305] [warning]
    THIS EXECUTABLE IS DEPRECATED AND WILL BE REMOVED IN A FUTURE RELEASE.
```
The `opensim.log` file was empty.

### Looking for feedback on...
- What other testing would be good to do?
- There is heavy usage of `PrintUsage()` and `Object::PrintPropertyInfo()`. Should I deal with those too? If so, in a new PR?

---
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2769)

### CODE REVIEW

**Comment by aymanhab** [comment]
@carmichaelong any reason not to merge this PR to feature_logging?

**Comment by carmichaelong** [comment]
I needed to make some changes to the tests after approval. Looks like they all pass now, but would be good if someone double checks the changes to the tests before merging.

**Comment by carmichaelong** [comment]
___
*[Applications/opensim-cmd/test/testCommandLineInterface.cpp, line 118 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/2769#-M7dAPtH6HigIivxLSFv:-M7dM8H78Kin1s_dVdOc:bj8i1fu) ([raw file](https://github.com/opensim-org/opensim-core/blob/74730534a4295ecf644d94e43190b22afa3e9c97/Applications/opensim-cmd/test/testCommandLineInterface.cpp#L118)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

I'd change the parameter name to substring to avoid confusion with the member, same for StartsWith class, though not user facing. Maybe more robust to have a method that removes logging prefix (within []) and leave the checks as is if not much work.
</blockquote></details>

I started off on that route, but some checks are multiple lines, so can't remove the start cleanly each time. Another route could be to just convert lots of this to regex?

**Comment by aymanhab** [comment]
That's fine @carmichaelong if it's too messy, feel free to merge as is once other comments are addressed.

**Comment by carmichaelong** [comment]
Thanks @aymanhab and @chrisdembia for feedback. I will definitely not add more `regex`'s then.

I think I'll leave the `ContainsSubstring` as is since it's a bit easier than removing `[]` sections, and I think would end up to a similar check.

@aymanhab I just made a push to make the parameters and member variables different in the two helper functions you mentioned. Let me know if this addresses your comment, or if I misinterpreted it I'm happy to make another change.

**Comment by aymanhab** [comment]
Thanks @carmichaelong LGTM.

**Pull request merged**
