### PR TITLE
update links and add example

### PR DESCRIPTION
**Pull request by antoinefalisse**
### Brief summary of changes

This PR updates links to the moco paper and the opensim github webpage, and adds an example to the list of examples.

### Testing I've completed

No testing needed.

### Looking for feedback on

Check links.

### CHANGELOG.md (choose one)

- no need to update because very minor

---
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2970)

### CODE REVIEW

**Review by aymanhab — APPROVED** [review]
LGTM, if you checked the resulting doxygen and it looks good feel free to merge.

**Comment by antoinefalisse** [comment]
@aymanhab is there a way to check the resulting doxygen without re-building locally? If not I do it, no problem.

**Comment by aymanhab** [comment]
I typically build only the doxygen target which should take a couple minutes. In the past we used to have a live doxygen generated and posted on myosin but I lost track of that, maybe @nickbianco would remember since he was working closely with Chris who owned myosin and can can chime in.

**Comment by antoinefalisse** [comment]
@Ayman, I built doxygen locally and made some changes - looking better now.

**Review by aymanhab — APPROVED** [review]
LGTM 👍

**Pull request merged**
