### PR TITLE
Add NMSM Pipeline contact elements for use in Moco

### PR DESCRIPTION
**Pull request by SpencerTWilliams**
### Brief summary of changes

This fork includes the new `MeyerFregly2016Muscle` and completes the implementation of the `MeyerFregly2016Force` included in the `StationPlaneContactForce` class. 

The `MeyerFregly2016Muscle` is intended to be used without tendon compliance. 

### Testing I've completed

I've successfully compiled OpenSim on Ubuntu with these changes. However, I have not been able to test using the new elements.

### Looking for feedback on...

I ran into an error while trying to compile a test for the `MeyerFregly2016Muscle` by modifying `testMocoActuators.cpp`:
```
/home/compiler/opensim-workspace/opensim-core-source/OpenSim/Moco/Test/testMocoActuators.cpp:95:26: error: expected type-specifier before ‘MeyerFregly2016Muscle’
   95 |         auto* actu = new MeyerFregly2016Muscle();
      |                          ^~~~~~~~~~~~~~~~~~~~~
``` 
I had the same error if I replaced the `auto` with `MeyerFregly2016Muscle`, so I think there may be an issue with including the new muscle as a type, even though the code files for the muscle compile correctly. Are there any issues with how I included the muscle in linking or registering the type in 2063d6f2d13177c829a9b7e39e662c0599d275dc?

### CHANGELOG.md (choose one)

- updated, but needs a merge conflict resolved I don't have permission for.

- - -
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3877)

### CODE REVIEW

**Review by nickbianco — CHANGES_REQUESTED** [review]
Thanks for creating the PR @SpencerTWilliams! I've left a handful of comments to get started. My biggest question right now is whether or not we should create a separate class the muscle or if it is possible to use `DeGrooteFregly2016Muscle`, since the implementations look very similar. Could you list the primary differences between the two classes? I'd like to get a better understanding before I review. 

> I ran into an error while trying to compile a test for the `MeyerFregly2016Muscle` by modifying `testMocoActuators.cpp`:

I think you might have forgotten an include statement in the test file? Feel free to push the test changes if you want me to take a look.

Finally, we use Reviewable for code reviews (click the purple button in the PR description). Let me know if you have any questions on how it works.

> Reviewed 6 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3877#-:-O4fl84hBQCX3PI0uagX:b-nd8qdf)* status: 6 of 8 files reviewed, 10 unresolved discussions (waiting on @SpencerTWilliams)

___
*[`CHANGELOG.md` line 63 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3877#-O4fkouV2PWldOc6_u8m:-O4fkouV2PWldOc6_u8n:bfp3je5) ([raw file](https://github.com/opensim-org/opensim-core/blob/75c00e7c0d55b1e6d8d86420be31e2ed0ff8b5e2/CHANGELOG.md#L63)):*
> ```Markdown
> - Fixed bug in `report.py` preventing plotting multiple MocoParameter values. (#3808)
> - Added SynergyController, a controller that computes controls for a model based on a linear combination of a set of Input control signals and a set of synergy vectors. (#3796)
> - Added `MeyerFregly2016Muscle` and completed the implementation of the `MeyerFregly2016Force` included in the `StationPlaneContactForce` class to support NMSM Pipeline-equivalent muscle and contant models in Moco. 
> ```

Typically we append the PR number in changelog entries:



_Suggestion:_
```Markdown
- Added `MeyerFregly2016Muscle` and completed the implementation of the `MeyerFregly2016Force` included in the `StationPlaneContactForce` class to support NMSM Pipeline-equivalent muscle and contant models in Moco. (#3877)
```
___
*[`OpenSim/Actuators/MeyerFregly2016Muscle.h` line 41 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3877#-O4fc-ZJBEu-GmhcEwBK:-O4fc-ZJBEu-GmhcEwBL:bjg7cqa) ([raw file](https://github.com/opensim-org/opensim-core/blob/75c00e7c0d55b1e6d8d86420be31e2ed0ff8b5e2/OpenSim/Actuators/MeyerFregly2016Muscle.h#L41)):*
> ```objc
> 
> This muscle implementation is based on the previously implemented 
> DeGrooteFregly2016Muscle.
> ```

At first glance, this implementation looks very similar to `DeGrooteFregly2016Muscle`,  which makes me wonder again if it's worth making these muscle separate classes. I think it would be worth enumerating the differences between the curves in `DeGrooteFregly2016Muscle` and the ones here to get a bette sense if an entirely separate class is necessary. 
___
*[`OpenSim/Moco/Components/StationPlaneContactForce.h` line 6 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3877#-O4fhQeCBBHSBzOa_wRH:-O4fhQeCBBHSBzOa_wRI:b-kcrh9n) ([raw file](https://github.com/opensim-org/opensim-core/blob/75c00e7c0d55b1e6d8d86420be31e2ed0ff8b5e2/OpenSim/Moco/Components/StationPlaneContactForce.h#L6)):*
> ```objc
>  * OpenSim: StationPlaneContactForce.h                                        *
>  * -------------------------------------------------------------------------- *
>  * Copyright (c) 2017 Stanford University and the Authors                     *
> ```

Might as well update the year too:



_Suggestion:_
```objc
 * Copyright (c) 2024 Stanford University and the Authors                     *
```
___
*[`OpenSim/Moco/Components/StationPlaneContactForce.h` line 146 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3877#-O4fcfzH1rjiLku1ApVf:-O4fcfzI80vSap_MQ-1_:b-u1gpxq) ([raw file](https://github.com/opensim-org/opensim-core/blob/75c00e7c0d55b1e6d8d86420be31e2ed0ff8b5e2/OpenSim/Moco/Components/StationPlaneContactForce.h#L146)):*
> ```objc
> B. J. (2016). Muscle Synergies Facilitate Computational Prediction of
> Subject-Specific Walking Motions. Frontiers in Bioengineering and
> Biotechnology, 4, 1055–27. http://doi.org/10.3389/fbioe.2016.00077 
> ```

Now that this contact element is being fleshed out, it would be good to expand the class description here (and possibly update the reference, if relevant). Consider explaining how the contact forces are compute and include equations. Refer to [MocoControlGoal](https://github.com/opensim-org/opensim-core/blob/aa1a3abe8f8179338bfedb9896f6cbe453e866f9/OpenSim/Moco/MocoGoal/MocoControlGoal.h) on how to write equations using Doxygen comments.
___
*[`OpenSim/Moco/Components/StationPlaneContactForce.h` line 178 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3877#-O4fhsoh2S8kgNAv3e6F:-O4fhsoh2S8kgNAv3e6G:b-rumjrq) ([raw file](https://github.com/opensim-org/opensim-core/blob/75c00e7c0d55b1e6d8d86420be31e2ed0ff8b5e2/OpenSim/Moco/Components/StationPlaneContactForce.h#L178)):*
> ```objc
>         const SimTK::Real y = pos[1];
>         const SimTK::Real velNormal = vel[1];
>         SimTK::Real velSliding = sqrt(vel[0] * vel[0] + vel[2] * vel[2]);
> ```

The OpenSim convention is that y-direction is vertical, but it would be good to note this somewhere in the class documentation above.
___
*[`OpenSim/Moco/Components/StationPlaneContactForce.h` line 185 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3877#-O4fj_Vl0xJr-eevcjrw:-O4fj_Vl0xJr-eevcjrx:b25z6mx) ([raw file](https://github.com/opensim-org/opensim-core/blob/75c00e7c0d55b1e6d8d86420be31e2ed0ff8b5e2/OpenSim/Moco/Components/StationPlaneContactForce.h#L185)):*
> ```objc
>         const SimTK::Real h = 1e-3;
>         const SimTK::Real c = 5e-4;
>         const SimTK::Real ymax = 1e-2;
> ```

It would be good to explain these hardcoded parameters in the class docs.
___
*[`OpenSim/Moco/Components/StationPlaneContactForce.h` line 198 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3877#-O4fjWQT6FC4aYjHMD73:-O4fjWQT6FC4aYjHMD74:b-rxyvht) ([raw file](https://github.com/opensim-org/opensim-core/blob/75c00e7c0d55b1e6d8d86420be31e2ed0ff8b5e2/OpenSim/Moco/Components/StationPlaneContactForce.h#L198)):*
> ```objc
>         if (SimTK::isNaN(Fspring) || SimTK::isInf(Fspring)) {
>             Fspring = 0;
>         }
> ```

I'm wondering if this if-statment should be removed. I'm not sure if we added these originally or borrowed them from the Meyer et al. implementation.
___
*[`OpenSim/Moco/Components/StationPlaneContactForce.h` line 211 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3877#-O4fi96y6DPSh6m10FMY:-O4fi96zBELX-hX5GNfw:bxs59fg) ([raw file](https://github.com/opensim-org/opensim-core/blob/75c00e7c0d55b1e6d8d86420be31e2ed0ff8b5e2/OpenSim/Moco/Components/StationPlaneContactForce.h#L211)):*
> ```objc
>         if (velSliding < 1e-10) {
>                 velSliding = 0;
>         }
> ```

Why not just let this be near zero? We try to avoid if-statements like this, as they can introduce discontinuties in the model.
___
*[`OpenSim/Moco/Components/StationPlaneContactForce.h` line 217 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3877#-O4fk13EByFROFc9NVp3:-O4fk13EByFROFc9NVp4:b-93pjel) ([raw file](https://github.com/opensim-org/opensim-core/blob/75c00e7c0d55b1e6d8d86420be31e2ed0ff8b5e2/OpenSim/Moco/Components/StationPlaneContactForce.h#L217)):*
> ```objc
>         if (SimTK::isNaN(horizontalForce) || SimTK::isInf(horizontalForce)) {
>             horizontalForce = 0;
>         }
> ```

Similar to my comment above: it would be ideal to not require this if-statement. I'm also wary about hiding NaN or Inf values that might indicate deeper issues with the model.
___
*[`OpenSim/Moco/Components/StationPlaneContactForce.h` line 219 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3877#-O4fjtN_-jrcKyQtGCKL:-O4fjtN_-jrcKyQtGCKM:b-oall9n) ([raw file](https://github.com/opensim-org/opensim-core/blob/75c00e7c0d55b1e6d8d86420be31e2ed0ff8b5e2/OpenSim/Moco/Components/StationPlaneContactForce.h#L219)):*
> ```objc
>         }
>         
>         const SimTK::Real slipOffset = 1e-4;
> ```

What is this? Should it be a property or grouped with the other hardcoded parameters above?

**Comment by nickbianco** [comment]
@SpencerTWilliams, just checking in on this PR. Let me know if you have any questions about the review.

**Comment by SpencerTWilliams** [comment]
Thanks for the suggestions! We found the documentation for our contact force equation and the meanings of the constants, so I'll push my changes with the updated class description. 

The `MeyerFregly2016Muscle` class is based on `DeGrooteFregly2016Muscle` and is very similar, but it uses different active and passive force-length and force-velocity curves with different numbers of coefficients. I made this class since we want a muscle that is completely consistent with the muscle model in our code, though it will look similar to the already existing `DeGrooteFregly2016Muscle`. 

For your comments on the if statements, I included those to guarantee that the contact force elements work exactly the same as they do in our code. We haven't had issues with discontinuities, but if these statements will cause problems for Moco, we can try removing them. The `slipOffset` constant likely accounts for any of these potential issues already as it prevents dividing by zero when calculating horizontal forces. This constant is not a property, so I'll move it up to be with the other hardcoded values for clarity.

**Comment by nickbianco** [comment]
Thanks for the update @SpencerTWilliams! 

> The MeyerFregly2016Muscle class is based on DeGrooteFregly2016Muscle and is very similar, but it uses different active and passive force-length and force-velocity curves with different numbers of coefficients. 

Could you be more specific about these differences? My understanding is that the curves in the MeyerFregly2016Muscle entirely different, or do they use the same general formulations (e.g., sum of Gaussians for the force-length curve) with slightly different coefficients? If it's the latter, then I'm somewhat inclined to not introduce a new muscle class.

> For your comments on the if statements, I included those to guarantee that the contact force elements work exactly the same as they do in our code. We haven't had issues with discontinuities, but if these statements will cause problems for Moco, we can try removing them.

I'm generally concerned about hiding Inf or NaN values in a component accessible to the wider userbase. If your force is produce Inf or NaN values something should probably be changed about your model, initial guess, etc. Zeroing out `velSliding` in that if-statement will introduce a discontinuity, but that doesn't mean your probably won't converge, especially with finite differences. I would want to know if these if-statements are merely safeguards or if they provide some functional benefit before agreeing to leave them in.

**Comment by nickbianco** [comment]
Also, just a heads up that the `Force` API will be changing based on https://github.com/opensim-org/opensim-core/pull/3891 soon. It might make sense to break up these two changes: we can use this PR for the contact force addition and then (if needed) open a second PR for the new muscle class.

**Comment by SpencerTWilliams** [comment]
I looked at the curve differences again, and the active force-length curves do have a similar formulation. However, the passive force-length and force-velocity curves are very different between the two muscles, with different numbers of coefficients. I think these differences would require a new muscle class. 

I'll test our model more to see whether it's possible to remove the Inf and NaN values. I think this check would be safe to remove at this point, so I'll remove it if it isn't possible to get Inf and NaN values from actual double inputs. 

Let me know if it ends up making more sense to make a different PR for the muscle. Would I need to change the contact force class to account for the `Force` API changes?

**Comment by adamkewley** [comment]
The force API changes are non-breaking so, in general, code can still override+use  the "raw" `computeForce` APIs. The `ForceProducer` + `ForceConsumer` APIs additional APIs that can be used to facilitate visualization, force reporting, etc.

Specifically for this PR, I don't think you need to change what you're doing in order to receive the benefits of the new API. I've already ensured that the new API is rolled out to `OpenSim::PathActuator`, which `OpenSim::Muscle` inherits from:

- https://github.com/opensim-org/opensim-core/pull/3891/files#diff-5531d7f57434db355a0f850f1439e04caeab955f43dc90a8b5ee22fb740c4ef5R201

Which ultimately means that any forces/actuations produced by this muscle class will automatically be report-able, visualize-able, etc.

**Comment by nickbianco** [comment]
@adamkewley, thanks for the info!

@SpencerTWilliams, yes, let's focus on the contact force additions here and have a separate PR for the muscle.

**Comment by SpencerTWilliams** [comment]
I've pushed my documentation and changes based on your suggestions. The NaN and Inf checks have been deleted from the force element. Should I go ahead and make the second PR for the muscle?

**Review by nickbianco — CHANGES_REQUESTED** [review]
The updates look good overall! I just have one comment to address since I'm still unsure about the if-statement for `velSliding`.

> Should I go ahead and make the second PR for the muscle?

Yes, go for it!

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3877#-:-O67Qo9mBXc296IZuFKf:bacatmm)* status: 6 of 8 files reviewed, 5 unresolved discussions (waiting on @SpencerTWilliams)

___
*[`CHANGELOG.md` line 26 at r4](https://reviewable.io/reviews/opensim-org/opensim-core/3877#-O67OpQW7uGG9JXBueYz:-O67OpQW7uGG9JXBueZ-:b-7yansz) ([raw file](https://github.com/opensim-org/opensim-core/blob/e113ed43b7c587cdd18874747c15d21cdeac5148/CHANGELOG.md#L26)):*
> ```Markdown
>   means that API users can now now ask many `Force` components what forces they produce (see #3891 for a
>   comprehensive overview).
> - Added `MeyerFregly2016Muscle` and completed the implementation of the `MeyerFregly2016Force` included in the `StationPlaneContactForce` class to support NMSM Pipeline-equivalent muscle and contant models in Moco. (#3877)
> ```

Update the changelog when removing `MeyerFregly2016Muscle` from this PR.
___
*[`OpenSim/Moco/Components/StationPlaneContactForce.h` line 211 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3877#-O4fi96y6DPSh6m10FMY:-O67PO7_3a6ca6V1e3ei:btz93qt) ([raw file](https://github.com/opensim-org/opensim-core/blob/75c00e7c0d55b1e6d8d86420be31e2ed0ff8b5e2/OpenSim/Moco/Components/StationPlaneContactForce.h#L211)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Why not just let this be near zero? We try to avoid if-statements like this, as they can introduce discontinuties in the model.
</blockquote></details>

I'm still unsure about keeping this if-statement. What would be the downside of removing it?

**Comment by SpencerTWilliams** [comment]
It looks like it's okay to remove that if-statement, so I took it out. I'll make the new muscle PR now.

**Review by nickbianco — CHANGES_REQUESTED** [review]
@SpencerTWilliams, I've left a few minor formatting suggestions. Now that the component looks complete and the muscle is no longer in the PR I have a few additional thoughts:

1. It looks like there are no testing changes currently in the PR. It looks like the contact force is not tested at all in [testMocoContact](https://github.com/opensim-org/opensim-core/blob/bd1767435902111fa9802b1eb00af0560867bbd6/OpenSim/Moco/Test/testMocoContact.cpp#L4). At the very least, the contact model should be added to the test there. It might make sense to beef up the tests for the `StationPlaneContactForce` elements, we have not looked at them in a while. 
2. Now that it is being formalized, we should probably move `StationPlaneContactForce.h/.cpp` next to `SmoothSphereHalfSpaceForce` under [OpenSim/Simulation/Model](https://github.com/opensim-org/opensim-core/tree/main/OpenSim/Simulation/Model). The `OpenSim/Moco/Components` folder is mostly reserved for internal classes. (Note that `OSIMMOCO_API` should be changed to `OSIMSIMULATION_API` when moved.)  I would also move `AckermannVanDenBogert2010Force` to the bottom of the file so that `MeyerFregly2016Force` is the first concrete class under `StationPlaneContactForce`.
3. As a follow on from 2., now that `MeyerFregly2016Force` is becoming a proper OpenSim force element, we should probably also  spruce up the base class `StationPlaneContactForce`.  This would involve adding some class documentation and addressing the TODO comments regarding caching. I can address these TODOs in a later PR, but if you want to take a stab at the class documentation that would be great. 

> Reviewed 8 of 8 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3877#-:-O6w2s5X2Aavb98L7n2F:b-hprmns)* status: all files reviewed, 3 unresolved discussions (waiting on @SpencerTWilliams)

___
*[`CHANGELOG.md` line 26 at r5](https://reviewable.io/reviews/opensim-org/opensim-core/3877#-O6w1ioj7q-Zj0CQ7VK7:-O6w1ioj7q-Zj0CQ7VK8:undefined) ([raw file](https://github.com/opensim-org/opensim-core/blob/51a4827bc2dbf697f947a9000667568b986ec4d7/CHANGELOG.md#L26)):*
> ```Markdown
>   means that API users can now now ask many `Force` components what forces they produce (see #3891 for a
>   comprehensive overview).
> - Completed the implementation of the `MeyerFregly2016Force` included in the `StationPlaneContactForce` class to support NMSM Pipeline-equivalent contant models in Moco. (#3877)
> ```





_Suggestion:_
```Markdown
- Completed the implementation of the `MeyerFregly2016Force` included in the `StationPlaneContactForce` class to support NMSM Pipeline-equivalent contact models in Moco. (#3877)
```
___
*[`OpenSim/Moco/Components/StationPlaneContactForce.h` line 153 at r5](https://reviewable.io/reviews/opensim-org/opensim-core/3877#-O6w2J_K7BDz65HqgCfy:-O6w2J_K7BDz65HqgCfz:undefined) ([raw file](https://github.com/opensim-org/opensim-core/blob/51a4827bc2dbf697f947a9000667568b986ec4d7/OpenSim/Moco/Components/StationPlaneContactForce.h#L153)):*
> ```objc
> Biotechnology, 4, 1055–27. http://doi.org/10.3389/fbioe.2016.00077 
> 
> Following OpenSim convention, this contact element assumes that the y direction 
> ```





_Suggestion:_
```objc
Following OpenSim convention, this contact element assumes that the y-direction
```
___
*[`OpenSim/Moco/Components/StationPlaneContactForce.h` line 197 at r5](https://reviewable.io/reviews/opensim-org/opensim-core/3877#-O6w2UMV2bC50XP1MkZI:-O6w2UMV2bC50XP1MkZJ:undefined) ([raw file](https://github.com/opensim-org/opensim-core/blob/51a4827bc2dbf697f947a9000667568b986ec4d7/OpenSim/Moco/Components/StationPlaneContactForce.h#L197)):*
> ```objc
> with a tanh function) and viscous (modeled with a linear function) friction 
> models may be used. 
>  */
> ```





_Suggestion:_
```objc
models may be used. */
```

**Comment by SpencerTWilliams** [comment]
Thanks for checking the formatting! I've just pushed my most recent changes.

I moved the `StationPlaneContactForce` files as you suggested, and I added some to the class documentation. Since the other two contact models in the class that I'm not familiar with have different calculations from `MeyerFregly2016Force`, I decided to keep the specifics of force calculations in the concrete class documentation. 

I looked at the tests in `testMocoContact`, and I'm not sure how to make these new tests work. I think the `TEMPLATE_TEST_CASE` would need to be updated:

```c++
TEMPLATE_TEST_CASE("testStationPlaneContactForce", "[tropter]", 
        AckermannVanDenBogert2010Force, EspositoMiller2018Force
        /* TODO MeyerFregly2016Force */) {
    testStationPlaneContactForce<TestType>();
}
```

Would it work to just replace the `/* TODO MeyerFregly2016Force */` with `MeyerFregly2016Force`? And since the other two concrete force types are not fully implemented, should we only be testing `MeyerFregly2016Force`?

If I'm understanding the existing tests correctly, they are currently testing that the model will be able to balance a body's weight. I think it would be good to have a few tests with given position and velocity values in the state to make sure the contact model produces the expected values from its parameters. It would be easy for me to figure out what those contact forces should be from our pipeline code, so would it be possible to create single time point states to test with?

**Comment by SpencerTWilliams** [comment]
I made your suggested change to the documentation and added to the contact element test. The `MeyerFregly2016Force` is now uncommented, and I commented out the other concrete types for now since they aren't fully implemented. 

I wrote a test for known kinematics based on how the others were formatted. I'm haven't been able to run these tests with the code changes, but the values I gave are what I would expect the model to produce. Does the test I added make sense?

**Review by nickbianco — CHANGES_REQUESTED** [review]
The added test looks good! I added a few comments.

> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3877#-:-O7jClc617KtVo1zEeCT:b-ufbssm)* status: all files reviewed, 3 unresolved discussions (waiting on @SpencerTWilliams)

___
*[`OpenSim/Moco/Test/testMocoContact.cpp` line 261 at r7](https://reviewable.io/reviews/opensim-org/opensim-core/3877#-O7jCQ8G9b5XkwGvImyW:-O7jCQ8G9b5XkwGvImyX:b-ma18cs) ([raw file](https://github.com/opensim-org/opensim-core/blob/a07c257078776843a4bea60ab69db94b9cc3c1da/OpenSim/Moco/Test/testMocoContact.cpp#L261)):*
> ```cpp
> // set of input kinematics and default parameters. 
> template<typename T>
> void testKnownKinematics() {
> ```

This test looks good, but you'll need to wrap it in a `TEST_CASE` to enable it. Would you expect it to pass with the other models? If so, then you could add it `testStationPlaneContactForce<T>`. Otherwise, you could create a standalone test just for `MeyerFregly2016Force`.
___
*[`OpenSim/Moco/Test/testMocoContact.cpp` line 541 at r7](https://reviewable.io/reviews/opensim-org/opensim-core/3877#-O7jC3nI5npFrnjQB-Ti:-O7jC3nI5npFrnjQB-Tj:b-bgf0v7) ([raw file](https://github.com/opensim-org/opensim-core/blob/a07c257078776843a4bea60ab69db94b9cc3c1da/OpenSim/Moco/Test/testMocoContact.cpp#L541)):*
> ```cpp
> 
> TEMPLATE_TEST_CASE("testStationPlaneContactForce", "[tropter]", 
>         /*AckermannVanDenBogert2010Force, EspositoMiller2018Force,*/
> ```

The tests are still passing with the other contact models, then I would leave those models uncommented here.
___
*[`OpenSim/Simulation/Model/StationPlaneContactForce.h` line 32 at r7](https://reviewable.io/reviews/opensim-org/opensim-core/3877#-O7jBvQI5T_Jq949QefC:-O7jBvQJ13F61QfD9-Lq:undefined) ([raw file](https://github.com/opensim-org/opensim-core/blob/a07c257078776843a4bea60ab69db94b9cc3c1da/OpenSim/Simulation/Model/StationPlaneContactForce.h#L32)):*
> ```objc
> Vertical force is calculated using stiffness and dissipation coefficients, 
> while horizontal force is calculated using a friction model. Multiple concrete 
> implementation of this class are available, but currently MeyerFregly2016Force 
> ```





_Suggestion:_
```objc
implementations of this class are available, but currently MeyerFregly2016Force
```

**Comment by SpencerTWilliams** [comment]
I added a `TEST_CASE` based on how the others were set up. These calculations are specific to the type of model, so I made the test specific to the `MeyerFregly2016Force`.

**Review by nickbianco — COMMENTED** [review]
I just enabled the CI given the recent test changes, let's see if they pass! You should also be able to run the test suite locally.

> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3877#-:-O7oQwK0ENbbfVMhIz3O:bz550i4)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SpencerTWilliams)

**Comment by nickbianco** [comment]
@SpencerTWilliams, the configuration step in these steps are failing because the [CMakeLists.txt file in OpenSim/Moco is looking for `StationPlaneContactForce`](https://github.com/opensim-org/opensim-core/blob/cbf9c74c065194dd4ac2d350bbd580a09a575848/OpenSim/Moco/CMakeLists.txt#L89), but it is no longer there. The lines for those components need to be removed. 

The CI failures on Windows and Mac are unrelated, a fix is in the works for those (#3921).

**Review by nickbianco — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3877)* status: 10 of 11 files reviewed, 1 unresolved discussion (waiting on @SpencerTWilliams)

___
*[`OpenSim/Moco/Test/testMocoContact.cpp` line 646 at r9](https://reviewable.io/reviews/opensim-org/opensim-core/3877#-O9L4sth2gL-ukLtqdWg:-O9L4sth2gL-ukLtqdWh:b-cdutxg) ([raw file](https://github.com/opensim-org/opensim-core/blob/5a26b492d43b0f69997e7b141381666dcd0b4f55/OpenSim/Moco/Test/testMocoContact.cpp#L646)):*
> ```cpp
> 
> TEST_CASE("testMeyerFregly2016ForceValues", "[casadi]") {
>     testKnownKinematics();
> ```

Since `testKnownKinematics()` only tests the `MeyerFregly2016Force` component, I think you could just move that code directly in to this `TEST_CASE`.

**Review by nickbianco — COMMENTED** [review]
@SpencerTWilliams I've resolved the merge conflicts and left another minor comment. Let's see if the tests pass!

> Reviewed 1 of 3 files at r9.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3877#-:-O9L5CwzEykmYCG9zt1A:bcnzph0)* status: all files reviewed, 1 unresolved discussion (waiting on @SpencerTWilliams)

**Review by nickbianco — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3877)* status: all files reviewed, 3 unresolved discussions (waiting on @SpencerTWilliams)

___
*[`OpenSim/Simulation/Model/StationPlaneContactForce.h` line 180 at r10](https://reviewable.io/reviews/opensim-org/opensim-core/3877#-O9_ahGf5-Oy_lo0oSwf:-O9_ahGf5-Oy_lo0oSwg:bpjxume) ([raw file](https://github.com/opensim-org/opensim-core/blob/a605a24f53086b5483fa19ce0a024390dd2ce0b1/OpenSim/Simulation/Model/StationPlaneContactForce.h#L180)):*
> ```objc
> 
>         /// Normal force.
>         y = y - resting_length;
> ```

`y` was marked as `const` above, so you cannot update it like this. You either need to remove the `const` qualifier above or assign this value to a new variable. (This is causing the CI to fail)
___
*[`OpenSim/Simulation/Model/StationPlaneContactForce.cpp` line 39 at r10](https://reviewable.io/reviews/opensim-org/opensim-core/3877#-O9_bC4ODaq3pyvE-o-7:-O9_bC4ODaq3pyvE-o-8:bkomxyi) ([raw file](https://github.com/opensim-org/opensim-core/blob/a605a24f53086b5483fa19ce0a024390dd2ce0b1/OpenSim/Simulation/Model/StationPlaneContactForce.cpp#L39)):*
> ```cpp
>         const auto& pt = getConnectee<Station>("station");
>         const auto pt1 = pt.getLocationInGround(s);
>         const SimTK::Vec3 force = calcContactForceOnStation(s);
> ```

CI is failing here because you need to update to the new method name: 



_Suggestion:_
```cpp
        const SimTK::Vec3 force = computeContactForceOnStation(s);
```

**Comment by nickbianco** [comment]
@SpencerTWilliams, I left a few comments on why the CI builds are failing. These are compile time errors, so I would recommend recompiling locally to catch these and any other compile errors still lingering. I would also recommend running the tests locally so you don't have to wait on CI to see if they pass or fail.

**Comment by SpencerTWilliams** [comment]
Thanks for the advice on handling the tests. For running tests locally, I've been having trouble modifying the build script to compile my fork with tests on Linux, which I had thought would be more convenient at first. 

I remember you had mentioned that you used CMake when you ran tests locally, so do you have directions I can follow for using CMake to compile and run OpenSim tests on Windows?

**Comment by nickbianco** [comment]
The C++ tests will be built by default, I don't think we have any CMake options to turn them off. I usually run tests locally through VS Code, but you can always run the compiled `testMocoContact` from the terminal.

**Comment by SpencerTWilliams** [comment]
Are there any changes I might need to make to compile with CMake locally? When I try to build through VS Code, I get this error:

```
[cmake] CMake Error at CMakeLists.txt:713 (find_package):
[cmake]   Could not find a package configuration file provided by "spdlog" with any
[cmake]   of the following names:
[cmake] 
[cmake]     spdlogConfig.cmake
[cmake]     spdlog-config.cmake
[cmake] 
[cmake]   Add the installation prefix of "spdlog" to CMAKE_PREFIX_PATH or set
[cmake]   "spdlog_DIR" to a directory containing one of the above files.  If "spdlog"
[cmake]   provides a separate development package or SDK, be sure it has been
[cmake]   installed.
```

I haven't changed the directory structure from the main branch of OpenSim, so I was wondering if it's a machine-specific issue.

**Comment by SpencerTWilliams** [comment]
Thanks, that error was fixed by building `dependencies` first! I did build OpenSim on Linux previously, but that was from the .sh build script, which clones OpenSim from the main branch before building. I also don't think it includes tests, so I wasn't sure how I needed to modify that script. 

With CMake, I"m still getting a similar error:

```
[cmake]   Could not find a package configuration file provided by "casadi" (requested
[cmake]   version 3.4.4) with any of the following names:
[cmake] 
[cmake]     casadiConfig.cmake
[cmake]     casadi-config.cmake
[cmake] 
[cmake]   Add the installation prefix of "casadi" to CMAKE_PREFIX_PATH or set
[cmake]   "casadi_DIR" to a directory containing one of the above files.  If "casadi"
[cmake]   provides a separate development package or SDK, be sure it has been
[cmake]   installed.
```

It looks like it would be the same sort of issue of needing to find a directory to build first, but I can't tell where this is. Do you have a guide for which directories I should build from before the project will work?

**Comment by nickbianco** [comment]
To build CasADi, you'll need to enable the `OPENSIM_WITH_CASADI` CMake variable. I'd try to follow the CMake settings in the build scripts for other settings.

**Comment by SpencerTWilliams** [comment]
From the build script, I can see that CMake is only used to build dependencies and then at the opensim-core, level, so this should be the last use of CMake, then. For the `OPENSIM_WITH_CASADI` variable, I have this on lines 192-193 in `CMakeLists.txt`:

```
option(OPENSIM_WITH_CASADI
        "Build CasADi support for Moco (MocoCasADiSolver)." ON)
```

If `OPENSIM_WITH_CASADI` is already enabled, is there something else CMake could be missing at this point, or something with CasADi I need to install before this will work?

**Comment by nickbianco** [comment]
Sorry, you also need to set that flag when building the dependencies.

**Comment by SpencerTWilliams** [comment]
Thanks, that was turned off in the dependencies. I built the dependencies again with that flag enabled, but I'm getting the same error at the core level. In the dependencies, am I supposed to see a directory for CasADi? I'm only seeing `catch2`, `docopt`, `simbody`, and `spdlog`.

**Comment by SpencerTWilliams** [comment]
I'm not getting a `CMakeCache.txt` file, so I don't think it's a caching issue. I met with Dr. Fregly, and he'll email you about our next steps for finishing this in a minute.

**Comment by nickbianco** [comment]
Closing. Work continuing on #3949.

**Pull request closed without merging**
