### PR TITLE
Disable the stock python autodoc feature in favor of doxygen

### PR DESCRIPTION
**Pull request by aymanhab**
Fixes issue #3033 

### Testing I've completed
Skim through some .py files
### Looking for feedback on...
Availability of Doxygen in Python environment/IDE
### CHANGELOG.md (choose one)

- no need to update because bug-fix

---
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3046)

### CODE REVIEW

**Comment by aymanhab** [comment]
Either @nickbianco or @carmichaelong to see how the doxygen appears in typical Python IDE/environment

**Comment by carmichaelong** [comment]
Check it out!

image

**Comment by nickbianco** [comment]
That's awesome! Looks great.

**Comment by aymanhab** [comment]
Excellent, thanks for testing @carmichaelong  it sure saves our python users digging in the CPP doxygen online.

**Comment by carmichaelong** [comment]
Agreed, FYI, I was looking at a random set of classes, and documentation with examples looks really nice (e.g. MocoInverse below):
image
image

**Comment by aymanhab** [comment]
Super, I wish we had it for this workshop but better late than never..

**Comment by aymanhab** [comment]
@carmichaelong  Would be great to approve this PR or let me know if you found issues that need to be addressed for approval. Thank you

**Review by carmichaelong — APPROVED** [review]
Whoops sorry thought for some reason you might still be working on stuff and just needed a spot check to keep going. LGTM

**Comment by aymanhab** [comment]
Thanks @carmichaelong much appreciated 👍

**Pull request merged**
