### PR TITLE
Fix ik memleak

### PR DESCRIPTION
**Pull request by aymanhab**
Fixes issue #3220

### Brief summary of changes
Delete model if owned by tool and allow Kinematics analysis to release the memory/storages it allocated on destruction 
### Testing I've completed
Valgrind doesn't show leaks in ik

### CHANGELOG.md (choose one)

- updated.

---
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3217)

### CODE REVIEW

**Comment by aymanhab** [comment]
This fixes the leak in IK and in Kinematics analysis reported on forum 
https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=91&t=14714&p=0&start=0&view=&sid=f5aa12579451413b33dff9a4fe5f71fe

**Review by carmichaelong — COMMENTED** [review]
Thanks @aymanhab this is looking good to me. Could you just also add a quick update to the CHANGELOG too?

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3217#-:-N4-Oyrp6YS5s2F-m6OS:byymc4y)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @aymanhab)

**Comment by aymanhab** [comment]
Done, thanks @carmichaelong 👍

**Review by carmichaelong — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3217#-:-N40ALwv64YnmYCtC7KH:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @aymanhab)

**Pull request merged**
