### PR TITLE
Fix matlab tests

### PR DESCRIPTION
**Pull request by aymanhab**
Fixes issue #0

### Brief summary of changes
fix 2 matlab test cases ta\hat fail locally
### Testing I've completed
ran tests locally and they pass,  one failure left Matlab_MocoWorkflow_Release though the problem solves, may need a look by @nickbianco to understand the issue

### CHANGELOG.md (choose one)

- no need to update because Matlab tests are not exposed to users

- - -
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3886)

### CODE REVIEW

**Comment by aymanhab** [comment]
@nickbianco This should fix the lingering matlab test failures for developers who happen to have matlab locally installed. Also to make our published codebase/tests consistent with our own API. Not urgent since broken for years..

**Review by nickbianco — APPROVED** [review]
Looks good! I just had one quick comment, but it's not blocking.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3886#-:-O7kPlzbCxP8P9okabhL:b-woz9ml)* status: all files reviewed, 1 unresolved discussion (waiting on @aymanhab)

___
*[`Bindings/Java/Matlab/tests/testOsimC3D.m` line 111 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3886#-O7kPaD9BKxNV3whHgmw:-O7kPaD9BKxNV3whHgmx:barz5s6) ([raw file](https://github.com/opensim-org/opensim-core/blob/ca0aaf21af4648d068090db23e737d6f2cfc5491/Bindings/Java/Matlab/tests/testOsimC3D.m#L111)):*
> ```objc
>             assert(abs(d.get(0)-d_m.get(0))<.001,'Force Data has been incorrectly altered');
>             assert(abs(d.get(1)-d_m.get(1))<.001,'Force Data has been incorrectly altered');
>             assert(abs(d.get(2)-d_m.get(2))<.001,'Force Data has been incorrectly altered');
> ```

I assume these tests were failing to some relatively high precision?

**Comment by aymanhab** [comment]
Thanks @nickbianco The old test was using plain equality of doubles after performing transformation/matrixt multiplication!

**Comment by aymanhab** [comment]
Thanks @nickbianco 👍

**Pull request merged**
