### PR TITLE
Adding pseudospectral collocation schemes to Moco

### PR DESCRIPTION
**Pull request by nickbianco**
This PR addes pseudospectral collocation schemes to Moco, as described in #3527.

### Brief summary of changes
- Added two new transcription schemes to CasADi, `CasOCLegendreGauss` and `CasOCLegendreGaussRadau` for the Gauss Pseudospectral Method (GPM) and Radau Pseudospectral Method (RPM), respectively. The names reflect the Legendre polynomial roots used in each scheme.
- Updates to `MocoCasADiSolver` to make these schemes available to `MocoStudy`. 

### Testing I've completed
- Tests have been added and/or updated in `testMocoAnalytic`, `testMocoActuators`, and `testMocoInterface` to test the new schemes.

### Looking for feedback on...
I'm 99% sure I implemented the schemes correctly, however I encountered some difficulty when testing the schemes on the "linear tangent steering" problem in `testMocoAnalytic`. Initially, running this test with `legendre-gauss-3` would cause the problem to almost immediately go into restoration mode in IPOPT. I updated some solver settings, including scaling problem variables, changing the CasADi finite differencing method, and reducing the number of variables (MUMPS was complaining about a memory issue at one point), and this helped with convergence.

My guess is that this problem has some unique numerical difficulties that come up if you're not careful with solver settings. However, I would appreciate a second eye on the testing changes I made so we're fully confident before merging. I did write a Matlab script in CasADi to test the problem formulation, and that seems more stable than the Moco implementation -- but that problem also had the benefit of true automatic differentiation, so it's a bit hard to compare.

I'm assigning @carmichaelong to review this, but @antoinefalisse and @nicos1993, if you have some time to look over the OCP details, that would be super helpful!

### CHANGELOG.md (choose one)

- updated.

- - -
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3534)

### CODE REVIEW

**Comment by antoinefalisse** [comment]
Will take a look next week.

**Comment by nicos1993** [comment]
I will take a look!

**Review by carmichaelong — CHANGES_REQUESTED** [review]
Code is looking good overall (I tried to take a careful look at all the details and indices and didn't catch any errors there). There's one (very minor) question and some documentation to address.

> Reviewed 5 of 10 files at r1, 1 of 1 files at r2, 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3534#-:-NcydtgJ1wkryBfY--ow:bjl7b65)* status: 6 of 11 files reviewed, 2 unresolved discussions (waiting on @nickbianco)

___
*[`OpenSim/Moco/MocoCasADiSolver/CasOCLegendreGauss.cpp` line 40 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3534#-NcieYK0Cio69X022MH2:-NcieYK0Cio69X022MH3:b2lhonn) ([raw file](https://github.com/opensim-org/opensim-core/blob/19e66b72e23da959ded7e6720255b51d7282487a/OpenSim/Moco/MocoCasADiSolver/CasOCLegendreGauss.cpp#L40)):*
> ```cpp
>         const int igrid = imesh * (m_degree + 1);
>         // There are no quadrature coefficients at the mesh points (i.e.,
>         // quadCoeffs(igrid) = 0.0).
> ```

Q: does this imply that the line above `DM quadCoeffs(m_numGridPoints, 1);` initializes `quadCoeffs` as all 0's upon construction? (no need to update any comments or code if that's the case)
___
*[`OpenSim/Moco/MocoCasADiSolver/CasOCLegendreGaussRadau.h` line 25 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3534#-NcihNX9DArY_aztsoXR:-NcihNX9DArY_aztsoXS:b-rebloc) ([raw file](https://github.com/opensim-org/opensim-core/blob/19e66b72e23da959ded7e6720255b51d7282487a/OpenSim/Moco/MocoCasADiSolver/CasOCLegendreGaussRadau.h#L25)):*
> ```objc
> namespace CasOC {
> 
> /// Enforce the differential equations in the problem using pseudospectral
> ```

these comments seem to be exactly the same as in `CasOCLegendreGauss.h`

**Review by nickbianco — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3534)* status: 6 of 11 files reviewed, 2 unresolved discussions (waiting on @carmichaelong and @nickbianco)

___
*[`OpenSim/Moco/MocoCasADiSolver/CasOCLegendreGauss.cpp` line 40 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3534#-NcieYK0Cio69X022MH2:-NczEEaxApWnNqbSrYRj:bdkbqhj) ([raw file](https://github.com/opensim-org/opensim-core/blob/19e66b72e23da959ded7e6720255b51d7282487a/OpenSim/Moco/MocoCasADiSolver/CasOCLegendreGauss.cpp#L40)):*
<details><summary><i>Previously, carmichaelong wrote…</i></summary><blockquote>

Q: does this imply that the line above `DM quadCoeffs(m_numGridPoints, 1);` initializes `quadCoeffs` as all 0's upon construction? (no need to update any comments or code if that's the case)
</blockquote></details>

Yes, that is correct.
___
*[`OpenSim/Moco/MocoCasADiSolver/CasOCLegendreGaussRadau.h` line 25 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3534#-NcihNX9DArY_aztsoXR:-NczEIL0CseLSKLqOyrn:b-rumsw8) ([raw file](https://github.com/opensim-org/opensim-core/blob/19e66b72e23da959ded7e6720255b51d7282487a/OpenSim/Moco/MocoCasADiSolver/CasOCLegendreGaussRadau.h#L25)):*
<details><summary><i>Previously, carmichaelong wrote…</i></summary><blockquote>

these comments seem to be exactly the same as in `CasOCLegendreGauss.h`
</blockquote></details>

I've updated the comments.

**Review by nickbianco — COMMENTED** [review]
Thanks @carmichaelong! Ready for review.

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3534#-:-NczEP2U0EH9aHIuqJyb:b-oexq78)* status: 6 of 11 files reviewed, 2 unresolved discussions (waiting on @carmichaelong and @nickbianco)

**Review by carmichaelong — CHANGES_REQUESTED** [review]
Thanks! Just a few minor notes on the documentation.

> Reviewed 1 of 10 files at r1, 1 of 2 files at r3, 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3534#-:-Nd1Pg5M2fVJrBZjaTGU:bvyozt8)* status: all files reviewed (commit messages unreviewed), 3 unresolved discussions (waiting on @nickbianco)

___
*[`OpenSim/Moco/MocoCasADiSolver/CasOCLegendreGauss.h` line 41 at r4](https://reviewable.io/reviews/opensim-org/opensim-core/3534#-Nd1O6vR2kwyBM2fJPZ0:-Nd1O6vR2kwyBM2fJPZ1:b-3wzudy) ([raw file](https://github.com/opensim-org/opensim-core/blob/b27491759f8c498129bd9aa2b061b7102d6b62da/OpenSim/Moco/MocoCasADiSolver/CasOCLegendreGauss.h#L41)):*
> ```objc
> /// mesh interval endpoint.
> ///
> /// Control approximation.
> ```

Could consider removing the first sentence here, or at least flipping the two sentences so that the details of what's implemented at least come first
___
*[`OpenSim/Moco/MocoCasADiSolver/CasOCLegendreGauss.h` line 43 at r4](https://reviewable.io/reviews/opensim-org/opensim-core/3534#-Nd1Nt8p0qOz646rRItI:-Nd1Nt8p0qOz646rRItJ:brmkwen) ([raw file](https://github.com/opensim-org/opensim-core/blob/b27491759f8c498129bd9aa2b061b7102d6b62da/OpenSim/Moco/MocoCasADiSolver/CasOCLegendreGauss.h#L43)):*
> ```objc
> /// Control approximation.
> /// ----------------------
> /// In [1, 2], the control is approximated using of basis of Lagrange polynomials
> ```

using *a* basis?
___
*[`OpenSim/Moco/MocoCasADiSolver/CasOCLegendreGaussRadau.h` line 42 at r4](https://reviewable.io/reviews/opensim-org/opensim-core/3534#-Nd1OlffBkrq9r3muBuy:-Nd1OlffBkrq9r3muBuz:be9qhxe) ([raw file](https://github.com/opensim-org/opensim-core/blob/b27491759f8c498129bd9aa2b061b7102d6b62da/OpenSim/Moco/MocoCasADiSolver/CasOCLegendreGaussRadau.h#L42)):*
> ```objc
> /// Control approximation.
> /// ----------------------
> /// In [1, 2], the control is approximated using of basis of Lagrange polynomials
> ```

Same comments as in the other header:
- of -> a(?)
- consider putting what's implemented first (either by removing the first sentence or rearranging)

**Comment by nickbianco** [comment]
@carmichaelong, ready for review (just realized I never pinged you).

**Review by carmichaelong — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3534#-:-NdH5bEZA_E6P1FiEkNh:bnfp4nl)* status: all files reviewed (commit messages unreviewed), 3 unresolved discussions (waiting on @nickbianco)

**Pull request merged**
