### PR TITLE
Add progress messages to tests

### PR DESCRIPTION
**Pull request by tkuchida**
Currently, testSTOFileAdapter and testTRCFileAdapter don't display anything while they are running, which is indistinguishable from malfunction. Added progress messages.

### CODE REVIEW

**Comment by chrisdembia** [comment]
LGTM!

**Comment by klshrinidhi** [comment]
:+1:

**Comment by chrisdembia** [comment]
I have not seen that Java_TestEditProperties timeout failure before but it is almost certainly unrelated. @tkuchida please merge once the tests pass.

**Comment by aymanhab** [comment]
Yes, completely unrelated, I wouldn't hold this PR for it.

**Pull request merged**
