### PR TITLE
Fix IDTool and IDSolver to account for extra q's in state

### PR DESCRIPTION
**Pull request by carmichaelong**
Fixes issue #2935 

### Brief summary of changes
- fix how IDTool orders coordinate splines to pass to IDSolver, and account for unused q slots
- allow IDSolver to be used when nq != nu
- new ID test with ThorascapularShoulderModel

### Testing I've completed
New test in testID. All other tests pass locally.

### CHANGELOG.md
- updated

---
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2971)

### CODE REVIEW

**Comment by carmichaelong** [comment]
@aymanhab @nickbianco I put you both on just in case one of you got to it first, but I think no need for both?

/cc @aseth1 @antoinefalisse might be interested to see these changes too

**Review by aymanhab — CHANGES_REQUESTED** [review]
> Reviewed 6 of 7 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2971)* status: all files reviewed, 5 unresolved discussions (waiting on @carmichaelong and @nickbianco)

___
*[Applications/ID/test/ThoracoscapularShoulderModel.osim, line 0 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/2971#-MUt6XipBRR-EVJN6Vpa:-MUt6XipBRR-EVJN6Vpb:b-851vpc) ([raw file](https://github.com/opensim-org/opensim-core/blob/1b266f0a456c73295e20e121f88ea569f6d3bf52/Applications/ID/test/ThoracoscapularShoulderModel.osim#L0)):*
If this is the model off the shelf, I'd put it in a common place e.g. OpenSim\Tests\shared so it can be re-used and avoid duplication.
___
*[Applications/ID/test/testID.cpp, line 60 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/2971#-MUt86mt30gXgR_Pl3QK:-MUt86mt30gXgR_Pl3QL:b-v2pgt6) ([raw file](https://github.com/opensim-org/opensim-core/blob/1b266f0a456c73295e20e121f88ea569f6d3bf52/Applications/ID/test/testID.cpp#L60)):*
> ```cpp
>         testThoracoscapularShoulderModel();
>         cout << "testThoracoscapularShoulderModel passed" << endl;
>     }
> ```

The model is actually called Scapulothoracic but shouldn't matter :smiley: 
___
*[Applications/ID/test/testID.cpp, line 120 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/2971#-MUtMPqcAWXD_1ylX40W:-MUtMPqd5ZTxjX38uYSr:bss6j6d) ([raw file](https://github.com/opensim-org/opensim-core/blob/1b266f0a456c73295e20e121f88ea569f6d3bf52/Applications/ID/test/testID.cpp#L120)):*
> ```cpp
>             genForce += "_force";
>         }
>         int colInd = (int)idToolTable.getColumnIndex(genForce);
> ```

May not be relevant for this specific model but how are coupled types handled by ID? Something feels wrong without 'else' clause for the last 'if'
___
*[OpenSim/Tools/InverseDynamicsTool.cpp, line 264 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/2971#-MUtNIj_3rZZ_wgi5TYz:-MUtNIj_3rZZ_wgi5TZ-:b-y77pnb) ([raw file](https://github.com/opensim-org/opensim-core/blob/1b266f0a456c73295e20e121f88ea569f6d3bf52/OpenSim/Tools/InverseDynamicsTool.cpp#L264)):*
> ```cpp
>         // Initialize the model's underlying computational system and get its default state.
>         SimTK::State& s = _model->initSystem();
>         auto coords = _model->getCoordinatesInMultibodyTreeOrder();
> ```

A high level comment explaining what's happening here and why is a must for future code maintenance.
___
*[OpenSim/Tools/InverseDynamicsTool.cpp, line 278 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/2971#-MUtNqIz4w3xWonJM7LK:-MUtNqIz4w3xWonJM7LL:b3aka3) ([raw file](https://github.com/opensim-org/opensim-core/blob/1b266f0a456c73295e20e121f88ea569f6d3bf52/OpenSim/Tools/InverseDynamicsTool.cpp#L278)):*
> ```cpp
>                 std::string svName = c.first;
>                 ComponentPath path(svName);
>                 std::string coordName = path.getSubcomponentNameAtLevel(
> ```

Can you explain the reason for the level -2 for the next developer up, please

**Review by carmichaelong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2971)* status: 6 of 7 files reviewed, 5 unresolved discussions (waiting on @aymanhab and @nickbianco)

___
*[Applications/ID/test/ThoracoscapularShoulderModel.osim, line  at r3](https://reviewable.io/reviews/opensim-org/opensim-core/2971#-MUt6XipBRR-EVJN6Vpa:-MUtlcyp5fqhM3ibzT2Y:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/1b266f0a456c73295e20e121f88ea569f6d3bf52/Applications/ID/test/ThoracoscapularShoulderModel.osim#L)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

If this is the model off the shelf, I'd put it in a common place e.g. OpenSim\Tests\shared so it can be re-used and avoid duplication.
</blockquote></details>

Done.
___
*[Applications/ID/test/testID.cpp, line 60 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/2971#-MUt86mt30gXgR_Pl3QK:-MUtQsGq9W63R6qvpBwW:b-s1eget) ([raw file](https://github.com/opensim-org/opensim-core/blob/1b266f0a456c73295e20e121f88ea569f6d3bf52/Applications/ID/test/testID.cpp#L60)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

The model is actually called Scapulothoracic but shouldn't matter :smiley: 
</blockquote></details>

Agreed! I went with what the model file name was from the simtk project
___
*[Applications/ID/test/testID.cpp, line 120 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/2971#-MUtMPqcAWXD_1ylX40W:-MUtPN5b7biFoWjOO9PB:b-cj40lu) ([raw file](https://github.com/opensim-org/opensim-core/blob/1b266f0a456c73295e20e121f88ea569f6d3bf52/Applications/ID/test/testID.cpp#L120)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

May not be relevant for this specific model but how are coupled types handled by ID? Something feels wrong without 'else' clause for the last 'if'
</blockquote></details>

Good point. Will change to align with the tool: https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Tools/InverseDynamicsTool.cpp#L351
___
*[OpenSim/Tools/InverseDynamicsTool.cpp, line 264 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/2971#-MUtNIj_3rZZ_wgi5TYz:-MUtQ9OnDur8IovlLMap:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/1b266f0a456c73295e20e121f88ea569f6d3bf52/OpenSim/Tools/InverseDynamicsTool.cpp#L264)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

A high level comment explaining what's happening here and why is a must for future code maintenance.
</blockquote></details>

Done.
___
*[OpenSim/Tools/InverseDynamicsTool.cpp, line 278 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/2971#-MUtNqIz4w3xWonJM7LK:-MUtQq7U2Bmqlk-Gu1jz:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/1b266f0a456c73295e20e121f88ea569f6d3bf52/OpenSim/Tools/InverseDynamicsTool.cpp#L278)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

Can you explain the reason for the level -2 for the next developer up, please
</blockquote></details>

Done.

**Comment by carmichaelong** [comment]
@aymanhab thanks for the review. I (tried to) address all comments in the last push. There are also a few changes that weren't in the last version that you reviewed where I put the coordinate functions on the stack because I thought some changes I made may be leaking memory and it was all for local use anyway.

**Review by aymanhab — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2971)* status: all files reviewed, 2 unresolved discussions (waiting on @carmichaelong and @nickbianco)

___
*[OpenSim/Tools/InverseDynamicsTool.cpp, line 278 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/2971#-MUtNqIz4w3xWonJM7LK:-MUyg4cc2nvoe3VLtHcr:b5o5w2w) ([raw file](https://github.com/opensim-org/opensim-core/blob/1b266f0a456c73295e20e121f88ea569f6d3bf52/OpenSim/Tools/InverseDynamicsTool.cpp#L278)):*
<details><summary><i>Previously, carmichaelong wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This precludes using models with unique coordinate Path but non-unique name, e.g. r_hip/flexion and l_hip/flexion, can we use the full ComponentPath as key? I understand some old mot/sto files fails that but wanted to bounce this off you.
___
*[OpenSim/Tools/InverseDynamicsTool.cpp, line 318 at r4](https://reviewable.io/reviews/opensim-org/opensim-core/2971#-MUw9zB0CADtayFPma2G:-MUw9zB1-Zh5PuSpxxn_:b-553k0l) ([raw file](https://github.com/opensim-org/opensim-core/blob/569d8894b47308dfe75f4613279daa9cbbbd6790/OpenSim/Tools/InverseDynamicsTool.cpp#L318)):*
> ```cpp
>             // Create differentiable splines of the coordinate data
>             GCVSplineSet coordSplines = GCVSplineSet(5, _coordinateValues);
> ```

No need to make a copy and assign here, just use the line to construct inplace
 GCVSplineSet coordSplines(5, _coordinateValues) ;

**Review by nickbianco — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2971)* status: all files reviewed, 3 unresolved discussions (waiting on @carmichaelong)

___
*[OpenSim/Tools/InverseDynamicsTool.cpp, line 267 at r4](https://reviewable.io/reviews/opensim-org/opensim-core/2971#-MUzN-a91GU6xMKYjs-q:-MUzN-aAEcM2GJxFv3I2:b7g37rx) ([raw file](https://github.com/opensim-org/opensim-core/blob/569d8894b47308dfe75f4613279daa9cbbbd6790/OpenSim/Tools/InverseDynamicsTool.cpp#L267)):*
> ```cpp
>         // Need to map the indices with the State's q's indices, which are
>         // not necessarily in the same order or even the same length. The
>         // State's q may be longer due, e.g. unused slots for quaternions
> ```

Add a brief comment about the difference between q's in the State (i.e.,`SimTK::State.getQ()`) versus an OpenSim::Coordinate.

**Comment by carmichaelong** [comment]
@aymanhab @nickbianco Thanks for the feedback during dev meeting and over GitHub. FYI, I realized this morning that simply reordering the q's is not sufficient because of the code in `InverseDynamicsSolver` at [these lines](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Simulation/InverseDynamicsSolver.cpp#L117), which assumes that q' = u. I'm working on a minimal change to the `InverseDynamicsSolver` to handle this, likely by adding another `solve()` function and fixing the current `solve()` function to correctly throw when nq != nu.

**Review by carmichaelong — COMMENTED** [review]
@aymanhab @nickbianco Should be good for another round of reviews. The logic is getting a bit more complicated, and I was having trouble finding the words for some of the comments, so I'm happy to go back and forth to make sure it's understandable for others

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2971#-:-MV7g9GA4S_gd2crPji1:be8e354)* status: 6 of 9 files reviewed, 3 unresolved discussions (waiting on @aymanhab and @nickbianco)

___
*[OpenSim/Tools/InverseDynamicsTool.cpp, line 267 at r4](https://reviewable.io/reviews/opensim-org/opensim-core/2971#-MUzN-a91GU6xMKYjs-q:-MV4EkZm3Rf0sFnA9kwq:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/569d8894b47308dfe75f4613279daa9cbbbd6790/OpenSim/Tools/InverseDynamicsTool.cpp#L267)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

Add a brief comment about the difference between q's in the State (i.e.,`SimTK::State.getQ()`) versus an OpenSim::Coordinate.
</blockquote></details>

Done.
___
*[OpenSim/Tools/InverseDynamicsTool.cpp, line 318 at r4](https://reviewable.io/reviews/opensim-org/opensim-core/2971#-MUw9zB0CADtayFPma2G:-MV4ACmA-Axhug5RK8TA:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/569d8894b47308dfe75f4613279daa9cbbbd6790/OpenSim/Tools/InverseDynamicsTool.cpp#L318)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

No need to make a copy and assign here, just use the line to construct inplace
 GCVSplineSet coordSplines(5, _coordinateValues) ;
</blockquote></details>

Done.

**Review by aymanhab — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2971)* status: all files reviewed, 5 unresolved discussions (waiting on @carmichaelong and @nickbianco)

___
*[OpenSim/Tools/InverseDynamicsTool.cpp, line 268 at r5](https://reviewable.io/reviews/opensim-org/opensim-core/2971#-MVI-K5t1eNubES3oOW5:-MVI-K5u5V6HDeUnyqFp:b-gw4sp9) ([raw file](https://github.com/opensim-org/opensim-core/blob/c94227392de36b8927c97c10cc805b85f3a02aab/OpenSim/Tools/InverseDynamicsTool.cpp#L268)):*
> ```cpp
>         // Each Coordinate's value and speed each correspond to an index
>         // in the model's underlying SimTK::State (value to a slot in the
>         // State's q, and speed to a slot in the State's u).
> ```

Coordinate's => Coordinates
value and speed each correspond => value and speed maps 
___
*[OpenSim/Tools/InverseDynamicsTool.cpp, line 270 at r5](https://reviewable.io/reviews/opensim-org/opensim-core/2971#-MVI-jiz05Tat73PhvNL:-MVI-jiz05Tat73PhvNM:b-chpu4b) ([raw file](https://github.com/opensim-org/opensim-core/blob/c94227392de36b8927c97c10cc805b85f3a02aab/OpenSim/Tools/InverseDynamicsTool.cpp#L270)):*
> ```cpp
>         // State's q, and speed to a slot in the State's u).
>         // So we need to map each OpenSim::Coordinate value and speed with the
>         // corresponding SimTK::State's q and u indices, respectively.
> ```

with => to
___
*[OpenSim/Tools/InverseDynamicsTool.cpp, line 283 at r5](https://reviewable.io/reviews/opensim-org/opensim-core/2971#-MVI-vJC3HUGmWxS4ySn:-MVI-vJDBz728z5Kujta:bta2gnl) ([raw file](https://github.com/opensim-org/opensim-core/blob/c94227392de36b8927c97c10cc805b85f3a02aab/OpenSim/Tools/InverseDynamicsTool.cpp#L283)):*
> ```cpp
>         auto coordMap = createSystemYIndexMap(*_model);
>         std::vector<int> coordIndsForEachQ(nq, intUnusedSlot);
>         std::vector<int> coordIndsForEachU(nu, intUnusedSlot);
> ```

Not sure what the additional 'Each' in variable names add to the meaning but can live with it.
___
*[OpenSim/Tools/InverseDynamicsTool.cpp, line 286 at r5](https://reviewable.io/reviews/opensim-org/opensim-core/2971#-MVI09geB-_e189jst1K:-MVI09geB-_e189jst1L:b-s4692q) ([raw file](https://github.com/opensim-org/opensim-core/blob/c94227392de36b8927c97c10cc805b85f3a02aab/OpenSim/Tools/InverseDynamicsTool.cpp#L286)):*
> ```cpp
>         for (const auto& c : coordMap) {
>             std::cout << c.first << " " << c.second << std::endl;
>             // SimTK::State layout is [q u z] 
> ```

Is this debugging code? If so use log_debug or remove

**Review by nickbianco — CHANGES_REQUESTED** [review]
Left a few comments, but changes LGTM. Would it be difficult to add a test case that isn't static so we don't miss this error during testing?

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2971#-:-MVI76LKDwJOqc4pbEzq:bmum30l)* status: all files reviewed, 6 unresolved discussions (waiting on @aymanhab and @carmichaelong)

___
*[OpenSim/Simulation/InverseDynamicsSolver.h, line 115 at r5](https://reviewable.io/reviews/opensim-org/opensim-core/2971#-MVI5gimDxguBDPUBS1t:-MVI5gin1iaXta2glWNY:bw95b6z) ([raw file](https://github.com/opensim-org/opensim-core/blob/c94227392de36b8927c97c10cc805b85f3a02aab/OpenSim/Simulation/InverseDynamicsSolver.h#L115)):*
> ```objc
> 
>     /** Same as above but for a given time series populate an Array (trajectory)
>        of generalized-coordinate forces (Vector), but can be used when dot != u.
> ```

The two "buts" here are confusing. Did you mean "...forces (Vector) that can be used..."?
___
*[OpenSim/Simulation/InverseDynamicsSolver.h, line 116 at r5](https://reviewable.io/reviews/opensim-org/opensim-core/2971#-MVI5sYjDqN3r2KbzKgY:-MVI5sYjDqN3r2KbzKgZ:b-alxwz5) ([raw file](https://github.com/opensim-org/opensim-core/blob/c94227392de36b8927c97c10cc805b85f3a02aab/OpenSim/Simulation/InverseDynamicsSolver.h#L116)):*
> ```objc
>     /** Same as above but for a given time series populate an Array (trajectory)
>        of generalized-coordinate forces (Vector), but can be used when dot != u.
>        This adds an extra vector, QIndsForEachU, which is the length of number of
> ```

"This includes an additional vector argument...". 

Also, consider a clearer name for 'QIndsForEachU' that uses full words (e.g., `indexMapQToU`, or even better, `indexMapCoordinatesToSpeeds` or `coordinatesToSpeedsIndexMap`. Also see comment below.
___
*[OpenSim/Tools/InverseDynamicsTool.cpp, line 283 at r5](https://reviewable.io/reviews/opensim-org/opensim-core/2971#-MVI-vJC3HUGmWxS4ySn:-MVI4WL0-9UrK7itN_kh:b3s215a) ([raw file](https://github.com/opensim-org/opensim-core/blob/c94227392de36b8927c97c10cc805b85f3a02aab/OpenSim/Tools/InverseDynamicsTool.cpp#L283)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

Not sure what the additional 'Each' in variable names add to the meaning but can live with it.
</blockquote></details>

I was thinking using something like `mapCoordinateToU`, `coordinateToUMap`, `coordinatesToSpeedsIndexMap` everywhere might be clearer.

**Review by aymanhab — CHANGES_REQUESTED** [review]
Agree with @nickbianco  

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2971#-:-MVN5_hf7Z9RgqU9nz_J:bnyvv2a)* status: all files reviewed, 6 unresolved discussions (waiting on @carmichaelong and @nickbianco)

___
*[OpenSim/Tools/InverseDynamicsTool.cpp, line 283 at r5](https://reviewable.io/reviews/opensim-org/opensim-core/2971#-MVI-vJC3HUGmWxS4ySn:-MVN5l736fJVdNKw-yxG:b-3lrmib) ([raw file](https://github.com/opensim-org/opensim-core/blob/c94227392de36b8927c97c10cc805b85f3a02aab/OpenSim/Tools/InverseDynamicsTool.cpp#L283)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

I was thinking using something like `mapCoordinateToU`, `coordinateToUMap`, `coordinatesToSpeedsIndexMap` everywhere might be clearer. 
</blockquote></details>

I guess we're in agreement that the names need improvement, the map is to an index rather than a Q/U but whatever makes sense to you while at it.

**Comment by carmichaelong** [comment]
@aymanhab spurious failure testID notes: failure is not related to comparing values. program exits with a random non-zero value. The last messages sent to the terminal:
```
[info] Running tool ...
[info] No external loads will be applied (external loads file not specified).
[info] InverseDynamicsTool: 10 time frames in 303 microsecond(s).
[info] Storage: read data file = testBallJoint_ID_output.sto (nr=10 nc=4)
```

This happened both on Mac CI. and randomly during local runs on my Windows machine. While it seems to fail randomly, it does seem to fail at the same place if it does fail (i.e., around [these lines](https://github.com/opensim-org/opensim-core/pull/2971/files#diff-1ba3258ae4f4d8f4b98503febeeaeeb7253ed33feda6b16ae797cb348e4dacb9R205) in `testBallJoint()`.

**Comment by aymanhab** [comment]
Thanks for the heads-up @carmichaelong, building locally now to test.

**Review by nickbianco — COMMENTED** [review]
> Reviewed 4 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2971)* status: all files reviewed, 6 unresolved discussions (waiting on @carmichaelong)

**Comment by aymanhab** [comment]
Call stack for crash is here
[Inline Frame] osimCommon.dll!OpenSim::ArrayPtrs<OpenSim::Property_Deprecated>::{dtor}() Line 108
	at D:\src\opensim-core\OpenSim\Common\ArrayPtrs.h(108)
osimCommon.dll!OpenSim::PropertySet::~PropertySet() Line 95
	at D:\src\opensim-core\OpenSim\Common\PropertySet.h(95)
[External Code]
[Inline Frame] osimSimulation.dll!SimTK::Array_<OpenSim::CoordinateReference,unsigned int>::destruct(OpenSim::CoordinateReference * b, const OpenSim::CoordinateReference * e) Line 3234
	at D:\build\opensim_dependencies_install\simbody\include\SimTKcommon\internal\Array.h(3234)
osimSimulation.dll!SimTK::Array_<OpenSim::CoordinateReference,unsigned int>::clear() Line 2601
	at D:\build\opensim_dependencies_install\simbody\include\SimTKcommon\internal\Array.h(2601)
[Inline Frame] osimSimulation.dll!SimTK::Array_<OpenSim::CoordinateReference,unsigned int>::deallocate() Line 1755
	at D:\build\opensim_dependencies_install\simbody\include\SimTKcommon\internal\Array.h(1755)
[Inline Frame] osimSimulation.dll!SimTK::Array_<OpenSim::CoordinateReference,unsigned int>::{dtor}() Line 1742
	at D:\build\opensim_dependencies_install\simbody\include\SimTKcommon\internal\Array.h(1742)
osimSimulation.dll!OpenSim::AssemblySolver::~AssemblySolver() Line 80
	at D:\src\opensim-core\OpenSim\Simulation\AssemblySolver.h(80)
[External Code]
[Inline Frame] osimSimulation.dll!std::default_delete<OpenSim::AssemblySolver>::operator()(OpenSim::AssemblySolver *) Line 2537
	at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include\memory(2537)
[Inline Frame] osimSimulation.dll!std::unique_ptr<OpenSim::AssemblySolver,std::default_delete<OpenSim::AssemblySolver>>::{dtor}() Line 2647
	at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include\memory(2647)
osimSimulation.dll!OpenSim::Model::~Model() Line 1039
	at D:\src\opensim-core\OpenSim\Simulation\Model\Model.h(1039)
testID.exe!testBallJoint() Line 221
	at D:\src\opensim-core\Applications\ID\test\testID.cpp(221)
testID.exe!main() Line 67
	at D:\src\opensim-core\Applications\ID\test\testID.cpp(67)
Which points to a generic crash deleting AssemblySolver for a model with a BallJoint. 
I'll investigate further keeping in mind that we rarely use BallJoints.

**Review by aymanhab — APPROVED** [review]
> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2971)* status: all files reviewed, 2 unresolved discussions (waiting on @carmichaelong)

**Comment by carmichaelong** [comment]
Thanks @aymanhab!

**Pull request merged**
