### PR TITLE
Add `ExpressionBasedFunction`

### PR DESCRIPTION
**Pull request by nickbianco**
Fixes issue #3812

### Brief summary of changes
Adds `ExpressionBasedFunction` for creating OpenSim `Function`s that leverage Lepton's expression parsing. 

### Testing I've completed
Add tests to `testFunctions.cpp`.

### CHANGELOG.md (choose one)

- updated.

- - -
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3892)

### CODE REVIEW

**Review by aymanhab — CHANGES_REQUESTED** [review]
Few minor questions but looks great

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3892#-:-O5KJqFh8p9-O9Axal6A:buoc88n)* status: all files reviewed, 2 unresolved discussions (waiting on @AllisonJohn and @nickbianco)

___
*[`OpenSim/Common/ExpressionBasedFunction.h` line 59 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3892#-O5KHK5yDtUMRhQ2bFVy:-O5KHK5yDtUMRhQ2bFVz:b-hr838t) ([raw file](https://github.com/opensim-org/opensim-core/blob/f38feba902a855e15afba6fb6cf63b9473c32479/OpenSim/Common/ExpressionBasedFunction.h#L59)):*
> ```objc
>     OpenSim_DECLARE_PROPERTY(expression, std::string, 
>             "The mathematical expression defining this Function.");
>     OpenSim_DECLARE_LIST_PROPERTY(variables, std::string, 
> ```

Space separated? Case sensitive? Quoted or not? allowed/disallowed names

On a related note, if the definition is invalid, when does it blow up? 
___
*[`OpenSim/Common/ExpressionBasedFunction.cpp` line 116 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3892#-O5KIPav6CnUElmnQ607:-O5KIPav6CnUElmnQ608:b-8mtdn9) ([raw file](https://github.com/opensim-org/opensim-core/blob/f38feba902a855e15afba6fb6cf63b9473c32479/OpenSim/Common/ExpressionBasedFunction.cpp#L116)):*
> ```cpp
>     Lepton::ExpressionProgram m_valueProgram;
>     std::vector<Lepton::ExpressionProgram> m_derivativePrograms;
> };
> ```

The prefix SimTK outside the namespace is a bit uncommon is that intentional? How would it show in documentation/doxygen?

Also is it in the style guide to use the m_ prefix?

**Review by nickbianco — COMMENTED** [review]
Thanks @aymanhab! Ready for review again.

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3892#-:-O5KxFGDD_PnBQLzS44G:bzhmxn2)* status: 7 of 9 files reviewed, 2 unresolved discussions (waiting on @AllisonJohn and @aymanhab)

___
*[`OpenSim/Common/ExpressionBasedFunction.h` line 59 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3892#-O5KHK5yDtUMRhQ2bFVy:-O5KoKUc3vZc3s9chXv2:b-i30fsd) ([raw file](https://github.com/opensim-org/opensim-core/blob/f38feba902a855e15afba6fb6cf63b9473c32479/OpenSim/Common/ExpressionBasedFunction.h#L59)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

Space separated? Case sensitive? Quoted or not? allowed/disallowed names

On a related note, if the definition is invalid, when does it blow up?
</blockquote></details>

List properties in XML will be space separated. I added some documentation about allowed/non-allowed variable names.
___
*[`OpenSim/Common/ExpressionBasedFunction.cpp` line 116 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3892#-O5KIPav6CnUElmnQ607:-O5Kmk2Z3-nHkpVq-uqT:b-qb2hsx) ([raw file](https://github.com/opensim-org/opensim-core/blob/f38feba902a855e15afba6fb6cf63b9473c32479/OpenSim/Common/ExpressionBasedFunction.cpp#L116)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

The prefix SimTK outside the namespace is a bit uncommon is that intentional? How would it show in documentation/doxygen?

Also is it in the style guide to use the m_ prefix?
</blockquote></details>

This class is internal and will be hidden from Doxgyen. See `MultivariatePolynomialFunction` for a similar implementation.

There's nothing in `DEVELOPING.md` or `CONTRIBUTING.md` about variable name prefixes.

**Review by aymanhab — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3892#-:-O5L4XZ57Lizcl1FCWSw:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AllisonJohn)

**Comment by nickbianco** [comment]
Thanks @aymanhab!

**Pull request merged**
