### PR TITLE
OpenSimConfig.cmake: if no BTK, then do not append BTK to LIB_DIR.

### PR DESCRIPTION
**Pull request by chrisdembia**
@klshrinidhi

### CODE REVIEW

**Comment by klshrinidhi** [comment]
If you are able to test it successfully, merge it. :+1:

**Comment by chrisdembia** [comment]
Tested just now, on OSX only. Is that sufficient?

**Comment by klshrinidhi** [comment]
Maybe. I can't be sure.

**Comment by chrisdembia** [comment]
I know. I mean for merging right now.

**Comment by klshrinidhi** [comment]
Go ahead and merge.

**Comment by chrisdembia** [comment]
In the future we can add a test to travis/appveyor that we can configure and build a downstream project.

**Pull request merged**
