### PR TITLE
Backport other opensim33

### PR DESCRIPTION
**Pull request by aymanhab**
Fix crash due to high DebugLevel and wrapping fixes from 3.3 (Expose CMC* classes and fix crash in ForceSet::append

### CODE REVIEW

**Comment by aymanhab** [comment]
Will address issues #446, #504

**Comment by aymanhab** [comment]
@chrisdembia These are mostly wrapping changes from 3.3, and a removal of a debugging codeblock that was crashing. Please let me know if you think it's ready to merge.

**Comment by aymanhab** [comment]
@chrisdembia can you review the changes to the test as the only material change in this PR? Are the python wrapping tests running on any of our integration environments?

**Comment by chrisdembia** [comment]
The python tests for this PR have run on Ubuntu but not on Windows; I think that's fine though. 

That debug output looks potentially useful...what do you think about leaving it in and perhaps comment it out with a note saying why they are commented out?

After that, please merge.

After you merge this PR, I'll make some additional changes to account for other changes (e.g, an extra test) that I have in my PR #495; and then we can close #495.

**Comment by aymanhab** [comment]
Thanks @chrisdembia the debug lines were removed because they were causing crashes when processing old properties (when high debug level was set issue #446)

**Comment by chrisdembia** [comment]
I knew they were causing crashes, but they seem useful as guides, perhaps if we later improve our logging.

**Comment by aymanhab** [comment]
Thanks @chrisdembia

**Pull request merged**
