### PR TITLE
Update version.h to version 4.5.1 to match intended tag for CMBBE

### PR DESCRIPTION
**Pull request by aymanhab**
Fixes issue #<issue_number>

### CHANGELOG.md (choose one)

- no need to update because...
- updated.

- - -
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3849)

### CODE REVIEW

**Review by nickbianco — APPROVED** [review]
Not sure why the CI is running tests for both the push and the PR, or why `Ubuntu2004` was failing for only one of the two. 

I re-ran that test, but I don't think it should be a hold up.

**Comment by aymanhab** [comment]
Thanks Nick,

I don't know why either, I was hoping the artifact would have the clean
4.5.1 without date/hash but that failed, will investigate.

**Comment by nickbianco** [comment]
> I was hoping the artifact would have the clean
4.5.1 without date/hash 

Would we need an annotated tag for that?

**Comment by aymanhab** [comment]
Yes and it is annotated as far as I can tell but if you see otherwise let
me know

**Comment by nickbianco** [comment]
@aymanhab shouldn't the date/hash will get stripped when we create an artifact from a GitHub Release? I don't remember creating artifacts off of PRs for 4.5.

**Comment by nickbianco** [comment]
@aymanhab should we merge this?

**Comment by aymanhab** [comment]
Sure, this was mainly intended to create doxygen and releases with good/short names as a side effect, but merging to main is fine too.

**Pull request merged**
