### PR TITLE
Add flag to compute_accelerations_without_forces to IMUDataReporter

### PR DESCRIPTION
**Pull request by aymanhab**
This allows for computing accelerations based only on kinematics

Fixes issue #0

### Brief summary of changes
Added flag to IMUDataReporter, created PositionMotion component in the analysis model

### Testing I've completed
Ran test cases to make sure nothing broke along the way
### Looking for feedback on...
How to test the functionality and if the call sequence in Record is correct for use with PositionMotion

### CHANGELOG.md (choose one)

- no need to update because it's part of a new functionality

---
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3020)

### CODE REVIEW

**Comment by aymanhab** [comment]
@nickbianco ci is failing because PositionMotion lives in osimMoco which depends on osimTools which depends on osimAnalysis library. Is there a reason to keep PositionMotion inside Moco instead of moving to a more generic place, e.g. osimSimulation? Will it drag other Moco classes with it? Thanks

**Review by nickbianco — COMMENTED** [review]
@aymanhab No, we don't need to keep PositionMotion in osimMoco. It's just a ModelComponent.

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3020#-:-MdK44-e62G1A-24JwyW:b-6s542r)* status: 0 of 3 files reviewed, all discussions resolved

**Review by nickbianco — CHANGES_REQUESTED** [review]
The use of PositionMotion looks good to me. To test, we should use a simulation result with known controls and compute accelerations with and without the controls (using the new flag) and make sure we get the same results. You could copy one of the double pendulum examples from Moco to get a solution with controls.

> Reviewed 2 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3020#-:-MdO42lgAq4uk-ZckKmu:b2b99xe)* status: all files reviewed, 4 unresolved discussions (waiting on @aymanhab)

___
*[OpenSim/Analyses/IMUDataReporter.h, line 63 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3020#-MdO257_7CCGg87vvVBc:-MdO257_7CCGg87vvVBd:bonangk) ([raw file](https://github.com/opensim-org/opensim-core/blob/b4d6b7b185f3c8e41790897e56e1baad4707d5af/OpenSim/Analyses/IMUDataReporter.h#L63)):*
> ```objc
>             "Report angular velocity of the IMU, default is true.");
>     OpenSim_DECLARE_PROPERTY(report_accelerometer_signals, bool,
>             "Report linear acceleration of the IMU, default is true.");
> ```

Consider:
`"Report the IMU accelerometer signals (default is 'true')."`
___
*[OpenSim/Analyses/IMUDataReporter.h, line 66 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3020#-MdO1kQWEbyUZtxIIdNM:-MdO1kQWEbyUZtxIIdNN:bleyygi) ([raw file](https://github.com/opensim-org/opensim-core/blob/b4d6b7b185f3c8e41790897e56e1baad4707d5af/OpenSim/Analyses/IMUDataReporter.h#L66)):*
> ```objc
>     OpenSim_DECLARE_PROPERTY(compute_accelerations_without_forces, bool,
>             "Ignore external forces and controls, use kinematics to compute "
>             " linear accelerations of the IMUs, default is false.");
> ```

Extra space in this line. Consider:
`"accelerometer signals (default is 'false')."`
___
*[OpenSim/Analyses/IMUDataReporter.cpp, line 135 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3020#-MdO1HD77GH6ZBsEUCFY:-MdO1HD77GH6ZBsEUCFZ:b-a1pp3n) ([raw file](https://github.com/opensim-org/opensim-core/blob/b4d6b7b185f3c8e41790897e56e1baad4707d5af/OpenSim/Analyses/IMUDataReporter.cpp#L135)):*
> ```cpp
>         sWorkingCopy.setQ(s.getQ());
>         sWorkingCopy.setU(s.getU());
>     }
> ```

Consider:
```c++
if (!get_compute_accelerations_without_forces()) {
    sWorkingCopy.setQ(s.getQ());
    sWorkingCopy.setU(s.getU());
}
```
___
*[OpenSim/Analyses/IMUDataReporter.cpp, line 218 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3020#-MdO3pQM6KK9BIcvYDKw:-MdO3pQM6KK9BIcvYDKx:b-n5ji4w) ([raw file](https://github.com/opensim-org/opensim-core/blob/b4d6b7b185f3c8e41790897e56e1baad4707d5af/OpenSim/Analyses/IMUDataReporter.cpp#L218)):*
> ```cpp
>         // PositionMotion.
>         TimeSeriesTable statesTable = _statesStore->exportToTable();
>         auto statesTraj = StatesTrajectory::createFromStatesTable(*_modelLocal,
> ```

You can use `StatesTrajectory::createFromStatesStorage()` and skip the table creation.

**Review by aymanhab — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3020)* status: 0 of 24 files reviewed, 4 unresolved discussions (waiting on @nickbianco)

___
*[OpenSim/Analyses/IMUDataReporter.h, line 63 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3020#-MdO257_7CCGg87vvVBc:-Me6Fz0vD2Axq9GJvz4L:bmd5opt) ([raw file](https://github.com/opensim-org/opensim-core/blob/b4d6b7b185f3c8e41790897e56e1baad4707d5af/OpenSim/Analyses/IMUDataReporter.h#L63)):*
> Report the IMU accelerometer signals (default is 'true')
Current comment parallels the gyro without reference to signals which are self-referential but I don't feel strongly against a change.
___
*[OpenSim/Analyses/IMUDataReporter.h, line 66 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3020#-MdO1kQWEbyUZtxIIdNM:-Me6GuXD8yQwTJNAMIeP:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/b4d6b7b185f3c8e41790897e56e1baad4707d5af/OpenSim/Analyses/IMUDataReporter.h#L66)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

Extra space in this line. Consider:
`"accelerometer signals (default is 'false')."`
</blockquote></details>

Done.
___
*[OpenSim/Analyses/IMUDataReporter.cpp, line 135 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3020#-MdO1HD77GH6ZBsEUCFY:-Me6H5nFA2TLdKw7de-G:borop71) ([raw file](https://github.com/opensim-org/opensim-core/blob/b4d6b7b185f3c8e41790897e56e1baad4707d5af/OpenSim/Analyses/IMUDataReporter.cpp#L135)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

Consider:
```c++
if (!get_compute_accelerations_without_forces()) {
    sWorkingCopy.setQ(s.getQ());
    sWorkingCopy.setU(s.getU());
}
```
</blockquote></details>

Definitely, just wasn't sure if any code will go into the else block!
___
*[OpenSim/Analyses/IMUDataReporter.cpp, line 218 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3020#-MdO3pQM6KK9BIcvYDKw:-Me6HyQvDCe7JEdYph-f:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/b4d6b7b185f3c8e41790897e56e1baad4707d5af/OpenSim/Analyses/IMUDataReporter.cpp#L218)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

You can use `StatesTrajectory::createFromStatesStorage()` and skip the table creation.
</blockquote></details>

Done.

**Review by nickbianco — CHANGES_REQUESTED** [review]
LGTM, with one small comment.

> Reviewed 2 of 23 files at r3, 21 of 21 files at r4, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3020#-:-Me7Pd46EWCAS7xSJOyG:bm6dar3)* status: all files reviewed, 1 unresolved discussion (waiting on @aymanhab)

___
*[OpenSim/Analyses/IMUDataReporter.h, line 63 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3020#-MdO257_7CCGg87vvVBc:-Me7OzFW2NDL7XJu-Gdo:b-bj8h36) ([raw file](https://github.com/opensim-org/opensim-core/blob/b4d6b7b185f3c8e41790897e56e1baad4707d5af/OpenSim/Analyses/IMUDataReporter.h#L63)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

> Report the IMU accelerometer signals (default is 'true')
Current comment parallels the gyro without reference to signals which are self-referential but I don't feel strongly against a change.
</blockquote></details>

Formatting isn't a big issue, but "linear acceleration of the IMU" is a little ambiguous, whereas "accelerometer signal" specifically refers to the gravity offset and re-expressed accelerations.

**Review by aymanhab — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3020)* status: 23 of 24 files reviewed, 1 unresolved discussion (waiting on @nickbianco)

___
*[OpenSim/Analyses/IMUDataReporter.h, line 63 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3020#-MdO257_7CCGg87vvVBc:-MeB7v003Ci57CWcL5Sq:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/b4d6b7b185f3c8e41790897e56e1baad4707d5af/OpenSim/Analyses/IMUDataReporter.h#L63)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

Formatting isn't a big issue, but "linear acceleration of the IMU" is a little ambiguous, whereas "accelerometer signal" specifically refers to the gravity offset and re-expressed accelerations. 
</blockquote></details>

Done.

**Review by nickbianco — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3020#-:-MeCPife2vMzFcUhuJF5:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aymanhab)

**Comment by aymanhab** [comment]
Thanks much @nickbianco  💯

**Pull request merged**
