### PR TITLE
Class StatesDocument

### PR DESCRIPTION
**Pull request by fcanderson**
### Brief summary of changes
Class `StatesDocument` is an addition to OpenSim that adds the ability to serialize and deserialize a **complete** time history of model states to and from a single `.ostates` file. This class fulfills a roadmap articulated about 10 years ago. See the bottom of [StatesTrajectory.h](https://github.com/fcanderson/opensim-core/blob/7c2b595433519c0f0c1597c48a92661091c655cc/OpenSim/Simulation/StatesTrajectory.h#L535).

Prior to class `StateDocument`, only the continuous states (e.g., joint coordinates, joint speeds, etc.) were serialized in a systematic manner, leaving discrete states and modeling options unserialized. One of the challenges in serializing discrete states is that their type can vary (e.g., `bool`, `int`, `double`, `Vec2`, `Vec3`, etc.) and existing approaches for serializing states (e.g., storage files and time series tables) do not easily support data of mixed types.

Class `StatesDocument` uses `XML` (see class `SimTK::Xml`) as the framework for serializing all state categories and all data types. It also contains serialization date stamps accounting for time zone, contains an annotation note, and supports serialization with a range of output precisions ( 1 to 20 digits), allowing the user to reduce the `.ostates` file size or achieve lossless de/serialization, .

Minor additions were made to class `StatesTrajectory` and `StatesTrajectoryReporter` to support the `StatesDocument` class. Note, however, that class `StatesDocument` is build on low-level `SimTK` classes and the recently enhanced [OpenSim::Component class](https://github.com/opensim-org/opensim-core/pull/3745), and does not have any knowledge of the `StatesTrajectory` or `StatesTrajectoryReporter` classes.

For details concerning class `StatesDocument`, consult the Doxygen compliant comments in [StatesDocument.h](https://github.com/fcanderson/opensim-core/blob/7c2b595433519c0f0c1597c48a92661091c655cc/OpenSim/Simulation/StatesDocument.h#L35).

### Testing I've completed
Class `StatesDocument` is accompanied by a unit test. See [testStatesDocument.cpp](https://github.com/fcanderson/opensim-core/blob/ostates_2/OpenSim/Simulation/Test/testStatesDocument.cpp). This unit test exercises state serialization in all categories (continuous variables, discrete variables, and modeling options) and in all supported data types (`bool`, `int`, `double`, `Vec2`, `Vec3`, `Vec4`, `Vec5`, `Vec6`). All OpenSim unit tests are passing on `Windows 10` for a `RelWithDebInfo` build. 

### Looking for feedback on...
- Are modifications to `StatesTrajectory` and `StatesTrajectoryReporter` acceptable?
- Should the unit test include more comprehensive checks of exception handling and a broader range of models?

### CHANGELOG.md (choose one)
I have not yet modified the CHANGELOG, thinking it would be wise to defer the update until an initial review was completed. I will do the update as soon as it looks like the review is converging on approval.

- - -
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3902)

### CODE REVIEW

**Comment by aymanhab** [comment]
Thanks @fcanderson Can we fix build failures to start. Thank you

**Comment by fcanderson** [comment]
Hi @aymanhab. Thanks for the reply. Sorry for the long radio silence. I got really busy with the class I'm teaching.
I believe the errors occur only during the wrapping (Java, Python, ...). I'm guessing I need to insert some compiler directives that prevent a wrapping attempt. I may have time to look into that this morning, as long as I don't need to put out any fires.

**Comment by aymanhab** [comment]
@fcanderson No problem, it's just an issue of missing default constructor I think, which I can explicitly communicate to SWIG but I wasn't sure if that's the intended behavior. Let me know if you get busy and I can investigate further. Thank you

**Comment by fcanderson** [comment]
I'll create a default constructor. It won't be useable for anything meaningful, but it might make the errors go away.

**Comment by fcanderson** [comment]
@aymanhab I added a default constructor. Continuous Integration now performs the wrapping successfully. At least the build/testing is getting farther.

The two tests are failing:
	132 - python_tests (Failed)
	133 - python_examples (Failed)

I haven't been doing the python wrapping on my desktop. I will look into doing that.
Do you have time to take a look to see if there is a quick fix? If not, I'll do some digging.

**Comment by aymanhab** [comment]
No worries @fcanderson I'll take a look and let you know if I have questions. Thank you 👍

**Comment by fcanderson** [comment]
Ok!  Thanks @aymanhab.

**Comment by aymanhab** [comment]
Failure details:
======================================================================
ERROR: test_index_and_iterator (test_states_trajectory.TestStatesTrajectory)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\dev\src\opensim-core\Bindings\Python\tests\test_states_trajectory.py", line 45, in test_index_and_iterator
    model.calcMassCenterPosition(state)
  File "D:\dev\build\opensim-core\Bindings\Python\Release\opensim\simulation.py", line 25970, in calcMassCenterPosition
    return _simulation.Model_calcMassCenterPosition(self, s)
ValueError: invalid null reference in method 'Model_calcMassCenterPosition', argument 2 of type 'SimTK::State const &'

**Comment by aymanhab** [comment]
@fcanderson The error happens while iterating through the stateTrajectory due to the change from std::vector into SimTK::Array in 
stateTrajectory.h is there a reason for the change? std::vector iterators are likely better supported by swig out of the box than our home grown SimTK::Array, but if the change is necessary I'll dig deeper into the iterator across bindings. Thank you

**Comment by aymanhab** [comment]
swig/python detected a memory leak of type 'SimTK::Array_< SimTK::State,unsigned int >::const_iterator *', no destructor found.
swig/python detected a memory leak of type 'SimTK::Array_< SimTK::State,unsigned int >::const_iterator *', no destructor found.

**Comment by fcanderson** [comment]
@aymanhab Thanks for tracking the origin of this error down.

The reason for the transition is that Simbody uses SimTK::Array_<T> for its underlying std::vector-like functionality. The original rationale (I assume coming from Sherm) was for some speed and for binary compatibility. The OpenSim::StatesDocument class uses SimTK::Array_<T> to be compatible with Simbody, as do a number of newly available trajectory methods in OpenSim::Component.

I get why swig would be more likely to handle std::vector properly than SimTK::Array_<T>.  One option might be to hide the underlying implementation (vector vs. Array_) so that python / java / etc. don't see it.  For example, by just using an index instead of an iterator -- a little slower sometimes, but I don't think noticeably.

I will look into this issue and see if I can come a good/easy solution.

**Comment by aymanhab** [comment]
Thanks @fcanderson My first inclination would be to restore the stateTrajectory class to use std::vector for backward compatibility of client code, so that iterators (which are used by the stateTrajectory class clients) are maintained. The speed up in SimTK::Array_ may be important for small arrays internal to simbody (where space efficiency matters) but std::vector is used extensively elsewhere and the State object is massive enough that overhead would be negligible I'd think.  I can try that myself if you agree so please let me know..

**Comment by fcanderson** [comment]
Agreed. I will revert to using std::vector. It will have ripple effects in the StatesDocument class and maybe in the Component trajectory related classes, but the number of changes are finite.

**Comment by fcanderson** [comment]
@aymanhab I'm following up after looking into the issue of `std::vector<>` vs. `SimTK::Array_<>` a bit more.

There are some compelling performance differences between the two, with `SimTK::Array_<>` being about 2 times faster. There are also some undesirable characteristics of `std::vector<>` having to do with memory and binary compatibility, particularly for Microsoft implementations.

The Simbody documentation goes into the details here:  [SimTK::Array_<> Details](https://simtk.org/api_docs/molmodel/api_docs22/Simbody/html/classSimTK_1_1Array__.html#_details). It looks like Sherm et al. invested significant effort into the `SimTK::Array_<>` class.

The differences are not just a matter of overhead. For example, simple operations like indexing through an array are 2 times slower for `std::vector`. The larger the array, the more the performance difference will be noticeable.

Since state trajectories may be fairly large at times, my leaning is to keep the innards of `OpenSim::StatesDocument` and the associated trajectory methods in `OpenSim::Component` based on `SimTK::Array_<>`.

To interface with the outside world, I propose simply adding a thin translation layer to `OpenSim::StatesDocument` that will translate a `std::vector<SimTK::State>` object into a `SimTK::Array_<SimTK::State>` object.

There are only two methods in OpenSim::StatesDocument where the translation would need to occur:
```
StatesDocument::StatesDocument(const Model& model, const Array_<State>& trajectory, const String& note, int p)
StatesDocument::deserialize(const Model& model, Array_<State>& traj)
```

I propose that we just add two additional methods so that `OpenSim::StatesDocument` can communicate with classes like `OpenSim::StateTrajectory` that use `std::vector<SimTK::Array_>`.

So the API would be:
```
StatesDocument::StatesDocument(const Model& model, const vector<State>& trajectory, const String& note, int p)
StatesDocument::StatesDocument(const Model& model, const Array_<State>& trajectory, const String& note, int p)

StatesDocument::deserialize(const Model& model, vector<State>& traj)
StatesDocument::deserialize(const Model& model, Array_<State>& traj)
```

The `vector`-based methods would need to perform a copy from `vector<State>` to `Array_<State>` (or vice versa), but that would only be done once and the cost would be small (I think) compared to the cost of iterating through all of the individual continuous, discrete, and modeling variables that make up the State using `vector` instead of `array`.

**Comment by fcanderson** [comment]
@aymanhab I will add that it looks like I can use the following constructor:
```
SimTK::Array_<T>::Array_ (std::vector<T> &v, const DontCopy)
```
which generates an `Array_<T>` that directly references (does not copy) the data of the `vector` argument. This constructor is dirt cheap and I believe a safe thing to use in the circumstance of the StatesDocument class.

**Comment by aymanhab** [comment]
Great investigation as always @fcanderson 👍 I guess clients of the class most always do iteration rather than indexing so this didn't factor in the design of stateTrajectory. I'm totally on board with making the interface be std::vector and the internals using SimTK::Array, we get the best of both worlds.

**Comment by fcanderson** [comment]
@aymanhab Ok! I reverted back to the std::vector<State> iterators, and the tests are passing. Thanks for identifying the issue!

**Review by aymanhab — CHANGES_REQUESTED** [review]
> Reviewed 2 of 8 files at r1, 1 of 2 files at r3, 1 of 1 files at r4, 2 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3902)* status: 6 of 10 files reviewed, 2 unresolved discussions (waiting on @fcanderson)

___
*[`OpenSim/Simulation/StatesTrajectoryReporter.cpp` line 39 at r5](https://reviewable.io/reviews/opensim-org/opensim-core/3902#-O90p-lwE8iUdg7xsiMZ:-O90p-lwE8iUdg7xsiM_:bcrzafg) ([raw file](https://github.com/opensim-org/opensim-core/blob/a09c2b3dd2088e68703169b953cc4874b35b6af6/OpenSim/Simulation/StatesTrajectoryReporter.cpp#L39)):*
> ```cpp
> const std::vector<SimTK::State>&
> StatesTrajectoryReporter::getStateArray() const {
>     return m_states.getStateArray();
> ```

Wonder if the name of the method should change?
___
*[`OpenSim/Simulation/Test/testStatesTrajectory.cpp` line 580 at r5](https://reviewable.io/reviews/opensim-org/opensim-core/3902#-O90pHla1mZjhmmkJzAN:-O90pHla1mZjhmmkJzAO:b-wjlucr) ([raw file](https://github.com/opensim-org/opensim-core/blob/a09c2b3dd2088e68703169b953cc4874b35b6af6/OpenSim/Simulation/Test/testStatesTrajectory.cpp#L580)):*
> ```cpp
>     //    states[5];
>     //#endif
> ```

Any reason to keep these comments?

**Review by fcanderson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3902)* status: 5 of 10 files reviewed, 2 unresolved discussions (waiting on @aymanhab and @nickbianco)

___
*[`OpenSim/Simulation/StatesTrajectoryReporter.cpp` line 39 at r5](https://reviewable.io/reviews/opensim-org/opensim-core/3902#-O90p-lwE8iUdg7xsiMZ:-O95a11RD5_WTVBfIpyy:btbhzeo) ([raw file](https://github.com/opensim-org/opensim-core/blob/a09c2b3dd2088e68703169b953cc4874b35b6af6/OpenSim/Simulation/StatesTrajectoryReporter.cpp#L39)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

Wonder if the name of the method should change?
</blockquote></details>

Ah, I think I see what you are suggesting. The return is now a `vector<>` instead of a `SimTK::Array_<>`.

I didn't want to use `getStateTrajectory()` since there is a `StateTrajectory` class.

The only reason I might not want to use `getStateVector()` is that name will likely conjure the notion of an object that contains the states at a single time stamp. A `SimTK::State` object itself is what some might think of as a state vector.

The name that I think is probably most accurate and least likely to be confused with some other entity in this arena is
```
getVectorOfStateObjects()
```
since an `std::vector<>` is returned.

If you agree, I'll go ahead and change the method name to `getVectorOfStateObjects()`.
___
*[`OpenSim/Simulation/Test/testStatesTrajectory.cpp` line 580 at r5](https://reviewable.io/reviews/opensim-org/opensim-core/3902#-O90pHla1mZjhmmkJzAN:-O95i6vw6Pd9vEYRnNnk:bjly0wa) ([raw file](https://github.com/opensim-org/opensim-core/blob/a09c2b3dd2088e68703169b953cc4874b35b6af6/OpenSim/Simulation/Test/testStatesTrajectory.cpp#L580)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

Any reason to keep these comments?
</blockquote></details>

I do not know why I commented out these lines originally. So, I'm glad you spotted them. It likely had to do with the fact that `testStatesTrajectory` fails for a Debug build. I might have thought that commenting out those lines would allow the test to run successfully. Not sure, but if I did, that was wrong. 

I just tested the code with those lines commented out and with those lines restored. Either way, the Debug build fails because of an array index out of bounds exception that is thrown while executing
```
SimTK_SUBTEST1(testFromStatesStorageInconsistentModel, pre40StoFname);  (testStatesTrajectory.cpp: line 799)
```

In a release build (either `Release` or `RelWithDebInfo`) the test passes because bounds checking is disabled.

Since I didn't write this test, the better thing to do restore the lines that I commented out. I'm not exactly sure what functionality they are testing.

As a general comment, there are a number of OpenSim tests that fail for a `Debug` build. I haven't reported them because I suspected that you all (the devs) were aware of the failures and had decided to pass on them as non-critical. After talking with @nickbianco , however, it seems that maybe running the tests for a `Debug` build isn't really part of the development cycle.  So maybe you all are not aware of the `Debug` test failures?

I intended to follow up with @nickbianco on this, but I just haven't had the resources to do it.

**Review by aymanhab — CHANGES_REQUESTED** [review]
A couple minor comments but otherwise looks great. My main question at the end of this was how would API users distinguish if they're using a Full state with discrete variable and modeling options vs. the traditional state that had only continuous variables. Maybe some documentation/disclaimers would do. 

> Reviewed 4 of 6 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3902#-:-O9Aag0r6RnIfnIm2jpZ:b-pihru1)* status: all files reviewed, 5 unresolved discussions (waiting on @fcanderson)

___
*[`OpenSim/Simulation/StatesDocument.h` line 221 at r6](https://reviewable.io/reviews/opensim-org/opensim-core/3902#-O9AY5XO3ui3rqGx9fRv:-O9AY5XO3ui3rqGx9fRw:bd83qak) ([raw file](https://github.com/opensim-org/opensim-core/blob/998e5ad7cf84a2c860592ac7e03d362a1e2f6ec4/OpenSim/Simulation/StatesDocument.h#L221)):*
> ```objc
> significant figures would go unnoticed).
> ```

Amazingly clear description @fcanderson Thank you :1st_place_medal: 
___
*[`OpenSim/Simulation/StatesDocument.cpp` line 435 at r6](https://reviewable.io/reviews/opensim-org/opensim-core/3902#-O9AZLzG0xNlyVuhCID8:-O9AZLzG0xNlyVuhCID9:bmf8b6x) ([raw file](https://github.com/opensim-org/opensim-core/blob/998e5ad7cf84a2c860592ac7e03d362a1e2f6ec4/OpenSim/Simulation/StatesDocument.cpp#L435)):*
> ```cpp
>     // Many other aspects are checked for consistency than just the model
>     // name. Those are more easily checked as the doc is parced.
> ```

parsed?
___
*[`OpenSim/Simulation/StatesDocument.cpp` line 450 at r6](https://reviewable.io/reviews/opensim-org/opensim-core/3902#-O9AZW8UCNDxZjnrPEzi:-O9AZ8Kf1uDTtqwwIWgy:b-7un8pk) ([raw file](https://github.com/opensim-org/opensim-core/blob/998e5ad7cf84a2c860592ac7e03d362a1e2f6ec4/OpenSim/Simulation/StatesDocument.cpp#L450)):*
> ```cpp
>         SimTK_ASSERT_ALWAYS(false, msg.c_str());
>     }
> ```

This maybe overstated on my side but we never gave the model name much significance, users easily modify model names in GUI or XML without thinking about downstream effects. Considering that the meat of consistency test is done elsewhere I wonder if you think this check is relevant here.
___
*[`OpenSim/Simulation/StatesDocument.cpp` line 673 at r6](https://reviewable.io/reviews/opensim-org/opensim-core/3902#-O9A_bmg6QTvoaGI8IVZ:-O9A_bmg6QTvoaGI8IV_:b-om6jwx) ([raw file](https://github.com/opensim-org/opensim-core/blob/998e5ad7cf84a2c860592ac7e03d362a1e2f6ec4/OpenSim/Simulation/StatesDocument.cpp#L673)):*
> ```cpp
>                 model, path, traj);
>         }
>         else {
> ```

These if/else(s) typically worry me because I don't know if we covered all cases. but with templates I guess that's the price to pay.  Is there a master list of these types that we can refer to in case e.g. Arrays of Vectors, Matrices or SpatialVectors beome valid types?
___
*[`OpenSim/Simulation/StatesTrajectoryReporter.cpp` line 39 at r5](https://reviewable.io/reviews/opensim-org/opensim-core/3902#-O90p-lwE8iUdg7xsiMZ:-O98p2xB2hEVC2bDOlfZ:bqog80t) ([raw file](https://github.com/opensim-org/opensim-core/blob/a09c2b3dd2088e68703169b953cc4874b35b6af6/OpenSim/Simulation/StatesTrajectoryReporter.cpp#L39)):*
<details><summary><i>Previously, fcanderson (Clay Anderson) wrote…</i></summary><blockquote>

Ah, I think I see what you are suggesting. The return is now a `vector<>` instead of a `SimTK::Array_<>`.

I didn't want to use `getStateTrajectory()` since there is a `StateTrajectory` class.

The only reason I might not want to use `getStateVector()` is that name will likely conjure the notion of an object that contains the states at a single time stamp. A `SimTK::State` object itself is what some might think of as a state vector.

The name that I think is probably most accurate and least likely to be confused with some other entity in this arena is
```
getVectorOfStateObjects()
```
since an `std::vector<>` is returned.

If you agree, I'll go ahead and change the method name to `getVectorOfStateObjects()`.
</blockquote></details>

Agreed

**Comment by fcanderson** [comment]
*[`OpenSim/Simulation/StatesDocument.cpp` line 450 at r6](https://reviewable.io/reviews/opensim-org/opensim-core/3902#-O9AZW8UCNDxZjnrPEzi:-O9BG5mx9N8E9-UFb_il:bqwe3rm) ([raw file](https://github.com/opensim-org/opensim-core/blob/998e5ad7cf84a2c860592ac7e03d362a1e2f6ec4/OpenSim/Simulation/StatesDocument.cpp#L450)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

This maybe overstated on my side but we never gave the model name much significance, users easily modify model names in GUI or XML without thinking about downstream effects. Considering that the meat of consistency test is done elsewhere I wonder if you think this check is relevant here.
</blockquote></details>

You are in a better position to make this call.

In an effort to avoid a situation where a user would perform a detailed analysis with the wrong set of states, I opted to make the bar for compatibility high. If a user really would like to conduct an analysis with a particular .ostates file that has a model name that doesn't match, I thought opening the file and manually changing the file name, though tedious, was not too much to ask.

You are familiar with use cases in the GUI, Matlab, etc.  What do you suggest?

**Comment by fcanderson** [comment]
*[`OpenSim/Simulation/StatesDocument.cpp` line 673 at r6](https://reviewable.io/reviews/opensim-org/opensim-core/3902#-O9A_bmg6QTvoaGI8IVZ:-O9BHZT3-KENJO0OgMFR:b-73p629) ([raw file](https://github.com/opensim-org/opensim-core/blob/998e5ad7cf84a2c860592ac7e03d362a1e2f6ec4/OpenSim/Simulation/StatesDocument.cpp#L673)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

These if/else(s) typically worry me because I don't know if we covered all cases. but with templates I guess that's the price to pay.  Is there a master list of these types that we can refer to in case e.g. Arrays of Vectors, Matrices or SpatialVectors beome valid types?
</blockquote></details>

I thought about ways of avoiding the if/else(s), but did not come up with something that wasn't burdensome. OpenSim has been used for YEARS and no one until I came along with my contact class has complained about other types besides `double` being unavailable.

I thought when another such case comes along, we could quickly add another if/else for the type in demand. It really only means the addition of several lines of code.

To clarify, in Simbody, any numerical type that can be represented by a `SimTK::AbstractValue()` is fair game for a `SimTK::DiscreteVariable`.

In `OpenSim::StatesDocument`, the supported types are listed in the documentation:
https://github.com/fcanderson/opensim-core/blob/ostates_2/OpenSim/Simulation/StatesDocument.h#L278

**Comment by fcanderson** [comment]
The following answer may not address your question adequately. I find it challenging to answer. If I come up short, a Zoom call in which you and I can go back and forth about concepts might be the easiest way to proceed.

API users should always assume that every instance of a `SimTK::State` that they encounter is comprised of continuous variables, discrete variables, and modeling options. For example, a joint clamp is implemented in OpenSim and Simbody using a modeling option.

For the purpose of state de/serialization,`OpenSim::StatesDocument` is the preferable path to take. Other approaches for de/serialization will leave any discrete states and modeling options uninitialized, unless additional measures are taken.

Historically, API programmers have taken those additional measures. When states other than the continuous states have been needed, those states have been saved in some ad hoc way.  For example, as a `Property` in the OpenSim model file or as separate input files (e.g., the time history of muscle excitations).  Users just haven't been aware that the need to do this, in some cases, stems from an inability to save the full state to file. API users have always been aware of their particular needs and so have programmed approaches that stepped around the fact that OpenSim was only able to save the continuous states to file.

The situation with my contact model targeted the Achilles' Heel of OpenSim. My contact model not only has input discrete states of various types (int, Vec3, etc) , it also has OUTPUT discrete states of different types! There just wasn't a viable way to handle this in OpenSim.

This whole area has been hard to communicate about. Nick has an appreciation of the details; he performed a detailed review of the enhacements to `OpenSim::Component`. In the Community Dev meetings, there's really only time for bullet points, not time to take a deep dive into the sometimes difficult finer points. And I'm not always the best communicator.

I see the OpenSim workflow as migrating to something like:
1. Open a model or create a model.
2. Perform a simulation (or some other kind of model-based computation).
3. Obtain the full state trajectory.
4. For future analysis (if desired), serialize the full trajectory of states using `OpenSim::StatesDocument`.
5. For post analysis, deserialize the full trajectory of states using `OpenSim::StatesDocument`.
6. Perform analyses, visualize movement, visualize results, perform additional simulations, etc. 
7. Write desired results to time series tables for plotting and/or other analyses that don't require the model.

I haven't seen the .ostates XML file as the end product from the user's point of view. I've seen it as a systematic and comprehensive means of getting at the information they desire. Because .ostates will always contain the full state, any piece of data concerning a model can be (re)generated.

**Comment by fcanderson** [comment]
*[`OpenSim/Simulation/StatesDocument.cpp` line 450 at r6](https://reviewable.io/reviews/opensim-org/opensim-core/3902#-O9AZW8UCNDxZjnrPEzi:-O9Bcwg7-rbumsSwx79V:b-t77xc3) ([raw file](https://github.com/opensim-org/opensim-core/blob/998e5ad7cf84a2c860592ac7e03d362a1e2f6ec4/OpenSim/Simulation/StatesDocument.cpp#L450)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

I'll leave it as is and see if it becomes an issue in actual use cases, at this level of API use, more stringent is better.
</blockquote></details>

agreed

**Comment by fcanderson** [comment]
*[`OpenSim/Simulation/StatesDocument.cpp` line 673 at r6](https://reviewable.io/reviews/opensim-org/opensim-core/3902#-O9A_bmg6QTvoaGI8IVZ:-O9BdEXi1IpvoUoacK3e:b-nru59m) ([raw file](https://github.com/opensim-org/opensim-core/blob/998e5ad7cf84a2c860592ac7e03d362a1e2f6ec4/OpenSim/Simulation/StatesDocument.cpp#L673)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

Thanks @fcanderson I'd add comment to the block in the cpp block so that future maintainers understand where this list came from and why.
</blockquote></details>

Working on it.

**Comment by fcanderson** [comment]
*[`OpenSim/Simulation/StatesTrajectoryReporter.cpp` line 39 at r5](https://reviewable.io/reviews/opensim-org/opensim-core/3902#-O90p-lwE8iUdg7xsiMZ:-O9BLIxM55o-J1PrDoN7:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/a09c2b3dd2088e68703169b953cc4874b35b6af6/OpenSim/Simulation/StatesTrajectoryReporter.cpp#L39)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

Agreed
</blockquote></details>

Done.

**Comment by fcanderson** [comment]
*[`OpenSim/Simulation/StatesDocument.cpp` line 435 at r6](https://reviewable.io/reviews/opensim-org/opensim-core/3902#-O9AZLzG0xNlyVuhCID8:-O9BFneJDLiAA0K2dfjz:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/998e5ad7cf84a2c860592ac7e03d362a1e2f6ec4/OpenSim/Simulation/StatesDocument.cpp#L435)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

parsed?
</blockquote></details>

Done.

**Review by aymanhab — COMMENTED** [review]
Thanks @fcanderson and I agree completely with your assessment regarding the holes in the current system before this PR, and appreciate the work you've done to enable this important functionality. 

My question was regarding the StateTrjectory class/methods e.g. exportToTable has no way to tell where it came from, could it export discrete variables or modeling-options? Maybe it doesn't matter (that's a totally satisfactory resolution) or if not we could maintain a flag for book-keeping. Mainly asking for clarification for users who are already utilizing the StatesTrajectory vehicle elsewhere. If that's a more involved discussion or something that you resolved earlier or better done on Zoom I'm totally open. Thanks again.

> Reviewed 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3902#-:-O9Bef1M-_kmZ9wDlhar:bfxlusx)* status: all files reviewed, 1 unresolved discussion (waiting on @fcanderson)

**Review by fcanderson — COMMENTED** [review]
My understanding is that StatesTrajectory generally gets the states from a StatesTrajectoryReporter, in which case the trajectory of SimTK::State objects it contains will have valid values for all state categories (continuous, discrete, modeling). If, however, StatesTrajectory gets its states from a saved file, then any instance of a SimTK::State that is based only on reading that file will only have valid values for the Continuous states; the discrete variables and modeling options will be left uninitialized. Valid values of discrete and modeling states, in this case, will have to come from another source (e.g., another input file).

A flag in the StatesTrajectory to indicate whether it contains an entirely valid trajectory of SimTK::State objects seems like it could be a useful thing. If the origin of the trajectory was from a StatesTrajectoryReport, the flag is set to COMPLETE. On the other hand, if the origin of the trajectory was from file, then the flag is set to INCOMPLETE.

In its current form, StatesTrajectory doesn't export discrete variables or modeling options. It could be modified to do so, however. OpenSim::Component now has the infrastructure to efficiently get or set each state variable (continuous, discrete, or modeling) individually from or into a SimTK::Array_<SimTK::State> by specifying the variable's path. OpenSim::Component keeps an std::map for each state category using path as the hash index.

Enhancing StatesTrajectory would be a natural step to take except for one road block (that I am aware of). TimeSeriesTable does not currently have a way to co-mingle variables of different types. I really don't like the idea of serializing to multiple files, one for each type encountered (one for the int's, one for double's, one for Vec3's, etc.). That seems like a recipe for a logistical nightmare. How do you manage to keep track of all the files that go together?

The appeal of using XML, at least as for an initial pass at this functionality, is that the xml attribute mechanism was a really natural way to encode variable type. AND, SimTK::Xml already knows how to serialize and deserialize ALL possible variable types that could be encountered in Simbody (matrices, SpatialVec, etc).  Using XML presented a clear path to getting all states in ONE file with a model name, appropriate precision, time stamp, and note.

If .ostate file size becomes an issue, I do think pursuing binary serialization would be a productive way to go. To get this functionality, augmenting the appropriate Simbody classes I think should be the point of attack.  There would just need to be a flag that is set in SimTK::Xml to signal binary serialization, and each concrete SimTK::Value type would need to know how to stream itself in binary form. The functionality may actually already exist. I haven't looked into it.

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3902#-:-O9ByDsvBSrrptqnnSSq:biwabq8)* status: all files reviewed, 1 unresolved discussion (waiting on @fcanderson)

**Review by fcanderson — COMMENTED** [review]
A follow-up:
1. I read about binary XML formats. It appears like a much debated topic. Most people it seems are not in favor of binary because it removes one of the hallmark design characteristics of XML -- it is user readable and editable with common editors.
2. A good alternative to using some kind of binary XML is to reduce file size using compression (e.g., zip'ing).
3. In StatesTrajectory.h, I do make a disclaimer about using StatesTrajectory::createFromStorage() and createfromStatesTable() as a deserialization approach.
See https://github.com/fcanderson/opensim-core/blob/ostates_2/OpenSim/Simulation/StatesTrajectory.h#L314

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3902#-:-O9CNpML7PcW_92AJi42:bug9ap3)* status: all files reviewed, 1 unresolved discussion (waiting on @fcanderson)

**Review by fcanderson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3902)* status: 8 of 10 files reviewed, 1 unresolved discussion (waiting on @aymanhab)

___
*[`OpenSim/Simulation/StatesDocument.cpp` line 673 at r6](https://reviewable.io/reviews/opensim-org/opensim-core/3902#-O9A_bmg6QTvoaGI8IVZ:-O9CSS7u5leC0WdIo4UN:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/998e5ad7cf84a2c860592ac7e03d362a1e2f6ec4/OpenSim/Simulation/StatesDocument.cpp#L673)):*
<details><summary><i>Previously, fcanderson (Clay Anderson) wrote…</i></summary><blockquote>

Working on it.
</blockquote></details>

Done.

**Review by fcanderson — COMMENTED** [review]
@aymanhab I believe I've addressed all the requested changes.

You'll notice that I pushed 1 or 2 more commits. I took the liberty of adjusting the documentation to reflect that both `std::vecter<SimTK::State>` or `SimTK::Array_<SimTK::State>` will work as in interface to class StatesDocument.

If all looks good to you, then it looks good to me.

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3902#-:-O9KUO6ZAUnMP8YjhJTw:b-m67k5c)* status: 8 of 10 files reviewed, 1 unresolved discussion (waiting on @aymanhab)

**Comment by fcanderson** [comment]
@aymanhab I just updated CHANGELOG.md. Thank you very much, Ayman, for your review. I am glad to have the chunk of functionality in OpenSim. Now that auto-update discrete states of different variable types are supported in OpenSim, the next stop is getting the ExponentialContact class merged and seeing how it performs.

**Review by aymanhab — APPROVED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3902)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @fcanderson)

**Pull request merged**
