### PR TITLE
CMake BUILD_TYPE/CONFIGURATION mismatch issue

### PR DESCRIPTION
**Pull request by klshrinidhi**
Addressing #1276.
Replacing #1483.

### CODE REVIEW

**Comment by chrisdembia** [comment]
Looks great to me except for one thing: on Mac and Linux, it is still possible to install OpenSim in multiple configurations; is this case handled? Xcode does not even need to be used to install in multiple configurations; someone could use separate build dirs with Makefiles and install multiple configurations.

**Comment by klshrinidhi** [comment]
I have addressed your comment. I think multi-config builds should be handled in Linux/Mac too now.

**Comment by aymanhab** [comment]
Thanks @klshrinidhi Looks good. Is there a way to handle these more generically (to avoid the check/branching based on PLATFORM_NAME)? If not then I'm fine with merging this solution as soon as builds/tests pass.

**Comment by chrisdembia** [comment]
LGTM. I restarted the travis-ci/pr build that had failed. Once that passes, please merge!

**Comment by klshrinidhi** [comment]
One build failed due to timeout after 78/82 tests passes.
Merging.

**Pull request merged**
