### PR TITLE
Whitespace

### PR DESCRIPTION
**Pull request by thomasklau**

### CODE REVIEW

**Comment by thomasklau** [comment]
@sherm1

**Comment by thomasklau** [comment]
Separate pull request so that I can submit my other pull request without whitespace changes

**Comment by thomasklau** [comment]
https://github.com/opensim-org/opensim-core/pull/547

**Comment by sherm1** [comment]
Thomas, same problem here. Claims to have 882 modified files and can't be merged automatically. Please discuss with @chrisdembia.

**Pull request closed without merging**
