### PR TITLE
Remove btk references

### PR DESCRIPTION
**Pull request by AlbertoCasasOrtiz**
Fixes issue -.

### Brief summary of changes

Removed all BTK dependencies since now we have switched to ezc3d.

### Testing I've completed

Github ci workflows passed in my local fork.

### Looking for feedback on...

-.

### CHANGELOG.md (choose one)

- updated.

- - -
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3280)

### CODE REVIEW

**Comment by AlbertoCasasOrtiz** [comment]
@aymanhab I have created this new pull request to remove all btk references. Everything is already merged and updated, and I did a deeper search here to find every reference to BTK.

**Comment by aymanhab** [comment]
Thanks @AlbertoCasasOrtiz Will definitely review it promptly. Is there a reason you're working off your own fork rather than off a branch? Using a branch allows us to switch to it easily rather than setup a new remote to see the code/changes but I don't know if you have a preference to work off a fork or if you had issues creating a branch off opensim-org/opensim-core directly due to permissions. If the latter please let me know and I'll make sure you can use branches for smoother integration. Thank you.

**Comment by AlbertoCasasOrtiz** [comment]
@aymanhab Sorry about that. I was using a fork so I don't pollute the main repository with tests and new branches. What you are saying seems reasonable to me, so I could work using branches from now on if you prefer.

**Comment by aymanhab** [comment]
No worries @AlbertoCasasOrtiz  As long as you don't try to merge to master you should be fine experimenting or doing whatever you want or pushing to your own branches on the server, it's only PRs to master that get reviewed. Thank you.

**Review by aymanhab — CHANGES_REQUESTED** [review]
> Reviewed 14 of 21 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3280)* status: 14 of 21 files reviewed, 1 unresolved discussion (waiting on @AlbertoCasasOrtiz and @aymanhab)

___
*[`CHANGELOG.md` line 14 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3280#-N9clyYD3F_WevfsH5H5:-N9clyYE6oH1ApbxQOQv:b-ynls0e) ([raw file](https://github.com/opensim-org/opensim-core/blob/568c4a78d2f4021c63051bae7e5bc8f4fe23e1ed/CHANGELOG.md#L14)):*
> ```Markdown
> - Made `Component::getSocketNames` a `const` member method (previously: non-const)
> - Modifed the swig interface files to make OpenSim::PathPointSet adopt new PathPoints inserted into it. (Issue #3276)
> - Remove BTK dependency and switched completely to ezc3d.
> ```

Remove references to obsoleted dependency BTK, use ezc3d exclusively.

**Review by aymanhab — COMMENTED** [review]
> Reviewed 7 of 21 files at r1.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3280)* status: all files reviewed, 1 unresolved discussion (waiting on @AlbertoCasasOrtiz)

**Review by aymanhab — COMMENTED** [review]
Looks good, just update changlelog for wording. Thank you

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3280#-:-N9gpLZ16hkvthz4fIzV:b-yp6ix1)* status: all files reviewed, 1 unresolved discussion (waiting on @AlbertoCasasOrtiz)

**Review by AlbertoCasasOrtiz — COMMENTED** [review]
Done, and solved conflict with master.

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3280#-:-N9h3sxg1_gISv-mGfi6:bncgvl5)* status: 19 of 21 files reviewed, 1 unresolved discussion (waiting on @aymanhab)

___
*[`CHANGELOG.md` line 14 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3280#-N9clyYD3F_WevfsH5H5:-N9h4362BPuLM3SDA11A:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/568c4a78d2f4021c63051bae7e5bc8f4fe23e1ed/CHANGELOG.md#L14)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

Remove references to obsoleted dependency BTK, use ezc3d exclusively. 
</blockquote></details>

Done.

**Review by aymanhab — APPROVED** [review]
Thanks @albertocasasortiz 

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3280#-:-N9hpGYw3QzO7KHUNyFD:b-pf3imk)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @AlbertoCasasOrtiz)

**Pull request merged**
