### PR TITLE
Install ipopt dependencies in ipopt folder to reduce book-keeping

### PR DESCRIPTION
**Pull request by aymanhab**
Fixes issue #3916
### CHANGELOG.md (choose one)

- no need to update because internal

- - -
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3920)

### CODE REVIEW

**Comment by aymanhab** [comment]
@mattpetrucci or @carmichaelong please try the artifact from below and let me know if the issue is fixed. Thanks
https://github.com/opensim-org/opensim-core/actions/runs/11112829283?pr=3920#artifacts

**Comment by mattpetrucci** [comment]
Ran into errors for when I 'import opensim as osim'

```
Traceback (most recent call last):
 File "<stdin>", line 1, in <module>
 File "/Users/Matt/Documents/OpenSimArtifacts/opensim-core-4.5.1-2024-09-30-6b2b49e/sdk/Python/opensim/__init__.py", line 18, in <module>
  from .simbody import *
 File "/Users/Matt/Documents/OpenSimArtifacts/opensim-core-4.5.1-2024-09-30-6b2b49e/sdk/Python/opensim/simbody.py", line 10, in <module>
  from . import _simbody
ImportError: dlopen(/Users/Matt/Documents/OpenSimArtifacts/opensim-core-4.5.1-2024-09-30-6b2b49e/sdk/Python/opensim/_simbody.so, 0x0002): Library not loaded: /usr/local/opt/gcc/lib/gcc/current/libgfortran.5.dylib
 Referenced from: <D46CB169-404E-3EFD-AD45-AD95D303C560> /Users/Matt/Documents/OpenSimArtifacts/opensim-core-4.5.1-2024-09-30-6b2b49e/sdk/lib/libipopt.3.dylib
 Reason: tried: '/libgfortran.5.dylib' (no such file), '/Users/Matt/Documents/OpenSimArtifacts/opensim-core-4.5.1-2024-09-30-6b2b49e/sdk/lib/libgfortran.5.dylib' (no such file), '/Users/Matt/Documents/OpenSimArtifacts/opensim-core-4.5.1-2024-09-30-6b2b49e/sdk/Simbody/lib/libgfortran.5.dylib' (no such file), '/usr/local/opt/gcc/lib/gcc/current/libgfortran.5.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/gcc/lib/gcc/current/libgfortran.5.dylib' (no such file), '/usr/local/opt/gcc/lib/gcc/current/libgfortran.5.dylib' (no such file), '/usr/local/lib/libgfortran.5.dylib' (no such file), '/usr/lib/libgfortran.5.dylib' (no such file, not in dyld cache) 
```

**Comment by aymanhab** [comment]
I'll give you the status report @mattpetrucci in case you want to move forward with work:
1. On osx ipopt compiles some fortran code requiring the fortran library libgfortran to be available. 
2. The inclusion of this library in the distribution is iffy. On one side we guarantee our application/executables work on all macs, on the other hand we shouldn't be distributing compilers/system libraries on our own.
3. In the past with old ipopt we did distribute these libraries but in other environments e.g. conda we just tell it to install fortran and it does it for us, it may not be this specific library even or may cause conflicts if we do it as the compilers are different.
4. As a workaround, if you're in a hurry to try the solutions below while I'm working on a permanent fix
https://stackoverflow.com/questions/57207357/dyld-library-not-loaded-usr-local-gfortran-lib-libgfortran-3-dylib-reason-im

**Comment by aymanhab** [comment]
Please try the latest mac artifact of this pr. Thanks

**Comment by mattpetrucci** [comment]
@aymanhab Thanks, this one, right?: https://github.com/opensim-org/opensim-core/actions/runs/11112829283?pr=3920#artifacts

If yes, still getting an error below. :

```
ImportError: dlopen(/Users/Matt/Documents/OpenSimArtifacts/opensim-core-4.5.1-2024-09-30-6b2b49e/sdk/Python/opensim/_simbody.so, 0x0002): Library not loaded: /usr/local/opt/gcc/lib/gcc/current/libgfortran.5.dylib
  Referenced from: <D46CB169-404E-3EFD-AD45-AD95D303C560> /Users/Matt/Documents/OpenSimArtifacts/opensim-core-4.5.1-2024-09-30-6b2b49e/sdk/lib/libipopt.3.dylib
  Reason: tried: '/libgfortran.5.dylib' (no such file), '/Users/Matt/Documents/OpenSimArtifacts/opensim-core-4.5.1-2024-09-30-6b2b49e/sdk/lib/libgfortran.5.dylib' (no such file), '/Users/Matt/Documents/OpenSimArtifacts/opensim-core-4.5.1-2024-09-30-6b2b49e/sdk/Simbody/lib/libgfortran.5.dylib' (no such file), '/usr/local/opt/gcc/lib/gcc/current/libgfortran.5.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/gcc/lib/gcc/current/libgfortran.5.dylib' (no such file), '/usr/local/opt/gcc/lib/gcc/current/libgfortran.5.dylib' (no such file), '/usr/local/lib/libgfortran.5.dylib' (no such file), '/usr/lib/libgfortran.5.dylib' (no such file, not in dyld cache)
```

**Comment by mattpetrucci** [comment]
Also, when I tried the fix here: https://stackoverflow.com/questions/57207357/dyld-library-not-loaded-usr-local-gfortran-lib-libgfortran-3-dylib-reason-im

And I try and `locate libgofortran.5.dylib` it cannot find it.

**Comment by aymanhab** [comment]
@mattpetrucci The artifact is here https://github.com/opensim-org/opensim-core/actions/runs/11152182195 and I just verified that it contains the library libgfortran under the sdk/lib folder AFAICT, can you double check that the file exists? Thanks

**Comment by mattpetrucci** [comment]
I can confirm the the `libgfortran.5dylib` does exist.

Unfortunately, looks like this triggered more errors when I `import opensim as osim`

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Matt/Documents/OpenSimArtifacts/opensim-core-4.5.1-2024-10-02-9dd8e16/sdk/Python/opensim/__init__.py", line 18, in <module>
    from .simbody import *
  File "/Users/Matt/Documents/OpenSimArtifacts/opensim-core-4.5.1-2024-10-02-9dd8e16/sdk/Python/opensim/simbody.py", line 10, in <module>
    from . import _simbody
ImportError: dlopen(/Users/Matt/Documents/OpenSimArtifacts/opensim-core-4.5.1-2024-10-02-9dd8e16/sdk/Python/opensim/_simbody.so, 0x0002): Library not loaded: @rpath/libgcc_s.1.1.dylib
  Referenced from: <DFAC9874-BA16-32EC-B8DA-E4FC7471A9E3> /Users/Matt/Documents/OpenSimArtifacts/opensim-core-4.5.1-2024-10-02-9dd8e16/sdk/lib/libcoinmumps.3.dylib
  Reason: tried: '/libgcc_s.1.1.dylib' (no such file), '/Users/Matt/Documents/OpenSimArtifacts/opensim-core-4.5.1-2024-10-02-9dd8e16/sdk/lib/libgcc_s.1.1.dylib' (no such file), '/Users/Matt/Documents/OpenSimArtifacts/opensim-core-4.5.1-2024-10-02-9dd8e16/sdk/Simbody/lib/libgcc_s.1.1.dylib' (no such file), '/Users/Matt/Documents/OpenSimArtifacts/opensim-core-4.5.1-2024-10-02-9dd8e16/sdk/lib/libgcc_s.1.1.dylib' (no such file), '/usr/local/Cellar/gcc/14.2.0/lib/gcc/current/gcc/x86_64-apple-darwin21/14/libgcc_s.1.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/Cellar/gcc/14.2.0/lib/gcc/current/gcc/x86_64-apple-darwin21/14/libgcc_s.1.1.dylib' (no such file), '/usr/local/Cellar/gcc/14.2.0/lib/gcc/current/gcc/libgcc_s.1.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/Cellar/gcc/14.2.0/lib/gcc/current/gcc/libgcc_s.1.1.dylib' (no such file), '/usr/local/Cellar/gcc/14.2.0/lib/gcc/current/libgcc_s.1.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/Cellar/gcc/14.2.0/lib/gcc/current/libgcc_s.1.1.dylib' (no such file), '/Users/Matt/Documents/OpenSimArtifacts/opensim-core-4.5.1-2024-10-02-9dd8e16/sdk/lib/libgcc_s.1.1.dylib' (no such file), '/Users/Matt/Documents/OpenSimArtifacts/opensim-core-4.5.1-2024-10-02-9dd8e16/sdk/lib/libgcc_s.1.1.dylib' (no such file), '/Users/Matt/Documents/OpenSimArtifacts/opensim-core-4.5.1-2024-10-02-9dd8e16/sdk/lib/libgcc_s.1.1.dylib' (no such file), '/Users/Matt/Documents/OpenSimArtifacts/opensim-core-4.5.1-2024-10-02-9dd8e16/sdk/lib/../../sdk/Simbody/lib/libgcc_s.1.1.dylib' (no such file), '/Users/Matt/Documents/OpenSimArtifacts/opensim-core-4.5.1-2024-10-02-9dd8e16/sdk/Python/opensim/libgcc_s.1.1.dylib' (no such file), '/Users/Matt/Documents/OpenSimArtifacts/opensim-core-4.5.1-2024-10-02-9dd8e16/sdk/Python/opensim/../../../sdk/lib/libgcc_s.1.1.dylib' (no such file), '/Users/runner/work/opensim-core/opensim-core-install/sdk/lib/libgcc_s.1.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/runner/work/opensim-core/opensim-core-install/sdk/lib/libgcc_s.1.1.dylib' (no such file), '/Users/Matt/Documents/OpenSimArtifacts/opensim-core-4.5.1-2024-10-02-9dd8e16/sdk/Python/opensim/../../../sdk/Simbody/lib/libgcc_s.1.1.dylib' (no such file), '/Users/runner/work/opensim-core/opensim-core-install/sdk/Simbody/lib/libgcc_s.1.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/runner/work/opensim-core/opensim-core-install/sdk/Simbody/lib/libgcc_s.1.1.dylib' (no such file), '/Users/Matt/Documents/OpenSimArtifacts/opensim-core-4.5.1-2024-10-02-9dd8e16/sdk/Python/opensim/libgcc_s.1.1.dylib' (no such file), '/Users/Matt/Documents/OpenSimArtifacts/opensim-core-4.5.1-2024-10-02-9dd8e16/sdk/Python/opensim/../../../sdk/lib/libgcc_s.1.1.dylib' (no such file), '/Users/runner/work/opensim-core/opensim-core-install/sdk/lib/libgcc_s.1.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/runner/work/opensim-core/opensim-core-install/sdk/lib/libgcc_s.1.1.dylib' (no such file), '/Users/Matt/Documents/OpenSimArtifacts/opensim-core-4.5.1-2024-10-02-9dd8e16/sdk/Python/opensim/../../../sdk/Simbody/lib/libgcc_s.1.1.dylib' (no such file), '/Users/runner/work/opensim-core/opensim-core-install/sdk/Simbody/lib/libgcc_s.1.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/runner/work/opensim-core/opensim-core-install/sdk/Simbody/lib/libgcc_s.1.1.dylib' (no such file), '/opt/anaconda3/envs/moco_artifact/bin/../lib/libgcc_s.1.1.dylib' (no such file), '/opt/anaconda3/envs/moco_artifact/bin/../lib/libgcc_s.1.1.dylib' (no such file), '/usr/local/lib/libgcc_s.1.1.dylib' (no such file), '/usr/lib/libgcc_s.1.1.dylib' (no such file, not in dyld cache)Library not loaded: @rpath/libgcc_s.1.1.dylib
  Referenced from: <293D8721-79EB-3627-8D61-7B0EC0B7CD2C> /Users/Matt/Documents/OpenSimArtifacts/opensim-core-4.5.1-2024-10-02-9dd8e16/sdk/lib/libgfortran.5.dylib
  Reason: tried: '/libgcc_s.1.1.dylib' (no such file), '/Users/Matt/Documents/OpenSimArtifacts/opensim-core-4.5.1-2024-10-02-9dd8e16/sdk/lib/libgcc_s.1.1.dylib' (no such file), '/Users/Matt/Documents/OpenSimArtifacts/opensim-core-4.5.1-2024-10-02-9dd8e16/sdk/Simbody/lib/libgcc_s.1.1.dylib' (no such file), '/Users/Matt/Documents/OpenSimArtifacts/opensim-core-4.5.1-2024-10-02-9dd8e16/sdk/lib/libgcc_s.1.1.dylib' (no such file), '/Users/Matt/Documents/OpenSimArtifacts/opensim-core-4.5.1-2024-10-02-9dd8e16/sdk/lib/libgcc_s.1.1.dylib' (no such file), '/Users/Matt/Documents/OpenSimArtifacts/opensim-core-4.5.1-2024-10-02-9dd8e16/sdk/lib/libgcc_s.1.1.dylib' (no such file), '/Users/Matt/Documents/OpenSimArtifacts/opensim-core-4.5.1-2024-10-02-9dd8e16/sdk/lib/../../sdk/Simbody/lib/libgcc_s.1.1.dylib' (no such file), '/Users/Matt/Documents/OpenSimArtifacts/opensim-core-4.5.1-2024-10-02-9dd8e16/sdk/Python/opensim/libgcc_s.1.1.dylib' (no such file), '/Users/Matt/Documents/OpenSimArtifacts/opensim-core-4.5.1-2024-10-02-9dd8e16/sdk/Python/opensim/../../../sdk/lib/libgcc_s.1.1.dylib' (no such file), '/Users/runner/work/opensim-core/opensim-core-install/sdk/lib/libgcc_s.1.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/runner/work/opensim-core/opensim-core-install/sdk/lib/libgcc_s.1.1.dylib' (no such file), '/Users/Matt/Documents/OpenSimArtifacts/opensim-core-4.5.1-2024-10-02-9dd8e16/sdk/Python/opensim/../../../sdk/Simbody/lib/libgcc_s.1.1.dylib' (no such file), '/Users/runner/work/opensim-core/opensim-core-install/sdk/Simbody/lib/libgcc_s.1.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/runner/work/opensim-core/opensim-core-install/sdk/Simbody/lib/libgcc_s.1.1.dylib' (no such file), '/Users/Matt/Documents/OpenSimArtifacts/opensim-core-4.5.1-2024-10-02-9dd8e16/sdk/Python/opensim/libgcc_s.1.1.dylib' (no such file), '/Users/Matt/Documents/OpenSimArtifacts/opensim-core-4.5.1-2024-10-02-9dd8e16/sdk/Python/opensim/../../../sdk/lib/libgcc_s.1.1.dylib' (no such file), '/Users/runner/work/opensim-core/opensim-core-install/sdk/lib/libgcc_s.1.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/runner/work/opensim-core/opensim-core-install/sdk/lib/libgcc_s.1.1.dylib' (no such file), '/Users/Matt/Documents/OpenSimArtifacts/opensim-core-4.5.1-2024-10-02-9dd8e16/sdk/Python/opensim/../../../sdk/Simbody/lib/libgcc_s.1.1.dylib' (no such file), '/Users/runner/work/opensim-core/opensim-core-install/sdk/Simbody/lib/libgcc_s.1.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/runner/work/opensim-core/opensim-core-install/sdk/Simbody/lib/libgcc_s.1.1.dylib' (no such file), '/opt/anaconda3/envs/moco_artifact/bin/../lib/libgcc_s.1.1.dylib' (no such file), '/opt/anaconda3/envs/moco_artifact/bin/../lib/libgcc_s.1.1.dylib' (no such file), '/usr/local/lib/libgcc_s.1.1.dylib' (no such file), '/usr/lib/libgcc_s.1.1.dylib' (no such file, not in dyld cache)
```

**Comment by aymanhab** [comment]
No worries @mattpetrucci  libgcc_s.1.1 is another system library that we can also include "begrudgingly" at least we know the previous fixes to handle libgfortran worked as expected 👍

**Comment by aymanhab** [comment]
@mattpetrucci Time for the next Whackamole round to see what pops up this time ;)  Thank you

**Comment by mattpetrucci** [comment]
@aymanhab This worked! I just had to pip install numpy since I was in a clean conda environment.

```
ModuleNotFoundError: No module named 'numpy'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Matt/Documents/OpenSimArtifacts/opensim-core-4.5.1-2024-10-03-fa63a37/sdk/Python/opensim/__init__.py", line 18, in <module>
    from .simbody import *
  File "/Users/Matt/Documents/OpenSimArtifacts/opensim-core-4.5.1-2024-10-03-fa63a37/sdk/Python/opensim/simbody.py", line 10, in <module>
    from . import _simbody
ImportError: numpy.core.multiarray failed to import
```

Once I cleared that error, no issues.

**Comment by aymanhab** [comment]
Outstanding, thanks for your patience 👍

**Comment by aymanhab** [comment]
Build failure on windows is unrelated as the PR doesn't touch any windows build related files.

**Review by nickbianco — CHANGES_REQUESTED** [review]
Looks good overall @aymanhab! I had a few minor comments about whether to keep or remove some commented out lines and debugging statements.

> Reviewed 1 of 2 files at r3, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3920#-:-O8ht3VZEjDlvL9PZzK3:b-uaedg2)* status: all files reviewed, 4 unresolved discussions (waiting on @AlbertoCasasOrtiz and @aymanhab)

___
*[`Vendors/tropter/cmake/CMakeLists.txt` line 13 at r5](https://reviewable.io/reviews/opensim-org/opensim-core/3920#-O8hsVch9y0K7zEBth5Y:-O8hsVch9y0K7zEBth5Z:b-b9zekg) ([raw file](https://github.com/opensim-org/opensim-core/blob/29cd4cc16404ed1dfd484d5341cd746a65ca1aac/Vendors/tropter/cmake/CMakeLists.txt#L13)):*
> ```CMake
>         #message(STATUS "ipopt dir ${IPOPT_LIBDIR}" )
>         message(STATUS "libgfortran_name ${libgfortran_name}")
>         message(STATUS "l==============================================================================")
> ```

Did you want to keep or remove these message statements? Can't tell if they're for debugging in this PR, or for future debugging. At least the commented out line and the last line with all the equal signs could be removed.
___
*[`Vendors/tropter/cmake/CMakeLists.txt` line 16 at r5](https://reviewable.io/reviews/opensim-org/opensim-core/3920#-O8hsiLV4Ut7T9hDfrn3:-O8hsiLV4Ut7T9hDfrn4:ba3dfna) ([raw file](https://github.com/opensim-org/opensim-core/blob/29cd4cc16404ed1dfd484d5341cd746a65ca1aac/Vendors/tropter/cmake/CMakeLists.txt#L16)):*
> ```CMake
> 
>     string(REPLACE "libgfortran.5" "libgcc_s.1.1" libgcc_name ${libgfortran_name})
>     message(STATUS "libgcc_name ${libgcc_name}")
> ```

Remove?
___
*[`Vendors/tropter/cmake/CMakeLists.txt` line 22 at r5](https://reviewable.io/reviews/opensim-org/opensim-core/3920#-O8hsl4m4d7OwC7W7rWl:-O8hsl4m4d7OwC7W7rWm:ba3dfna) ([raw file](https://github.com/opensim-org/opensim-core/blob/29cd4cc16404ed1dfd484d5341cd746a65ca1aac/Vendors/tropter/cmake/CMakeLists.txt#L22)):*
> ```CMake
>         OUTPUT_VARIABLE libquadmath_name
>         OUTPUT_STRIP_TRAILING_WHITESPACE)
>         message(STATUS "libquadmath_name ${libquadmath_name}")
> ```

Remove?
___
*[`Vendors/tropter/cmake/tropter_install_mac_dependency_libraries.cmake.in` line 81 at r5](https://reviewable.io/reviews/opensim-org/opensim-core/3920#-O8hsxXMBrB-IHoe4TVb:-O8hsxXMBrB-IHoe4TVc:b-6iumz9) ([raw file](https://github.com/opensim-org/opensim-core/blob/29cd4cc16404ed1dfd484d5341cd746a65ca1aac/Vendors/tropter/cmake/tropter_install_mac_dependency_libraries.cmake.in#L81)):*
> ```
> #install_name_tool_change(tropter coinmumps.3 "@IPOPT_LIBDIR@")
> #install_name_tool_change(tropter metis "@IPOPT_LIBDIR@")
> #install_name_tool_add_rpath(tropter)
> ```

Remove commented out lines?

**Review by aymanhab — COMMENTED** [review]
Totally, commented /debugging lines were removed

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3920#-:-O8iKobP0MbLj5lV7PcL:b-thwnlr)* status: 1 of 3 files reviewed, 4 unresolved discussions (waiting on @AlbertoCasasOrtiz and @nickbianco)

**Review by nickbianco — APPROVED** [review]
:LGTM:

**Comment by aymanhab** [comment]
Thanks @nickbianco 🥇

**Pull request merged**
