### PR TITLE
Throw exception if xml tag for an object is not recognized

### PR DESCRIPTION
**Pull request by aymanhab**
Fixes issue #2911 

### Brief summary of changes
Throw instead of logging an error when an recognized type is found in osim/xml file

### Testing I've completed
Run the test suite

### CHANGELOG.md (choose one)
- updated.

---
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2914)

### CODE REVIEW

**Review by nickbianco — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2914)* status: all files reviewed, 1 unresolved discussion (waiting on @aymanhab)

___
*[OpenSim/Common/Object.cpp, line 606 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2914#-MO3d_US1NPTOw9IrHQV:-MO3d_US1NPTOw9IrHQW:b-o5s8y7) ([raw file](https://github.com/opensim-org/opensim-core/blob/9205e78df12039ab5d80e3673a79202ee5b29a93/OpenSim/Common/Object.cpp#L606)):*
> ```cpp
>         return defaultObj->clone();
> 
>     throw Exception( "Object::newInstanceOfType(): object type '{}' is not a registered Object! It will be ignored.", objectTypeTag);
> ```

Should we use log_error() here (and below)?

**Review by aymanhab — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2914)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @nickbianco)

___
*[OpenSim/Common/Object.cpp, line 606 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2914#-MO3d_US1NPTOw9IrHQV:-MO5GwnWAgtw_V1R3EUq:b-9s4rkl) ([raw file](https://github.com/opensim-org/opensim-core/blob/9205e78df12039ab5d80e3673a79202ee5b29a93/OpenSim/Common/Object.cpp#L606)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

Should we use log_error() here (and below)?
</blockquote></details>

I added the log_error but typically an Exception is thrown to indicate a catastrophic failure so nobody goes back to check the log as is the case with other exceptions in the same file but I added it anyway. Thanks @nickbianco

**Comment by adamkewley** [comment]
Thanks for looking into this, but I don't understand the solution. 

Doesn't this change effectively just throw an exception into a [Pokemon handler](https://www.hackterms.com/pokemon%20exception%20handling) which discards the exception entirely and demotes it to a warning message anyway? The warning still fairly vague and mention `It will be ignored` as part of an *exception* message. Is that the intent?

If this is related to #2911 then, to clarify, being unable to instantiate an object in the osim file should throw an exception that causes the entire application to fail.

**Review by nickbianco — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2914)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aymanhab)

**Review by aymanhab — COMMENTED** [review]
@adamkewley Thanks for the "catch" and the "Pokemon" reference :smile: Indeed the earlier commits were intended to fix the test cases that were relying on the erroneous behavior. Now they are all fixed and the exception is being propagated. A test case was beefed up to test the change. Please let me know if this PR fixes issue #2911 or if not how it changes the behavior if any. Thank you

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2914#-:-MOCf6jT5wFASjWbHQCn:b-adp2zs)* status: 3 of 4 files reviewed, all discussions resolved

**Comment by aymanhab** [comment]
Pending further testing by @adamkewley

**Comment by adamkewley** [comment]
All seems good, but I need to quickly check this branch out and try (e.g.) `opensim-cmd` with it to see how it crashes

**Comment by adamkewley** [comment]
The error isn't being propagated when (e.g.) running `opensim-cmd`. 

If I follow the same steps as in #2911:

- Copy Arm26
- Add `<BsMuscle></BsMuscle>` to the `<ForceSet><objects>`
- Use that file

It's printing:

```
[info] Preparing to run ForwardTool.
[info] AbstractTool default loading model Arm26/arm26.osim
[info] Updating Model file from 20303 to latest format...
[error] Object::newInstanceOfType(): object type 'BsMuscle' is not a registered Object! It will be ignored.
Object type BsMuscle not recognized
[info] Loaded model arm26 from file Arm26/arm26.osim
[warning] Couldn't find file 'ground_ribs.vtp'
# other warnings
```

Where `Object type BsMuscle not recognized` is what the Pokemon catcher prints in `Object.cpp:941`. The behavior I'm expecting is that the execution halts with an error.

**Comment by aymanhab** [comment]
@adamkewley There's no Pokemon catcher at Object.cpp:941, you maybe looking at an earlier version of the code. At any rate, if the Model construction aborts and throws an exception then it's up to the call-site to decide how to handle it AFAIK. It could be that our tools/commands don't handle this properly but keep in mind that the same library code is used from the application/GUI where exceptions should not cause abort/catastrophic failure.

**Comment by adamkewley** [comment]
@aymanhab what you are saying was not true when I tested it this morning. 

The github UI might hide this, but my reflogs + signed email chains do not. The latest commit in this repository was `4af02b801ba3a65bed5bac423eec6e991bd0f08b` this morning:

```
git log --walk-reflogs --date=iso
commit 4af02b801ba3a65bed5bac423eec6e991bd0f08b (HEAD -> throw_unrecognized_type_osim, origin/throw_unrecognized_type_osim)
Reflog: HEAD@{2020-12-15 08:54:48 +0000} (Adam Kewley <contact@adamkewley.com>)
Reflog message: checkout: moving from master to throw_unrecognized_type_osim
Author: aymanhab <ahabib@stanford.edu>
Date:   2020-12-09 11:41:27 -0800

    Register type that was causing testProbes to fail

commit d7e92c2a7f5fc923f7537f0d582fb3b9ebda838d (origin/master, origin/HEAD, master)
Reflog: HEAD@{2020-12-15 08:44:41 +0000} (Adam Kewley <contact@adamkewley.com>)
Reflog message: clone: from https://github.com/opensim-org/opensim-core.git
Merge: 2a491899f 6fa8e586c
Author: Adam Kewley <contact@adamkewley.com>
Date:   2020-12-15 09:40:15 +0100

    Merge pull request #2877 from adamkewley/feature-merge-scapulothoracicjoint
    
    Feature merge ScapulothoracicJoint into opensim-core
```

And you retrospectively pushed the changes shown in the github UI around 8 minutes before writing your reply:

```
Delivered-To: adamk117@gmail.com
Received: by 2002:a02:a515:0:0:0:0:0 with SMTP id e21csp3989300jam;
        Tue, 15 Dec 2020 09:23:44 -0800 (PST)
X-Google-Smtp-Source: ABdhPJzHZOti2lNo6+bH3Ef2qHC0ScyC3Z2OOs8yiZW2X2VvZkceWBoBsOS+hDzLgJkIF1rqQY3g
X-Received: by 2002:a17:90a:aa8f:: with SMTP id l15mr29826788pjq.135.1608053023814;
        Tue, 15 Dec 2020 09:23:43 -0800 (PST)

----==_mimepart_5fd8f11d7002f_5e19b4248425
Content-Type: text/plain;
 charset=UTF-8
Content-Transfer-Encoding: 7bit

@aymanhab pushed 2 commits.

f09f5988157ee6b45a9bd8d0d371c5c3e95f6c25  Propagate Exception thrown when unrecognized type is encountered and fix test case that utilized incorrect behavior
89ea61f6f0ec7679514a4194dff1a5d7eb876f47  Beef up testSerialization to check throw on unrecognized types


-- 
```

Figuring this out--because rectifying this kind of rudimentary mistake in my workflow is quite important for me--wasted roughly 10 minutes of my time. 

The revision I had access to did have that defect:

```
awk '{if(935 < NR && NR < 945) print $0}' OpenSim/Common/Object.cpp

            while(iter != propElementIter->element_end()){
                // Create an Object of the element tag's type.
                try {
                    object = newInstanceOfType(iter->getElementTag());
                } catch (const Exception& ) { 
                    std::cerr << "Object type " << iter->getElementTag() << " not recognized" 
                              << std::endl; 
                    iter++; 
                    continue; 
```

**Comment by aymanhab** [comment]
@adamkewley I made a push this morning to make sure the repo is up to date with my local version from days ago so this may explain, though the trail on this PR didn't show new commits so I assumed it was up to date already, sorry about the confusion. Anyway, let me know if the latest version addresses your issue. Thank you.

**Comment by adamkewley** [comment]
All seems within expectations when I gave it a try:

```
[info] Updating Model file from 30000 to latest format...
[error] Object::newInstanceOfType(): object type 'ToyReflexController' is not a registered Object! It will be ignored.
[*** LOG ERROR #0001 ***] [2020-12-18 15:34:10] [] {argument not found}
```

Although one thing I'm wondering is how many legacy files are going to break OpenSim when in this stricter mode (the above was `ToyDropLanding`).

**Comment by aymanhab** [comment]
Thanks for the review & testing @adamkewley 👍  You probably see more plugins/missing-type issues than typical users due to the shoulder model plugin but even that will be reduced the next time around. I think a clear failure is better than quiet failure as you pointed out earlier, so I'll go ahead and merge.

**Pull request merged**
