### PR TITLE
[bindings] Thelen depends on pennation/activation classes.

### LINKED ISSUE #688: MuscleFixedWidthPennationModel and MuscleFirstOrderActivationDynamicModel are not properly wrapped
I can get the objects of these types but I can't do anything with them (no methods/properties).

Observed in MATLAB.

### PR DESCRIPTION
**Pull request by chrisdembia**
Fixes #688 

@aymanhab could you review?

### CODE REVIEW

**Comment by aymanhab** [comment]
@chrisdembia Don't know why Appveyor test failed, since likely unrelated. The changes related to Thelen muscle look good/appropriate.

For the first time I saw a list of warnings related to DataTable.h. @klshrinidhi Did you have a chance to look into these warnings, or did you check the resulting python classes @chrisdembia ? If not we should open a separate issue to address. Thanks.

**Comment by chrisdembia** [comment]
Nice catch.

**Comment by chrisdembia** [comment]
Ready for review again.

**Comment by chrisdembia** [comment]
Thank you.

**Pull request merged**
