### PR TITLE
[WIP] CMake BUILD_TYPE/CONFIGURATION mismatch issue 

### PR DESCRIPTION
**Pull request by klshrinidhi**
Addressing #1276.

Windows testing was done in #1475. Appveyor builds show that the solution successfully stops the build when a mismatch in CONFIG is found between Simbody and OpenSim.
Linux testing was done locally.

### CODE REVIEW

**Comment by chrisdembia** [comment]
I like the overall strategy. This will certainly help users. Have you tried this on Windows when Simbody has been built and installed in multiple configurations (e.g., Release and Debug)? In that case, in which case my hunch is that `Simbody_CONFIGURATION` is `"Debug;Release"`.

**Comment by klshrinidhi** [comment]
I have not. I have to test that.

**Comment by aymanhab** [comment]
What is e-bugging 😃 ?

**Comment by chrisdembia** [comment]
> What is e-bugging 😃 ?

Its what all the cool kids are doing these days.

**Comment by klshrinidhi** [comment]
Replacing this PR with #1487.

**Pull request closed without merging**
