### PR TITLE
Fix some CMC tests in Debug

### PR DESCRIPTION
**Pull request by chrisdembia**
Two of the CMC tests were failing in debug because the minimum step size for the integrator was set to an invalid value of 0. This PR fixes those two tests.

There is still one more CMC test that is failing in debug mode due to timing out; I have left that as ignored for now.

### CODE REVIEW

**Comment by chrisdembia** [comment]
> Perhaps just set minimum_integrator_step_size to 1e-12?

Sounds good to me; will do.

**Comment by chrisdembia** [comment]
Tests are passing. Looking for another reviewer.

**Comment by aseth1** [comment]
It may avoid confusion if the default value in `AbstactTool` matched what is in the setup files as well. 
Currently,
`_minDT = 1.0e-8;`

Maybe change that to `1.0e-12` as well?

Otherwise LGTM and  :+1: for finding and sorting out the issue. Thanks!

**Comment by chrisdembia** [comment]
Changing the default values will change people's results. I'd prefer to change the value in the CMC test setup files to 1e-8; is that fine?

**Comment by tkuchida** [comment]
> I'd prefer to change the value in the CMC test setup files to 1e-8; is that fine?

:+1: (assuming the tests pass). I should have suggested to set `minimum_integrator_step_size` to _something small_, not to 1e-12 specifically.

**Comment by aseth1** [comment]
> I'd prefer to change the value in the CMC test setup files to 1e-8; is that fine?

Yes. I think that would be consistent with what was being used by default.

**Comment by chrisdembia** [comment]
I will re-ignore `testOptimizationExample*` on travis because it has been timing out sporadically on travis. This PR will still provide the benefit of no longer ignoring some of the CMC tests.

**Comment by chrisdembia** [comment]
Thanks for the initial reviews. This is ready for review/merge.

**Comment by chrisdembia** [comment]
Thank you @tkuchida

**Pull request merged**
