### PR TITLE
Create a CTest for the python examples

### PR DESCRIPTION
**Pull request by chrisdembia**
This PR runs CTest on the Python tests, and addresses #1294.

This PR also takes advantage of features in CMake 3.0 to simplify some of the cmake scripts.

### CODE REVIEW

**Comment by klshrinidhi** [comment]
:+1:

**Comment by chrisdembia** [comment]
Thanks @klshrinidhi . Would anyone else be interested in reviewing this?

**Comment by aymanhab** [comment]
Sure, looking good. Merging.

**Comment by chrisdembia** [comment]
Thank you!

**Pull request merged**
