### PR TITLE
Use imus in opensense

### PR DESCRIPTION
**Pull request by aymanhab**
Fixes issue #0

### Brief summary of changes
When using IMUPlacer, create and add IMUs to the calibrated model. Make sure IMUs are added in the ModelComponent Set so that they're accessible to GUI.

### Testing I've completed
Built GUI against this branch, ran IMU placer, calibrated model matched 4.2 and IMUs are accessible.

### Looking for feedback on...
Whether this needs to be documented since it should be transparent to users

### CHANGELOG.md (choose one)

- no need to update because...
- updated.

---
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3002)

### CODE REVIEW

**Comment by aymanhab** [comment]
@carmichaelong This PR basically uses the IMU abstraction introduced in PR #2997 so that the IMUPlacer creates IMUs rather than frames and arbitrary blocks of geometry. Allowing GUI to show IMUs and treat them uniformly for Analysis/reporting purposes.

**Review by carmichaelong — COMMENTED** [review]
Looks good overall. I just had one comment which was more of a question than a blocking comment

> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3002#-:-Ma_EEy65jQQbwsTzMC_:b-kgtqb5)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @aymanhab)

___
*[OpenSim/Analyses/IMUDataReporter.cpp, line 159 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3002#-Ma_E6cC7CDZ3cJYqsM7:-Ma_E6cC7CDZ3cJYqsM8:bgjnsd8) ([raw file](https://github.com/opensim-org/opensim-core/blob/5266e9c9c1cd0937c4c583fa40827d0d1336ee94/OpenSim/Analyses/IMUDataReporter.cpp#L159)):*
> ```cpp
>         for (IMU& imu : compList) { 
>             SimTK::ReferencePtr<OpenSim::IMU> imuRef(imu);
>             _imuComponents.push_back(std::shared_ptr<IMU>(imuRef.get())); 
> ```

I assume this was a necessary change, but I'm curious as to why `make_shared` needed to be replaced here?

**Comment by aymanhab** [comment]
@carmichaelong make_shared<> create a new object and the shared pointer, in this case we don't want to create an object, just initialize the shared_ptr with existing pointer. Pretty messy but justified because when using it from GUI I was getting assertions/failures due to the implicit copying due to make_shared

**Comment by aymanhab** [comment]
This is ready for review, the essence of the change is moving away from shared_ptr to Objects that live in a Model due to reference counting issues and mostly sticking with home brew SimTK::ReferencePtr which isn't reference counted. This incarnation works well with corresponding GUI PR

**Review by carmichaelong — CHANGES_REQUESTED** [review]
Thanks @aymanhab, looks good. I left one small comment. One other question in general: It seems like the std smart pointers aren't playing with the GUI very well, so seems like using the SimTK ones is a good solution now. Are there any problems you foresee down the road with doing this? (I wouldn't consider this a blocking question)

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3002#-:-MaywFqg1EguuWyHaiHI:b-zbnnop)* status: 1 of 10 files reviewed, 2 unresolved discussions (waiting on @aymanhab and @carmichaelong)

___
*[OpenSim/Simulation/OpenSense/IMU.h, line 47 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3002#-Mayub-f446bz0STntcO:-Mayub-f446bz0STntcP:b-597xwg) ([raw file](https://github.com/opensim-org/opensim-core/blob/7a99b604454139c76381029cda7ec7f090c508d0/OpenSim/Simulation/OpenSense/IMU.h#L47)):*
> ```objc
>     IMU() {  }
>     virtual ~IMU() { 
>     };
> ```

Why are the constructor and destructor empty rather than default?

**Review by aymanhab — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3002)* status: 1 of 10 files reviewed, 2 unresolved discussions (waiting on @aymanhab and @carmichaelong)

___
*[OpenSim/Simulation/OpenSense/IMU.h, line 47 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3002#-Mayub-f446bz0STntcO:-Mazq8mE5OzXvCRxf40r:bhx97t2) ([raw file](https://github.com/opensim-org/opensim-core/blob/7a99b604454139c76381029cda7ec7f090c508d0/OpenSim/Simulation/OpenSense/IMU.h#L47)):*
<details><summary><i>Previously, carmichaelong wrote…</i></summary><blockquote>

Why are the constructor and destructor empty rather than default?
</blockquote></details>

With no private data members they should be the same, I mainly introduced the bodies to place debugging/logging lines there but ended up removing. Changed to default for consistency with the remaining constructors/copy/move operators etc.

**Comment by aymanhab** [comment]
@carmichaelong This should be good to go, thanks for the quick turnaround.

**Review by carmichaelong — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3002#-:-Mb8-qnt3EAtz4R18UMv:bnfp4nl)* status: 1 of 10 files reviewed, 1 unresolved discussion (waiting on @aymanhab and @carmichaelong)

**Comment by aymanhab** [comment]
Thanks @carmichaelong much appreciated 👍

**Pull request merged**
