### PR TITLE
[TGCS] Address remaining dry run feedback.

### PR DESCRIPTION
**Pull request by chrisdembia**
### Brief summary of changes

- Give a more useful error message for when users exit the visualizer without simulating once.
- Instruct users to use an appropriate variable name for the reporter, since the remaining code assumes a specific name.
- Tell users that simulating won't work after adding the device but before wiring up the controller's input.

### Testing I've completed

Ran all 3 parts of the tutorial successfully.

### CHANGELOG.md (choose one)

- no need to update because hopper example was not in 3.3.

### CODE REVIEW

**Comment by nickbianco** [comment]
LGTM. The new error message and plotting changes worked fine in my test.

**Comment by chrisdembia** [comment]
> LGTM. The new error message and plotting changes worked fine in my test.

Great. Thanks for testing.

**Comment by carmichaelong** [comment]
Didn't even realize that notice the error message was that seemingly weird when you don't run a simulation. Just tested before and after and all LGTM.

**Comment by chrisdembia** [comment]
Yeah you get an exception in `toString_impl()`. Thanks for trying the changes @carmichaelong . I'll merge this now.

**Pull request merged**
