### PR TITLE
Fix testInitState for macOS.

### PR DESCRIPTION
**Pull request by chrisdembia**
This PR fixes the failure of testInitState on macOS. This was done by increasing the number of samples used to validateMemoryUseEstimates.

### CODE REVIEW

**Comment by chrisdembia** [comment]
@tkuchida I have addressed your comment.

**Comment by tkuchida** [comment]
Looks good, but I don't think I can merge (per [Rule 6](https://github.com/opensim-org/opensim-core/blob/master/CONTRIBUTING.md#making-a-pull-request-pr)).

**Comment by chrisdembia** [comment]
Thanks @tkuchida.  Tests passing. Looking for another reviewer.

**Comment by aseth1** [comment]
LGTM

**Comment by chrisdembia** [comment]
Thank you!

**Pull request merged**
