### PR TITLE
Convert testConstraints to catch2

### PR DESCRIPTION
**Pull request by AllisonJohn**
Fixes issue #3555

### Brief summary of changes
Added catch2 to the cmake file for SimbodyEngine and converted testConstraints to catch2

### Testing I've completed
testConstaints still passes

### CHANGELOG.md (choose one)
- no need to update because... internal

- - -
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3837)

### CODE REVIEW

**Review by nickbianco — CHANGES_REQUESTED** [review]
Just one minor formatting request.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3837#-:-O12jgli3jbtOT6OWbt5:b-c19jmi)* status: all files reviewed, 1 unresolved discussion (waiting on @AllisonJohn)

___
*[`OpenSim/Simulation/SimbodyEngine/Test/testConstraints.cpp` line 71 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3837#-O12jW5777JWTYawKNY8:-O12jW5777JWTYawKNY9:b-g35vea) ([raw file](https://github.com/opensim-org/opensim-core/blob/9778d8761f9594757dc655dc9b08a8f86c130cc0/OpenSim/Simulation/SimbodyEngine/Test/testConstraints.cpp#L71)):*
> ```cpp
> #include "SimTKsimbody.h"
> ```

nit: Move catch2 include here and remove extra lines.

**Comment by nickbianco** [comment]
@AllisonJohn, I reviewed this PR using Reviewable, we'll use that for reviews from now on. Click the purple button in the PR description to leave your response. Let me know if you have any questions about how it works.

**Review by AllisonJohn — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3837)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AllisonJohn)

**Comment by AllisonJohn** [comment]
> @AllisonJohn, I reviewed this PR using Reviewable, we'll use that for reviews from now on. Click the purple button in the PR description to leave your response. Let me know if you have any questions about how it works.

Hopefully it's ok that I merged it, it seemed like reviewable wanted me to do that

**Pull request merged**
