### PR TITLE
Add ActivationCoordinateActuator.h

### PR DESCRIPTION
**Pull request by chrisdembia**
Addressed part of #2559 

### Brief summary of changes

This PR brings over Moco's ActivationCoordinateActuator, which is a CoordinateActuator with activation dynamics.

### Testing I've completed

ActivationCoordinateActuator has been used successfully in Moco for many months.

### CHANGELOG.md (choose one)

- updated...

The Doxygen for this PR can be viewed at http://myosin.sourceforge.net/?C=N;O=D; click the folder whose name is this PR's number.

---
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2699)

### CODE REVIEW

**Comment by chrisdembia** [comment]
We have a test in Moco that tests the bounds on the activation state, but this test depends on Moco.

Any suggestions for how to test this? I can add it to `testComponents.cpp`, which tests serialization, etc.

**Comment by aymanhab** [comment]
@chrisdembia if there's a small subset of moco that exercises this functionality then we can do it altogether, if not just add it to the generic Component tests for connection/serialization. At the end of the day users will see it regardless if using Moco or not and they will ask how to use it (in FD, SO, etc.)

**Comment by chrisdembia** [comment]
@aymanhab I pushed a test case.

Ready for review again.

**Comment by chrisdembia** [comment]
Thanks @aymanhab

**Comment by carmichaelong** [comment]
PR looks good. Just one tiny comment about how we document CHANGELOG which may not be relevant for this PR anyway.

**Comment by chrisdembia** [comment]
Thanks @carmichaelong . I added the PR number to the changelog.

Ready for review.

**Comment by carmichaelong** [comment]
:lgtm:

**Comment by chrisdembia** [comment]
Thanks. Merging.

**Comment by ostr1969** [comment]
I have tried. there are 3 issues:
1. there is a comment line in ActivationCoordinateActuator that says :
"Larger value means activation can change more rapidly "
this is wrong/oposite
2. controllers not shown in opensim gui.
3. there is a problem in model.getcontroltable
Exception in 4links_example: Incorrect number of columns,  Thrown at DataTable.h:662 in appendRow()

**Comment by chrisdembia** [comment]
> 1. there is a comment line in ActivationCoordinateActuator that says :
>    "Larger value means activation can change more rapidly "
>    this is wrong/oposite

Thanks for catching this!! I opened a new pull request.



> 2\. controllers not shown in opensim gui.

I'm not sure which controller you're mentioning. `ActivationCoordinateActuator` is an Actuator that is not yet supported in the released 4.1 GUI (it's only just been merged into this repository).

**Comment by ostr1969** [comment]
also model.print and then model(string) gives:
Encountered unrecognized Object typename ActivationCoordinateActuator while reading property 
so you cant save and restore a model with this actuator.

**Comment by chrisdembia** [comment]
@ostr1969 Did you build the master branch of the repository from source?

**Pull request merged**
