### PR TITLE
Update SWIG annotated header to be in sync. with latest Simbody Decorati...

### PR DESCRIPTION
**Pull request by aymanhab**
...veGeometry. This fixes build problems for SWIG generated files.

### CODE REVIEW

**Comment by chrisdembia** [comment]
This file was essentially copied over from Simbody, right?

**Comment by aymanhab** [comment]
Yes, except a few lines had to be ifdef SWIG out to work around the PIMPL macros etc.

**Comment by chrisdembia** [comment]
Looks good to me then. Any other reviewers?

**Comment by aymanhab** [comment]
Thanks @chrisdembia maybe @sherm1 can review since he's familiar with the change in Simbody and this check-in is intended to bring the two projects in sync.

**Comment by sherm1** [comment]
Looks good to me. Is there anything there other than copying in the new DecorativeGeometry.h and #ifdef-ing out the PIMPL stuff?

**Comment by aymanhab** [comment]
Nope that's it.

**Comment by aymanhab** [comment]
Thanks Sherm.

**Pull request merged**
