### PR TITLE
Move PositionMotion class from Moco/Components to Simulation

### PR DESCRIPTION
**Pull request by aymanhab**
Also fix call sites and bindings

Fixes issue #3023

### Testing I've completed
Ran test suite
### CHANGELOG.md (choose one)

- no need to update because should be transparent to users

---
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3024)

### CODE REVIEW

**Review by nickbianco — CHANGES_REQUESTED** [review]
LGTM. Left a few comments, but they could be ignored.

> Reviewed 19 of 19 files at r1.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3024#-:-MdTy7aw2AdC_W6Pn6lU:bkho5su)* status: all files reviewed, 3 unresolved discussions (waiting on @aymanhab)

___
*[Bindings/Java/swig/java_simulation.i, line 206 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3024#-MdTxSSh1nk0qqyDuqif:-MdTxSSh1nk0qqyDuqig:b-jz5vf5) ([raw file](https://github.com/opensim-org/opensim-core/blob/d11c581cc536e025f9acd3753e08b0f43d5b47f6/Bindings/Java/swig/java_simulation.i#L206)):*
> ```SWIG
> 
> %import "java_common.i"
> moco_unique_ptr(OpenSim::PositionMotion);
> ```

I guess we could rename this macro to `unique_ptr` since it's not Moco specific. If `unique_ptr` is a conflict then maybe `java_unique_ptr`.
___
*[Bindings/Python/swig/python_simulation.i, line 134 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3024#-MdTxVCsD2ajMTSzoyIG:-MdTxVCsD2ajMTSzoyIH:brrx6al) ([raw file](https://github.com/opensim-org/opensim-core/blob/d11c581cc536e025f9acd3753e08b0f43d5b47f6/Bindings/Python/swig/python_simulation.i#L134)):*
> ```SWIG
> %template(_StdVectorState) std::vector<SimTK::State>;
> 
> moco_unique_ptr(OpenSim::PositionMotion);
> ```

Could rename this macro to `unique_ptr` since it's not Moco specific. If `unique_ptr` is a conflict then maybe `python_unique_ptr`.
___
*[OpenSim/Simulation/PositionMotion.h, line 26 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3024#-MdTxyBlClNvWVm6an5O:-MdTxyBlClNvWVm6an5P:bt9whce) ([raw file](https://github.com/opensim-org/opensim-core/blob/d11c581cc536e025f9acd3753e08b0f43d5b47f6/OpenSim/Simulation/PositionMotion.h#L26)):*
> ```objc
> #include <OpenSim/Common/TimeSeriesTable.h>
> #include <OpenSim/Simulation/Model/ModelComponent.h>
> #include "osimSimulationDLL.h"
> ```

Is the full path not needed for this include?

**Review by aymanhab — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3024)* status: all files reviewed, 3 unresolved discussions (waiting on @aymanhab and @nickbianco)

___
*[Bindings/Java/swig/java_simulation.i, line 206 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3024#-MdTxSSh1nk0qqyDuqif:-MdTykYe4Sv2rLyXII2k:b-t294ki) ([raw file](https://github.com/opensim-org/opensim-core/blob/d11c581cc536e025f9acd3753e08b0f43d5b47f6/Bindings/Java/swig/java_simulation.i#L206)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

I guess we could rename this macro to `unique_ptr` since it's not Moco specific. If `unique_ptr` is a conflict then maybe `java_unique_ptr`.
</blockquote></details>

The name of the macro in java/preliminaries.i and python/preliminaries.i is already moco_unique_ptr despite the fact it's indeed not moco specific. I tried to keep this PR from mashrooming but in a separate PR we can rename to opensim_unique_ptr
___
*[OpenSim/Simulation/PositionMotion.h, line 26 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3024#-MdTxyBlClNvWVm6an5O:-MdU0e6N2ZYbMcWWkC-U:b-vfpcjs) ([raw file](https://github.com/opensim-org/opensim-core/blob/d11c581cc536e025f9acd3753e08b0f43d5b47f6/OpenSim/Simulation/PositionMotion.h#L26)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

Is the full path not needed for this include?
</blockquote></details>

No because the files are in the same folder.

**Review by aymanhab — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3024)* status: 10 of 21 files reviewed, 3 unresolved discussions (waiting on @nickbianco)

___
*[Bindings/Java/swig/java_simulation.i, line 206 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3024#-MdTxSSh1nk0qqyDuqif:-MdYo2YS3D8CA7W3SH0x:b-r42y2p) ([raw file](https://github.com/opensim-org/opensim-core/blob/d11c581cc536e025f9acd3753e08b0f43d5b47f6/Bindings/Java/swig/java_simulation.i#L206)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

The name of the macro in java/preliminaries.i and python/preliminaries.i is already moco_unique_ptr despite the fact it's indeed not moco specific. I tried to keep this PR from mashrooming but in a separate PR we can rename to opensim_unique_ptr
</blockquote></details>

I went ahead and renamed the macros to opensim_unique_ptr
___
*[Bindings/Python/swig/python_simulation.i, line 134 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3024#-MdTxVCsD2ajMTSzoyIG:-MdYoIYC4ZxB_fAa8IHi:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/d11c581cc536e025f9acd3753e08b0f43d5b47f6/Bindings/Python/swig/python_simulation.i#L134)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

Could rename this macro to `unique_ptr` since it's not Moco specific. If `unique_ptr` is a conflict then maybe `python_unique_ptr`.
</blockquote></details>

Done.
___
*[OpenSim/Simulation/PositionMotion.h, line 26 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3024#-MdTxyBlClNvWVm6an5O:-MdYoEDI-TLDXepHbLqh:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/d11c581cc536e025f9acd3753e08b0f43d5b47f6/OpenSim/Simulation/PositionMotion.h#L26)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

No because the files are in the same folder.
</blockquote></details>

Done.

**Review by nickbianco — APPROVED** [review]
:lgtm:

> Reviewed 11 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3024#-:-MdcNI63BkbB8ai02BGl:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aymanhab)

**Comment by aymanhab** [comment]
Thanks @nickbianco I'll keep this on a branch until TGCS build is ready so we don't change the API/bindings (due to moving the class between two libraries)

**Review by nickbianco — APPROVED** [review]
I think we could merge this now to keep the other PR moving along. The PositionMotion class isn't really supposed to be used directly, so the bindings and API changes shouldn't be a problem. Unless you're worried about the CI builds (or something)?

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3024#-:-MdykKrJ-mjh2j5xbwYs:b-xo0m3a)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aymanhab)

**Comment by aymanhab** [comment]
Didn't want to introduce changes before practice session but can merge now.
Thank you

**Review by nickbianco — APPROVED** [review]
Sounds good!

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3024#-:-Mdz0YFY-R6i9Iy_qo7-:bdnerq5)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aymanhab)

**Comment by aymanhab** [comment]
Thanks @nickbianco

**Pull request merged**
