### PR TITLE
Remove isObjectUpToDateWithProperties() checks (asserts) from Thelen2003Muscle

### PR DESCRIPTION
**Pull request by aseth1**
Checking `isObjectUpToDateWithProperties()` prior to any calculation in a `Component` is not a sustainable approach to maintaining validity. That is a separate issue from this PR, but why I think we are justified in removing the asserts.

The asserts fail because `Thelen2003Muscle::isObjectUpToDateWithProperties` is almost always `false` since `GeometryPath` updates its `PathPointSet` property during a simulation.
This was causing any test case using the `Thelen2004Muscle` to fail in debug. IMHO it is more important to run these tests in debug than have these asserts in place, so they were removed. The GeometryPath rummaging through properties is also another issue we should fix, but separate from this one.

Locally, I still get tests that timeout but others like `testInducedAccelerations` now pass.

>
1>  87% tests passed, 9 tests failed out of 70
1>
1>  Total Test time (real) = 3143.60 sec
1>
1>  The following tests FAILED:
1>  	 42 - testOptimizationExampleRuns (Timeout)
1>  	 53 - testWrapping (Timeout)
1>  	 62 - testCMCArm26 (Timeout)
1>  	 63 - testCMCEMGDrivenArm (Timeout)
1>  	 64 - testCMCGait10dof18musc (Timeout)
1>  	 65 - testCMCSingleMuscle (Timeout)
1>  	 66 - testCMCSingleRigidTendonMuscle (Timeout)
1>  	 68 - testCMCWithControlConstraintsGait2354 (Timeout)
1>  	 69 - testCMCWithControlConstraintsRunningModel (Timeout)

Once the enabled CI tests (in debug) pass I will restore those tests that do not appear in the above list and then update #393, with a change from 15 exclusions (failures) to the 9 above.

### CODE REVIEW

**Comment by aseth1** [comment]
@chrisdembia @aymanhab @klshrinidhi I was able to restore 6 tests that were being excluded, namely: testInitState, testPrescribedForce, testInducedAccelerations, testAssemblySolver, testComponents, testForward.

They still take a long time to execute, but at least they are being tested again. Let me know what you think.

**Comment by chrisdembia** [comment]
LGTM.

**Comment by aymanhab** [comment]
Looks good @aseth1 Merging.

**Comment by aseth1** [comment]
Thanks!!

**Pull request merged**
