### PR TITLE
Add TableUtilities and more CommonUtilities.

### PR DESCRIPTION
**Pull request by chrisdembia**
Part of #2559 

### Brief summary of changes

- Bring over a suite of utility functions from Moco (https://github.com/opensim-org/opensim-core/tree/moco).
- Add TableUtilities to filter, pad, resample TimeSeriesTables.
- Update VisualizerUtilities::showMotion() and StatesTrajectory to use a TimeSeriesTable.

Some of these changes are required for #2793 (e.g., `solveBisection()`).

### Testing I've completed

- Ran ctests.

### Looking for feedback on...

naming of new functions.

### CHANGELOG.md (choose one)

- updated.

@carmichaelong @aymanhab I don't think we need both of you to review, but either of you could review, so I've added both of you as reviewers.

@adamkewley , no pressure whatsoever, but feel free to pitch in on this review if you're interested. @aymanhab and @carmichaelong already have some context for this PR, so if you want more context, we can chat about it.

---
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2808)

### CODE REVIEW

**Comment by chrisdembia** [comment]
Tests finally pass :)

**Comment by adamkewley** [comment]
Nothing particularly unusual in there. Most of the stuff I spotted was more "things to think about", rather than game-changers, so I'd just take what I've written non-seriously if you need to ship this quickly.

**Comment by aymanhab** [comment]
> > _[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2808)_ status: 1 of 28 files reviewed, 1 unresolved discussion (waiting on @aymanhab and @carmichaelong)
> 
> _[CHANGELOG.md, line 18 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/2808#-MARbLTM55rffWzdGkae:-MARspVc8APQhmGT-FFX:bqbhfhd) ([raw file](https://github.com/opensim-org/opensim-core/blob/668001c30c6e700408afd3a206f23492d42ffa94/CHANGELOG.md#L18)):_
> 
> Previously, aymanhab (Ayman Habib) wrote…
> @aymanhab let me know which of the two approaches edits you prefer:
> 
> `Introduce the following utility functions in OpenSim/Common/CommonUtilities.h:`
> 
> versus
> 
> `Introduce utilities for creating SimTK::Vectors, linear interpolation, updating table column labels from v3.3 to v4.0 syntax, and solving for a function's root using bisection (OpenSim/Common/CommonUtilities.h).`

I prefer the second which gives the high level functionality as seen by users. We can link to the PR or an issue summarizing the change if some user wants to go deeper. Thanks @chrisdembia

**Comment by chrisdembia** [comment]
> I prefer the second which gives the high level functionality as seen by users. We can link to the PR or an issue summarizing the change if some user wants to go deeper. Thanks @chrisdembia

Done.

**Comment by aymanhab** [comment]
Finished a pass of review, overall looks good, left a few questions/suggestions. Thanks @chrisdembia

**Comment by chrisdembia** [comment]
Thanks @aymanhab

**Pull request merged**
