### PR TITLE
Avoid exceptions when writing STO files.

### PR DESCRIPTION
**Pull request by chrisdembia**
### Brief summary of changes

- On master, writing a STO file causes multiple exceptions to be thrown when determining the correct type of adapter to use. This is unpleasant when trying to debug code. This PR avoids throwing exceptions when simply determining which adapter to use.

### Testing I've completed

- Ran CTest locally.

### CHANGELOG.md (choose one)

- no need to update because...minor, mostly for developers.
The Doxygen for this PR can be viewed at http://myosin.sourceforge.net/?C=N;O=D; click the folder whose name is this PR's number.

---
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2397)

### CODE REVIEW

**Comment by chrisdembia** [comment]
> LGTM, I assume the new URL is more robust.

Sourceforge is not too robust in general but at least it works more often than `stack.nl`.

**Comment by chrisdembia** [comment]
It'd be great for this to get merged. This is part of the `for_muscollo` branch.

**Comment by jenhicks** [comment]
@aymanhab Will review again.

**Comment by chrisdembia** [comment]
@aymanhab there probably is. I would like to avoid spending more time on this issue right now, especially since it's minor and the data types we support for tables is unlikely to grow much.

**Comment by jenhicks** [comment]
OK to merge, per discussion with @aymanhab

**Comment by chrisdembia** [comment]
Thanks @aymanhab

**Pull request merged**
