### PR TITLE
Add 32-bit build to AppVeyor

### PR DESCRIPTION
**Pull request by tkuchida**
See #902 and #912. The [related Simbody PR](https://github.com/simbody/simbody/pull/481) has been merged.

### CODE REVIEW

**Comment by chrisdembia** [comment]
Ah! The Java test is probably failing because we probably install a 64-bit JDK/JRE. See here for the different java installations on appveyor: https://www.appveyor.com/docs/installed-software#java

You can see that CMake is finding the 64-bit JDK/JRE: https://ci.appveyor.com/project/opensim-org/opensim-core/build/3157/job/k26jmtwchfgy9y6b#L105

The CMake docs say you can set the CMake variable `JAVA_HOME` to tell CMake where to look for Java:
- Java: https://cmake.org/cmake/help/v3.0/module/FindJava.html
- JNI: https://cmake.org/cmake/help/v3.0/module/FindJNI.html?highlight=findjni

**Comment by tkuchida** [comment]
[testComponents failure on 64-bit build](https://ci.appveyor.com/project/opensim-org/opensim-core/build/3163/job/6nvjy0jertwtea8q#L624) is unrelated to this PR and is already being tracked (see #708).

**Comment by chrisdembia** [comment]
That failure is also intermittent; restarting the build should allow us to see a ✅ .

**Comment by tkuchida** [comment]
@chrisdembia Would you please grant me permission to restart AppVeyor builds?

**Comment by chrisdembia** [comment]
> @chrisdembia Would you please grant me permission to restart AppVeyor builds?

Done; let me know if it didn't work.

**Comment by tkuchida** [comment]
> Done; let me know if it didn't work.

Thanks! :gift:

**Comment by tkuchida** [comment]
The [related Simbody PR](https://github.com/simbody/simbody/pull/481) has been merged. Ready for review.

**Comment by chrisdembia** [comment]
I'm going to retry the appveyor/branch build, just to check.

**Comment by chrisdembia** [comment]
Actually, we cannot merge this until we resolve https://github.com/simbody/simbody#483, since simbody's binaries were not actually updated (I believe).

**Comment by tkuchida** [comment]
Merged master and [testCMCWithControlConstraintsRunningModel](https://ci.appveyor.com/project/opensim-org/opensim-core/build/3223/job/virk64xqldqqqu4q#L701) segfaulted on 64-bit Windows (32-bit passed). An issue about periodic failures of testCMCWithControlConstraintsRunningModel has already been raised (see #350).

**Comment by tkuchida** [comment]
> we cannot merge this until we resolve https://github.com/simbody/simbody/issues/483

The Simbody issue has been resolved (presumably caused by Update 2 of the 32-bit VC++ 2015 compiler).

Merged master and all tests pass. Ready for review.

**Comment by chrisdembia** [comment]
🎆

**Comment by tkuchida** [comment]
Great! :checkered_flag:

**Pull request merged**
