### PR TITLE
Finding darn external loads

### PR DESCRIPTION
**Pull request by chrisdembia**
Fixes part 1 of https://github.com/opensim-org/opensim-gui/issues/1061

### CHANGELOG.md (choose one)

- no need to update because...
- updated...

The Doxygen for this PR can be viewed at http://myosin.sourceforge.net/?C=N;O=D; click the folder whose name is this PR's number.

---
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2366)

### CODE REVIEW

**Comment by aseth1** [comment]
LGTM

**Comment by chrisdembia** [comment]
Thanks @aseth1 for the rapid review.

**Comment by chrisdembia** [comment]
FYI I'm adding a test to this PR.

**Comment by aymanhab** [comment]
@chrisdembia The challenge testing this is that it has to go into matsre branch on core before GUI can be built against it, not sure what sequence make sense but extensive local testing may help.

**Comment by aymanhab** [comment]
I think you can merge now.  Thanks @chrisdembia

**Comment by chrisdembia** [comment]
Great. Thank you.

**Pull request merged**
