### PR TITLE
XML memory leak fixes

### PR DESCRIPTION
**Pull request by fcanderson**
XML-related memory leaks were reported when deserializing Rajagopal2015.osim, an OpenSim v3.0 full-body model.  See issue #3537.

I used WinCRT to help find the memory leaks.  Since WinCRT is platform specific (i.e., runs only on Windows) and requires some changes to the source code to leak test effectively, this PR only includes the leak fixes (not the modified code that I used to identify the leaks and verify that they were fixed).

None of the observed leaks associated with deserializing Rajagopal2015.osim were due to coding errors in SimTK::Xml. SimTK::Xml looks like it is working fine, with no intrinsic leaks.  (@adamkewley and I did find a constructor in SimTK::Xml that should be revised, but it is not the source of any leaks that I can identity).

The reported memory leaks were occurring in OpenSim in various ```updateFromXMLNode()``` calls. In particular, ```updateFromXMLNode()```  for ```OpenSim::Body```, ```OpenSim::Coordinate```, ```OpenSim::ContactGeometry```, ```OpenSim::Muscle```, ```OpenSim::PhysicalFrame```, and ```OpenSim::WrapObject```.

The leaks were related to converting from an older version of OpenSim (i.e., from v3.0) to the current version.  Thus, the memory leaks can be sidestepped by converting old models to the current version (by deserializing them and then saving to a new .osim model file).  This sort of sidestepping doesn't address a situation in which an old version model is repeatedly deserialized, however.

Fortunately, all of the leaks had something in common and so were not tooooo difficult to find. In each case, a new element was created and not freed, or an element was removed from the XML document, was not inserted elsewhere in the model hierarchy, and was not freed. In all these cases, the fix was simply to call ```clearOrphan()``` on the element in question.

Rajogopal2015.osim, whether v3.0 or the current version, is now deserializing without memory leaks.

Fixes issue #3537

@adamkewley tested for memory leaks when deserializing a number of other OpenSim models (i.e., models other than Rajagopal2015.osim) and found more leaks! He then added ```clearOrphan()``` calls to fix those leaks as well! Those fixes are included in this PR. See "(added)" line numbers in the section, **"Brief summary of fixes"**, below.

So, it looks like most, if not all, memory leaks associated with deserializing any OpenSim model have been fixed.

### Brief summary of fixes
In the files listed below, I inserted calls to ```clearOrphan()```. To make these calls easier to find, amidst all the trailing whitespaces that were removed, I included the line numbers of the insertions.

1. SimbodyEngine/Body.cpp : line 397
2. SimbodyEngine/Coordinate.cpp : line 705
3. Model/ContactGeometry.cpp : line 192 (added) 
4. Model/Muscle.cpp : lines 110, 121
5. Model/PhysicalFrame.cpp : line 190
6. Wrap/WrapObject.cpp : lines 218, 238, 260, 269 (added), 276 (added)

### Testing completed
- In Simbody, I mimicked the operations that are commonly performed in OpenSim during deserialization and verified that no leaks within SimTK::Xml occur. In every case I've encountered, the leaks occur because an orphaned node is not cleared, which is the responsibility of the caller.
- For a few simple models (those that I am using to test my exponential contact model), I verified that no leaks occur during deserialization.
- For the new ```StatesDocument``` class I'm developing, I verified that no leaks occur when states trajectories are de/serialized.  Class ```StatesDocument``` uses SimTK::Xml as the basis for serialization.
- For Rajagopal2015.osim (v3.0), I verified that deserialization created leaks before the above fixes and that no leaks were created after the fixes.
- For Rajagopal2015.osim, I verified that serialization of the model to a new file produced identical output before and after the above fixes.  That is, the fixes appear not to be altering execution; they're just freeing abandoned memory blocks.
- @adamkewley tested more extensively for memory leaks using libASAN on many OpenSim models. He confirms that all leaks when deserializing Rajagopal2015.osim were eliminated and, after the addition of 3 more ```clearOrphan()``` calls (noted above in the summary of fixes as "added"), all memory leaks for the other models were eliminated as well.

### CHANGELOG.md (choose one)
- updated

- - -
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3594)

### CODE REVIEW

**Comment by nickbianco** [comment]
@fcanderson, based on the failures, it looks like your fork branch is still out of date with `main` (i.e., missing some of the changes from the `FunctionBasedPath` PR). You might need to sync the `main` branch on your fork with `opensim-org:main` and then merge it into this branch.

**Comment by fcanderson** [comment]
Thanks for the input @nickbianco.  I have synced several times (both my main and this branch).  I think the problem is that on one of the past syncs, some out-of-date code got merged into one of the files that I committed (Muscle.cpp).  So, the problem source has not been corrected on subsequent syncs. That is, the problem source is being treated as one of my intended changes.  Testing that assumption now.

**Comment by nickbianco** [comment]
@fcanderson, gotcha. Let me know if you have trouble resolving the code changes!

**Comment by aymanhab** [comment]
@fcanderson Thanks again for doing this, if you had too many unnecessary local changes, it may make sense to rebase to the latest main to have git merge explicitly ask you and decide about each change separately, just a thought in case it's getting too messy.

**Comment by fcanderson** [comment]
ok. That took unnecessarily long, but looks like the build issues are resolved. Thanks for the support, @nickbianco  and @aymanhab .

**Comment by adamkewley** [comment]
Great work @fcanderson !

I'll separately confirm the reported leaks are gone, but don't let that block this.

(nit: please do white-space changes in separate PRs in the future. It makes reviewing and archival change investigation much easier)

**Review by aymanhab — APPROVED** [review]
LGTM :+1:  Thanks @fcanderson the code changes look good, We can wait for @adamkewley who has tools to assess presence/size of memory leaks on various platforms to confirm the leak fix. 
I also assume there're no other instances of 'removeNode' lurking around without a matching clearOrphan. 
Excellent job!

> Reviewed 2 of 6 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3594#-:-NiAfyNG98fakeiTy2q5:b-x05y9p)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @fcanderson)

**Comment by fcanderson** [comment]
@adamkewley, will do on handling whitespace changes in separate PRs.

**Comment by adamkewley** [comment]
I can confirm that the memory leaks for Rajagopal2015.osim are gone. Horray 🎈 ! My left-testicle shall be sent courier.

---

Related to this (it's probably the same leak, but in different source locations), I also ran a quick bash script for testing all `opensim-model`s with your branch (the code for building libASAN etc is [here](https://github.com/opensim-org/opensim-core/issues/3537)):

```bash
# i.e. pump all osim files through a libASAN-enabled binary
IFS=$'\n'; for f in $(find opensim-models -name "*.osim"); do echo "${f}" && ./osim-libasan-build/testWrapping "${f}" | grep -v "^\["; done
```

The following files produced leaks:

```text
opensim-models/Models/WalkerModel/WalkerModelTerrain.osim

=================================================================
==7271==ERROR: LeakSanitizer: detected memory leaks

Indirect leak of 17280 byte(s) in 80 object(s) allocated from:
    #0 0x7f032e53c1e7 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x7f0328b91061 in SimTK::Xml::Element::Element(SimTK::String const&, SimTK::String const&) /home/adam/opensim-core/dependencies/simbody/SimTKcommon/src/Xml.cpp:696
    #2 0x7ffcf719f9cf  ([stack]+0x1d9cf)
    #3 0x7f032b1c92f6 in OpenSim::Object::updateFromXMLNode(SimTK::Xml::Element&, int) /home/adam/opensim-core/OpenSim/Common/Object.cpp:954

Indirect leak of 4480 byte(s) in 40 object(s) allocated from:
    #0 0x7f032e53c1e7 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x7f0328b93b68 in SimTK::Xml::Element::setValue(SimTK::String const&) /home/adam/opensim-core/dependencies/simbody/SimTKcommon/src/Xml.cpp:750
    #2 0x7f032c445239 in OpenSim::ContactGeometry::updateFromXMLNode(SimTK::Xml::Element&, int) /home/adam/opensim-core/OpenSim/Simulation/Model/ContactGeometry.cpp:161
    #3 0x7ffcf719f9cf  ([stack]+0x1d9cf)
    #4 0x7f032b1c92f6 in OpenSim::Object::updateFromXMLNode(SimTK::Xml::Element&, int) /home/adam/opensim-core/OpenSim/Common/Object.cpp:954
```

```text
opensim-models/Models/SoccerKick/SoccerKickingModel.osim

=================================================================
==7466==ERROR: LeakSanitizer: detected memory leaks

Indirect leak of 432 byte(s) in 2 object(s) allocated from:
    #0 0x7f7aafe961e7 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x7f7aaa4eb061 in SimTK::Xml::Element::Element(SimTK::String const&, SimTK::String const&) /home/adam/opensim-core/dependencies/simbody/SimTKcommon/src/Xml.cpp:696
    #2 0x7fffb02d11df  ([stack]+0x1e1df)
    #3 0x7f7aacb232f6 in OpenSim::Object::updateFromXMLNode(SimTK::Xml::Element&, int) /home/adam/opensim-core/OpenSim/Common/Object.cpp:954

Indirect leak of 112 byte(s) in 1 object(s) allocated from:
    #0 0x7f7aafe961e7 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x7f7aaa4edb68 in SimTK::Xml::Element::setValue(SimTK::String const&) /home/adam/opensim-core/dependencies/simbody/SimTKcommon/src/Xml.cpp:750
    #2 0x7f7aadd9f239 in OpenSim::ContactGeometry::updateFromXMLNode(SimTK::Xml::Element&, int) /home/adam/opensim-core/OpenSim/Simulation/Model/ContactGeometry.cpp:161
    #3 0x7fffb02d11df  ([stack]+0x1e1df)
    #4 0x7f7aacb232f6 in OpenSim::Object::updateFromXMLNode(SimTK::Xml::Element&, int) /home/adam/opensim-core/OpenSim/Common/Object.cpp:954
```

```text
opensim-models/Models/Jumper/DynamicJumperModel.osim

=================================================================
==7510==ERROR: LeakSanitizer: detected memory leaks

Indirect leak of 4752 byte(s) in 22 object(s) allocated from:
    #0 0x7f0d545191e7 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x7f0d4eb6e061 in SimTK::Xml::Element::Element(SimTK::String const&, SimTK::String const&) /home/adam/opensim-core/dependencies/simbody/SimTKcommon/src/Xml.cpp:696
    #2 0x7fff291724bf  ([stack]+0x1e4bf)
    #3 0x7f0d511a62f6 in OpenSim::Object::updateFromXMLNode(SimTK::Xml::Element&, int) /home/adam/opensim-core/OpenSim/Common/Object.cpp:954

Indirect leak of 1232 byte(s) in 11 object(s) allocated from:
    #0 0x7f0d545191e7 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x7f0d4eb70b68 in SimTK::Xml::Element::setValue(SimTK::String const&) /home/adam/opensim-core/dependencies/simbody/SimTKcommon/src/Xml.cpp:750
    #2 0x7f0d52422239 in OpenSim::ContactGeometry::updateFromXMLNode(SimTK::Xml::Element&, int) /home/adam/opensim-core/OpenSim/Simulation/Model/ContactGeometry.cpp:161
    #3 0x7fff291724bf  ([stack]+0x1e4bf)
    #4 0x7f0d511a62f6 in OpenSim::Object::updateFromXMLNode(SimTK::Xml::Element&, int) /home/adam/opensim-core/OpenSim/Common/Object.cpp:954
```

```text
opensim-models/Models/Arm26/arm26.osim

=================================================================
==7928==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 864 byte(s) in 4 object(s) allocated from:
    #0 0x7f7a2acba1e7 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x7f7a2530f061 in SimTK::Xml::Element::Element(SimTK::String const&, SimTK::String const&) /home/adam/opensim-core/dependencies/simbody/SimTKcommon/src/Xml.cpp:696
    #2 0x7fff29d1394f  ([stack]+0x1594f)
    #3 0x7f7a279472f6 in OpenSim::Object::updateFromXMLNode(SimTK::Xml::Element&, int) /home/adam/opensim-core/OpenSim/Common/Object.cpp:954

Indirect leak of 4320 byte(s) in 20 object(s) allocated from:
    #0 0x7f7a2acba1e7 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x7f7a2530f061 in SimTK::Xml::Element::Element(SimTK::String const&, SimTK::String const&) /home/adam/opensim-core/dependencies/simbody/SimTKcommon/src/Xml.cpp:696
    #2 0x7fff29d1394f  ([stack]+0x1594f)
    #3 0x7f7a279472f6 in OpenSim::Object::updateFromXMLNode(SimTK::Xml::Element&, int) /home/adam/opensim-core/OpenSim/Common/Object.cpp:954

Indirect leak of 448 byte(s) in 4 object(s) allocated from:
    #0 0x7f7a2acba1e7 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x7f7a25311b68 in SimTK::Xml::Element::setValue(SimTK::String const&) /home/adam/opensim-core/dependencies/simbody/SimTKcommon/src/Xml.cpp:750
    #2 0x7f7a291f2af8 in OpenSim::WrapObject::updateFromXMLNode(SimTK::Xml::Element&, int) /home/adam/opensim-core/OpenSim/Simulation/Wrap/WrapObject.cpp:204
    #3 0x7fff29d1394f  ([stack]+0x1594f)
    #4 0x7f7a279472f6 in OpenSim::Object::updateFromXMLNode(SimTK::Xml::Element&, int) /home/adam/opensim-core/OpenSim/Common/Object.cpp:954

Indirect leak of 448 byte(s) in 4 object(s) allocated from:
    #0 0x7f7a2acba1e7 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x7f7a25311b68 in SimTK::Xml::Element::setValue(SimTK::String const&) /home/adam/opensim-core/dependencies/simbody/SimTKcommon/src/Xml.cpp:750
    #2 0x7f7a291f2fc5 in OpenSim::WrapObject::updateFromXMLNode(SimTK::Xml::Element&, int) /home/adam/opensim-core/OpenSim/Simulation/Wrap/WrapObject.cpp:211
    #3 0x7fff29d1394f  ([stack]+0x1594f)
    #4 0x7f7a279472f6 in OpenSim::Object::updateFromXMLNode(SimTK::Xml::Element&, int) /home/adam/opensim-core/OpenSim/Common/Object.cpp:954

Indirect leak of 448 byte(s) in 4 object(s) allocated from:
    #0 0x7f7a2acba1e7 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x7f7a25311b68 in SimTK::Xml::Element::setValue(SimTK::String const&) /home/adam/opensim-core/dependencies/simbody/SimTKcommon/src/Xml.cpp:750
    #2 0x7f7a291f2846 in OpenSim::WrapObject::updateFromXMLNode(SimTK::Xml::Element&, int) /home/adam/opensim-core/OpenSim/Simulation/Wrap/WrapObject.cpp:200
    #3 0x7fff29d1394f  ([stack]+0x1594f)
    #4 0x7f7a279472f6 in OpenSim::Object::updateFromXMLNode(SimTK::Xml::Element&, int) /home/adam/opensim-core/OpenSim/Common/Object.cpp:954

Indirect leak of 124 byte(s) in 4 object(s) allocated from:
    #0 0x7f7a2acba1e7 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x7f7a2484ffee in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (/lib/x86_64-linux-gnu/libstdc++.so.6+0x14bfee)
```

```text

```

**Comment by adamkewley** [comment]
@fcanderson I investigated the above leaks, keeping your observation about `clearOrphan` in mind, and I managed to plug all remaining leaks with the following diff, if you'd like to push it to this PR (it's effectively your work @fcanderson - I'm just expanding it to 2 more places):

```diff
git diff origin/xml_memory_leak_fixes..HEAD
diff --git a/OpenSim/Simulation/Model/ContactGeometry.cpp b/OpenSim/Simulation/Model/ContactGeometry.cpp
index 001889a86..a364d0d00 100644
--- a/OpenSim/Simulation/Model/ContactGeometry.cpp
+++ b/OpenSim/Simulation/Model/ContactGeometry.cpp
@@ -189,6 +189,8 @@ void ContactGeometry::updateFromXMLNode(SimTK::Xml::Element& node,
             }
             if (addAppearanceNode)
                 node.insertNodeAfter(node.element_end(), appearanceNode);
+           else if (appearanceNode.isOrphan())
+                appearanceNode.clearOrphan();
         }
     }
     Super::updateFromXMLNode(node, versionNumber);
diff --git a/OpenSim/Simulation/Wrap/WrapObject.cpp b/OpenSim/Simulation/Wrap/WrapObject.cpp
index 4b206226c..58af02350 100644
--- a/OpenSim/Simulation/Wrap/WrapObject.cpp
+++ b/OpenSim/Simulation/Wrap/WrapObject.cpp
@@ -266,11 +266,15 @@ void WrapObject::updateFromXMLNode(SimTK::Xml::Element& node,
                 appearanceNode.insertNodeAfter(appearanceNode.element_end(),
                         visibleNode);
                 appearanceModified = true;
+            } else if (visibleNode.isOrphan()) {
+                visibleNode.clearOrphan();
             }

             // Add Appearance to the WrapObject.
             if (appearanceModified) {
                 node.insertNodeAfter(node.element_end(), appearanceNode);
+            } else if (appearanceNode.isOrphan()) {
+                appearanceNode.clearOrphan();
             }
         }
     }
@@ -287,4 +291,4 @@ SimTK::Transform WrapObject::calcWrapGeometryTransformInBaseFrame() const
     const auto& X_FP = getTransform();
     const auto X_BP = X_BF * X_FP;
     return X_BP;
-}
\ No newline at end of file
+}
```

**Comment by fcanderson** [comment]
@adamkewley Nice finds! I will include the three ```clearOphan()``` calls that you added in this PR. So satisfying to have all deserialization leaks plugged. I have notifications set to alert me when your left testicle arrives.  lol

**Comment by aymanhab** [comment]
I believe the ci build failures are unrelated, so ready to merge when the build finishes and with @adamkewley blessings. Thanks again @fcanderson

**Comment by fcanderson** [comment]
Thanks for the review @aymanhab and @adamkewley, who found and fixed 3 more deserialization leaks!

**Comment by adamkewley** [comment]
Shall we? :>

**Comment by fcanderson** [comment]
I should update the CHANGELOG.md to make the fix more general.  Doing that now.

**Comment by fcanderson** [comment]
Ok. CHANGELOG.md updated. Ready for the merge, I think.

**Comment by aymanhab** [comment]
Since last build succeeded no need to hold any more. Merging 🥇 🍾

**Pull request merged**
