### PR TITLE
Add moment arm test for a joint comprised of a plurality of bodies

### PR DESCRIPTION
**Pull request by tkuchida**
Addresses #578. Uses the same CompoundJoint as [testJoints.cpp](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Simulation/SimbodyEngine/Test/testJoints.cpp#L154). I can move the class to a common location if a suitable one exists. The only candidate I'm aware of is [auxiliaryTestFunctions.h](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Auxiliary/auxiliaryTestFunctions.h), but it doesn't seem desirable to add `#include` overhead there for Joint.

### CODE REVIEW

**Comment by tkuchida** [comment]
> I think it would be nice to avoid the duplicate header file.

Which .h file is duplicated?

**Comment by tkuchida** [comment]
> I think it would be nice to avoid the duplicate header file.

There aren't any duplicate .h files introduced in this PR and I'm not suggesting to create any. I agree: duplicate .h files would be bad. I'll follow the example of ComponentsForTesting.h and move CompoundJoint to a common location.

**Comment by chrisdembia** [comment]
Oops; I meant duplicate class.

**Comment by tkuchida** [comment]
> I think it would be nice to avoid the duplicate header file.

Moved definition of CompoundJoint class to a separate file.

**Comment by tkuchida** [comment]
[Timeout on Travis in Debug mode](https://travis-ci.org/opensim-org/opensim-core/builds/205986818).

**Pull request merged**
