### PR TITLE
Popup warning message when MotionType between <=3.3 to 4.0 is inconsistent

### PR DESCRIPTION
**Pull request by aseth1**
Final part of fixes to issue #2240 

### Brief summary of changes
Wired the message generated in #2243 to the validation log used by https://github.com/opensim-org/opensim-gui/pull/953. Added method to append to the log. 

### Testing I've completed
Loaded leg6dof9musc with a build of https://github.com/opensim-org/opensim-gui/pull/953 to produce the following error message:
image

### Looking for feedback on...
Is the message comprehensible?

### CHANGELOG.md (choose one)
- MotionType handling was added to the CHANGELOG in #2240

The Doxygen for this PR can be viewed at http://myosin.sourceforge.net/?C=N;O=D; click the folder whose name is this PR's number.

### CODE REVIEW

**Comment by aymanhab** [comment]
@aseth1 The message is clear to me but would be quite intimidating to most users to digest in one shot (as you would expect from a dialog in an application rather than a page full of text), and if they hit ok they're dead! 
I'd lean to shorten the message with a stern warning about what could be wrong suggest rerunning the tools and to add a link to a  "living" confluence page that describes what users need to do, and why and what tools to use to fix the problem if they have old result files.

**Comment by jenhicks** [comment]
I suggest you replace text starting with "Consequently ..." with something like the following

**You must update any motion files you generated in version 3.3 or earlier**. You can:

1) Run the utility .... (in the scripting shell) OR
2) Re-run the inverse kinematics tool with your model in 4.0

In versions 3.3 and earlier, we allowed some Coupled coordinates to be incorrectly labeled as "Rotational" degrees of freedom .... [Then add in the explanatory/background text]

**Comment by aseth1** [comment]
@chrisdembia the message was updated based on feedback above. Please test with https://github.com/opensim-org/opensim-gui/pull/953 to see if the message is readable. Thanks!

**Comment by chrisdembia** [comment]
Here's the latest message:

image

**Comment by chrisdembia** [comment]
The name of the method is incorrect; the correct name is `updatePre40KinematicsFilesFor40MotionType()`.


Here is my suggested revision:

            "You must update any motion files you generated in version 3.3 or earlier. You can:\n"
            "  (1) Run the updatePre40KinematicsFilesFor40MotionType() utility (in the scripting shell) OR\n"
            "  (2) Re-run the inverse kinematics tool with the updated model in 4.0\n"
            "In versions prior to 4.0, we allowed some Coupled coordinates to be incorrectly\n"
            "labeled as Rotational. This\n"
            "will lead to incorrect motion when playing back a pre-4.0 motion file (.mot or .sto in\n"
            "degrees) and produces inverse-dynamics and static-optimization results."

**Comment by aseth1** [comment]
@chrisdembia please go ahead and update. Thanks!

**Comment by chrisdembia** [comment]
@aseth1 I've updated the message (and made some additional tweaks beyond my comment above).

**Comment by aymanhab** [comment]
I like the details but don't think "motionType" should appear at the top of user-facing messages. I'd use something like "was labeled as Rotational but was found to be Coupled based on joint definition" this would avoid the impression that the decision was arbitrary on our side.

**Comment by chrisdembia** [comment]
@aymanhab I incorporated your feedback. Is it possible to have the GUI wrap the text for us so we don't need to put in so many newlines explicitly?

**Comment by aymanhab** [comment]
@chrisdembia This off-the-shelf warning message does not have much formatting support.  The html formatted message with scrollbar had more since it's html but wasn't appealing to the team.

**Comment by chrisdembia** [comment]
Okay well then this PR LGTM.

**Comment by aymanhab** [comment]
LGTM as well @chrisdembia 
For this to show up in the gui though we need to merge https://github.com/opensim-org/opensim-gui/pull/953

**Pull request merged**
