### PR TITLE
Fix format of ConsoleReporter numbers to scientific

### PR DESCRIPTION
**Pull request by klshrinidhi**
Fixes issue #1556.

### Brief summary of changes
As per discussion with @chrisdembia, set display format of numbers to scientific.

### Testing I've completed
Tested locally.
Output for testREADME.cpp without changes mentioned in #1556.
```
[reporter]
              |   /model_/bice|               | 
          time| ps|fiber_force|    elbow_angle| 
--------------| --------------| --------------| 
  0.000000e+00| 1.18096897e+00| 1.57079633e+00| 
1.00000000e+00| 5.72750904e+01| 7.70664118e-01| 
2.00000000e+00| 1.97284113e+01| 1.56804557e+00| 
3.00000000e+00| 5.60904315e+01| 1.44198608e+00| 
4.00000000e+00| 3.45483498e+01| 1.50834805e+00| 
5.00000000e+00| 3.26037208e+01| 1.51802366e+00| 
6.00000000e+00| 3.71360518e+01| 1.50212351e+00| 
7.00000000e+00| 3.56985024e+01| 1.50718884e+00| 
8.00000000e+00| 3.41860103e+01| 1.50791862e+00| 
9.00000000e+00| 3.43416494e+01| 1.50672695e+00| 
1.00000000e+01| 3.57847134e+01| 1.50716396e+00| 
```
Output for testREADME.cpp with changes mentioned in #1556 to reproduce the problem.
```
[reporter]
              |   /model_/bice|               | 
          time| ps|fiber_force|    elbow_angle| 
--------------| --------------| --------------| 
  0.000000e+00| 1.18096897e+00| 1.57079633e+00| 
1.23456000e-06| 1.18096946e+00| 1.57079633e+00| 
2.46912000e-06| 1.18097095e+00| 1.57079633e+00| 
3.70368000e-06| 1.18097337e+00| 1.57079633e+00| 
4.93824000e-06| 1.18097679e+00| 1.57079633e+00| 
6.17280000e-06| 1.18098119e+00| 1.57079633e+00| 
7.40736000e-06| 1.18098656e+00| 1.57079633e+00| 
8.64192000e-06| 1.18099290e+00| 1.57079633e+00| 
9.87648000e-06| 1.18100021e+00| 1.57079633e+00| 
1.11110400e-05| 1.18100849e+00| 1.57079633e+00| 
1.23456000e-05| 1.18101774e+00| 1.57079633e+00| 
1.35801600e-05| 1.18102796e+00| 1.57079633e+00| 
1.48147200e-05| 1.18103914e+00| 1.57079633e+00| 
1.60492800e-05| 1.18105128e+00| 1.57079633e+00| 
1.72838400e-05| 1.18106439e+00| 1.57079633e+00| 
1.85184000e-05| 1.18107845e+00| 1.57079633e+00| 
1.97529600e-05| 1.18109348e+00| 1.57079632e+00| 
2.09875200e-05| 1.18110946e+00| 1.57079632e+00| 
2.22220800e-05| 1.18112640e+00| 1.57079632e+00| 
2.34566400e-05| 1.18114430e+00| 1.57079632e+00| 
2.46912000e-05| 1.18116315e+00| 1.57079632e+00| 
2.59257600e-05| 1.18118295e+00| 1.57079632e+00| 
2.71603200e-05| 1.18120370e+00| 1.57079632e+00| 
2.83948800e-05| 1.18122540e+00| 1.57079632e+00| 
2.96294400e-05| 1.18124806e+00| 1.57079632e+00| 
3.08640000e-05| 1.18127165e+00| 1.57079632e+00| 
3.20985600e-05| 1.18129620e+00| 1.57079632e+00| 
3.33331200e-05| 1.18132169e+00| 1.57079632e+00| 
3.45676800e-05| 1.18134812e+00| 1.57079632e+00| 
3.58022400e-05| 1.18137549e+00| 1.57079632e+00| 
3.70368000e-05| 1.18140381e+00| 1.57079632e+00| 
3.82713600e-05| 1.18143306e+00| 1.57079632e+00| 
3.95059200e-05| 1.18146325e+00| 1.57079632e+00| 
4.07404800e-05| 1.18149438e+00| 1.57079632e+00| 
4.19750400e-05| 1.18152644e+00| 1.57079632e+00| 
4.32096000e-05| 1.18155943e+00| 1.57079632e+00| 
4.44441600e-05| 1.18159336e+00| 1.57079632e+00| 
4.56787200e-05| 1.18162822e+00| 1.57079632e+00| 
4.69132800e-05| 1.18166400e+00| 1.57079632e+00| 
4.81478400e-05| 1.18170072e+00| 1.57079632e+00| 
[reporter]
              |   /model_/bice|               | 
          time| ps|fiber_force|    elbow_angle| 
--------------| --------------| --------------| 
4.93824000e-05| 1.18173836e+00| 1.57079632e+00| 
5.06169600e-05| 1.18177693e+00| 1.57079631e+00| 
5.18515200e-05| 1.18181642e+00| 1.57079631e+00| 
5.30860800e-05| 1.18185683e+00| 1.57079631e+00| 
5.43206400e-05| 1.18189817e+00| 1.57079631e+00| 
5.55552000e-05| 1.18194042e+00| 1.57079631e+00| 
5.67897600e-05| 1.18198360e+00| 1.57079631e+00| 
5.80243200e-05| 1.18202769e+00| 1.57079631e+00| 
5.92588800e-05| 1.18207270e+00| 1.57079631e+00| 
6.04934400e-05| 1.18211862e+00| 1.57079631e+00| 
6.17280000e-05| 1.18216545e+00| 1.57079631e+00| 
6.29625600e-05| 1.18221320e+00| 1.57079631e+00| 
6.41971200e-05| 1.18226186e+00| 1.57079631e+00| 
6.54316800e-05| 1.18231142e+00| 1.57079631e+00| 
6.66662400e-05| 1.18236190e+00| 1.57079631e+00| 
6.79008000e-05| 1.18241328e+00| 1.57079630e+00| 
6.91353600e-05| 1.18246556e+00| 1.57079630e+00| 
7.03699200e-05| 1.18251875e+00| 1.57079630e+00| 
7.16044800e-05| 1.18257285e+00| 1.57079630e+00| 
7.28390400e-05| 1.18262784e+00| 1.57079630e+00| 
7.40736000e-05| 1.18268373e+00| 1.57079630e+00| 
7.53081600e-05| 1.18274052e+00| 1.57079630e+00| 
7.65427200e-05| 1.18279821e+00| 1.57079630e+00| 
7.77772800e-05| 1.18285680e+00| 1.57079630e+00| 
7.90118400e-05| 1.18291628e+00| 1.57079630e+00| 
8.02464000e-05| 1.18297665e+00| 1.57079630e+00| 
8.14809600e-05| 1.18303791e+00| 1.57079630e+00| 
8.27155200e-05| 1.18310007e+00| 1.57079629e+00| 
...more...
```

### CODE REVIEW

**Comment by klshrinidhi** [comment]
Updated the output in the file Readme.md

**Comment by chrisdembia** [comment]
Thanks for doing this. Why were so many more lines output in the second case? Did the reporting interval change?

**Comment by tkuchida** [comment]
:+1: Looks good!

**Comment by chrisdembia** [comment]
Thank you.

**Pull request merged**
