### PR TITLE
Copy python example scripts into installation

### PR DESCRIPTION
**Pull request by chrisdembia**
This PR edits CMake files so that the python example files are copied into the installation. Example scripts are placed into the `share/doc/OpenSim/Scripts/Python` directory on UNIX, and into the `sdk/Scripts/Python` directory on Windows. Thus, this PR partially addresses a concern raised in #1113.

This PR also deletes a duplicate file that entered the repository through #1183.

I was going to also include running the python examples as part of our tests, but that ended up being more complicated than I thought and so I would like to punt on that for now.

### CODE REVIEW

**Comment by tkuchida** [comment]
[AppVeyor failure](https://ci.appveyor.com/project/opensim-org/opensim-core/build/4304/job/vr7ac6gbwtj80gii#L1380) is due to unsigned int wrap through zero; reported in #1196.

**Comment by tkuchida** [comment]
:+1: LGTM

**Comment by chrisdembia** [comment]
Would anyone else like to review this?

**Comment by jimmyDunne** [comment]
I will

**Comment by aymanhab** [comment]
@chrisdembia not sure if there's an issue dedicated to installation layout but if we're going to make an Alpha build for API only then we should have a planned layout for all platforms, including models, scripts, sdk (headers and libraries) etc.

**Comment by chrisdembia** [comment]
Yeah; I agree that we need to decide on an installation layout for all platforms. I'm happy to change where the python examples go in future PRs.

**Comment by aymanhab** [comment]
Related issue #979

**Comment by chrisdembia** [comment]
Ah thanks for the link.

**Comment by chrisdembia** [comment]
I have fixed merge conflicts. This PR is ready for review.

**Comment by chrisdembia** [comment]
Thank you!

**Pull request merged**
