### PR TITLE
[travis] Disable testWrapping in debug

### PR DESCRIPTION
**Pull request by chrisdembia**
It has been timing out.

### CODE REVIEW

**Comment by aseth1** [comment]
It still baffles me why we are getting `The job exceeded the maxmimum time limit for jobs, and has been terminated` [here](https://travis-ci.org/opensim-org/opensim-core/jobs/127594741), even though it did not exceed 50min.

**Comment by chrisdembia** [comment]
Yeah I don't get it either. The other weird thing is that *other* travis builds regularly go over 1 hour. 😖

**Comment by tkuchida** [comment]
I'm less interested in why Travis bails after 48min49s rather than 50min, and more interested in why testWrapping takes 17min—are we getting 17min worth of information from the test? Also, note [from this page](https://docs.travis-ci.com/user/common-build-problems/#My-builds-are-timing-out) that a timeout can also occur if no log output is produced for 10min. :watch:

**Comment by chrisdembia** [comment]
I wonder if it's a recent regression.

**Comment by tkuchida** [comment]
Hm… testWrapping only takes a long time (17.5min) on clang in Debug mode; in all other AppVeyor and Travis environments, it takes no more than 4min. :hourglass:

**Comment by chrisdembia** [comment]
Would someone like to merge this?

**Pull request merged**
