### PR TITLE
Add Matlab Script to Sandbox

### PR DESCRIPTION
**Pull request by jimmyDunne**
Matlab Script to showcase Column labels

### CODE REVIEW

**Comment by chrisdembia** [comment]
Nice. This looks pretty good to me, but I suppose it is @tkuchida's decision as to whether he should merge it into his existing branch/PR (note that the destination branch is `tkuchida-fixTableReporterColumnLabels`).

As it is mostly written as a test, this file should eventually be moved to the separate MATLAB tests directory (Bindings/Java/Matlab/tests). @jimmyDunne I don't expect you to do this; it can be done later on.

**Comment by jimmyDunne** [comment]
Sounds good. I can also do a seperate PR into master if @tkuchida prefers. I don't want to hold his PR up, I just wanted to get this script up and somehow connect it to his PR. 

If there is a better mechanisim to do this please let me know.

**Comment by chrisdembia** [comment]
> If there is a better mechanism to do this, please let me know.

Personally, I think this is the right mechanism.



> I don't want to hold his PR up

Since this adds only to the sandbox, it should not hold his PR up.

**Comment by tkuchida** [comment]
@jimmyDunne: Does #1279 satisfy your desiderata? If so, we can merge into the PR branch without further review since the script resides in the sandbox.

**Comment by tkuchida** [comment]
Nevermind: please do *not* merge this PR into the other branch as the design requirements have changed.

**Pull request closed without merging**
