### PR TITLE
Convert Thelen2003Muscle properties into private subcomponents

### LINKED ISSUE #687: Bugs in properties with Thelen2003Muscle (optimal_fiber_length and activation_time_constant)
Two critical bugs:

1. The `optimal_fiber_length` property exists in both Muscle and in MuscleFixedWidthPennationModel, so the Thelen2003Muscle has this property twice. Somehow, an old model gets the correct value in both places (when the model is updated).
2. The `activation_time_constant` and `deactivation_time_constant` properties were moved from Thelen2003Muscle to MuscleFirstOrderActivationDynamicModel *but are not copied over when updating the model file*. Thus, the updated model just has the default time constants.

Before:

```xml
				<Thelen2003Muscle name="hamstrings_r">
					<!--Flag indicating whether the force is disabled or not. Disabled means that the force is not active in subsequent dynamics realizations.-->
					<isDisabled>false</isDisabled>
					<!--Minimum allowed value for control signal. Used primarily when solving for control values.-->
					<min_control>0</min_control>
					<!--Maximum allowed value for control signal. Used primarily when solving for control values.-->
					<max_control>1</max_control>
					<!--The set of points defining the path of the muscle.-->
					<GeometryPath>
						<!--The set of points defining the path-->
						<PathPointSet>
							<objects>
								<PathPoint name="bifemlh_r-P1">
									<location> -0.129056 -0.105091 0.0711468</location>
									<body>pelvis</body>
								</PathPoint>
								<PathPoint name="bifemlh_r-P2">
									<location> -0.0297545 -0.0355868 0.0290922</location>
									<body>tibia_r</body>
								</PathPoint>
								<PathPoint name="bifemlh_r-P3">
									<location> -0.0231314 -0.0556538 0.0339063</location>
									<body>tibia_r</body>
								</PathPoint>
							</objects>
							<groups />
						</PathPointSet>
						<!--The wrap objecs that are associated with this path-->
						<PathWrapSet>
							<objects />
							<groups />
						</PathWrapSet>
						<!--Used to display the path in the 3D window-->
						<VisibleObject name="display">
							<!--Set of geometry files and associated attributes, allow .vtp, .stl, .obj-->
							<GeometrySet>
								<objects />
								<groups />
							</GeometrySet>
							<!--Three scale factors for display purposes: scaleX scaleY scaleZ-->
							<scale_factors> 1 1 1</scale_factors>
							<!--transform relative to owner specified as 3 rotations (rad) followed by 3 translations rX rY rZ tx ty tz-->
							<transform> -0 0 -0 0 0 0</transform>
							<!--Whether to show a coordinate frame-->
							<show_axes>false</show_axes>
							<!--Display Pref. 0:Hide 1:Wire 3:Flat 4:Shaded Can be overriden for individual geometries-->
							<display_preference>4</display_preference>
						</VisibleObject>
					</GeometryPath>
					<!--The maximum force this actuator can produce.-->
					<optimal_force>1</optimal_force>
					<!--Maximum isometric force that the fibers can generate-->
					<max_isometric_force>2700</max_isometric_force>
					<!--Optimal length of the muscle fibers-->
					<optimal_fiber_length>0.123631055838816</optimal_fiber_length>
					<!--Resting length of the tendon-->
					<tendon_slack_length>0.369758937646367</tendon_slack_length>
					<!--Angle between tendon and fibers at optimal fiber length expressed in radians-->
					<pennation_angle_at_optimal>0</pennation_angle_at_optimal>
					<!--Maximum contraction velocity of the fibers, in optimal fiberlengths/second-->
					<max_contraction_velocity>10</max_contraction_velocity>
					<!--time constant for ramping up muscle activation-->
					<activation_time_constant>0.01</activation_time_constant>
					<!--time constant for ramping down of muscle activation-->
					<deactivation_time_constant>0.04</deactivation_time_constant>
					<!--tendon strain at maximum isometric muscle force-->
					<FmaxTendonStrain>0.033</FmaxTendonStrain>
					<!--passive muscle strain at maximum isometric muscle force-->
					<FmaxMuscleStrain>0.6</FmaxMuscleStrain>
					<!--shape factor for Gaussian active muscle force-length relationship-->
					<KshapeActive>0.5</KshapeActive>
					<!--exponential shape factor for passive force-length relationship-->
					<KshapePassive>4</KshapePassive>
					<!--force-velocity shape factor-->
					<Af>0.3</Af>
					<!--maximum normalized lengthening force-->
					<Flen>1.8</Flen>
				</Thelen2003Muscle>
```

After updating:
```xml
				<Thelen2003Muscle name="hamstrings_r">
					<!--Flag indicating whether the force is disabled or not. Disabled means that the force is not active in subsequent dynamics realizations.-->
					<isDisabled>false</isDisabled>
					<!--Minimum allowed value for control signal. Used primarily when solving for control values.-->
					<min_control>0</min_control>
					<!--Maximum allowed value for control signal. Used primarily when solving for control values.-->
					<max_control>1</max_control>
					<!--The set of points defining the path of the muscle.-->
					<GeometryPath>
						<!--The set of points defining the path-->
						<PathPointSet>
							<objects>
								<PathPoint name="bifemlh_r-P1">
									<location> -0.129056 -0.105091 0.0711468</location>
									<body>pelvis</body>
								</PathPoint>
								<PathPoint name="bifemlh_r-P2">
									<location> -0.0297545 -0.0355868 0.0290922</location>
									<body>tibia_r</body>
								</PathPoint>
								<PathPoint name="bifemlh_r-P3">
									<location> -0.0231314 -0.0556538 0.0339063</location>
									<body>tibia_r</body>
								</PathPoint>
							</objects>
							<groups />
						</PathPointSet>
						<!--The wrap objects that are associated with this path-->
						<PathWrapSet>
							<objects />
							<groups />
						</PathWrapSet>
					</GeometryPath>
					<!--The maximum force this actuator can produce.-->
					<optimal_force>1</optimal_force>
					<!--Maximum isometric force that the fibers can generate-->
					<max_isometric_force>2700</max_isometric_force>
					<!--Optimal length of the muscle fibers-->
					<optimal_fiber_length>0.123631055838816</optimal_fiber_length>
					<!--Resting length of the tendon-->
					<tendon_slack_length>0.369758937646367</tendon_slack_length>
					<!--Angle between tendon and fibers at optimal fiber length expressed in radians-->
					<pennation_angle_at_optimal>0</pennation_angle_at_optimal>
					<!--Maximum contraction velocity of the fibers, in optimal fiberlengths/second-->
					<max_contraction_velocity>10</max_contraction_velocity>
					<!--The model governing the excitation-to-activation dynamics.-->
					<MuscleFirstOrderActivationDynamicModel>
						<!--Activation time constant in seconds-->
						<activation_time_constant>0.015</activation_time_constant>
						<!--Deactivation time constant in seconds-->
						<deactivation_time_constant>0.05</deactivation_time_constant>
					</MuscleFirstOrderActivationDynamicModel>
					<!--The model governing the fiber and tendon kinematics.-->
					<MuscleFixedWidthPennationModel>
						<!--Optimal length of the muscle fibers (overridden when this is a subcomponent of Muscle)-->
						<optimal_fiber_length>0.123631055838816</optimal_fiber_length>
						<!--Angle between tendon and fibers at optimal fiber length expressed in radians (overridden when this is a subcomponent of Muscle)-->
						<pennation_angle_at_optimal>0</pennation_angle_at_optimal>
						<!--Maximum pennation angle (radians)-->
						<maximum_pennation_angle>1.47062890563334</maximum_pennation_angle>
					</MuscleFixedWidthPennationModel>
					<!--tendon strain at maximum isometric muscle force-->
					<FmaxTendonStrain>0.033</FmaxTendonStrain>
					<!--passive muscle strain at maximum isometric muscle force-->
					<FmaxMuscleStrain>0.6</FmaxMuscleStrain>
					<!--shape factor for Gaussian active muscle force-length relationship-->
					<KshapeActive>0.5</KshapeActive>
					<!--exponential shape factor for passive force-length relationship-->
					<KshapePassive>4</KshapePassive>
					<!--force-velocity shape factor-->
					<Af>0.3</Af>
					<!--maximum normalized lengthening force-->
					<Flen>1.8</Flen>
				</Thelen2003Muscle>
```

### PR DESCRIPTION
**Pull request by tkuchida**
Converted `MuscleFixedWidthPennationModel` and `MuscleFirstOrderActivationDynamicModel` properties into private (non-serialized) subcomponents of `Thelen2003Muscle`. The properties of these subcomponents are overridden by `Thelen2003Muscle` in `extendFinalizeFromProperties()`. Test cases updated/augmented.

Fixes #687

### CODE REVIEW

**Comment by chrisdembia** [comment]
Nothing really changed between this and #687 (other than resolving the merge conflict), right?

**Comment by tkuchida** [comment]
> Nothing really changed between this and #687 (other than resolving the merge conflict), right?

#687 is the issue, so I assume you're asking whether there are any differences between this branch and the branch from the original PR #805. There are no differences.

**Comment by chrisdembia** [comment]
Oh oops; yes that's what I meant.

**Comment by tkuchida** [comment]
`Component::getStateVariablesNamesAddedByComponent()` is throwing a read access violation exception ("this was nullptr") when `Model::getStateVariableNames()` is called from the `Manager` constructor. Any hints? Sorry if this is related to a known issue; I don't understand the implications of all the GitHub issues.

**Comment by chrisdembia** [comment]
There's a known issue that you must call `initSystem()` in order to call `getStateVariableNames()`. Is it the same issue here? #729

**Comment by tkuchida** [comment]
> Is it the same issue here? #729

:confused: That issue was raised in December. This branch was working before #810 was merged; I thought I would just need to revise to account for item 1 in #810 ("defining subcomponents…") since "The rest of the Component API should have remained the same."

**Comment by chrisdembia** [comment]
Found the bug. I'll commit a fix to this branch in a second.

**Comment by chrisdembia** [comment]
I committed what I hope is a fix. Let me know if there are still issues.

**Comment by tkuchida** [comment]
Thanks @chrisdembia. This looks like something testComponents should have caught. Should we create an issue to add more thorough test cases?

**Comment by chrisdembia** [comment]
Maybe. There's another test failure now in testIterators.

**Comment by aseth1** [comment]
Sorry Tom it was my fault. I will add states to the Sub component in testComponentInterface and then make sure the states (or related) Outputs are valid. The same is true for adopted components (that are not held as properties) . Go ahead and open an issue if you wish but I should address it in my next PR.

**Comment by aseth1** [comment]
Also you have to change the number of components back to 77. Just because the components are internal doesn't meany they aren't included in the tree (they have to be to automatically invoke their Component extension methods). You do hide their properties from user mangling.

**Comment by tkuchida** [comment]
Merged master and reverted counts in testIterators as per Ajay's comment, above. Tests passing locally; ready for review :chicken:

**Comment by tkuchida** [comment]
Thanks for merging :poultry_leg:

**Pull request merged**
