### PR TITLE
example{1|2}DataTable projects now appear in Examples folder

### PR DESCRIPTION
**Pull request by tkuchida**
Addresses #785.

### CODE REVIEW

**Comment by klshrinidhi** [comment]
@tkuchida 
I think moving examples is a good idea and not sure why I didn't have it this way in the first place.
But I would avoid using `GLOB` to grab all the cpp files to compile. [It is not recommended by CMake](https://cmake.org/cmake/help/v3.4/command/file.html).

**Comment by tkuchida** [comment]
> But I would avoid using `GLOB` to grab all the cpp files to compile.

Fixed. I followed the other CMakeLists.txt files in the project, many of which use `GLOB`. Should an issue be created to eradicate `GLOB`?

**Comment by klshrinidhi** [comment]
Thanks for fixing.
I think an issue to track *elimination of `GLOB`* would be good.

**Comment by tkuchida** [comment]
TODO: if the determination in #787 is that `GLOB` is actually preferred, undo the change made in the second commit to this branch before merging.

**Comment by chrisdembia** [comment]
It's fine to use not use GLOB here I think; @sherm1's comment in #787 is more related to `OpenSim/Common/`, `OpenSim/Simulation/`, etc.

**Comment by tkuchida** [comment]
> It's fine to use not use GLOB here I think

In that case, this PR can be merged IMO (the AppVeyor failure is irr:elephant: -- same thing happens [on master](https://ci.appveyor.com/project/opensim-org/opensim-core/branch/master)).

**Pull request merged**
