### PR TITLE
Use ResetOnCopy<unique_ptr<ModelVisualizer>> in Model.

### PR DESCRIPTION
**Pull request by chrisdembia**
Since ModelVisualizer has a private destructor, I needed to create a custom deleter within Model, which is friended to ModelVisualizer.

### CODE REVIEW

**Comment by sherm1** [comment]
That deleter is pretty cool, but I have a few questions:
- I couldn't spot where the deleter class was made a friend of ModelVisualizer. Did I miss it or did it somehow earn friendship by being a local class of Model, which is explicitly friended?
- Wouldn't it be better just to make ModelVisualizer's destructor public?

**Comment by chrisdembia** [comment]
> Did I miss it or did it somehow earn friendship by being a local class of Model, which is explicitly friended?

This was kinda mysterious to me and I just assumed what you say.



> Wouldn't it be better just to make ModelVisualizer's destructor public?

Probably. I didn't want to spend too much time on this, and thought making the destructor public might require more extensive review. Though, I suppose the important thing is that the constructor is private; I don't know why the destructor would need to be private. I'll go this route instead.

**Comment by chrisdembia** [comment]
I got rid of the deleter. Ready for review again.

**Comment by sherm1** [comment]
Looks great. Merging.

**Comment by chrisdembia** [comment]
Thanks

**Pull request merged**
