### PR TITLE
Java and matlab tests

### PR DESCRIPTION
**Pull request by chrisdembia**
@aymanhab, here is support for Java and MATLAB tests. See Bindings/Java/tests/TestBasics.java.

### CODE REVIEW

**Comment by aymanhab** [comment]
Excellent, thanks a million @chrisdembia Will wait until tests pass (at least on one platform) and merge.

**Comment by chrisdembia** [comment]
I tried fixing the windows failures but have not succeeded yet. Right now the issue is that I'm unable to properly set PATH so that osimJavaJNI.dll can find the other OpenSim libraries.

**Comment by chrisdembia** [comment]
Well it seems like the java test works on Appveyor, even if it doesn't work on my local machine. The travis failures are unrelated.

I pushed some cleanup of the CMakeLists, but this shouldn't affect the CI builds.

**Comment by chrisdembia** [comment]
@aymanhab I'll let you take care of merging this.

**Comment by aymanhab** [comment]
Sure. No worries.

**Comment by aymanhab** [comment]
Bogus failure compiling Wrapping. Merging so we can use the testing functionality for upcoming wrapping changes.

**Comment by chrisdembia** [comment]
Thank you.

**Pull request merged**
