### PR TITLE
Backport contact opensim33

### PR DESCRIPTION
**Pull request by aymanhab**
Backport support for mesh flle formats (.stl, .vtp) from OpenSim 3.3 code base

### CODE REVIEW

**Comment by aymanhab** [comment]
Travis failure is bogus and happens in unrelated libraries sporadicly

**Comment by sherm1** [comment]
Changes look good to me, Ayman.
Especially cool that the GitHub diff viewer apparently understands `.stl` files and showed me a live sphere in the viewer! Check it out.

**Comment by aymanhab** [comment]
Yes, I saw that, really cool.

**Comment by aymanhab** [comment]
Please let me know if this's ready to merge @sherm1 or any other interested party. The meat of the change is one line that replaces the call loadObjFile() with loadFile() the rest is beefing up the test case to exercise it.

**Comment by aymanhab** [comment]
Great, thanks much @sherm1

**Pull request merged**
