### PR TITLE
Uniform Time Sampling in XsenseDataReader and ADPMDataReader

### PR DESCRIPTION
**Pull request by alexbeattie42**
Fixes issue #3976

### Brief summary of changes

Implementation of the method described in [this issue](https://github.com/opensim-org/opensim-core/issues/3976)

### Testing I've completed

Tested locally. Will add tests

### Looking for feedback on...
@aymanhab and @nickbianco 
- do you have feedback on this method for creating the uniformly spaced interval
- where is the correct place for the uniform time creation function to live. Maybe `TableUtilities`?

### CHANGELOG.md (choose one)

- updated

- - -
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3977)

### CODE REVIEW

**Comment by nickbianco** [comment]
@alexbeattie42, would the existing [CommonUtilities::createVectorLinspace](https://github.com/opensim-org/opensim-core/blob/c82ded4c62260193707fa1199d35dd70340c8060/OpenSim/Common/CommonUtilities.h#L82) be sufficient here?

**Comment by alexbeattie42** [comment]
@nickbianco Thanks for the suggestion! I updated the the code to use the `createVectorLinspace` function and it is working properly. Is there any simple way to avoid the copy from `SimTK::Vector` to `std::vector<double>`.

```cpp
    std::vector<double> times(times_vec.getContiguousScalarData(),times_vec.getContiguousScalarData() + times_vec.size());
```

I looked at modifying the `createTablesFromMatrices` method [here](https://github.com/opensim-org/opensim-core/blob/main/OpenSim/Common/IMUDataReader.cpp#L11) but there does not appear to be a constructor for the `TimeSeriesTable` that accepts a `SimTK::Vector`. This kine of thing is done [here](https://github.com/opensim-org/opensim-core/blob/main/OpenSim/Common/Test/testDataTable.cpp#L955) but I'm curious if there's a better way that you know of.

**Comment by nickbianco** [comment]
I suppose we could add another linspace function to CommonUtilities that returns a `std::vector` rather than a `SimTK::Vector`.

**Comment by alexbeattie42** [comment]
@nickbianco could you take another look?

**Review by alexbeattie42 — COMMENTED** [review]
@nickbianco Thanks! These are fixed now

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3977#-:-OENUTxZ4y7y8EPKnym_:byljv13)* status: 1 of 4 files reviewed, all discussions resolved (waiting on @nickbianco)

**Review by nickbianco — APPROVED** [review]
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3977)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alexbeattie42)

**Comment by nickbianco** [comment]
Thanks @alexbeattie42!

**Pull request merged**
