### PR TITLE
Converting use of property variables to getter method calls in DeGrooteFregly2016Muscle

### PR DESCRIPTION
**Pull request by AllisonJohn**
Fixes issue #3483

### Brief summary of changes
- Made get methods for the properties so that they can update more often
- Replaced all usages of the instance variables with get method calls, got rid of variables
- Except for m_isTendonDynamicsExplicit because it would cause errors

### Testing I've completed

- running testDeGrooteFregly2016Muscle
- [perf-win]
- using the HangingMuscleModel example, added the properties as parameters and checked that they changed after the solve

### Looking for feedback on...
Previously extendFinalizeFromProperties had several checks for the properties before changing the variables. So is it a problem if we are now changing the variables without doing these checks?

### CHANGELOG.md (choose one)
- updated.

- - -
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3836)

### CODE REVIEW

**Comment by nickbianco** [comment]
Here are the performance testing results:

|                           Test Name | lhs [secs] | stderr [secs] | rhs [secs] | stderr [secs] | Speedup |
| ----------------------------------- | ---------- | ------------- | ---------- | ------------- | ------- |
| ellipsoid_wrap_function_based_paths |       1.07 |          0.00 |       1.05 |          0.00 |    1.01 |
|                    MocoSquatToStand |       3.23 |          0.00 |       3.27 |          0.00 |    0.99 |
|                      ellipsoid_wrap |       1.33 |          0.00 |       1.34 |          0.00 |    1.00 |
|                               Arm26 |       0.15 |          0.00 |       0.15 |          0.00 |    1.00 |
| ToyDropLanding_function_based_paths |       4.85 |          0.01 |       4.85 |          0.00 |    1.00 |
|                     MocoSlidingMass |       0.75 |          0.00 |       0.76 |          0.00 |    1.00 |
|                      ToyDropLanding |       5.54 |          0.01 |       5.47 |          0.01 |    1.01 |
|                     passive_dynamic |       1.93 |          0.00 |       1.94 |          0.00 |    1.00 |
|          passive_dynamic_noanalysis |       1.33 |          0.00 |       1.33 |          0.00 |    1.00 |
|      ToyDropLanding_fbp_stepwisereg |       4.69 |          0.01 |       4.63 |          0.00 |    1.01 |
|                      RajagopalModel |       4.03 |          0.00 |       4.11 |          0.01 |    0.98 |
|            ToyDropLanding_nomuscles |       0.24 |          0.00 |       0.23 |          0.00 |    1.03 |
|                            Gait2354 |       0.19 |          0.00 |       0.19 |          0.00 |    0.99 |

**Review by nickbianco — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3836#-:-O1SQH6GAPz866W7RLwE:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @AllisonJohn)

___
*[`OpenSim/Actuators/DeGrooteFregly2016Muscle.h` line 855 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3836#-O1SQ7R49jxTeWCaRaf9:-O1SQ7R49jxTeWCaRafA:b32v57) ([raw file](https://github.com/opensim-org/opensim-core/blob/c9bcfa225ca1b64c4221beee57238cba4dcb684c/OpenSim/Actuators/DeGrooteFregly2016Muscle.h#L855)):*
> ```objc
>         return get_max_contraction_velocity() * get_optimal_fiber_length();
>     }
>     /// Tendon stiffness parameter kT from De Groote et al., 2016. Instead of
> ```

+1

**Review by nickbianco — CHANGES_REQUESTED** [review]
Just noticed this comment:

> Previously extendFinalizeFromProperties had several checks for the properties before changing the variables. So is it a problem if we are now changing the variables without doing these checks?

@AllisonJohn good point! I think this is a case where users need to be smart about setting variable bounds during parameter optimization. The checks will still apply for the initial parameter values, but users will need to know what parameter bounds are acceptable for the model. 

Could you add a section to the class documentation in the header file listing the acceptable bounds for each parameter? You should note that the bounds will not be automatically enforced during during parameter optimization, so users should make sure that the bounds given to `MocoParameter` fall within these bounds. Otherwise, it might not be possible to apply the optimized parameter values to the model.

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3836#-:-O1SS4Lv2GV626FPBrv4:b9iuncq)* status: all files reviewed, 1 unresolved discussion (waiting on @AllisonJohn)

**Review by nickbianco — COMMENTED** [review]
One more thing: the properties with `_default_` in the name only get applied to the model during model initialization, so it does not make sense to optimize these values with `MocoParameter`, as they will not be applied to the model.

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3836#-:-O1STmnh47sM5QGHV4Ik:b4ehq59)* status: all files reviewed, 1 unresolved discussion (waiting on @AllisonJohn)

**Review by nickbianco — CHANGES_REQUESTED** [review]
Nice addition to the docs! Just a few comments to make things a bit clearer and leverage Doxgyen formatting.

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3836#-:-O1TDCBb6nS1WU45OmPU:b-uq5suc)* status: all files reviewed, 7 unresolved discussions (waiting on @AllisonJohn)

___
*[`OpenSim/Actuators/DeGrooteFregly2016Muscle.h` line 83 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3836#-O1TAkx0CZkEg1OSwclr:-O1TAkx0CZkEg1OSwcls:bsw8sgh) ([raw file](https://github.com/opensim-org/opensim-core/blob/6bdfaeaac2eaa88770262d6a7c5116c5dc2cfa57/OpenSim/Actuators/DeGrooteFregly2016Muscle.h#L83)):*
> ```objc
> time-stepping.
> 
> @section property Property Optimization
> ```

I would rename this section to "Property bounds", and start with listing the property bounds. Then after that, make the note about parameter optimization.
___
*[`OpenSim/Actuators/DeGrooteFregly2016Muscle.h` line 84 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3836#-O1TBq_96Ct6KI1MpnU0:-O1TBq_96Ct6KI1MpnU1:b-mf3wnb) ([raw file](https://github.com/opensim-org/opensim-core/blob/6bdfaeaac2eaa88770262d6a7c5116c5dc2cfa57/OpenSim/Actuators/DeGrooteFregly2016Muscle.h#L84)):*
> ```objc
> 
> @section property Property Optimization
> To include properties in optimization, add them as a MocoParameter. The
> ```

Consider a slight rehprase: "Muscle properties can be optimized using MocoParameter". 
___
*[`OpenSim/Actuators/DeGrooteFregly2016Muscle.h` line 86 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3836#-O1TBVXoEOdeMhi68pAL:-O1TBVXoEOdeMhi68pAM:bpvgvc5) ([raw file](https://github.com/opensim-org/opensim-core/blob/6bdfaeaac2eaa88770262d6a7c5116c5dc2cfa57/OpenSim/Actuators/DeGrooteFregly2016Muscle.h#L86)):*
> ```objc
> To include properties in optimization, add them as a MocoParameter. The
> acceptable bounds for each property will be automatically enforced at
> initialization but NOT during parameter optimization, so the user must supply
> ```

You can emphasize a word by bolding it in Doxygen:



_Suggestion:_
```objc
initialization but **not** during parameter optimization, so the user must supply
```
___
*[`OpenSim/Actuators/DeGrooteFregly2016Muscle.h` line 87 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3836#-O1TCGdR3_9JzkJ_xmeA:-O1TCGdR3_9JzkJ_xmeB:byo5kh7) ([raw file](https://github.com/opensim-org/opensim-core/blob/6bdfaeaac2eaa88770262d6a7c5116c5dc2cfa57/OpenSim/Actuators/DeGrooteFregly2016Muscle.h#L87)):*
> ```objc
> acceptable bounds for each property will be automatically enforced at
> initialization but NOT during parameter optimization, so the user must supply
> these bounds to MocoParameter. The acceptable bounds for each property are:
> ```

Since you say bounds here, so it would be write out the upper and lower bounds for each parameter, even if they are infinite. For example, activation time constant would be `[0, inf]`. This would be clearer for users who are adding a MocoParameter to their problem using these guidelines.
___
*[`OpenSim/Actuators/DeGrooteFregly2016Muscle.h` line 89 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3836#-O1TC4lT6ZPOJAVH8Ivi:-O1TC4lUAWGXdaH7birf:ba11os7) ([raw file](https://github.com/opensim-org/opensim-core/blob/6bdfaeaac2eaa88770262d6a7c5116c5dc2cfa57/OpenSim/Actuators/DeGrooteFregly2016Muscle.h#L89)):*
> ```objc
> these bounds to MocoParameter. The acceptable bounds for each property are:
> 
> activation_time_constant > 0
> ```

Make this a bulleted list in Doxygen by using hyphens, for example:



_Suggestion:_
```objc
 - activation_time_constant > 0
```
___
*[`OpenSim/Actuators/DeGrooteFregly2016Muscle.h` line 128 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3836#-O1TCp-OAHKDYtxIgfmB:-O1TCp-OAHKDYtxIgfmC:b-5yc959) ([raw file](https://github.com/opensim-org/opensim-core/blob/6bdfaeaac2eaa88770262d6a7c5116c5dc2cfa57/OpenSim/Actuators/DeGrooteFregly2016Muscle.h#L128)):*
> ```objc
>     OpenSim_DECLARE_PROPERTY(activation_time_constant, double,
>             "Smaller value means activation can increase more rapidly. "
>             "Default: 0.015 seconds. Bounds: > 0.");
> ```

Similar to above, set the full lower and upper bounds here (and for the other properties below):



_Suggestion:_
```objc
            "Default: 0.015 seconds. Bounds: [0, inf].");
```

**Review by AllisonJohn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3836)* status: 3 of 4 files reviewed, 7 unresolved discussions (waiting on @nickbianco)

___
*[`OpenSim/Actuators/DeGrooteFregly2016Muscle.h` line 83 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3836#-O1TAkx0CZkEg1OSwclr:-O1TOpymAM2i8k-e_Uha:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/6bdfaeaac2eaa88770262d6a7c5116c5dc2cfa57/OpenSim/Actuators/DeGrooteFregly2016Muscle.h#L83)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

I would rename this section to "Property bounds", and start with listing the property bounds. Then after that, make the note about parameter optimization.
</blockquote></details>

Done.
___
*[`OpenSim/Actuators/DeGrooteFregly2016Muscle.h` line 84 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3836#-O1TBq_96Ct6KI1MpnU0:-O1TOtQdBWzBh58Fts88:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/6bdfaeaac2eaa88770262d6a7c5116c5dc2cfa57/OpenSim/Actuators/DeGrooteFregly2016Muscle.h#L84)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Consider a slight rehprase: "Muscle properties can be optimized using MocoParameter".
</blockquote></details>

Done.
___
*[`OpenSim/Actuators/DeGrooteFregly2016Muscle.h` line 86 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3836#-O1TBVXoEOdeMhi68pAL:-O1TOuGyDQ3qFw56idu4:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/6bdfaeaac2eaa88770262d6a7c5116c5dc2cfa57/OpenSim/Actuators/DeGrooteFregly2016Muscle.h#L86)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

You can emphasize a word by bolding it in Doxygen:
</blockquote></details>

Done.
___
*[`OpenSim/Actuators/DeGrooteFregly2016Muscle.h` line 87 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3836#-O1TCGdR3_9JzkJ_xmeA:-O1TOua9EHncCn1qJCwp:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/6bdfaeaac2eaa88770262d6a7c5116c5dc2cfa57/OpenSim/Actuators/DeGrooteFregly2016Muscle.h#L87)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Since you say bounds here, so it would be write out the upper and lower bounds for each parameter, even if they are infinite. For example, activation time constant would be `[0, inf]`. This would be clearer for users who are adding a MocoParameter to their problem using these guidelines.
</blockquote></details>

Done.
___
*[`OpenSim/Actuators/DeGrooteFregly2016Muscle.h` line 89 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3836#-O1TC4lT6ZPOJAVH8Ivi:-O1TOwU54Q-s-WwysXad:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/6bdfaeaac2eaa88770262d6a7c5116c5dc2cfa57/OpenSim/Actuators/DeGrooteFregly2016Muscle.h#L89)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Make this a bulleted list in Doxygen by using hyphens, for example:
</blockquote></details>

Done.
___
*[`OpenSim/Actuators/DeGrooteFregly2016Muscle.h` line 128 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3836#-O1TCp-OAHKDYtxIgfmB:-O1TOoqCBRimJZom6m9p:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/6bdfaeaac2eaa88770262d6a7c5116c5dc2cfa57/OpenSim/Actuators/DeGrooteFregly2016Muscle.h#L128)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Similar to above, set the full lower and upper bounds here (and for the other properties below):
</blockquote></details>

Done.

**Review by nickbianco — CHANGES_REQUESTED** [review]
Three more minor changes, then we should be good to go.

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3836#-:-O1TZVLRE0ZAkdA-NfsV:b-kxltqb)* status: all files reviewed, 3 unresolved discussions (waiting on @AllisonJohn)

___
*[`OpenSim/Actuators/DeGrooteFregly2016Muscle.h` line 95 at r4](https://reviewable.io/reviews/opensim-org/opensim-core/3836#-O1TZKRE3iHDRPr5cB9S:-O1TZKRE3iHDRPr5cB9T:bkjciwd) ([raw file](https://github.com/opensim-org/opensim-core/blob/ea38b664e6c175cd21ee214c33fb831698f70043/OpenSim/Actuators/DeGrooteFregly2016Muscle.h#L95)):*
> ```objc
>  - default_activation: (0, inf]
>  - default_normalized_tendon_force: [0, 5]
> @note The methods getMinNormalizedTendonForce() and
> ```

Add a space here:



_Suggestion:_
```objc
 - default_normalized_tendon_force: [0, 5]

@note The methods getMinNormalizedTendonForce() and
```
___
*[`OpenSim/Actuators/DeGrooteFregly2016Muscle.h` line 98 at r4](https://reviewable.io/reviews/opensim-org/opensim-core/3836#-O1TYw8y9inNtiesz-pu:-O1TYw8y9inNtiesz-pv:undefined) ([raw file](https://github.com/opensim-org/opensim-core/blob/ea38b664e6c175cd21ee214c33fb831698f70043/OpenSim/Actuators/DeGrooteFregly2016Muscle.h#L98)):*
> ```objc
>    getMaxNormalizedTendonForce() provide these bounds for use in custom solvers.
> 
> @note Muscle properties can be optimized as a MocoParameter. The acceptable
> ```





_Suggestion:_
```objc
@note Muscle properties can be optimized using MocoParameter. The acceptable
```
___
*[`OpenSim/Actuators/DeGrooteFregly2016Muscle.h` line 103 at r4](https://reviewable.io/reviews/opensim-org/opensim-core/3836#-O1TYgpZAad6a53jyNFb:-O1TYgpZAad6a53jyNFc:undefined) ([raw file](https://github.com/opensim-org/opensim-core/blob/ea38b664e6c175cd21ee214c33fb831698f70043/OpenSim/Actuators/DeGrooteFregly2016Muscle.h#L103)):*
> ```objc
> 
> @note Default properties cannot be optimized because they are applied during
> initialization only.
> ```





_Suggestion:_
```objc
@note The properties `default_activation` and `default_normalized_tendon_force` 
cannot be optimized because they are applied during model initialization only.
```

**Review by AllisonJohn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3836)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @nickbianco)

___
*[`OpenSim/Actuators/DeGrooteFregly2016Muscle.h` line 95 at r4](https://reviewable.io/reviews/opensim-org/opensim-core/3836#-O1TZKRE3iHDRPr5cB9S:-O1TrRYl0kVR7BohRLMK:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/ea38b664e6c175cd21ee214c33fb831698f70043/OpenSim/Actuators/DeGrooteFregly2016Muscle.h#L95)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Add a space here:
</blockquote></details>

Done.
___
*[`OpenSim/Actuators/DeGrooteFregly2016Muscle.h` line 98 at r4](https://reviewable.io/reviews/opensim-org/opensim-core/3836#-O1TYw8y9inNtiesz-pu:-O1TrRyo3onYVZQSiCDD:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/ea38b664e6c175cd21ee214c33fb831698f70043/OpenSim/Actuators/DeGrooteFregly2016Muscle.h#L98)):*
> ```objc
>    getMaxNormalizedTendonForce() provide these bounds for use in custom solvers.
> 
> @note Muscle properties can be optimized as a MocoParameter. The acceptable
> ```

Done.
___
*[`OpenSim/Actuators/DeGrooteFregly2016Muscle.h` line 103 at r4](https://reviewable.io/reviews/opensim-org/opensim-core/3836#-O1TYgpZAad6a53jyNFb:-O1TrWhO1mjsK8WSTtst:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/ea38b664e6c175cd21ee214c33fb831698f70043/OpenSim/Actuators/DeGrooteFregly2016Muscle.h#L103)):*
> ```objc
> 
> @note Default properties cannot be optimized because they are applied during
> initialization only.
> ```

Done.

**Review by nickbianco — APPROVED** [review]
:lgtm:

Great work @AllisonJohn!

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3836#-:-O1UuYt67rj8WiiSkFs8:bgg1881)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AllisonJohn)

**Pull request merged**
