### PR TITLE
Bug Fix in the Component API

### PR DESCRIPTION
**Pull request by fcanderson**
Fixes issue #3803

This PR addresses an assertion failure that was occurring in `Debug` mode and fixes bugs in `Component::setModelingOption()` and `Component::getModelingOption()`.

- In `Debug` mode, an assertion fails upon initialization of `ssIndex`, `dvIndex`, and `moIndex` (lines `4091`, `4094`, `4180`, `4183` in `Component.h`). Originally, these indexes were initialized to `-1`, much as one would initialize a pointer to `null`.  However, an assertion in `SimTK::State` fails (only in Debug mode) and interrupts execution. As an alternative solution, initializing these indexes to an unreasonably large number will avoid an assertion failure and almost certainly flag an improperly initialized index.
- The wrong `_namedModelingOptionInfo` member variable was being consulted. The owner's map should have been consulted, as opposed to the calling `Component`'s map. This bug went unidentified by `testComponentInterface.cpp` because the map `find`s were all successful.

### Brief summary of changes
- `ssIndex`, `dvIndex`, and `moIndex` are now initialized to `999999`.
- `Component::_namedModelingOptionInfo` of the owner is now being queried instead of the `Component` on which the `get` or `set` was called.
- Added a Catch2 test to `testComponentInterface.cpp` that triggers a `VariableNotFound` exception, which would have caught this bug even in Release mode.

### Testing I've completed
I re-ran `testComponentInterface` in both Release and Debug modes. All tests are passing.

### CHANGELOG.md (choose one)
- No need to update because a new feature was not added and because there is no change to the API.

- - -
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3804)

### CODE REVIEW

**Comment by fcanderson** [comment]
@nickbianco and @aymanhab. Do either of you have time to review my bug fixes and merge this PR? There are just a few tweaks to existing code and a few added lines.

Thanks,
-Clay

**Comment by aymanhab** [comment]
Thanks @fcanderson I'll try to review today.

**Review by aymanhab — CHANGES_REQUESTED** [review]
Thanks @fcanderson Love the test, left a minor comment, you're more aware of the context so your call if other options would work. Thank you

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3804#-:-O-7F3Vc4AZCxfgmthFB:b2z6sp6)* status: all files reviewed, 1 unresolved discussion (waiting on @fcanderson)

___
*[`OpenSim/Common/Component.h` line 4091 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3804#-O-7E_I5Elf5RvFQzOno:-O-7E_I5Elf5RvFQzOnp:bt5w8v8) ([raw file](https://github.com/opensim-org/opensim-core/blob/95979b97a935ce5bb1d3296ec146ca0ee547b6a7/OpenSim/Common/Component.h#L4091)):*
> ```objc
> 
>         // Index of the SimTK::Subsystem to which this modeling option belongs
>         SimTK::SubsystemIndex           ssIndex{999999};
> ```

Looks fine though my preference would be to have a clearly specified Invalid Index rather than assume arbitrary large number doubles as a flag, but if that's too big of a change and is used elsewhere I'm ok with this.

**Review by fcanderson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3804)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @aymanhab)

___
*[`OpenSim/Common/Component.h` line 4091 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3804#-O-7E_I5Elf5RvFQzOno:-O-7eTUx3m20MrTRRSv9:bkk1rk2) ([raw file](https://github.com/opensim-org/opensim-core/blob/95979b97a935ce5bb1d3296ec146ca0ee547b6a7/OpenSim/Common/Component.h#L4091)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

Looks fine though my preference would be to have a clearly specified Invalid Index rather than assume arbitrary large number doubles as a flag, but if that's too big of a change and is used elsewhere I'm ok with this.
</blockquote></details>

Thanks very much for the review, Ayman.

I wasn't satisfied with the unreasonably large integer either. I took a deep dive in Simbody and looked for a special integer that means "uninitialized" or "invalid" in the context of an index. I found one!

The special integer is `static const SimTK::InvalidIndex`.  Apparently, all instances of a defined index type in Simbody are initialized to this constant upon creation (at least in debug mode).  Here is a comment segment from `common.h` (lines 418-421) in Simbody:
```
 * If you create a type "ThingIndex" you will also get a constant of
 * type ThingIndex named "InvalidThingIndex" which will be the initial
 * value of any objects of type ThingIndex, and will have the same numerical
 * value as SimTK::InvalidIndex.
```

So, the upshot is... We do not need to initialize `ssIndex`, `dvIndex`, and `moIndex` in class `OpenSim::Component` because these indexes are initialized under the covers in Simbody when they are created.

I therefore removed the overriding initialization to `999999`.

All checks in `testComponentInterface.cpp` are passing.

**Review by aymanhab — APPROVED** [review]
Great job @fcanderson Thank you

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3804#-:-O-83f20-iMhnmf6NM5f:b-suz1c7)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @fcanderson)

**Review by aymanhab — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3804#-:-O-83lRu8gz3mHupdEk7:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @fcanderson)

**Review by fcanderson — COMMENTED** [review]
Awesome @aymanhab.
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3804#-:-O-9dqcg4lZDynHswNXr:bpph8ab)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @fcanderson)

**Comment by fcanderson** [comment]
@aymanhab @nickbianco I'm working to identify the reason for the C-I failure for the "Windows" build.
`testPrescribedForce` is the specific test that is failing.

All tests pass on my desktop for both Visual Studio 2019 and Visual Studio 2022 builds.
- My fork/branch is up-to-date with `opensim-org:main` (i.e., I have synched).
- I'm running the same version of Simbody (GIT_TAG d98f05fa1899633b544757e6c179562940f0849d).
- I'm running the latest versions of Visual Studio Community 2019 (16.11.37) and Visual Studio Community 2022 (17.10.3).
- I'm running on Windows 10. (I do not have a computer running Windows 11).

At this point I'm wondering if the difference in behavior between my desktop and C-I has to do with either the version of Visual Studio or the version of Windows.

In the past I have seen differences in the standard C++ libraries on Windows 10 vs. Windows 11. I had to program around them in Simbody.  See https://github.com/simbody/simbody/issues/780.

So, for C-I, I'm specifically wondering:

1. What version of Windows is running (10 or 11)?
2. What version of Visual Studio Community 2019 is running?

I'm assuming I need to get to the bottom of this before the bug fixes in this PR are merged? 
Merger of these bug fixes is a prerequisite for the PR I will submit for the new `StatesDocument` class.

Thanks. I know you guys are busy.

**Comment by nickbianco** [comment]
@fcanderson the `testPrescribedForce` failure is unrelated to your changes here. We've been running into this issue in other PRs and not sure what the root cause is yet.

Sorry if you went down the rabbit hole on this! You can ignore that failure if it continues to persist (although sometimes re-running the CI will get it to pass).

**Comment by fcanderson** [comment]
@nickbianco @aymanhab

Thanks for the response, Nick. I didn't go too far down the rabbit hole.

Given that the failure is unrelated to my changes, would one of you merge this PR?
Or, is a review from another person needed?

**Comment by aymanhab** [comment]
Merged, thanks @fcanderson

**Comment by fcanderson** [comment]
@aymanhab @nickbianco 
Awesome. Thanks, Ayman.

**Pull request merged**
