### PR TITLE
MocoOutputConstraint option for two outputs

### PR DESCRIPTION
**Pull request by AllisonJohn**
Fixes issue #3848

### Brief summary of changes
Similar to #3851 , add optional second output and operator to combine the two outputs for the constraint. 

### Testing I've completed
Added a test to testMocoGoals.cpp

### CHANGELOG.md (choose one)

- to be updated.

- - -
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3855)

### CODE REVIEW

**Review by nickbianco — COMMENTED** [review]
@AllisonJohn, looks great overall! Good job carrying over the style from the `MocoOutputGoal` PR. I noticed a couple of minor things, some of which could be ported back over to `MocoOutputGoal`. That could be done here or in a separate PR (or even the other PR if it's still open). Up to you.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3855#-:-O2RNVeg0z6z1FaF6uHi:b5f72bj)* status: all files reviewed, 12 unresolved discussions (waiting on @AllisonJohn)

___
*[`OpenSim/Moco/MocoOutputConstraint.h` line 59 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3855#-O2RHNJY4FSB5KBs-nth:-O2RHNJY4FSB5KBs-nti:b-n2afx8) ([raw file](https://github.com/opensim-org/opensim-core/blob/b49354372127544754760f1bd44a515ac30cf9ea/OpenSim/Moco/MocoOutputConstraint.h#L59)):*
> ```objc
>     format is "/path/to/component|output_name". This Output should have the same
>     type as the first Output. If providing a second Output, the user must also
>     provide an operation via `setOperation()`. */
> ```

Since the only thing this class can allow are path constraints, you could add the rest of the sentence as in `setOutputPath()`above:



_Suggestion:_
```objc
    /** Set the absolute path to the optional second Output in the model to be 
    used in this path constraint. The format is "/path/to/component|output_name". 
    This Output should have the same  type as the first Output. If providing a 
    second Output, the user must also provide an operation via `setOperation()`. 
    */
```
___
*[`OpenSim/Moco/MocoOutputConstraint.h` line 116 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3855#-O2RHmS-7N113F1BRhKo:-O2RHmS-7N113F1BRhKp:bx1pxy) ([raw file](https://github.com/opensim-org/opensim-core/blob/b49354372127544754760f1bd44a515ac30cf9ea/OpenSim/Moco/MocoOutputConstraint.h#L116)):*
> ```objc
>     OpenSim_DECLARE_PROPERTY(output_path, std::string,
>             "The absolute path to the Output in the model (i.e.,"
>             "'/path/to/component|output_name'");
> ```

As above, you could add back "...to be used in this path constraint..." here.
___
*[`OpenSim/Moco/MocoOutputConstraint.h` line 119 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3855#-O2RKvWQBoSPjq4qFKo1:-O2RKvWQBoSPjq4qFKo2:bx1pxy) ([raw file](https://github.com/opensim-org/opensim-core/blob/b49354372127544754760f1bd44a515ac30cf9ea/OpenSim/Moco/MocoOutputConstraint.h#L119)):*
> ```objc
>     OpenSim_DECLARE_PROPERTY(second_output_path, std::string,
>             "The absolute path to the optional second Output in the model (i.e.,"
>             "'/path/to/component|output_name'");
> ```

As above, you could add back "...to be used in this path constraint..." here.
___
*[`OpenSim/Moco/MocoOutputConstraint.h` line 135 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3855#-O2RL-0a5zGf9b6xjnUd:-O2RL-0a5zGf9b6xjnUe:b-b7aqjf) ([raw file](https://github.com/opensim-org/opensim-core/blob/b49354372127544754760f1bd44a515ac30cf9ea/OpenSim/Moco/MocoOutputConstraint.h#L135)):*
> ```objc
> 
>     /** Initialize additional information when there are two Outputs:
>      * the second Output, the operation, and the dependsOnStage. */
> ```

nit: match comment style here:



_Suggestion:_
```objc
    the second Output, the operation, and the dependsOnStage. */
```
___
*[`OpenSim/Moco/MocoOutputConstraint.h` line 143 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3855#-O2RLFfq03rnpqTDjRfr:-O2RLFfq03rnpqTDjRfs:undefined) ([raw file](https://github.com/opensim-org/opensim-core/blob/b49354372127544754760f1bd44a515ac30cf9ea/OpenSim/Moco/MocoOutputConstraint.h#L143)):*
> ```objc
>     double calcCompositeOutputValue(const SimTK::State&) const;
> 
>     /** Get a reference to the Output for this goal. */
> ```





_Suggestion:_
```objc
    /** Get a reference to the Output for this path constraint. */
```
___
*[`OpenSim/Moco/MocoOutputConstraint.h` line 148 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3855#-O2RLJB_8voOw1FoKuQr:-O2RLJB_8voOw1FoKuQs:undefined) ([raw file](https://github.com/opensim-org/opensim-core/blob/b49354372127544754760f1bd44a515ac30cf9ea/OpenSim/Moco/MocoOutputConstraint.h#L148)):*
> ```objc
>         return static_cast<const Output<T>&>(m_output.getRef());
>     }
>     /** Get a reference to the second Output for this goal. */
> ```





_Suggestion:_
```objc
    /** Get a reference to the second Output for this path constraint. */
```
___
*[`OpenSim/Moco/MocoOutputConstraint.h` line 198 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3855#-O2RMR8VAtmuQzZgS_27:-O2RMR8VAtmuQzZgS_28:b5c06bk) ([raw file](https://github.com/opensim-org/opensim-core/blob/b49354372127544754760f1bd44a515ac30cf9ea/OpenSim/Moco/MocoOutputConstraint.h#L198)):*
> ```objc
>         Type_SpatialVec,
>     };
>     /** Get the string of the data type (for error messages) */
> ```

nit: punctuation



_Suggestion:_
```objc
    /** Get the string of the data type (for error messages). */
```
___
*[`OpenSim/Moco/MocoOutputConstraint.h` line 199 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3855#-O2RMY-98PZaRmTSMNUv:-O2RMY-98PZaRmTSMNUw:be26sa2) ([raw file](https://github.com/opensim-org/opensim-core/blob/b49354372127544754760f1bd44a515ac30cf9ea/OpenSim/Moco/MocoOutputConstraint.h#L199)):*
> ```objc
>     };
>     /** Get the string of the data type (for error messages) */
>     std::string getDataTypeStr(DataType type) const {
> ```

nit: avoid abbreviations in method names, whenever possible (I missed this one in the last PR):



_Suggestion:_
```objc
    std::string getDataTypeString(DataType type) const {
```
___
*[`OpenSim/Moco/MocoOutputConstraint.cpp` line 220 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3855#-O2RLe5g5Rz28zy9b4d0:-O2RLe5g5Rz28zy9b4d1:bso3nm3) ([raw file](https://github.com/opensim-org/opensim-core/blob/b49354372127544754760f1bd44a515ac30cf9ea/OpenSim/Moco/MocoOutputConstraint.cpp#L220)):*
> ```cpp
>         if (m_minimizeVectorNorm) {
>             SimTK::Vec3 value1 = getOutput<SimTK::Vec3>().getValue(state);
>             SimTK::Vec3 value2 = getSecondOutput<SimTK::Vec3>().getValue(state);
> ```

Use `const T&`:



_Suggestion:_
```cpp
            const SimTK::Vec3& value1 = getOutput<SimTK::Vec3>().getValue(state);
            const SimTK::Vec3& value2 = getSecondOutput<SimTK::Vec3>().getValue(state);
```
___
*[`OpenSim/Moco/MocoOutputConstraint.cpp` line 230 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3855#-O2RLvYU1XKEzDjYi4_I:-O2RLvYU1XKEzDjYi4_J:b-oa2hcx) ([raw file](https://github.com/opensim-org/opensim-core/blob/b49354372127544754760f1bd44a515ac30cf9ea/OpenSim/Moco/MocoOutputConstraint.cpp#L230)):*
> ```cpp
>         if (m_minimizeVectorNorm) {
>             SimTK::SpatialVec value1 = getOutput<SimTK::SpatialVec>().getValue(state);
>             SimTK::SpatialVec value2 = getSecondOutput<SimTK::SpatialVec>().getValue(state);
> ```

Use `const T&`:



_Suggestion:_
```cpp
            const SimTK::SpatialVec& value1 = getOutput<SimTK::SpatialVec>().getValue(state);
            const SimTK::SpatialVec& value2 = getSecondOutput<SimTK::SpatialVec>().getValue(state);
```
___
*[`OpenSim/Moco/MocoOutputConstraint.cpp` line 259 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3855#-O2RMtQ_09rDInlQzPV1:-O2RMtQ_09rDInlQzPV2:b-j1ps5m) ([raw file](https://github.com/opensim-org/opensim-core/blob/b49354372127544754760f1bd44a515ac30cf9ea/OpenSim/Moco/MocoOutputConstraint.cpp#L259)):*
> ```cpp
>     else if (m_data_type == Type_Vec3) { type = "SimTK::Vec3"; }
>     else if (m_data_type == Type_SpatialVec) { type = "SimTK::SpatialVec"; }
>     str += fmt::format(", type: {}", type);
> ```

I think you could use  `getDataTypeString` here.
___
*[`OpenSim/Moco/Test/testMocoGoals.cpp` line 980 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3855#-O2RNRYlAkr45Puetug0:-O2RNRYm1S3tPsDJJDov:byo8gf1) ([raw file](https://github.com/opensim-org/opensim-core/blob/b49354372127544754760f1bd44a515ac30cf9ea/OpenSim/Moco/Test/testMocoGoals.cpp#L980)):*
> ```cpp
> }
> 
> TEMPLATE_TEST_CASE("MocoOutputConstraint with two outputs", "", MocoCasADiSolver,
> ```

Cool test!

**Review by nickbianco — CHANGES_REQUESTED** [review]
(dummy comment to request changes)

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3855#-:-O2RO-eMCl9G5XJ34zq8:bv4jnds)* status: all files reviewed, 12 unresolved discussions (waiting on @AllisonJohn)

**Review by AllisonJohn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3855)* status: 1 of 3 files reviewed, 9 unresolved discussions (waiting on @nickbianco)

___
*[`OpenSim/Moco/MocoOutputConstraint.h` line 59 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3855#-O2RHNJY4FSB5KBs-nth:-O2RRmMg4241K7O27qtE:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/b49354372127544754760f1bd44a515ac30cf9ea/OpenSim/Moco/MocoOutputConstraint.h#L59)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Since the only thing this class can allow are path constraints, you could add the rest of the sentence as in `setOutputPath()`above:
</blockquote></details>

Done.
___
*[`OpenSim/Moco/MocoOutputConstraint.h` line 116 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3855#-O2RHmS-7N113F1BRhKo:-O2RSR8aAlwBDdnyr3X9:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/b49354372127544754760f1bd44a515ac30cf9ea/OpenSim/Moco/MocoOutputConstraint.h#L116)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

As above, you could add back "...to be used in this path constraint..." here.
</blockquote></details>

Done.
___
*[`OpenSim/Moco/MocoOutputConstraint.h` line 119 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3855#-O2RKvWQBoSPjq4qFKo1:-O2RSRSM9ryqS3eBmgkg:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/b49354372127544754760f1bd44a515ac30cf9ea/OpenSim/Moco/MocoOutputConstraint.h#L119)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

As above, you could add back "...to be used in this path constraint..." here.
</blockquote></details>

Done.
___
*[`OpenSim/Moco/MocoOutputConstraint.h` line 143 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3855#-O2RLFfq03rnpqTDjRfr:-O2RRX7j7AQrAuFl6Z7A:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/b49354372127544754760f1bd44a515ac30cf9ea/OpenSim/Moco/MocoOutputConstraint.h#L143)):*
> ```objc
>     double calcCompositeOutputValue(const SimTK::State&) const;
> 
>     /** Get a reference to the Output for this goal. */
> ```

Done.
___
*[`OpenSim/Moco/MocoOutputConstraint.h` line 148 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3855#-O2RLJB_8voOw1FoKuQr:-O2RRWsM2N_dYa5Yo_NH:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/b49354372127544754760f1bd44a515ac30cf9ea/OpenSim/Moco/MocoOutputConstraint.h#L148)):*
> ```objc
>         return static_cast<const Output<T>&>(m_output.getRef());
>     }
>     /** Get a reference to the second Output for this goal. */
> ```

Done.
___
*[`OpenSim/Moco/MocoOutputConstraint.cpp` line 220 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3855#-O2RLe5g5Rz28zy9b4d0:-O2RQ5w09KYSnBhxLimV:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/b49354372127544754760f1bd44a515ac30cf9ea/OpenSim/Moco/MocoOutputConstraint.cpp#L220)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Use `const T&`:
</blockquote></details>

Done.
___
*[`OpenSim/Moco/MocoOutputConstraint.cpp` line 230 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3855#-O2RLvYU1XKEzDjYi4_I:-O2RQ6a-EHfDP5L1iP5Z:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/b49354372127544754760f1bd44a515ac30cf9ea/OpenSim/Moco/MocoOutputConstraint.cpp#L230)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Use `const T&`:
</blockquote></details>

Done.
___
*[`OpenSim/Moco/MocoOutputConstraint.cpp` line 259 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3855#-O2RMtQ_09rDInlQzPV1:-O2RQcno9oVUpXZTJNgn:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/b49354372127544754760f1bd44a515ac30cf9ea/OpenSim/Moco/MocoOutputConstraint.cpp#L259)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

I think you could use  `getDataTypeString` here.
</blockquote></details>

Done.
___
*[`OpenSim/Moco/Test/testMocoGoals.cpp` line 980 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3855#-O2RNRYlAkr45Puetug0:-O2RQehSAiWkKMbiRik8:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/b49354372127544754760f1bd44a515ac30cf9ea/OpenSim/Moco/Test/testMocoGoals.cpp#L980)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Cool test!
</blockquote></details>

Done.

**Review by nickbianco — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3855)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AllisonJohn)

**Review by nickbianco — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3855)* status: all files reviewed, 1 unresolved discussion (waiting on @AllisonJohn)

___
*[`OpenSim/Moco/Test/testMocoGoals.cpp` line 1199 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3855#-O2VQf_r2Kd09ZKtnZic:-O2VQf_r2Kd09ZKtnZid:bs4lcx5) ([raw file](https://github.com/opensim-org/opensim-core/blob/df3541fa02023e27a2cede9a97ce87ab7ac7b5b5/OpenSim/Moco/Test/testMocoGoals.cpp#L1199)):*
> ```cpp
>         StatesTrajectory trajectory = solution.exportToStatesTrajectory(*model);
>         const SimTK::State& 
>           ialState = trajectory.front();
> ```

Something funny happened here, probably when resolving merge conflicts. This is causing the tests to fail, but is an easy fix.

**Review by AllisonJohn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3855)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @nickbianco)

___
*[`OpenSim/Moco/Test/testMocoGoals.cpp` line 1199 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3855#-O2VQf_r2Kd09ZKtnZic:-O2VSPAMEzQBlkHkFUa5:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/df3541fa02023e27a2cede9a97ce87ab7ac7b5b5/OpenSim/Moco/Test/testMocoGoals.cpp#L1199)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Something funny happened here, probably when resolving merge conflicts. This is causing the tests to fail, but is an easy fix.
</blockquote></details>

Done.

**Review by nickbianco — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3855#-:-O2VV3VD5sze6Ehhrdcs:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AllisonJohn)

**Pull request merged**
