### PR TITLE
Add SmoothSphereHalfSpaceForce component

### PR DESCRIPTION
**Pull request by chrisdembia**
Fixes part of #2559

### Brief summary of changes

- This PR introduces the SmoothSphereHalfSpaceForce component for use with Moco.

### Testing I've completed

- Copied the Hunt-Crossley test.
- We have used this component for many months in Moco with much success.

### Looking for feedback on...

I'd like feedback on the interface.

### CHANGELOG.md (choose one)

- updated...

The Doxygen for this PR can be viewed at http://myosin.sourceforge.net/?C=N;O=D; click the folder whose name is this PR's number.

---
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2665)

### CODE REVIEW

**Comment by aymanhab** [comment]
Thanks @chrisdembia will review. Is this needed for 4.1 or for workshops? May create a 4.1 branch in prep for release if not. @jenhicks your thoughts?

**Comment by chrisdembia** [comment]
This is not needed for 4.1 or for workshops.

**Comment by chrisdembia** [comment]
@aymanhab could we move this forward now that 4.1 is released?

**Comment by chrisdembia** [comment]
> LGTM, would be good to have a model file in the repository with this component so that we can test downstream effects.

This PR includes the model OpenSim/Simulation/Test/BouncingBall_SmoothSphereHalfSpace.osim containing this new contact component. Are you thinking of a different type of model?

**Comment by chrisdembia** [comment]
Thank you!

**Pull request merged**
