### PR TITLE
[travis] Build in Release to be consistent with appveyor

### PR DESCRIPTION
**Pull request by chrisdembia**
To be consistent with AppVeyor, we now build in Release on Travis. This follows a similar change for Simbody https://github.com/simbody/simbody/pull/555.

### CODE REVIEW

**Comment by aseth1** [comment]
Feel free to merge when conflict is resolved.

**Comment by aseth1** [comment]
@chrisdembia can you investigate the Mac build failures?

**Comment by chrisdembia** [comment]
The mac build is failing for the same reason as others are seeing; https://github.com/PowerShell/PowerShell/issues/5062

I'll attempt a fix.

**Comment by chrisdembia** [comment]
@aseth1 ready for review again.

**Comment by chrisdembia** [comment]
Ah I see you said that I could merge this. Merging.

**Pull request merged**
