### PR TITLE
Use casadi 3.5.5 and revert specification of IPOPT_LIBRARIES on windows

### PR DESCRIPTION
**Pull request by aymanhab**
Fixes issue #3798 

### Brief summary of changes
change tag and spec for libraries on windows, will use ci to check other changes on mac, linux

### Testing I've completed
run ci
### CHANGELOG.md (choose one)

- no need to update because...
- updated.

- - -
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3799)

### CODE REVIEW

**Comment by aymanhab** [comment]
@nickbianco This PR does the reversion and all tests pass on all platforms but I'd like to wait and build a GUI on top of it to see if /what are the downstream problems with installation and RPAPTH settings. In the meantime, you may backport the one file  change here locally to continue building/running on windows. Let me know if you run into issues or unexpected behavior.

**Comment by nickbianco** [comment]
Great! I'll try backporting into my local branch on Windows and see how it goes.

**Comment by aymanhab** [comment]
Test failure is bogus, gui built cleanly with this PR.

**Review by nickbianco — APPROVED** [review]
:LGTM:

**Comment by aymanhab** [comment]
Thanks @nickbianco 👍

**Pull request merged**
