### PR TITLE
Get rid of some clang warnings related to ModelComponentSet::getModel().

### PR DESCRIPTION
**Pull request by chrisdembia**
This PR gets rid of some warnings generated by clang when checking for a null model like `&getModel()`.

### CODE REVIEW

**Comment by klshrinidhi** [comment]
:+1:

**Comment by chrisdembia** [comment]
Thanks @klshrinidhi. Any other reviewers?

**Comment by chrisdembia** [comment]
Reviewing this PR should be very quick. Anyone else interested?

**Comment by chrisdembia** [comment]
Thank you!

**Pull request merged**
