### PR TITLE
[Moco] Include auxiliary derivatives in the analyze() utility

### PR DESCRIPTION
**Pull request by nickbianco**
Fixes issue #3166

### Brief summary of changes
Previously, calculations from the `analyze()` utility for muscles of type `DeGrooteFregly2016Muscle` using implicit muscle-tendon dynamics may have been incorrect since the derivative of normalized tendon force was not being included in the `SimTK::State`. This is because this auxiliary derivative variable is implemented using a `SimTK::DiscreteVariable` which must be manually updated at each time point (similar to control values).

Changes include:
- Updates to `MocoUtilities::analyzeMocoTrajectory` and `SimulationUtilities::analyze` to include auxiliary derivatives/discrete variables are included.
- Updates to `MocoTrajectory` to make accessing derivatives (and Lagrange multipliers) easier.

### Testing I've completed
- Significant updates to `testMocoActuators` to improve tests overall as well as adding equilibrium tests.
- Updates to `testMocoInverse` to check that equilibrium is enforce correctly in a walking example.

### CHANGELOG.md (choose one)

- updated.

---
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3170)

### CODE REVIEW

**Comment by nickbianco** [comment]
@carmichaelong this is higher priority than #3142.

**Review by carmichaelong — CHANGES_REQUESTED** [review]
As I was finishing up the review, I noticed the CI failures (but looking good overall). Seems like `testMocoGoals` and `testAnalyzeTool` are consistently failing over all platforms, with some issues with a table not having column headers. Perhaps related to if you use `analyze()` but don't pass in a `discreteVariablesTable`?

> Reviewed 4 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3170#-:-Mz2_OhKB7NIKa8PIlwY:b-3yqjco)* status: 4 of 7 files reviewed, 5 unresolved discussions (waiting on @carmichaelong and @nickbianco)

___
*[OpenSim/Moco/MocoUtilities.h, line 78 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3170#-Mz2OyIlABurpV1EYXl-:-Mz2OyIlABurpV1EYXl0:b8paoy5) ([raw file](https://github.com/opensim-org/opensim-core/blob/e8241ae560a6fd8939f84729242732e70a10a87a/OpenSim/Moco/MocoUtilities.h#L78)):*
> ```objc
>     for (const std::string& label : labels) {
>         ComponentPath path(label);
>         if (path.getComponentName() == "accel") {
> ```

this looks alright, but just double checking that there isn't some way of knowing acceleration indices ahead of time to avoid string comparisons?
___
*[OpenSim/Moco/Test/testMocoActuators.cpp, line 136 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3170#-Mz2PhHm6oQ9SOKAdBHO:-Mz2PhHm6oQ9SOKAdBHP:baxuk01) ([raw file](https://github.com/opensim-org/opensim-core/blob/c76a63959c5c232262feeb2076a30aa55174f9e1/OpenSim/Moco/Test/testMocoActuators.cpp#L136)):*
> ```cpp
>         solver.set_optim_convergence_tolerance(1e-4);
>         solver.set_optim_constraint_tolerance(1e-4);
>         solver.set_minimize_implicit_auxiliary_derivatives(true);
> ```

I'm assuming this (and the line above removing the `MocoInitialForceEquilibriumDGFGoal` is part of beefing up the equilibrium tests by explicitly not enforcing equilibrium through the problem setup?
___
*[OpenSim/Moco/Test/testMocoActuators.cpp, line 155 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3170#-Mz2U9nl2JMgxqsJTRJb:-Mz2U9nm9pt7PbyjdywT:b8q2ajr) ([raw file](https://github.com/opensim-org/opensim-core/blob/e8241ae560a6fd8939f84729242732e70a10a87a/OpenSim/Moco/Test/testMocoActuators.cpp#L155)):*
> ```cpp
>         outputPaths.emplace_back(".*velocity.*");
>         auto table = study.analyze(solutionTrajOpt, outputPaths);
>         //STOFileAdapter::write(table, solutionFilename + "_outputs.sto");
> ```

did you still want to print these out or is this to clean up test output? (a few similar ones below too)
___
*[OpenSim/Moco/Test/testMocoActuators.cpp, line 277 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3170#-Mz2UfMI1KB4ZMoxQzDO:-Mz2UfMI1KB4ZMoxQzDP:b-8n32dk) ([raw file](https://github.com/opensim-org/opensim-core/blob/e8241ae560a6fd8939f84729242732e70a10a87a/OpenSim/Moco/Test/testMocoActuators.cpp#L277)):*
> ```cpp
>         const double error = cmcTraj.compareContinuousVariablesRMS(
>                 solutionTrajOpt, {{"states", states}});
>         CHECK(error < 0.5);
> ```

is this tolerance is getting a little large? 0.5 rad is roughly 30 deg? or is activation driving this?
___
*[OpenSim/Simulation/SimulationUtilities.h, line 277 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3170#-Mz2OIIp0A9N9yZIB9lv:-Mz2OIIp0A9N9yZIB9lw:bly2i3b) ([raw file](https://github.com/opensim-org/opensim-core/blob/e8241ae560a6fd8939f84729242732e70a10a87a/OpenSim/Simulation/SimulationUtilities.h#L277)):*
> ```objc
>     // to the components associated with each discrete variable.
>     std::vector<std::pair<std::string, SimTK::ReferencePtr<const Component>>>
>     discreteComponentRefs;
> ```

perhaps tab this line over? i'm not actually 100% sure what our convention is here with such a long type

**Review by nickbianco — COMMENTED** [review]
Thanks @carmichaelong. Yes, I was doing the "empty table" check incorrectly, leading to the failing tests. Addressing some comments now, but will implement code fixes soon.

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3170#-:-Mz2tLoNDHYgBI6ytgNQ:bhd98rv)* status: 4 of 7 files reviewed, 5 unresolved discussions (waiting on @carmichaelong)

___
*[OpenSim/Moco/MocoUtilities.h, line 78 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3170#-Mz2OyIlABurpV1EYXl-:-Mz2rskcCm3I3Ew_ZCdf:bqkek87) ([raw file](https://github.com/opensim-org/opensim-core/blob/e8241ae560a6fd8939f84729242732e70a10a87a/OpenSim/Moco/MocoUtilities.h#L78)):*
<details><summary><i>Previously, carmichaelong wrote…</i></summary><blockquote>

this looks alright, but just double checking that there isn't some way of knowing acceleration indices ahead of time to avoid string comparisons?
</blockquote></details>

Perhaps a better way to handle this is to store a list of indices to the derivatives for coordinate accelerations within the MocoTrajectory. Or just provide methods for getting the acceleration names from MocoTrajectory. I'll give it a shot.
___
*[OpenSim/Moco/Test/testMocoActuators.cpp, line 136 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3170#-Mz2PhHm6oQ9SOKAdBHO:-Mz2sHaj6RAUQab_Fsb1:b-fw7wpa) ([raw file](https://github.com/opensim-org/opensim-core/blob/c76a63959c5c232262feeb2076a30aa55174f9e1/OpenSim/Moco/Test/testMocoActuators.cpp#L136)):*
<details><summary><i>Previously, carmichaelong wrote…</i></summary><blockquote>

I'm assuming this (and the line above removing the `MocoInitialForceEquilibriumDGFGoal` is part of beefing up the equilibrium tests by explicitly not enforcing equilibrium through the problem setup?
</blockquote></details>

Yeah, I found a better match between the implicit derivative variables and the state derivatives computed from explicit mode when turning this off. I don't compare those values in a test anywhere, but it was helpful to see a match. The initial equilibrium goal is unneeded now because I set the initial value for all the states (this was also necessary to get good matches between implicit and explicit modes).
___
*[OpenSim/Moco/Test/testMocoActuators.cpp, line 155 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3170#-Mz2U9nl2JMgxqsJTRJb:-Mz2sCAj4NsLCrX2nwmv:b-m04htx) ([raw file](https://github.com/opensim-org/opensim-core/blob/e8241ae560a6fd8939f84729242732e70a10a87a/OpenSim/Moco/Test/testMocoActuators.cpp#L155)):*
<details><summary><i>Previously, carmichaelong wrote…</i></summary><blockquote>

did you still want to print these out or is this to clean up test output? (a few similar ones below too)
</blockquote></details>

This was intentional. I don't want to be printing out these files all the time anymore.
___
*[OpenSim/Moco/Test/testMocoActuators.cpp, line 277 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3170#-Mz2UfMI1KB4ZMoxQzDO:-Mz2smWJ0PJsruNRizwE:b-sbaohu) ([raw file](https://github.com/opensim-org/opensim-core/blob/e8241ae560a6fd8939f84729242732e70a10a87a/OpenSim/Moco/Test/testMocoActuators.cpp#L277)):*
<details><summary><i>Previously, carmichaelong wrote…</i></summary><blockquote>

is this tolerance is getting a little large? 0.5 rad is roughly 30 deg? or is activation driving this?
</blockquote></details>

This is the RMS error across the whole trajectory for the states. The states start to deviate towards the ends of the trajectory, but the qualitative match is pretty good. I don't really want to go down the rabbit hole of making CMC match well to Moco at any precise numerical level.
___
*[OpenSim/Simulation/SimulationUtilities.h, line 277 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3170#-Mz2OIIp0A9N9yZIB9lv:-Mz2tACg-q9TnWjfQbyx:b-6zn1k4) ([raw file](https://github.com/opensim-org/opensim-core/blob/e8241ae560a6fd8939f84729242732e70a10a87a/OpenSim/Simulation/SimulationUtilities.h#L277)):*
<details><summary><i>Previously, carmichaelong wrote…</i></summary><blockquote>

perhaps tab this line over? i'm not actually 100% sure what our convention is here with such a long type
</blockquote></details>

This the convention I've used before. I could tab over, but both look equally bad tbh.

**Review by carmichaelong — COMMENTED** [review]
Looks like it's all good now (Mac CI randomly failed twice but is OK now). Thanks for the discussion on some parts. I think this could be merged as is. The discussion to avoid string lookups does not not need to be addressed in this PR to get this in and could be deferred too.

> Reviewed 2 of 7 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3170#-:-MzHAlnM8NxjJBEr6sxF:b-dgydzo)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @nickbianco)

___
*[OpenSim/Moco/MocoUtilities.h, line 78 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3170#-Mz2OyIlABurpV1EYXl-:-Mz44XOKCj16Jv3dd3SO:b-bd3u27) ([raw file](https://github.com/opensim-org/opensim-core/blob/e8241ae560a6fd8939f84729242732e70a10a87a/OpenSim/Moco/MocoUtilities.h#L78)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

Perhaps a better way to handle this is to store a list of indices to the derivatives for coordinate accelerations within the MocoTrajectory. Or just provide methods for getting the acceleration names from MocoTrajectory. I'll give it a shot.
</blockquote></details>

This can also be deferred for a future PR if it's not straightforward
___
*[OpenSim/Moco/Test/testMocoActuators.cpp, line 277 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3170#-Mz2UfMI1KB4ZMoxQzDO:-Mz44GFN7Dbnwl6HPnZ1:bs4r9ho) ([raw file](https://github.com/opensim-org/opensim-core/blob/e8241ae560a6fd8939f84729242732e70a10a87a/OpenSim/Moco/Test/testMocoActuators.cpp#L277)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

This is the RMS error across the whole trajectory for the states. The states start to deviate towards the ends of the trajectory, but the qualitative match is pretty good. I don't really want to go down the rabbit hole of making CMC match well to Moco at any precise numerical level.
</blockquote></details>

Yeah no need to go down a rabbit hole. I wonder since CMC can diverge so much over time if shortening the test is more useful then? No need to do that for this PR if you think it's OK as is

 (late edit: i'm noticing it looks like the test is only over 0.46 seconds already so clearly this is well thought out)

**Review by nickbianco — COMMENTED** [review]
Well, I did the opposite of deferring it. I abstracted the string checks away inside `MocoTrajectory`, which led me to add some new convenience accessors to `MocoTrajectory`, which then made me realize I could fix a known bug. 

Sorry to extend the scope of the PR, but these updates were worth including while I was already in the zone. 

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3170#-:-MzIDHUM91MtQQM30B91:b967naq)* status: 4 of 7 files reviewed, 2 unresolved discussions (waiting on @carmichaelong)

___
*[OpenSim/Moco/Test/testMocoActuators.cpp, line 277 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3170#-Mz2UfMI1KB4ZMoxQzDO:-MzICp0m1qf7g9DJCnlX:b-iwylho) ([raw file](https://github.com/opensim-org/opensim-core/blob/e8241ae560a6fd8939f84729242732e70a10a87a/OpenSim/Moco/Test/testMocoActuators.cpp#L277)):*
<details><summary><i>Previously, carmichaelong wrote…</i></summary><blockquote>

Yeah no need to go down a rabbit hole. I wonder since CMC can diverge so much over time if shortening the test is more useful then? No need to do that for this PR if you think it's OK as is

 (late edit: i'm noticing it looks like the test is only over 0.46 seconds already so clearly this is well thought out)
</blockquote></details>

Some might say *too* well thought out.

**Comment by nickbianco** [comment]
@aymanhab do you know why `testContext` is failing? I'd like to get a passing build so I can use the build artifacts.

**Review by carmichaelong — CHANGES_REQUESTED** [review]
No worries. Can you describe the bug you were looking to fix or point to an existing issue (or is it as simple as the description given in the edited CHANGELOG)? As I was reading the meat of the `MocoTrajectory.cpp` changes, it seemed like having some context for that could be helpful while reviewing

> Reviewed 1 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3170#-:-MzRBSK57-SeViqG8pfk:b-9cvrr8)* status: 4 of 8 files reviewed, 1 unresolved discussion (waiting on @carmichaelong and @nickbianco)

___
*[OpenSim/Moco/MocoTrajectory.h, line 569 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3170#-MzJ7N8X2iLfsVIlASRs:-MzJ7N8X2iLfsVIlASRt:b4sj82y) ([raw file](https://github.com/opensim-org/opensim-core/blob/5dd3188239c43a11d6e09709663b29cdce058dee/OpenSim/Moco/MocoTrajectory.h#L569)):*
> ```objc
>         ensureUnsealed();
>         auto indices = getValueIndices();
>         if (indices.empty()) indices.push_back(0);
> ```

I'm not exactly sure how to review these repeated sets of lines:
```
if (indices.empty()) indices.push_back(0);
return {m_states.block(0, indices[0],
             m_states.nrow(), getNumValues())};
```

But I'm assuming from tests that this format is correct for whatever the users of this function are

**Review by nickbianco — COMMENTED** [review]
> Did you have any tests in mind to target the overwriting non-acceleration derivatives issues?

Ready for review.

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3170#-:-MzqZ6bg1jwbbKs6xER4:b-fybqj9)* status: 5 of 9 files reviewed, 1 unresolved discussion (waiting on @carmichaelong)

___
*[OpenSim/Moco/MocoTrajectory.h, line 569 at r3](https://reviewable.io/reviews/opensim-org/opensim-core/3170#-MzJ7N8X2iLfsVIlASRs:-MzqZ1wrC01QuajnEkC-:b5ixks7) ([raw file](https://github.com/opensim-org/opensim-core/blob/5dd3188239c43a11d6e09709663b29cdce058dee/OpenSim/Moco/MocoTrajectory.h#L569)):*
<details><summary><i>Previously, carmichaelong wrote…</i></summary><blockquote>

I'm not exactly sure how to review these repeated sets of lines:
```
if (indices.empty()) indices.push_back(0);
return {m_states.block(0, indices[0],
             m_states.nrow(), getNumValues())};
```

But I'm assuming from tests that this format is correct for whatever the users of this function are
</blockquote></details>

Good comment: I added test coverage for these methods to be sure.

**Review by carmichaelong — APPROVED** [review]
> Reviewed 1 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3170)* status: 5 of 9 files reviewed, 1 unresolved discussion (waiting on @carmichaelong)

**Comment by nickbianco** [comment]
Thanks @carmichaelong!

**Pull request merged**
