### PR TITLE
Incrementing XMLDocument number to 30506

### PR DESCRIPTION
**Pull request by tkuchida**
Per @aymanhab's request in #1002

### CODE REVIEW

**Comment by aymanhab** [comment]
I don't see any open PRs that change XML format so I'm happy to merge this once the tests pass so we can draw a line and start testing model file conversion unless there are objections by @aseth1 or @chrisdembia who may be aware of conflicting changes in the pipe.

**Comment by chrisdembia** [comment]
I am not aware of any conflicting changes.

**Comment by tkuchida** [comment]
MovingPathPoint failed in testComponents.cpp on AppVeyor: [MovingPathPoint.initSystem() increased memory use by 316%.](https://ci.appveyor.com/project/opensim-org/opensim-core/build/3689/job/txkoqtk68pfd30yb#L889).

**Comment by chrisdembia** [comment]
Could be an intermittent failure. Did you try re-building?

**Comment by tkuchida** [comment]
> Did you try re-building?

Passed on second try.

**Comment by chrisdembia** [comment]
I wish more things would just work the second time.

**Comment by aymanhab** [comment]
Or that we get the same behavior every time ;)

**Comment by tkuchida** [comment]
> Or that we get the same behavior every time ;)

:+1: :smile:

**Comment by aymanhab** [comment]
Merging based on discussion/approval by @aseth1. Thanks.

**Pull request merged**
