### PR TITLE
Expose Array of Vec3 for pathwrap usage

### PR DESCRIPTION
**Pull request by aymanhab**
Fixes issue #<issue_number>

### Brief summary of changes
PathWrapPoint returns intermediate points on wrap surface as an instance of OpenSim::Array<SimTK::Vec3> which is unusable from GUI, Scripting if class is not exposed
### Testing I've completed
Built bindings and the return type is now usable
### CHANGELOG.md (choose one)

- no need to update because the method//interface is new to 4.0

The Doxygen for this PR can be viewed at http://myosin.sourceforge.net/?C=N;O=D; click the folder whose name is this PR's number.

### CODE REVIEW

**Comment by aymanhab** [comment]
WIP pending the merge of PR #1721 don't review until then, this's a one line change in SWIG wrapping

**Comment by aymanhab** [comment]
Now this is a trivial exposure of instantiated template in SWIG.

**Comment by aymanhab** [comment]
Thanks for the super quick review @chrisdembia and @tkuchida

**Comment by aymanhab** [comment]
testExternalLoads failing sporadically on AppVeyor, is that expected? Unlikely related to this PR that touches only SWIG wrapping.

**Comment by chrisdembia** [comment]
I do not know of any such sporadic failure. Does the log provide any clues?

**Comment by tkuchida** [comment]
Currently, the only failure is timeout on Travis/debug.

**Comment by chrisdembia** [comment]
Thanks for reporting, @tkuchida . Since we do not build the bindings in Debug, I'll merge this.

**Comment by aymanhab** [comment]
Thank you

**Pull request merged**
