### PR TITLE
Updated to ezc3d 1.4.9

### PR DESCRIPTION
**Pull request by pariterre**
Fixes issue #3209 

### Brief summary of changes
Updated to newest ezc3d version

### Testing I've completed
None - Rely on the tests here

### Looking for feedback on...
None

### CHANGELOG.md (choose one)
- updated.

---
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3212)

### CODE REVIEW

**Comment by aymanhab** [comment]
Thanks @pariterre but the build fails on all platforms trying to locate ezc3d, did anything change about how ezc3d uses CMake?

**Comment by aymanhab** [comment]
Sorry to bug you again about this @pariterre but where does this stand? How are other projects finding EZC3D? Thanks

**Comment by pariterre** [comment]
@aymanhab 
Sorry I haven't had the time to finish this. Actually @teliason changed the CMake in a recent PR and I am trying to figure out this exact thing! I should come back to it soon

**Comment by pariterre** [comment]
Hi @aymanhab 
I've made some tests with the new CMake developed by @SpaceIm (sorry I tagged the wrong developer last time). 
Includes and linkings are now implicitly done using the usual `target_link_libraries`, with a small twist for windows (as one must copy the DLLs). Here is a minimal example:
```cmake
cmake_minimum_required(VERSION 3.5)

project(test_project_that_includes_ezc3d LANGUAGES CXX)
add_executable(test_project_that_includes_ezc3d main.cpp)

set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

find_package(ezc3d REQUIRED)
target_link_libraries(test_project_that_includes_ezc3d ezc3d)

# Copy the DLL in required folder for windows
if (WIN32)
  add_custom_command(TARGET test_project_that_includes_ezc3d POST_BUILD
    COMMAND ${CMAKE_COMMAND} -E copy $<TARGET_RUNTIME_DLLS:test_project_that_includes_ezc3d> $<TARGET_FILE_DIR:test_project_that_includes_ezc3d>
    COMMAND_EXPAND_LISTS
  )
endif(WIN32)
```
Which allows for:
```c++
#include <ezc3d/ezc3d_all.h>
int main()
{
    ezc3d::c3d emptyC3d;
    emptyC3d.print();
    return 0;
}
```
But, in the case of OpenSim, you are kind of manually moving stuff around to link the library and include the headers. 
I am not sure what is the best way to do that... @spacelm, do you have a suggestion?

**Comment by aymanhab** [comment]
@pariterre Thanks for looking into this, I'm getting closer but I'm have a problem finding out what variables are exported by your find_package(), our CMake files used ezc3d_LIBRARY_DIR, ezc3d_LIBRARY, ezc3d_INCLUDE_DIR and I'm having a hard time finding out what variables are defined by your new config file or what they are set to on various platforms, can you or @spacelm clarify? We're not using the latest cutting edge CMake version/options and we prefer not to so that our users are not forced to upgrade. Thank you

**Comment by pariterre** [comment]
@SpaceIm 
Does this mean that each time an `add_executable` is called, a target_link_library with ezc3d should be called, or some sort of global link is possible?

**Comment by SpaceIm** [comment]
If you want global link, there is https://cmake.org/cmake/help/latest/command/link_libraries.html, but it's a bad practice because you lose the true relationship between your targets.

**Comment by pariterre** [comment]
@aymanhab 
Okay, ping me if you need me. While you are at it, you may actually change 1.4.9 to 1.5.0 since I push another release last week (added the capability to read ROTATION in the c3d files, which won't impact you though)

See you :)

**Comment by aymanhab** [comment]
Closing since this was subsumed by another PR that upgraded to version 1.5

**Pull request closed without merging**
