### PR TITLE
Streamline examples TGCS workshop

### PR DESCRIPTION
**Pull request by antoinefalisse**
@nickbianco and @carmichaelong 

### Brief summary of changes

Streamline examples for workshop by adding part of the code users have to fill out. I have tried to add code where it is either repetitive, a lot of text, or quite challenging to understand what is happening (eg safedowncast). Maybe it is too much?

### Testing I've completed

No needed.

### Looking for feedback on...

Too much added or not appropriate?

---
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3030)

### CODE REVIEW

**Review by nickbianco — CHANGES_REQUESTED** [review]
Thanks @antoinefalisse! I think these changes look mostly good. I left some comments below (only on the Matlab scripts, but make the same changes in Python too). 

One overarching comment is to leave a space in methods whenever participants need to fill something in. So, for example, instead of
```
inverse.set_initial_time();
```
it would be
```
inverse.set_initial_time( );
```

Just a small thing to differentiate from methods that have no arguments.

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3030#-:-Me7Qr3Z4R9vjSLB47JO:b54935w)* status: all files reviewed, 6 unresolved discussions (waiting on @antoinefalisse)

___
*[Bindings/Java/Matlab/examples/Moco/exampleEMGTracking/exampleEMGTracking.m, line 28 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3030#-Me7S1ok-AsBCiZYcpBi:-Me7S1ok-AsBCiZYcpBj:bklz1or) ([raw file](https://github.com/opensim-org/opensim-core/blob/05604bfb10cbd10f9a3c45f7fdc7b1d58973caa9/Bindings/Java/Matlab/examples/Moco/exampleEMGTracking/exampleEMGTracking.m#L28)):*
> ```objc
> % TableProcessor we just created.
> inverse.setKinematics();
> inverse.set_kinematics_allow_extra_columns(true);
> ```

I think we can have users type out this section.
___
*[Bindings/Java/Matlab/examples/Moco/exampleEMGTracking/exampleEMGTracking.m, line 69 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3030#-Me7S4j15_A_Z8Vz9Eo-:-Me7S4j15_A_Z8Vz9Eo0:b1s5iu4) ([raw file](https://github.com/opensim-org/opensim-core/blob/05604bfb10cbd10f9a3c45f7fdc7b1d58973caa9/Bindings/Java/Matlab/examples/Moco/exampleEMGTracking/exampleEMGTracking.m#L69)):*
> ```objc
> tracking.setReferenceLabel('/forceset/gasmed_l', 'gastrocnemius');
> tracking.setReferenceLabel('/forceset/tibant_l', 'tibialis_anterior');
> tracking.setReferenceLabel('/forceset/bfsh_l', );
> ```

You can fill in the rest of the bifem short head line here, and users will fill in the last one only.
___
*[Bindings/Java/Matlab/examples/Moco/exampleEMGTracking/exampleEMGTracking.m, line 79 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3030#-Me7SH8a9VuR0EzF-CXL:-Me7SH8a9VuR0EzF-CXM:bawi3rd) ([raw file](https://github.com/opensim-org/opensim-core/blob/05604bfb10cbd10f9a3c45f7fdc7b1d58973caa9/Bindings/Java/Matlab/examples/Moco/exampleEMGTracking/exampleEMGTracking.m#L79)):*
> ```objc
> tracking.addScaleFactor('gastroc_factor', '/forceset/gasmed_l', [0.01 1.0]); 
> tracking.addScaleFactor('tibant_factor', '/forceset/tibant_l', [0.01 1.0]); 
> tracking.addScaleFactor('bifem_factor', '/forceset/bfsh_l', ); 
> ```

Same as above, you can fill in the rest of the bifem short head line here, and users will fill in the last one only.
___
*[Bindings/Java/Matlab/examples/Moco/exampleEMGTracking/exampleEMGTracking.m, line 88 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3030#-Me7SdsMDeg0HqnzTcBk:-Me7SdsMDeg0HqnzTcBl:b-uka0yq) ([raw file](https://github.com/opensim-org/opensim-core/blob/05604bfb10cbd10f9a3c45f7fdc7b1d58973caa9/Bindings/Java/Matlab/examples/Moco/exampleEMGTracking/exampleEMGTracking.m#L88)):*
> ```objc
> % resetProblem().
> solver = MocoCasADiSolver.safeDownCast(study.updSolver());
> solver.
> ```

I think we'll just give the users the whole `solver.resetProblem(problem)` line.
___
*[Bindings/Java/Matlab/examples/Moco/exampleEMGTracking/exampleEMGTracking.m, line 102 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3030#-Me7TLSo2yXOMGBkes6t:-Me7TLSo2yXOMGBkes6u:bsqq3bo) ([raw file](https://github.com/opensim-org/opensim-core/blob/05604bfb10cbd10f9a3c45f7fdc7b1d58973caa9/Bindings/Java/Matlab/examples/Moco/exampleEMGTracking/exampleEMGTracking.m#L102)):*
> ```objc
> 
> % Part 3h: Get the values of the optimized scale factors.
> trackingSolution = 
> ```

Let's give users this line too and just have the fill in the line for the gluteus factor.
___
*[Bindings/Java/Matlab/examples/Moco/exampleSquatToStand/exampleIMUTracking/exampleIMUTracking.m, line 113 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3030#-Me7SwleCkBv1ZuIHaLZ:-Me7SwleCkBv1ZuIHaL_:b-8ou1ls) ([raw file](https://github.com/opensim-org/opensim-core/blob/05604bfb10cbd10f9a3c45f7fdc7b1d58973caa9/Bindings/Java/Matlab/examples/Moco/exampleSquatToStand/exampleIMUTracking/exampleIMUTracking.m#L113)):*
> ```objc
> % the offset frame paths. This is necessary for the tracking goal we'll add
> % to the problem in Part 4. 
> ```

Let's give users this line where we update the column, since it's more of a bookkeeping step.

**Review by antoinefalisse — COMMENTED** [review]
Done.

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3030#-:-MeB7RN0Bzj0FHWOk4Js:b-896fix)* status: all files reviewed, 6 unresolved discussions (waiting on @nickbianco)

___
*[Bindings/Java/Matlab/examples/Moco/exampleEMGTracking/exampleEMGTracking.m, line 28 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3030#-Me7S1ok-AsBCiZYcpBi:-MeB4uxf0wh6BEckXsL5:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/05604bfb10cbd10f9a3c45f7fdc7b1d58973caa9/Bindings/Java/Matlab/examples/Moco/exampleEMGTracking/exampleEMGTracking.m#L28)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

I think we can have users type out this section.
</blockquote></details>

Done.
___
*[Bindings/Java/Matlab/examples/Moco/exampleEMGTracking/exampleEMGTracking.m, line 69 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3030#-Me7S4j15_A_Z8Vz9Eo-:-MeB5Atv1Ua3TMaPh1zF:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/05604bfb10cbd10f9a3c45f7fdc7b1d58973caa9/Bindings/Java/Matlab/examples/Moco/exampleEMGTracking/exampleEMGTracking.m#L69)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

You can fill in the rest of the bifem short head line here, and users will fill in the last one only.
</blockquote></details>

Done.
___
*[Bindings/Java/Matlab/examples/Moco/exampleEMGTracking/exampleEMGTracking.m, line 79 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3030#-Me7SH8a9VuR0EzF-CXL:-MeB5HEHEoI8uaoDJUDf:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/05604bfb10cbd10f9a3c45f7fdc7b1d58973caa9/Bindings/Java/Matlab/examples/Moco/exampleEMGTracking/exampleEMGTracking.m#L79)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

Same as above, you can fill in the rest of the bifem short head line here, and users will fill in the last one only.
</blockquote></details>

Done.
___
*[Bindings/Java/Matlab/examples/Moco/exampleEMGTracking/exampleEMGTracking.m, line 88 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3030#-Me7SdsMDeg0HqnzTcBk:-MeB5PLf0wmIHmgnTqQ3:bfpk43p) ([raw file](https://github.com/opensim-org/opensim-core/blob/05604bfb10cbd10f9a3c45f7fdc7b1d58973caa9/Bindings/Java/Matlab/examples/Moco/exampleEMGTracking/exampleEMGTracking.m#L88)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

I think we'll just give the users the whole `solver.resetProblem(problem)` line.
</blockquote></details>

Done. Should we adjust the Part 3e? They won't have to do anything, but you probably still want to explain what is happening. So it might be fine as is.
___
*[Bindings/Java/Matlab/examples/Moco/exampleEMGTracking/exampleEMGTracking.m, line 102 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3030#-Me7TLSo2yXOMGBkes6t:-MeB5peBAtJnzFmhduOT:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/05604bfb10cbd10f9a3c45f7fdc7b1d58973caa9/Bindings/Java/Matlab/examples/Moco/exampleEMGTracking/exampleEMGTracking.m#L102)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

Let's give users this line too and just have the fill in the line for the gluteus factor.
</blockquote></details>

Done.
___
*[Bindings/Java/Matlab/examples/Moco/exampleSquatToStand/exampleIMUTracking/exampleIMUTracking.m, line 113 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3030#-Me7SwleCkBv1ZuIHaLZ:-MeB681eD_JmJsVLahN0:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/05604bfb10cbd10f9a3c45f7fdc7b1d58973caa9/Bindings/Java/Matlab/examples/Moco/exampleSquatToStand/exampleIMUTracking/exampleIMUTracking.m#L113)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

Let's give users this line where we update the column, since it's more of a bookkeeping step.
</blockquote></details>

Done.

**Review by nickbianco — APPROVED** [review]
:lgtm: 

> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3030#-:-MeCPbvW3qZXm8o0Hsm2:bg7igkv)* status: all files reviewed, 1 unresolved discussion (waiting on @antoinefalisse)

___
*[Bindings/Java/Matlab/examples/Moco/exampleEMGTracking/exampleEMGTracking.m, line 88 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3030#-Me7SdsMDeg0HqnzTcBk:-MeCPPgP2QyNHHWK2cDs:b1nv15i) ([raw file](https://github.com/opensim-org/opensim-core/blob/05604bfb10cbd10f9a3c45f7fdc7b1d58973caa9/Bindings/Java/Matlab/examples/Moco/exampleEMGTracking/exampleEMGTracking.m#L88)):*
<details><summary><i>Previously, antoinefalisse (Antoine Falisse) wrote…</i></summary><blockquote>

Done. Should we adjust the Part 3e? They won't have to do anything, but you probably still want to explain what is happening. So it might be fine as is.
</blockquote></details>

I think it's fine as is. We can explain what's happening in the slides and keep the same numbering and everything.

**Review by carmichaelong — APPROVED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3030)* status: all files reviewed, 1 unresolved discussion (waiting on @antoinefalisse)

**Comment by nickbianco** [comment]
Thanks @antoinefalisse!

**Pull request merged**
