### PR TITLE
[Moco] Matlab version of example2DWalkingMetaoblics

### PR DESCRIPTION
**Pull request by nickbianco**
### Brief summary of changes
- Add Brian Umberger's Matlab version of example2DWalkingMetabolics.

### Testing I've completed
- Ran the example locally.

### CHANGELOG.md (choose one)
- updated.

---
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3021)

### CODE REVIEW

**Review by carmichaelong — CHANGES_REQUESTED** [review]
Looks great and it worked locally for me. Left a few minor comments.

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3021#-:-MdOfUCs-Uhxuc4153Tp:b-2r34bk)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @nickbianco)

___
*[Bindings/Java/Matlab/examples/Moco/example2DWalking/example2DWalkingMetabolics.m, line 100 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3021#-MdOE__C2FyLeDlyuoDr:-MdOE__C2FyLeDlyuoDs:b-amsnwh) ([raw file](https://github.com/opensim-org/opensim-core/blob/bc73be4d4a9b9cb1b599d1f117ca98033df7d833/Bindings/Java/Matlab/examples/Moco/example2DWalking/example2DWalkingMetabolics.m#L100)):*
> ```objc
> tableProcessor.append(TabOpLowPassFilter(6));
> 
> % ModelProcessor modelprocessor = ModelProcessor(baseModel);
> ```

Cleanup from C++ example? Also, does this section need a comment?
___
*[Bindings/Java/Matlab/examples/Moco/example2DWalking/example2DWalkingMetabolics.m, line 122 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3021#-MdOGxrN0fBgfnVcQbQ2:-MdOGxrN0fBgfnVcQbQ3:b-v90moe) ([raw file](https://github.com/opensim-org/opensim-core/blob/bc73be4d4a9b9cb1b599d1f117ca98033df7d833/Bindings/Java/Matlab/examples/Moco/example2DWalking/example2DWalkingMetabolics.m#L122)):*
> ```objc
> model.initSystem();
> 
> % Symmetric coordinate values (except for pelvis_tx) and speeds
> ```

(I would not consider this a blocking comment, especially if there haven't been too many questions about how to use the symmetry goals so far.)

Along with the well-named variables in doxygen (even though there are no explicit comments for the constructor), I was able to figure out what was going on here, so I think it's OK as is. The comments and code also look to be the same in the adjacent example2DWalking.m file.

If there was a small upgrade to be made, it could be helpful to give some high-level comments about what's going on here (something like the following but better worded: we want final coordinate values of one side to match the initial value of the other side, OR if there is no side associated, make sure that the final value is the same as the initial value).
___
*[Bindings/Java/Matlab/examples/Moco/example2DWalking/example2DWalkingMetabolics.m, line 222 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3021#-MdOIer3CDwL7jaCL-p1:-MdOIer3CDwL7jaCL-p2:b9rq3kd) ([raw file](https://github.com/opensim-org/opensim-core/blob/bc73be4d4a9b9cb1b599d1f117ca98033df7d833/Bindings/Java/Matlab/examples/Moco/example2DWalking/example2DWalkingMetabolics.m#L222)):*
> ```objc
> 
> % Uncomment next line to visualize the result
> study.visualize(fullStride);
> ```

Comment out? Or change previous line's comment to match

Also, geometry files would be needed to see the skeleton

**Review by nickbianco — COMMENTED** [review]
@carmichaelong Thanks for the quick review. I was already halfway through this so I just finished up the changes you suggested.

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3021#-:-MdOzJkD9SeoOmRAhHMG:bpbewgx)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @carmichaelong)

___
*[Bindings/Java/Matlab/examples/Moco/example2DWalking/example2DWalkingMetabolics.m, line 100 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3021#-MdOE__C2FyLeDlyuoDr:-MdOvj10E4xUpQjKnaK9:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/bc73be4d4a9b9cb1b599d1f117ca98033df7d833/Bindings/Java/Matlab/examples/Moco/example2DWalking/example2DWalkingMetabolics.m#L100)):*
<details><summary><i>Previously, carmichaelong wrote…</i></summary><blockquote>

Cleanup from C++ example? Also, does this section need a comment?
</blockquote></details>

Done.
___
*[Bindings/Java/Matlab/examples/Moco/example2DWalking/example2DWalkingMetabolics.m, line 122 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3021#-MdOGxrN0fBgfnVcQbQ2:-MdOydJD2r_Qfz5Gdx_D:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/bc73be4d4a9b9cb1b599d1f117ca98033df7d833/Bindings/Java/Matlab/examples/Moco/example2DWalking/example2DWalkingMetabolics.m#L122)):*
<details><summary><i>Previously, carmichaelong wrote…</i></summary><blockquote>

(I would not consider this a blocking comment, especially if there haven't been too many questions about how to use the symmetry goals so far.)

Along with the well-named variables in doxygen (even though there are no explicit comments for the constructor), I was able to figure out what was going on here, so I think it's OK as is. The comments and code also look to be the same in the adjacent example2DWalking.m file.

If there was a small upgrade to be made, it could be helpful to give some high-level comments about what's going on here (something like the following but better worded: we want final coordinate values of one side to match the initial value of the other side, OR if there is no side associated, make sure that the final value is the same as the initial value).
</blockquote></details>

Done.
___
*[Bindings/Java/Matlab/examples/Moco/example2DWalking/example2DWalkingMetabolics.m, line 222 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3021#-MdOIer3CDwL7jaCL-p1:-MdOyfll7QLZ70i-GGab:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/bc73be4d4a9b9cb1b599d1f117ca98033df7d833/Bindings/Java/Matlab/examples/Moco/example2DWalking/example2DWalkingMetabolics.m#L222)):*
<details><summary><i>Previously, carmichaelong wrote…</i></summary><blockquote>

Comment out? Or change previous line's comment to match

Also, geometry files would be needed to see the skeleton
</blockquote></details>

Done.

**Review by carmichaelong — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3021)* status: 0 of 4 files reviewed, 5 unresolved discussions (waiting on @nickbianco)

___
*[Bindings/Java/Matlab/examples/Moco/example2DWalking/example2DWalking.m, line 111 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3021#-MdQk3IaEBtHEos_mkZT:-MdQk3IaEBtHEos_mkZU:b-2cswhm) ([raw file](https://github.com/opensim-org/opensim-core/blob/704ac5f4ce124384bfd5eefab4a07c7fb71461e4/Bindings/Java/Matlab/examples/Moco/example2DWalking/example2DWalking.m#L111)):*
> ```objc
> % Symmetric coordinate values (except for pelvis_tx) and speeds. Here, we 
> % constrain final coordinate values of one leg to match the initial value of the 
> % other leg. Or, in the case of the pelvis_tx value, we constraint the final 
> ```

constraint -> constrain
___
*[Bindings/Java/Matlab/examples/Moco/example2DWalking/example2DWalking.m, line 135 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3021#-MdQk5Vv8QRWfT-URMxB:-MdQk5Vv8QRWfT-URMxC:b-28v5mi) ([raw file](https://github.com/opensim-org/opensim-core/blob/704ac5f4ce124384bfd5eefab4a07c7fb71461e4/Bindings/Java/Matlab/examples/Moco/example2DWalking/example2DWalking.m#L135)):*
> ```objc
> end
> 
> % Symmetric muscle activations. Here, we  constrain final muscle activation 
> ```

looks like two spaces snuck in here
___
*[Bindings/Java/Matlab/examples/Moco/example2DWalking/example2DWalkingMetabolics.m, line 132 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3021#-MdQkGjF2FlL7uvJEJ8o:-MdQkGjF2FlL7uvJEJ8p:b-2cswhm) ([raw file](https://github.com/opensim-org/opensim-core/blob/704ac5f4ce124384bfd5eefab4a07c7fb71461e4/Bindings/Java/Matlab/examples/Moco/example2DWalking/example2DWalkingMetabolics.m#L132)):*
> ```objc
> % Symmetric coordinate values (except for pelvis_tx) and speeds. Here, we 
> % constrain final coordinate values of one leg to match the initial value of the 
> % other leg. Or, in the case of the pelvis_tx value, we constraint the final 
> ```

constraint -> constrain
___
*[Bindings/Java/Matlab/examples/Moco/example2DWalking/example2DWalkingMetabolics.m, line 156 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3021#-MdQkIE65wuO1Hvdk0yQ:-MdQkIE65wuO1Hvdk0yR:b-jd1zui) ([raw file](https://github.com/opensim-org/opensim-core/blob/704ac5f4ce124384bfd5eefab4a07c7fb71461e4/Bindings/Java/Matlab/examples/Moco/example2DWalking/example2DWalkingMetabolics.m#L156)):*
> ```objc
> end
> 
> % Symmetric muscle activations. Here, we  constrain final muscle activation 
> ```

two spaces
___
*[Bindings/Java/Matlab/examples/Moco/example2DWalking/example2DWalkingMetabolics.m, line 233 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3021#-MdQqE5FBDA1RZr7OH9E:-MdQqE5FBDA1RZr7OH9F:b-q8kmwe) ([raw file](https://github.com/opensim-org/opensim-core/blob/704ac5f4ce124384bfd5eefab4a07c7fb71461e4/Bindings/Java/Matlab/examples/Moco/example2DWalking/example2DWalkingMetabolics.m#L233)):*
> ```objc
> 
> % Visualize the result.
> study.visualize(fullStride);
> ```

The ribs and scapula didn't show up. I wanted to put this comment in the .osim file, but since it isn't modified and doesn't show up in Reviewable, I figure this is the next best place:

In `2d_gait.osim`, L2252: `hat_ribs.vtp` -> `hat_ribs_scap.vtp`

**Review by nickbianco — COMMENTED** [review]
Ready for review.

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3021#-:-MdT0MWu2G8EJnytWwbx:b8pt725)* status: 0 of 4 files reviewed, 5 unresolved discussions (waiting on @carmichaelong)

___
*[Bindings/Java/Matlab/examples/Moco/example2DWalking/example2DWalking.m, line 111 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3021#-MdQk3IaEBtHEos_mkZT:-MdT-FR6CTMv_DHiZ9-A:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/704ac5f4ce124384bfd5eefab4a07c7fb71461e4/Bindings/Java/Matlab/examples/Moco/example2DWalking/example2DWalking.m#L111)):*
<details><summary><i>Previously, carmichaelong wrote…</i></summary><blockquote>

constraint -> constrain
</blockquote></details>

Done.
___
*[Bindings/Java/Matlab/examples/Moco/example2DWalking/example2DWalking.m, line 135 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3021#-MdQk5Vv8QRWfT-URMxB:-MdT-KRA5cGuv7hx34t5:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/704ac5f4ce124384bfd5eefab4a07c7fb71461e4/Bindings/Java/Matlab/examples/Moco/example2DWalking/example2DWalking.m#L135)):*
<details><summary><i>Previously, carmichaelong wrote…</i></summary><blockquote>

looks like two spaces snuck in here
</blockquote></details>

Done.
___
*[Bindings/Java/Matlab/examples/Moco/example2DWalking/example2DWalkingMetabolics.m, line 132 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3021#-MdQkGjF2FlL7uvJEJ8o:-MdT-KwYA4fCPiQf3F2W:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/704ac5f4ce124384bfd5eefab4a07c7fb71461e4/Bindings/Java/Matlab/examples/Moco/example2DWalking/example2DWalkingMetabolics.m#L132)):*
<details><summary><i>Previously, carmichaelong wrote…</i></summary><blockquote>

constraint -> constrain
</blockquote></details>

Done.
___
*[Bindings/Java/Matlab/examples/Moco/example2DWalking/example2DWalkingMetabolics.m, line 156 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3021#-MdQkIE65wuO1Hvdk0yQ:-MdT-Np-4KSsH4b4GJBo:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/704ac5f4ce124384bfd5eefab4a07c7fb71461e4/Bindings/Java/Matlab/examples/Moco/example2DWalking/example2DWalkingMetabolics.m#L156)):*
<details><summary><i>Previously, carmichaelong wrote…</i></summary><blockquote>

two spaces
</blockquote></details>

Done.
___
*[Bindings/Java/Matlab/examples/Moco/example2DWalking/example2DWalkingMetabolics.m, line 233 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3021#-MdQqE5FBDA1RZr7OH9E:-MdT-wK_63XwDmVc9EBZ:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/704ac5f4ce124384bfd5eefab4a07c7fb71461e4/Bindings/Java/Matlab/examples/Moco/example2DWalking/example2DWalkingMetabolics.m#L233)):*
<details><summary><i>Previously, carmichaelong wrote…</i></summary><blockquote>

The ribs and scapula didn't show up. I wanted to put this comment in the .osim file, but since it isn't modified and doesn't show up in Reviewable, I figure this is the next best place:

In `2d_gait.osim`, L2252: `hat_ribs.vtp` -> `hat_ribs_scap.vtp`
</blockquote></details>

Done.

**Review by carmichaelong — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3021#-:-MdT1tmOEAK3bkKdhKIL:bnfp4nl)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @nickbianco)

**Comment by nickbianco** [comment]
Thanks @carmichaelong!

**Pull request merged**
