### PR TITLE
Update VisualizeModel.cpp

### PR DESCRIPTION
**Pull request by gautam1858**
adding the muscle controller

### CODE REVIEW

**Comment by jimmyDunne** [comment]
This is a specific test for the visualizer, what does adding a muscle controller do to improve that?

**Comment by gautam1858** [comment]
An additional component to control the muscle along with visualiser would be useful and thought test meaning we can try out different codes.Adding a muscle controller is really helpful when there will be end to end control with visualisation and muscle control i.e with the model. It opens up ideas for researchers and a bonus for the researches, in general if you have visualisation then it would be nice to have controller as well in the test.

**Comment by jimmyDunne** [comment]
What you are looking to do is develop an example, not a test. The tests are designed to test the compilation and need to be small and specific. 

Examples need to be added to opensim-core/OpenSim/Examples/

**Comment by chrisdembia** [comment]
@gautam1858 thank you for your eagerness to contribute! It is very much appreciated. However, @jimmyDunne is correct. As a result, I am closing this PR.

 @gautam1858, the README example contains a muscle, a controller that controls the muscle, and also visualization. What does this example miss that you would like to see?

**Comment by gautam1858** [comment]
@jimmyDunne @chrisdembia ok thank you

**Pull request closed without merging**
