### PR TITLE
Fix doxygen 43

### PR DESCRIPTION
**Pull request by aymanhab**
Fixes issue #0

### Brief summary of changes
Rearrange doxygen annotations to fix warnings

### Testing I've completed
Ran doxygen and there was only 1 warning left

### Looking for feedback on...
If the doxygen output is same/better/worse (since these commands were previously ignored).

### CHANGELOG.md (choose one)

- no need to update because internal

---
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3031)

### CODE REVIEW

**Comment by aymanhab** [comment]
@nickbianco For your review, I can create the doxygen documents or you can get the branch and only inspect the handful of Moco classes that got affected. Please let me know your preference.

**Review by nickbianco — CHANGES_REQUESTED** [review]
Thanks @aymanhab, can you send me the doxygen documents?

> Reviewed 1 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3031#-:-MeCQMMm2CTTxy6UmsAt:b-utoj5w)* status: 1 of 14 files reviewed, 1 unresolved discussion (waiting on @aymanhab)

___
*[Bindings/Python/CMakeLists.txt, line 76 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3031#-MeCQVJO6GNC3gkdbIh8:-MeCQVJP8g3NbITPnTGq:b-hb6sf7) ([raw file](https://github.com/opensim-org/opensim-core/blob/f385713e7b4624e0ab1697cee306e36a5f6d5e5e/Bindings/Python/CMakeLists.txt#L76)):*
> ```CMake
>     # the wrappers. This variable holds the parts of the swig command that
>     # are shared between both invocations.
>     set(_swig_common_args -c++ -python -py3 -doxygen 
> ```

Extra space.

**Comment by aymanhab** [comment]
Will send link to google drive zip file separately.

**Comment by aymanhab** [comment]
https://drive.google.com/file/d/1SPb54ydtfiHgf40znudG89HvjQKp7Jvs/view?usp=sharing

**Review by nickbianco — CHANGES_REQUESTED** [review]
Thanks @aymanhab. Everything looks mostly good, except that using `\section` and `\subsection` causes some words to be cut-off. I left some comments below.

> Reviewed 13 of 14 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3031#-:-MeCb-diDZBzKCUCBOow:b75q4xw)* status: all files reviewed, 7 unresolved discussions (waiting on @aymanhab)

___
*[OpenSim/Moco/MocoDirectCollocationSolver.h, line 36 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3031#-MeCX2B46dD5dcWXJ_VL:-MeCX2B46dD5dcWXJ_VM:b4ljevh) ([raw file](https://github.com/opensim-org/opensim-core/blob/ef5a37d76b123cca709ef898f4b7bcd33afde31e/OpenSim/Moco/MocoDirectCollocationSolver.h#L36)):*
> ```objc
> 
> Direct Collocation Solver
> =========================
> ```

Just checking: these new headings are needed to avoid the doxgyen warnings?
___
*[OpenSim/Moco/MocoGoal/MocoAccelerationTrackingGoal.h, line 42 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3031#-MeCZBPN2xV5LYg8HOj0:-MeCZBPN2xV5LYg8HOj1:balt85c) ([raw file](https://github.com/opensim-org/opensim-core/blob/ef5a37d76b123cca709ef898f4b7bcd33afde31e/OpenSim/Moco/MocoGoal/MocoAccelerationTrackingGoal.h#L42)):*
> ```objc
> 
> \section MocoAccelerationTrackingGoal
> \subsection Default usage
> ```

This cuts off the word "Default" in doxygen. Maybe switch to the underline format? In other words,

```
MocoAccelerationTrackingGoal
=========================

Default usage
-------------------
```
___
*[OpenSim/Moco/MocoGoal/MocoAccelerationTrackingGoal.h, line 48 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3031#-MeCZIRt8HizwjcfrUE5:-MeCZIRt8HizwjcfrUE6:b3gptll) ([raw file](https://github.com/opensim-org/opensim-core/blob/ef5a37d76b123cca709ef898f4b7bcd33afde31e/OpenSim/Moco/MocoGoal/MocoAccelerationTrackingGoal.h#L48)):*
> ```objc
> to the ground frame and expressed in the ground frame.
> 
> \subsection Tracking inertial measurement unit (IMU) signals
> ```

This cuts off the word "Tracking" in doxygen. Maybe switch to the underline format? See comment above.
___
*[OpenSim/Moco/MocoGoal/MocoContactTrackingGoal.h, line 109 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3031#-MeC_wDz8YUhelcNO5Q4:-MeC_wDz8YUhelcNO5Q5:b1t0i8f) ([raw file](https://github.com/opensim-org/opensim-core/blob/ef5a37d76b123cca709ef898f4b7bcd33afde31e/OpenSim/Moco/MocoGoal/MocoContactTrackingGoal.h#L109)):*
> ```objc
>     expressed in ground.
> 
> # Tracking a subset of force components
> ```

Does switching the header sizes work, in other words:

```
## Tracking a subset of force components
<text>

# Usage
<text>
```
___
*[OpenSim/Simulation/StatesTrajectory.h, line 78 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3031#-MeCaZBc7vJBDlRZG43t:-MeCaZBc7vJBDlRZG43u:b94uq5t) ([raw file](https://github.com/opensim-org/opensim-core/blob/ef5a37d76b123cca709ef898f4b7bcd33afde31e/OpenSim/Simulation/StatesTrajectory.h#L78)):*
> ```objc
>  * trajectory.
>  *
>  * \subsection Using with an OpenSim:: Model 
> ```

The word "Using" is cut-off here. Weird, this issue only happens with sentence headers (e.g., `\subsection Guarantees` is fine).
___
*[OpenSim/Simulation/Model/SmoothSphereHalfSpaceForce.h, line 38 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3031#-MeCawcKE-EqDsbp1SmF:-MeCawcKE-EqDsbp1SmG:b-f6izcl) ([raw file](https://github.com/opensim-org/opensim-core/blob/ef5a37d76b123cca709ef898f4b7bcd33afde31e/OpenSim/Simulation/Model/SmoothSphereHalfSpaceForce.h#L38)):*
> ```objc
> contact geometries is done through properties of this component.
> 
> \section Constant contact force
> ```

"Constant" is cut-off here.

**Review by aymanhab — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3031)* status: 11 of 14 files reviewed, 7 unresolved discussions (waiting on @nickbianco)

___
*[Bindings/Python/CMakeLists.txt, line 76 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3031#-MeCQVJO6GNC3gkdbIh8:-MeCrv_F0WUj_IoPjWDc:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/f385713e7b4624e0ab1697cee306e36a5f6d5e5e/Bindings/Python/CMakeLists.txt#L76)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

Extra space.
</blockquote></details>

Done.
___
*[OpenSim/Moco/MocoDirectCollocationSolver.h, line 36 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3031#-MeCX2B46dD5dcWXJ_VL:-MeCrxgd9RABrDjZ8Mb2:b-nom1wg) ([raw file](https://github.com/opensim-org/opensim-core/blob/ef5a37d76b123cca709ef898f4b7bcd33afde31e/OpenSim/Moco/MocoDirectCollocationSolver.h#L36)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

Just checking: these new headings are needed to avoid the doxgyen warnings?
</blockquote></details>

Yes, the doxygen requirement is that if you have subsection then you must be within a section which was not the case in most of these files, so I added a section for the class name, we could also have removed the subsection labels altogether since they were ignored anyway
___
*[OpenSim/Moco/MocoGoal/MocoAccelerationTrackingGoal.h, line 42 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3031#-MeCZBPN2xV5LYg8HOj0:-MeDg8trC6bmRkAvUdQS:bcsbk7d) ([raw file](https://github.com/opensim-org/opensim-core/blob/ef5a37d76b123cca709ef898f4b7bcd33afde31e/OpenSim/Moco/MocoGoal/MocoAccelerationTrackingGoal.h#L42)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

This cuts off the word "Default" in doxygen. Maybe switch to the underline format? In other words,

```
MocoAccelerationTrackingGoal
=========================

Default usage
-------------------
```
</blockquote></details>

The syntax for \subsection is "subsection <tag> text, fixed it. The Markdown handling is rather buggy/undocumented
___
*[OpenSim/Moco/MocoGoal/MocoAccelerationTrackingGoal.h, line 48 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3031#-MeCZIRt8HizwjcfrUE5:-MeERD510j9DSDbiCxhR:bnj1ybm) ([raw file](https://github.com/opensim-org/opensim-core/blob/ef5a37d76b123cca709ef898f4b7bcd33afde31e/OpenSim/Moco/MocoGoal/MocoAccelerationTrackingGoal.h#L48)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

This cuts off the word "Tracking" in doxygen. Maybe switch to the underline format? See comment above.
</blockquote></details>

Fixed by fixing command syntax adding label
___
*[OpenSim/Moco/MocoGoal/MocoContactTrackingGoal.h, line 109 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3031#-MeC_wDz8YUhelcNO5Q4:-MeESPhRCUvQ5EFTU5AQ:b-wc4vyf) ([raw file](https://github.com/opensim-org/opensim-core/blob/ef5a37d76b123cca709ef898f4b7bcd33afde31e/OpenSim/Moco/MocoGoal/MocoContactTrackingGoal.h#L109)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

Does switching the header sizes work, in other words:

```
## Tracking a subset of force components
<text>

# Usage
<text>
```
</blockquote></details>

No, there's a hierarchy sections, then subsections then subsubsections nested within rather than arbitrary order of items with header sizes
___
*[OpenSim/Simulation/StatesTrajectory.h, line 78 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3031#-MeCaZBc7vJBDlRZG43t:-MeDg32t497XildVrOhP:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/ef5a37d76b123cca709ef898f4b7bcd33afde31e/OpenSim/Simulation/StatesTrajectory.h#L78)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

The word "Using" is cut-off here. Weird, this issue only happens with sentence headers (e.g., `\subsection Guarantees` is fine).
</blockquote></details>

Done.
___
*[OpenSim/Simulation/Model/SmoothSphereHalfSpaceForce.h, line 38 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3031#-MeCawcKE-EqDsbp1SmF:-MeEVh0v7AhjGcMJRda1:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/ef5a37d76b123cca709ef898f4b7bcd33afde31e/OpenSim/Simulation/Model/SmoothSphereHalfSpaceForce.h#L38)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

"Constant" is cut-off here.
</blockquote></details>

Done.

**Comment by aymanhab** [comment]
.zip file updated with latest output, also beefed up IMU class doxygen

**Review by nickbianco — CHANGES_REQUESTED** [review]
Thanks for the clarifications. Just a few small changes left.

> Reviewed 3 of 3 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3031#-:-MeLlt__0yIrtYRw0X6Y:bv9ffv3)* status: all files reviewed, 2 unresolved discussions (waiting on @aymanhab)

___
*[OpenSim/Moco/MocoDirectCollocationSolver.h, line 36 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3031#-MeCX2B46dD5dcWXJ_VL:-MeLnJxh7jk3ivM-XJ_e:b-q88gyi) ([raw file](https://github.com/opensim-org/opensim-core/blob/ef5a37d76b123cca709ef898f4b7bcd33afde31e/OpenSim/Moco/MocoDirectCollocationSolver.h#L36)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

Yes, the doxygen requirement is that if you have subsection then you must be within a section which was not the case in most of these files, so I added a section for the class name, we could also have removed the subsection labels altogether since they were ignored anyway
</blockquote></details>

Sounds good.  Could we change the top heading to `MocoDirectCollocationSolver`?
___
*[OpenSim/Moco/MocoGoal/MocoAccelerationTrackingGoal.h, line 48 at r4](https://reviewable.io/reviews/opensim-org/opensim-core/3031#-MeLlVa-4jzfp291vOqB:-MeLlVa0-lR-0x_u9PTM:b5evnm5) ([raw file](https://github.com/opensim-org/opensim-core/blob/98663763096010cce6b398cc6a326df4321ab666/OpenSim/Moco/MocoGoal/MocoAccelerationTrackingGoal.h#L48)):*
> ```objc
> to the ground frame and expressed in the ground frame.
> 
> \subsection trMocoAccelerationTrackingGoal Tracking inertial measurement unit (IMU) signals
> ```

Why `tr` instead of `use_`?
___
*[OpenSim/Moco/MocoGoal/MocoContactTrackingGoal.h, line 109 at r2](https://reviewable.io/reviews/opensim-org/opensim-core/3031#-MeC_wDz8YUhelcNO5Q4:-MeLnQPuEQMAXy945ksY:bfyxl8t) ([raw file](https://github.com/opensim-org/opensim-core/blob/ef5a37d76b123cca709ef898f4b7bcd33afde31e/OpenSim/Moco/MocoGoal/MocoContactTrackingGoal.h#L109)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

No, there's a hierarchy sections, then subsections then subsubsections nested within rather than arbitrary order of items with header sizes
</blockquote></details>

Makes sense. Rather than having one subheading bigger than the other, could you add a top heading called `MocoContactTrackingGoal`?

**Review by aymanhab — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3031)* status: 12 of 15 files reviewed, 1 unresolved discussion (waiting on @nickbianco)

___
*[OpenSim/Moco/MocoGoal/MocoAccelerationTrackingGoal.h, line 48 at r4](https://reviewable.io/reviews/opensim-org/opensim-core/3031#-MeLlVa-4jzfp291vOqB:-MeOSGx48vNv9gexUM7j:bcz34c8) ([raw file](https://github.com/opensim-org/opensim-core/blob/98663763096010cce6b398cc6a326df4321ab666/OpenSim/Moco/MocoGoal/MocoAccelerationTrackingGoal.h#L48)):*
<details><summary><i>Previously, nickbianco (Nicholas Bianco) wrote…</i></summary><blockquote>

Why `tr` instead of `use_`?
</blockquote></details>

use_... is used already later in the file,  so cant be used here. I chose tr for tracking, but will replace with imu_ instead to keep labels unique.

**Review by nickbianco — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3031#-:-MeQZPmp8VITLFI9YMD2:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aymanhab)

___
*[OpenSim/Moco/MocoGoal/MocoAccelerationTrackingGoal.h, line 48 at r4](https://reviewable.io/reviews/opensim-org/opensim-core/3031#-MeLlVa-4jzfp291vOqB:-MeQZHwPAloEtHfmnBfC:b3bbpjh) ([raw file](https://github.com/opensim-org/opensim-core/blob/98663763096010cce6b398cc6a326df4321ab666/OpenSim/Moco/MocoGoal/MocoAccelerationTrackingGoal.h#L48)):*
<details><summary><i>Previously, aymanhab (Ayman Habib) wrote…</i></summary><blockquote>

use_... is used already later in the file,  so cant be used here. I chose tr for tracking, but will replace with imu_ instead to keep labels unique.
</blockquote></details>

Ah okay, just needed unique labels.

**Comment by aymanhab** [comment]
Thanks @nickbianco 👍

**Pull request merged**
