### PR TITLE
[doxygen] Nested classes appear below the rest.

### PR DESCRIPTION
**Pull request by chrisdembia**
Without this PR, nested classes appear at the top of the class page. This PR moves the nested classes farther down.

### CODE REVIEW

**Comment by tkuchida** [comment]
@chrisdembia: I built the doxygen from master and from this branch, but have been unable to find any differences. Can you point me to the class(es) this change affects?

**Comment by chrisdembia** [comment]
> I built the doxygen from master and from this branch, but have been unable to find any differences. Can you point me to the class(es) this change affects?

Thanks. You could also have used the automatically-built doxygen at myosin.sourceforge.net.

Before: http://myosin.sourceforge.net/754/classOpenSim_1_1Component.html
After: http://myosin.sourceforge.net/755/classOpenSim_1_1Component.html

Look for the short description of the `StateVariable` class.

**Comment by tkuchida** [comment]
> myosin.sourceforge.net

Thanks; I couldn't remember where that was. It also doesn't help that I was looking at the _user_ documentation, not the _developer_ version. Anyway, the change looks good to me. :+1:

**Comment by chrisdembia** [comment]
> Thanks; I couldn't remember where that was.

I've been unable to think of a convenient way to remind people of this link. I wanted to create an entry in the list of "checks" (travis, appveyor) that just gave the right link, but I was unable to do this. Any ideas?

> Anyway, the change looks good to me.

Thanks.

**Comment by tkuchida** [comment]
>I've been unable to think of a convenient way to remind people of this link.

The "before" and "after" links you provided in your reply (or screencaps) would have been helpful in the original PR. It wouldn't be particularly visible, but we could include the link in CONTRIBUTING.md in the [Making a Pull Request (PR)](https://github.com/opensim-org/opensim-core/blob/master/CONTRIBUTING.md#making-a-pull-request-pr) section, item 5. :football:

**Comment by chrisdembia** [comment]
Thanks; I put it in a more general area since it applies for reviewing all PR's.

**Pull request merged**
