### PR TITLE
Add function visualize().

### PR DESCRIPTION
**Pull request by chrisdembia**
Fixes part of issue #2559 

### Brief summary of changes

- This PR adds a function for visualizing an existing motion from the API.

### Testing I've completed

- We use this heavily in Moco, including during workshops.

### CHANGELOG.md (choose one)

- updated...

The Doxygen for this PR can be viewed at http://myosin.sourceforge.net/?C=N;O=D; click the folder whose name is this PR's number.

---
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/2580)

### CODE REVIEW

**Comment by marnunez** [comment]
Is or will this be included for Python/Matlab wrapping?

**Comment by chrisdembia** [comment]
> Is or will this be included for Python/Matlab wrapping?

@marnunez I haven't tested that yet but that is the goal.

**Comment by chrisdembia** [comment]
@aymanhab I only included the changes for CommonUtilities for now. I'll make a separate PR for `visualize()`. Ready for review.

**Comment by chrisdembia** [comment]
Bah, `put_time` requires gcc > 5.0. I'm not sure what to do. Should we update the Travis machines?

**Comment by aymanhab** [comment]
I see some versions of gcc from 2015 https://gcc.gnu.org/releases.html if it comes as default now on linux, osx then definitely, if not maybe we can find a replacement call that works on earlier versions

**Comment by chrisdembia** [comment]
> maybe we can find a replacement call that works on earlier versions

Thanks @aymanhab. I'm trying that.

**Comment by chrisdembia** [comment]
@aymanhab ready for review.

**Comment by chrisdembia** [comment]
CI has passed. I mainly want to use this in the visualize() function to set the title of the visualizer. Matlab/Python surely have their own convenient ways to create a date/time string.

**Pull request merged**
