### PR TITLE
Adding support for `InputController` in Moco

### PR DESCRIPTION
**Pull request by nickbianco**
Fixes issues #3698, #3747, #3772.

### Brief summary of changes

These changes add generic support for using `InputController`s in Moco. Moco will detect any `InputController`s in the model and create OCP control variables for each "Input control" that the `InputController` requires. The number, order, and labels of Input control variables are determined based on `getInputControlLabels()` (renamed from `getExpectedInputChannelAliases()`)  which each concrete implementation of `InputController` must provide. The behavior of `InputController` was modified so that if no `Output` channels are connected to its list `Input` the `InputController` will not compute controls, and if the incorrect number of `Output` channels are connected an exception is thrown.

`MocoGoal::IntegrandInput` and `MocoGoal::GoalInput` have a new slots for passing Input control variables from solvers to `MocoGoal`s. Solvers can use `MocoProblemRep::getInputControls()` to get a vector containing Input control values; this vector contains _all_ control values (i.e., including those from `ActuatorInputController`), so we also provide `MocoGoal::getInputControlIndexMap()` and `MocoPathConstraint::getInputControlIndexMap()` to get Input control indexes for user-added `InputController`s only. The following `MocoGoal`s and `MocoPathConstraint`s have been updated to support Input controls:

- `MocoControlGoal`
- `MocoControlTrackingGoal`
- `MocoPeriodicityGoal`
- `MocoControlBoundConstraint`

Bounds for Input controls can be set via `MocoProblem::setInputControlInfo()` and `MocoTrajectory` was updated with get, set, and utility methods for accessing and modifiying Input controls in a trajectory. With these changes, controls for actuators associated with user-added `Controller`s no longer get populated in a `MocoSolution` automatically (to support using a solution as an initial guess in a subsequent problem). To compensate, the method `MocoTrajectory::generateControlsFromModelControllers()` can be used to populate a trajectory with the full model controls vector for use in post-hoc analyses. 

Some other changes include:

- `ActuatorInputController` and `ControlDistributor` are designated as internal classes for Moco use only.
- Added the static utility function `ControlDistributor::addControlDistributorAndConnectInputControllers()`.
- `MocoProblemRep::getInputControlIndexes()` was added to facilitate conversion between `MocoTrajectory` and solver trajectory types.
- `MocoUtilities::prescribeControlsToModel()` now adds `SignalGenerator`s to models with `InputController`s to drive Input controls.
- Removed `ignore_controlled_actuators` from `MocoPeriodicityGoal` and `MocoControlBoundConstraint` since users can simply choose to not add these controls to the goal/constraint. 
- Various minor drive-by fixes.

### Testing I've completed

Added `testMocoControllers.cpp`, which covers all aspects of the changes outlined above. These tests feature a toy controller, `TriplePendulumController`, which derives from `InputController` and has two "synergy" Input controls that map to three actuator controls.

### Looking for feedback on...

I think conversions between `MocoTrajectory` and solver trajectory types could be cleaner. The current implementation avoids having to rewrite `CasOC::Iterate::resample()`, but since this method shouldn't depend on `MocoCasOCProblem` anyway, maybe rewriting it is the solution here.

### CHANGELOG.md (choose one)

- updated.

[perf-win]

### Performance analysis

Platform: Windows, self-hosted runner

|                           Test Name | lhs [secs] | stderr [secs] | rhs [secs] | stderr [secs] | Speedup |
| ----------------------------------- | ---------- | ------------- | ---------- | ------------- | ------- |
|                               Arm26 |       0.34 |          0.00 |       0.35 |          0.00 |    0.98 |
|                      ellipsoid_wrap |       4.12 |          0.00 |       4.12 |          0.00 |    1.00 |
| ellipsoid_wrap_function_based_paths |       3.43 |          0.00 |       3.41 |          0.00 |    1.01 |
|                            Gait2354 |       0.41 |          0.00 |       0.41 |          0.00 |    1.01 |
|                     MocoSlidingMass |       1.48 |          0.00 |       1.48 |          0.00 |    1.00 |
|                    MocoSquatToStand |      11.32 |          0.57 |      11.27 |          0.10 |    1.00 |
|                     passive_dynamic |       5.60 |          0.01 |       5.53 |          0.00 |    1.01 |
|          passive_dynamic_noanalysis |       3.41 |          0.00 |       3.37 |          0.00 |    1.01 |
|                      RajagopalModel |       8.90 |          0.01 |       8.83 |          0.00 |    1.01 |
|                      ToyDropLanding |      13.44 |          0.01 |      13.53 |          0.11 |    0.99 |
|      ToyDropLanding_fbp_stepwisereg |      12.36 |          0.08 |      12.28 |          0.02 |    1.01 |
| ToyDropLanding_function_based_paths |      12.48 |          0.10 |      12.42 |          0.02 |    1.00 |
|            ToyDropLanding_nomuscles |       0.58 |          0.00 |       0.57 |          0.00 |    1.01 |

- - -
This change is [Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3769)

### CODE REVIEW

**Review by chrisdembia — CHANGES_REQUESTED** [review]
I'm curious about the performance impact here. (It would be great for the auto-generated performance analysis above to include a more realistic Moco use case than sliding mass.)

> Reviewed 34 of 52 files at r1.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3769#-:-NxzxDxA4Gt7q4rRUIqc:busneh0)* status: 34 of 52 files reviewed, 12 unresolved discussions (waiting on @nickbianco)

___
*[`doc/Moco/MocoUserGuide.dox` line 71 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3769#-NxzmeX2A6RZZMlMI7XX:-NxzmeX2A6RZZMlMI7XY:bmheq72) ([raw file](https://github.com/opensim-org/opensim-core/blob/4cf78a68c24839a7cc925cd767b4cd0709594c0a/doc/Moco/MocoUserGuide.dox#L71)):*
> ```
> multiple Controller%s are additive, since this is the behavior in OpenSim.
> 
> Controls associated with "OCP-controlled" actuators will not be included 
> ```

Maybe I'm getting lost with the language, but if Moco needed to solve for the controls with the optimizer, don't we need to put that in the MocoSolution? I would think model-controlled actuator controls do NOT go in the MocoSolution, and OCP-controlled actuator controls DO go in the MocoSolution.
___
*[`doc/Moco/MocoUserGuide.dox` line 98 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3769#-NxznV3K8Gzrdad0EPET:-NxznV3K8Gzrdad0EPEU:b-10p0gv) ([raw file](https://github.com/opensim-org/opensim-core/blob/4cf78a68c24839a7cc925cd767b4cd0709594c0a/doc/Moco/MocoUserGuide.dox#L98)):*
> ```
> not.
> 
> @subsection mocoinputcontrollers InputController support
> ```

Consider starting this section with a motivating example for the feature (e.g., synergies, reflexes). Otherwise, I fear it is too abstract for most people.
___
*[`doc/Moco/MocoUserGuide.dox` line 121 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3769#-NxznkyR9Of1ih1oo74o:-NxznkyR9Of1ih1oo74p:undefined) ([raw file](https://github.com/opensim-org/opensim-core/blob/4cf78a68c24839a7cc925cd767b4cd0709594c0a/doc/Moco/MocoUserGuide.dox#L121)):*
> ```
> include Input controls associated with a solved MocoProblem, and the 
> Input controls trajectory can be accessed via 
> MocoTrajectory::getInputControlsTrajectory. Finally, the method 
> ```





_Suggestion:_
```
getInputControlsTrajectory()
```
___
*[`OpenSim/Moco/MocoControlBoundConstraint.h` line 30 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3769#-Nxzp-bF13XnqiWXQZfU:-Nxzp-bF13XnqiWXQZfV:undefined) ([raw file](https://github.com/opensim-org/opensim-core/blob/4cf78a68c24839a7cc925cd767b4cd0709594c0a/OpenSim/Moco/MocoControlBoundConstraint.h#L30)):*
> ```objc
> /** This class constrains any number of control signals from ScalarActuator%s 
> or Input%s to InputController%s to be between two time-based functions. It is 
> possible to constrain the control signal to be exactly to a provided function; 
> ```





_Suggestion:_
```objc
control signal to match the value from a provided function
```
___
*[`OpenSim/Moco/MocoControlBoundConstraint.cpp` line 146 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3769#-Nxztaka0Da2eZM8Fbpm:-Nxztaka0Da2eZM8Fbpn:b-cqhjb3) ([raw file](https://github.com/opensim-org/opensim-core/blob/4cf78a68c24839a7cc925cd767b4cd0709594c0a/OpenSim/Moco/MocoControlBoundConstraint.cpp#L146)):*
> ```cpp
>     const auto& controls = getModel().getControls(state);
>     const auto& input_controls = 
>             getModel().getComponentList<ControlDistributor>().begin()
> ```

I think this is an O(n) search through components. I don't think the MocoConstraints have access to the MocoProblemRep but perhaps MocoConstraint and MocoGoal could have `getInputControls()` functions?
___
*[`OpenSim/Moco/MocoProblem.h` line 161 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3769#-NxzxdhG68uLK23qHlvx:-NxzxdhG68uLK23qHlvy:undefined) ([raw file](https://github.com/opensim-org/opensim-core/blob/4cf78a68c24839a7cc925cd767b4cd0709594c0a/OpenSim/Moco/MocoProblem.h#L161)):*
> ```objc
>     /// Set information about a single Input control variable in this phase.
>     /// Similar to setControlInfo(). The name for an Input control is the path 
>     /// follows the format <InputController_path>/<Input_label> (e.g.,
> ```





_Suggestion:_
```objc
    /// Similar to setControlInfo(). The name for an Input control
    /// follows the format <InputController_path>/<Input_label> (e.g.,
```
___
*[`OpenSim/Moco/MocoProblemRep.cpp` line 130 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3769#-Nxzz18D6bdnf7oi7Y6P:-Nxzz18D6bdnf7oi7Y6Q:b-7m74ox) ([raw file](https://github.com/opensim-org/opensim-core/blob/4cf78a68c24839a7cc925cd767b4cd0709594c0a/OpenSim/Moco/MocoProblemRep.cpp#L130)):*
> ```cpp
>             const auto& actuPath = actu.getAbsolutePathString();
>             OPENSIM_THROW_IF(!actu.get_appliesForce(), Exception,
>                     "Expected all actuators controlled by '{}' to be enabled, "
> ```

nice!
___
*[`OpenSim/Moco/MocoProblemRep.cpp` line 145 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3769#-Nxzz6wt7R6z_n-pTMRI:-Nxzz6wt7R6z_n-pTMRJ:b-67gqc5) ([raw file](https://github.com/opensim-org/opensim-core/blob/4cf78a68c24839a7cc925cd767b4cd0709594c0a/OpenSim/Moco/MocoProblemRep.cpp#L145)):*
> ```cpp
>     // ActuatorInputController we just added for actuators that are not already
>     // controlled by a user-defined controller.
>     ControlDistributor::addControlDistributorAndConnectInputControllers(
> ```

Maybe have this return the ControlDistributor that it added, so you don't need to get it yourself in the next line.
___
*[`OpenSim/Moco/MocoStudy.h` line 170 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3769#-NxzzZfJEiXt5hYVlaik:-NxzzZfJEiXt5hYVlail:bofe0dj) ([raw file](https://github.com/opensim-org/opensim-core/blob/4cf78a68c24839a7cc925cd767b4cd0709594c0a/OpenSim/Moco/MocoStudy.h#L170)):*
> ```objc
>     ///       Controller%s in the model, first call 
>     ///       MocoTrajectory::generateControlsFromModelControllers() to populate 
>     ///       the trajectory with the correct model controls.
> ```

What happens if a user does not do this?
___
*[`OpenSim/Moco/MocoTrajectory.h` line 476 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3769#-Ny--X6_80skycu6ZEeD:-Ny--X6_80skycu6ZEeE:b-iyw10q) ([raw file](https://github.com/opensim-org/opensim-core/blob/4cf78a68c24839a7cc925cd767b4cd0709594c0a/OpenSim/Moco/MocoTrajectory.h#L476)):*
> ```objc
>     /// @note Use `overwrite` to replace existing control values in the
>     ///       trajectory, if desired. 
>     void generateControlsFromModelControllers(Model model, 
> ```

nit/bonus points for writing a unit test for this function
___
*[`OpenSim/Moco/MocoGoal/MocoGoal.h` line 391 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3769#-Ny-01kTE6FZjap1f1Re:-Ny-01kTE6FZjap1f1Rf:bdfzlc9) ([raw file](https://github.com/opensim-org/opensim-core/blob/4cf78a68c24839a7cc925cd767b4cd0709594c0a/OpenSim/Moco/MocoGoal/MocoGoal.h#L391)):*
> ```objc
>     }
> 
>     /// Get a map between Input control names and their indexes in the Input 
> ```

nit: indices? :shrug: 



_Code quote:_
```objc
indexes 
```
___
*[`OpenSim/Moco/MocoGoal/MocoGoal.cpp` line 69 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3769#-Ny-0K9g8p1tAng0nj4J:-Ny-0K9g8p1tAng0nj4K:b-m1ckdf) ([raw file](https://github.com/opensim-org/opensim-core/blob/4cf78a68c24839a7cc925cd767b4cd0709594c0a/OpenSim/Moco/MocoGoal/MocoGoal.cpp#L69)):*
> ```cpp
> }
> 
> std::unordered_map<std::string, int> MocoGoal::getInputControlIndexMap(
> ```

nit: If this takes a model as an argument, is this function depending on any member variables? Should it be in a Utilities file instead?  Or should the function use getModel() internally instead?



_Code quote:_
```cpp
getInputControlIndexMap
```
___
*[`OpenSim/Simulation/Model/Model.cpp` line 1978 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3769#-Ny-0om02qOF4RuACbiD:-Ny-0om02qOF4RuACbiE:b-31r5vx) ([raw file](https://github.com/opensim-org/opensim-core/blob/4cf78a68c24839a7cc925cd767b4cd0709594c0a/OpenSim/Simulation/Model/Model.cpp#L1978)):*
> ```cpp
> }
> 
> void Model::markControlsAsInvalid(const SimTK::State& s) const
> ```

nit: Should this be unit-tested?

**Review by nickbianco — COMMENTED** [review]
Thanks for the review @chrisdembia! Made a first pass at some changes, but still need to add a few unit tests. 

> I'm curious about the performance impact here. (It would be great for the auto-generated performance analysis above to include a more realistic Moco use case than sliding mass.)

Agreed, I'll try adding a MocoInverse test or something.

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3769#-:-Ny1sWbF46pEUTngffL3:b-9i8owj)* status: 18 of 52 files reviewed, 12 unresolved discussions (waiting on @chrisdembia)

___
*[`doc/Moco/MocoUserGuide.dox` line 71 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3769#-NxzmeX2A6RZZMlMI7XX:-Ny1KKRAAFxN1rEZHlk2:b-e7cfs4) ([raw file](https://github.com/opensim-org/opensim-core/blob/4cf78a68c24839a7cc925cd767b4cd0709594c0a/doc/Moco/MocoUserGuide.dox#L71)):*
<details><summary><i>Previously, chrisdembia (Christopher Dembia) wrote…</i></summary><blockquote>

Maybe I'm getting lost with the language, but if Moco needed to solve for the controls with the optimizer, don't we need to put that in the MocoSolution? I would think model-controlled actuator controls do NOT go in the MocoSolution, and OCP-controlled actuator controls DO go in the MocoSolution.
</blockquote></details>

Oops, this was a typo. Changing to "Model-controlled".
___
*[`doc/Moco/MocoUserGuide.dox` line 98 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3769#-NxznV3K8Gzrdad0EPET:-Ny1Ko2N5-cwIvT0nG6A:b-9fmn3c) ([raw file](https://github.com/opensim-org/opensim-core/blob/4cf78a68c24839a7cc925cd767b4cd0709594c0a/doc/Moco/MocoUserGuide.dox#L98)):*
<details><summary><i>Previously, chrisdembia (Christopher Dembia) wrote…</i></summary><blockquote>

Consider starting this section with a motivating example for the feature (e.g., synergies, reflexes). Otherwise, I fear it is too abstract for most people.
</blockquote></details>

Good suggestion. Done.
___
*[`doc/Moco/MocoUserGuide.dox` line 121 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3769#-NxznkyR9Of1ih1oo74o:-Ny1KkwxC2KPxLMRY1BV:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/4cf78a68c24839a7cc925cd767b4cd0709594c0a/doc/Moco/MocoUserGuide.dox#L121)):*
> ```
> include Input controls associated with a solved MocoProblem, and the 
> Input controls trajectory can be accessed via 
> MocoTrajectory::getInputControlsTrajectory. Finally, the method 
> ```

Done.
___
*[`OpenSim/Moco/MocoControlBoundConstraint.h` line 30 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3769#-Nxzp-bF13XnqiWXQZfU:-Ny1Y9_u5dq49pPOFhok:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/4cf78a68c24839a7cc925cd767b4cd0709594c0a/OpenSim/Moco/MocoControlBoundConstraint.h#L30)):*
> ```objc
> /** This class constrains any number of control signals from ScalarActuator%s 
> or Input%s to InputController%s to be between two time-based functions. It is 
> possible to constrain the control signal to be exactly to a provided function; 
> ```

Done.
___
*[`OpenSim/Moco/MocoControlBoundConstraint.cpp` line 146 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3769#-Nxztaka0Da2eZM8Fbpm:-Ny1jt-k4rHF9rr3yzdM:btgqqh) ([raw file](https://github.com/opensim-org/opensim-core/blob/4cf78a68c24839a7cc925cd767b4cd0709594c0a/OpenSim/Moco/MocoControlBoundConstraint.cpp#L146)):*
<details><summary><i>Previously, chrisdembia (Christopher Dembia) wrote…</i></summary><blockquote>

I think this is an O(n) search through components. I don't think the MocoConstraints have access to the MocoProblemRep but perhaps MocoConstraint and MocoGoal could have `getInputControls()` functions?
</blockquote></details>

I added a `getInputControls()` method to `MocoPathConstraint`. `MocoGoal` does not need one since the `Input` control values are fed directly via the changes to `IntegrandInput` and `GoalInput`. But perhaps it would be better to revert those changes and use `getInputControls()` instead. I'll give it a go.
___
*[`OpenSim/Moco/MocoProblem.h` line 161 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3769#-NxzxdhG68uLK23qHlvx:-Ny1ZakvB0MlyGr5iR9x:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/4cf78a68c24839a7cc925cd767b4cd0709594c0a/OpenSim/Moco/MocoProblem.h#L161)):*
> ```objc
>     /// Set information about a single Input control variable in this phase.
>     /// Similar to setControlInfo(). The name for an Input control is the path 
>     /// follows the format <InputController_path>/<Input_label> (e.g.,
> ```

Done.
___
*[`OpenSim/Moco/MocoProblemRep.cpp` line 145 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3769#-Nxzz6wt7R6z_n-pTMRI:-Ny1jaK-Aub5zIVJSgVb:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/4cf78a68c24839a7cc925cd767b4cd0709594c0a/OpenSim/Moco/MocoProblemRep.cpp#L145)):*
<details><summary><i>Previously, chrisdembia (Christopher Dembia) wrote…</i></summary><blockquote>

Maybe have this return the ControlDistributor that it added, so you don't need to get it yourself in the next line.
</blockquote></details>

Done.
___
*[`OpenSim/Moco/MocoStudy.h` line 170 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3769#-NxzzZfJEiXt5hYVlaik:-Ny1l6CbAwJad02ntB1b:b-23fbfa) ([raw file](https://github.com/opensim-org/opensim-core/blob/4cf78a68c24839a7cc925cd767b4cd0709594c0a/OpenSim/Moco/MocoStudy.h#L170)):*
<details><summary><i>Previously, chrisdembia (Christopher Dembia) wrote…</i></summary><blockquote>

What happens if a user does not do this?
</blockquote></details>

The missing controls will be set to zero, which is the current behavior of `analyze`. But perhaps we should call `generateControlsFromModelControllers()` internally to avoid any user issues.
___
*[`OpenSim/Moco/MocoGoal/MocoGoal.h` line 391 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3769#-Ny-01kTE6FZjap1f1Re:-Ny1cfPX0T4dpXD9V9rZ:b-qpy5aw) ([raw file](https://github.com/opensim-org/opensim-core/blob/4cf78a68c24839a7cc925cd767b4cd0709594c0a/OpenSim/Moco/MocoGoal/MocoGoal.h#L391)):*
<details><summary><i>Previously, chrisdembia (Christopher Dembia) wrote…</i></summary><blockquote>

nit: indices? :shrug:
</blockquote></details>

Both are valid pluralizations of "index". Based on a random comment from Sherm I saw on a Simbody PR, I recently adopted using "indexes" since it contains the root word in the pluralization. I think it's especially nice for method naming.
___
*[`OpenSim/Moco/MocoGoal/MocoGoal.cpp` line 69 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3769#-Ny-0K9g8p1tAng0nj4J:-Ny1eCyr3oxC97Do6xdA:blx8kp8) ([raw file](https://github.com/opensim-org/opensim-core/blob/4cf78a68c24839a7cc925cd767b4cd0709594c0a/OpenSim/Moco/MocoGoal/MocoGoal.cpp#L69)):*
<details><summary><i>Previously, chrisdembia (Christopher Dembia) wrote…</i></summary><blockquote>

nit: If this takes a model as an argument, is this function depending on any member variables? Should it be in a Utilities file instead?  Or should the function use getModel() internally instead?
</blockquote></details>

Switched to use `getModel()`.

**Review by nickbianco — COMMENTED** [review]
@chrisdembia ready for review.

Let me know what you think about storing a reference pointer for the `ControlDistributor` in `MocoGoal` and `MocoPathConstraint`. It's nice that individual goals do not need to do this caching, but it requires a check that the model actually contains the `ControlDistributor` when calling `initializeOnModel`, which is not the case when calling `initializeOnModel` separately from a `MocoProblem` (as is the case in some of our unit tests).

Also, I added a benchmarking test based on the squat-to-stand example from the Moco distribution. It's a predictive muscle-driven example, but runs reasonably fast with function-based paths, so I think it will be a nice addition.

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3769#-:-Ny77zFXD-skSAFZoJWi:bkpmire)* status: 18 of 53 files reviewed, 10 unresolved discussions (waiting on @chrisdembia)

___
*[`OpenSim/Simulation/Model/Model.cpp` line 1978 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3769#-Ny-0om02qOF4RuACbiD:-Ny6Y1vu9mOBW6seu8Jm:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/4cf78a68c24839a7cc925cd767b4cd0709594c0a/OpenSim/Simulation/Model/Model.cpp#L1978)):*
<details><summary><i>Previously, chrisdembia (Christopher Dembia) wrote…</i></summary><blockquote>

nit: Should this be unit-tested?
</blockquote></details>

Done.

**Review by chrisdembia — CHANGES_REQUESTED** [review]
> Reviewed 11 of 52 files at r1, 3 of 3 files at r2, 13 of 20 files at r3, 2 of 4 files at r4, 6 of 6 files at r5.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3769)* status: all files reviewed (commit messages unreviewed), 3 unresolved discussions (waiting on @nickbianco)

___
*[`doc/Moco/MocoUserGuide.dox` line 98 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3769#-NxznV3K8Gzrdad0EPET:-NyDMmwy7D9WEMyqARJr:bnq95dc) ([raw file](https://github.com/opensim-org/opensim-core/blob/4cf78a68c24839a7cc925cd767b4cd0709594c0a/doc/Moco/MocoUserGuide.dox#L98)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Good suggestion. Done.
</blockquote></details>

excellent!
___
*[`OpenSim/Moco/MocoStudy.h` line 170 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3769#-NxzzZfJEiXt5hYVlaik:-NyDQLvG7OnOHTANGZ_B:borvr5k) ([raw file](https://github.com/opensim-org/opensim-core/blob/4cf78a68c24839a7cc925cd767b4cd0709594c0a/OpenSim/Moco/MocoStudy.h#L170)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

The missing controls will be set to zero, which is the current behavior of `analyze`. But perhaps we should call `generateControlsFromModelControllers()` internally to avoid any user issues.
</blockquote></details>

Sounds like a good idea. I guess the reason not to do that is if::
1. we can't detect well if it's necessary (but I think we can?)
2. users might call analyze() multiple times, and we'd be repeating a calculation unnecessarily--but then we could maybe add a flag or a different variant of the function that skips the calculation.

Most likely, users will forget to call the function, and there will be forum posts (similar to people forgetting to finalizeFromProperties()).
___
*[`OpenSim/Moco/Components/ActuatorInputController.h` line 58 at r5](https://reviewable.io/reviews/opensim-org/opensim-core/3769#-NyDPs-16w8fzDOwOp53:-NyDPs-16w8fzDOwOp54:bg6527e) ([raw file](https://github.com/opensim-org/opensim-core/blob/5f8794cb2d5000b69fdefdced3d4df2445600932/OpenSim/Moco/Components/ActuatorInputController.h#L58)):*
> ```objc
> 
>     /// @brief Test comment. 
>     // TODO if no actuators connected, returns empty vector.
> ```

nit in case you intended to address this in this PR. I
___
*[`OpenSim/Moco/MocoGoal/MocoGoal.h` line 391 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3769#-Ny-01kTE6FZjap1f1Re:-NyDPBez29lDX3vsuE__:baowd5z) ([raw file](https://github.com/opensim-org/opensim-core/blob/4cf78a68c24839a7cc925cd767b4cd0709594c0a/OpenSim/Moco/MocoGoal/MocoGoal.h#L391)):*
<details><summary><i>Previously, nickbianco (Nick Bianco) wrote…</i></summary><blockquote>

Both are valid pluralizations of "index". Based on a random comment from Sherm I saw on a Simbody PR, I recently adopted using "indexes" since it contains the root word in the pluralization. I think it's especially nice for method naming.
</blockquote></details>

Oh yes I love that -- helps a bunch with searching/grepping.
___
*[`OpenSim/Moco/tropter/TropterProblem.h` line 106 at r5](https://reviewable.io/reviews/opensim-org/opensim-core/3769#-NyDNz4r6O6rXhv49XXY:-NyDNz4r6O6rXhv49XXZ:b-tf6n80) ([raw file](https://github.com/opensim-org/opensim-core/blob/5f8794cb2d5000b69fdefdced3d4df2445600932/OpenSim/Moco/tropter/TropterProblem.h#L106)):*
> ```objc
>         for (const auto& controlName : allControlNames) {
>             const auto& info = m_mocoProbRep.hasInputControlInfo(controlName) ? 
>                     m_mocoProbRep.getInputControlInfo(controlName) :
> ```

nit: Seems like an opportunity to add a more convenient accessor that internally resolves whether the control is an Input or non-Input control.

**Review by nickbianco — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3769)* status: 46 of 54 files reviewed, 1 unresolved discussion (waiting on @chrisdembia)

___
*[`OpenSim/Moco/MocoStudy.h` line 170 at r1](https://reviewable.io/reviews/opensim-org/opensim-core/3769#-NxzzZfJEiXt5hYVlaik:-NyMji6V0fkR2dM7wVif:b-gcpnnm) ([raw file](https://github.com/opensim-org/opensim-core/blob/4cf78a68c24839a7cc925cd767b4cd0709594c0a/OpenSim/Moco/MocoStudy.h#L170)):*
<details><summary><i>Previously, chrisdembia (Christopher Dembia) wrote…</i></summary><blockquote>

Sounds like a good idea. I guess the reason not to do that is if::
1. we can't detect well if it's necessary (but I think we can?)
2. users might call analyze() multiple times, and we'd be repeating a calculation unnecessarily--but then we could maybe add a flag or a different variant of the function that skips the calculation.

Most likely, users will forget to call the function, and there will be forum posts (similar to people forgetting to finalizeFromProperties()).
</blockquote></details>

I forgot that I did add a check within `analyzeMocoTrajectory`  that throws an exception if you don't call `generateControlsFromModelControllers()` (i.e., if the number of controls doesn't match the number of model controls). I think I didn't opt for calling it internally because it would require making a copy of the trajectory. 

If we eventually support having OCP controls on top of `Controller` controls, then we might consider adding the call since it would be possible to have the same number of controls as the model but not have the `Controller` contributions. Or we find a way to "flag" the trajectory as not having the controller controls. But I think that could be future work beyond this PR.
___
*[`OpenSim/Moco/Components/ActuatorInputController.h` line 58 at r5](https://reviewable.io/reviews/opensim-org/opensim-core/3769#-NyDPs-16w8fzDOwOp53:-NyMhUzW1HQMJDdvwRxR:b-896fix) ([raw file](https://github.com/opensim-org/opensim-core/blob/5f8794cb2d5000b69fdefdced3d4df2445600932/OpenSim/Moco/Components/ActuatorInputController.h#L58)):*
<details><summary><i>Previously, chrisdembia (Christopher Dembia) wrote…</i></summary><blockquote>

nit in case you intended to address this in this PR. I
</blockquote></details>

Done.

**Review by chrisdembia — COMMENTED** [review]
> Reviewed 8 of 8 files at r6.
> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3769)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @nickbianco)

**Review by chrisdembia — COMMENTED** [review]
I just now saw your comment about the ControlDistributor. I think it's fine if the ControlDistributor is sometimes null, in unit tests, etc. My memory is that the problem should only truly be exercised through a MocoProblemRep. I wonder if we have to make `initializeOnModel()` a private function, and make `MocoProblemRep` a friend.

Thanks for adding the benchmarking test.

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3769#-:-NyNnGWOCLDmBqA9mgSI:b-qgph0s)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @nickbianco)

**Review by chrisdembia — COMMENTED** [review]
Also, great work on this! What a substantial feature!

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3769#-:-NyNoX6B46mwSlKsXKfy:b-fb0sbu)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @nickbianco)

**Review by chrisdembia — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/opensim-org/opensim-core/3769#-:-NyNochmAxmp6ciwcD_7:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @nickbianco)

**Comment by nickbianco** [comment]
Thanks @chrisdembia!

**Pull request merged**
